### ISSUE TITLE
Observability Spike:  What components do we need in the cluster beyond the gitops runtime? 

### ISSUE THREAD

**Issue by markramm** [weaveworks/weave-gitops#10]
I believe hooks for monitoring  the gitops runtime via Prometheus/Grafana already exist.   

I expect we therefore need to provide a base platform stack that includes prometheus, graphana, and alert manager.

As soon as there is a testable/usable version of the flux UI, I expect we will want to install that as well. 

Spike goal is to determine what components need to be added, and create initial stories for weave gitops cluster observability.

**Comment by palemtnrider** [comment]
Closing as we know we will need prometheus
