### ISSUE TITLE
Provide clearer guidance when gitops app add . command fails due to lack of permissions on target repo

### ISSUE THREAD

**Issue by davidstauffer** [weaveworks/weave-gitops#1001]
**Describe the bug**
The `gitops app add . `command fails. After the successful device auth with github the following error returns:
`uploading deploy key
Error: failed to create app service: error getting git clients: error setting up deploy keys: error uploading deploy key: error uploading deploy key multiple errors occurred: 
- POST https://api.github.com/repos/wego-example/podinfo-deploy/keys: 404 Not Found []
- the requested resource was not found` 

**Environment**
 - gitops: [ v0.4.0]
 - kubernetes:  [v1.21.1]
    - [X] KinD - kind v0.11.1]
    - [ ] k3s - _version_
    - [ ] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_
 - Browser + version: [e.g. chrome 74, safari 12, firefox 87]
 -
**Affects versions**

**To Reproduce**
1. Clone podinfo-deploy
2. Execute `gitops app add .`
3. Authenticate via device flow with github
4. See error on deploy key

**Expected behavior**
Error message to guide user that insufficient permission level for the target repo.

**Config and Logs**
If applicable, add logs to help explain your problem. _please compress the output before attaching_
- [ ] gitops config
- [ ] `gitops` cli call output (and parameters)
- [ ] gitops-controller logs
- [ ] Events from wego-* namespaces
- [ ] `kubectl cluster-info dump`
- [ ] Prometheus alerts

**Screenshots**
![image](https://user-images.githubusercontent.com/3997420/139706229-b43482fa-1d26-45c7-806a-ac7c40609e0a.png)

**Additional context**

**Comment by davidstauffer** [comment]
My mistake. Did not fork the repo.

**Comment by sympatheticmoose** [comment]
The issue description shows the user experience when someone attempts to sync a repo where they do not have appropriate permissions. This is something folks trip over during our workshops when they skip the step to fork our sample repo. The error message is fairly cryptic and if possible would be great to improve.

**Comment by jpellizzari** [comment]
From refinement: let's come up with a better error message for this situation

**Comment by sympatheticmoose** [comment]
(fwiwi my understanding from that slack conversation is that the Flux upgrade will fix a different error that would be encountered later in this workflow where the RSA key would be rejected.)
