### ISSUE TITLE
Associating a cluster with a repo

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#1002]
A user needs to be able to associate a new "leaf" cluster with a GitOps repo. We want to support this in Core via the `gitops install` CLI command.

This sequence diagram lays out what needs to happen from the users perspective:
![assoc_cluster](https://user-images.githubusercontent.com/2802257/139715804-bf1df238-07b3-425b-8d00-8ae65a48ae6e.png)

Assumptions about this flow:
* The user already has a GitOps repo created
* All git references point to `main`

Acceptance Criteria:
* Implement the functionality denoted in the sequence diagram in the CLI
* Only support associating a cluster via PR for this work (auto-merge can come later)
* CLI command must be covered with acceptance tests (unit tests assumed)
* Adhere to the architecture v1 ADR

Implementations expectations:
* Adds a `models.Cluster`
* Writes the cluster via a `GitOpsRepoWriter` or equivalent `interface`
* Adds a `ClusterApplier` interface to add GitOps Runtime and cluster Automation
* Only coverts to yaml `[]byte` just before applying (arguments should be types wherever possible)

**Comment by bigkevmcd** [comment]
We need to think about how the MCCP UI fits with this.

**Comment by jpellizzari** [comment]
@bigkevmcd I had originally scoped this to include an API method to associate a cluster, which could have turned association into part of a CAPI creation operation, but wasn't sure how the `kubeconfig` or equivalent would be stored.

Would you mind elaborating on your concerns here?

**Comment by bigkevmcd** [comment]
We want to migrate the MCCP cluster list into this, so that users have the status of attached clusters.

If this is about associating an existing cluster, then it doesn't feel like this is a CAPI thing at all?

**Comment by bigkevmcd** [comment]
We've talked about how we integrate with "remote" clusters from the main cluster, and having a "kubeconfig" for a cluster would definitely help (assuming that the main cluster can access the "remote").

**Comment by jpellizzari** [comment]
@bigkevmcd Please let me know if the scope of this ticket needs to change, or if we need to hop on a call.

**Comment by bigkevmcd** [comment]
We don't need to implement the UI in this ticket, but we do need to make sure that layering the MCCP view of clusters and their status can operate with the association implemented here.

**Comment by jpellizzari** [comment]
> We don't need to implement the UI in this ticket, but we do need to make sure that layering the MCCP view of clusters and their status can operate with the association implemented here.

Might be related: #1004
