### ISSUE TITLE
Spike: Figure out what states and metrics make up a healthy app

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#1004]
We need to agree as a team/product on which values users want to see in an `Application` status/detail view (CLI+API+UI). We also need to decide what makes an `Application` healthy or unhealthy.

Spike deliverables (document in this issue comments):
* Work with product to determine which values should make up an aggregated healthy/unhealthy `bool` for an Application
* * Single cluster?
* * Multi-cluster?
* Determine what status information users care about to show in a single `Application` "get status" operation.

Timebox: 8h

**Comment by J-Thompson12** [comment]
Current status information
`NAME  READY MESSAGE REVISION  SUSPENDED`

Possible Application Changes:
- if revision was at least the short commit hash. It may even be helpful to have it be a link to the commit like we do in get commits
- Its hard to say what is in scope for an application but after a little chat with the team it may be helpful to just have as a quick glance the overall pod status for an application. So if one pod is stuck in a backoff loop status would convey the liveness status for that pod. Then the users can go investigate further on their own.

It could look like 
```
NAME                    READY   MESSAGE                                                         REVISION                                        SUSPENDED 
gitrepository/nginx     True    Fetched revision: main/09dae79fbe2dd631b3ae279bfdd010e5af73ccc7 main/09dae79fbe2dd631b3ae279bfdd010e5af73ccc7   False    

NAME                    READY   MESSAGE                                                         REVISION                                        SUSPENDED 
kustomization/nginx     True    Applied revision: main/09dae79fbe2dd631b3ae279bfdd010e5af73ccc7 main/09dae79fbe2dd631b3ae279bfdd010e5af73ccc7   False  

NAME                   STATUS       MESSAGE                                                        
pod/nginx              Unhealthy    Liveness probe failed: cat: can't open '/tmp/healthy': No such file or directory main/09dae79fbe2dd631b3ae279bfdd010e5af73ccc7  
```
Something I noticed when viewing other options was how this company handled the application information. Specifically pointing out adding health and age. 
![Screen Shot 2021-11-05 at 1.02.42 PM.png](https://images.zenhubusercontent.com/5f45671c0e03ccbad5072566/234edd22-bcea-4b30-a878-7c8dc797720c)

Cluster status:
I looked at what enterprise already has implemented. They already show statuses from the CAPI lifecycle. @sympatheticmoose @markramm this would be a product decision on how much we take from enterprise on this. If we implement mccp we can use the same cluster information that enterprise has.

**Comment by jpellizzari** [comment]
Health checks:
* Source is unable to clone
* Kustomization is unable to reconcile
* Pods are not ready

If any of the above are in a "failed" state we mark the app as unhealthy.

In the case of multi-cluster, if an `Application` exists on multiple clusters, we aggregate the above metrics to give a global health status for an `Application`.

**Comment by jpellizzari** [comment]
@jpellizzari carve this up into tasks

**Comment by palemtnrider** [comment]
The title of this spike also mentions metrics but I don't see any called out.

**Comment by palemtnrider** [comment]
> In the case of multi-cluster, if an `Application` exists on multiple clusters, we aggregate the above metrics to give a global health status for an `Application`.

We will need to consider that we may have different application versions (or git refs) deployed to different clusters.  Indicating what "version" is on the cluster will be critical for troubleshooting.

**Comment by sympatheticmoose** [comment]
@palemtnrider how is version determined?

> we can have different environments deployed to multiple clusters. We will need to indicate that as well.
I would consider this more application details than application health status. i.e. if you discover an application is unhealthy, you then look into the differences which exist between deployments - cluster/env/other
