### ISSUE TITLE
I'm unable to add a new application with the 'Add Application' button in WGE 0.0.13 (=0.0.12)

### ISSUE THREAD

**Issue by LutzLange** [weaveworks/weave-gitops#1010]
**Describe the bug**
I'm taken through the whole flow including the authentication parts with Github.

**What is the severity of the bug**
serverity/Major

**Environment**
This is a demo environment that the Solution Architects will use : https://demo3.weavegitops.com
This cluster runs under cx-administrator in AWS EKS cluster wge-sademo-3 in Region eu-central-1

Feel free to investigate. 

**To Reproduce**
![App_Add_Failure](https://user-images.githubusercontent.com/2788194/139925506-9e1ff018-1453-41a3-b5cb-25a698b9890c.png)
Fill in the values, try with your own values.

**Expected behavior**

**Config and Logs**
$ k get events -n flux-system
LAST SEEN   TYPE     REASON   OBJECT                      MESSAGE
6m50s       Normal   error    kustomization/flux-system   validation failed: unable to recognize "4c133ad4-bb60-4605-a526-258bb6b32520.yaml": no matches for kind "Cluster" in version "cluster.x-k8s.io/v1alpha4"...
4m25s       Normal   error    gitrepository/flux-system   unable to clone 'ssh://git@github.com/weavegitops/demo3-repo', error: unknown error: ERROR: You're using an RSA key with SHA-1, which is no longer allowed. Please use a newer client or a different key type.

**Additional context**
The error above points to the problem. Stefan told me on Slack that flux 0.21.0 which is about to be released will fix this problem.

**Comment by LutzLange** [comment]
I did upgrade to flux 0.21.0
I did use a fork of pod-info this time.

I'm getting a different error  now : 
![app_add_failure2](https://user-images.githubusercontent.com/2788194/140046673-24620e97-f4ae-4aac-8b67-1cd617115a1a.png)

**Comment by sympatheticmoose** [comment]
@LutzLange ok so that error _looks_ like its reading your kubecontext as `https://10.100.0.1:443` rather than `wge-sademo-3`. Then its failing in a similar manner to https://github.com/weaveworks/weave-gitops/issues/979. Could you confirm output of `kubectl config current-context`?

**Comment by sympatheticmoose** [comment]
@LutzLange is this still an issue for you? If so please let me know on the above.

**Comment by iahmad9** [comment]
@sympatheticmoose @LutzLange Is it still an issue?

**Comment by sympatheticmoose** [comment]
closing. Please re-open if still a problem.
