### ISSUE TITLE
Add top level status section on each application's page

### ISSUE THREAD

**Issue by bia** [weaveworks/weave-gitops#1016]
Relates to #876 

We need a top level status section on each application's page so that the application's state is apparent once the page loads. The 'Application / podinfo-deploy' title is also not needed because of the breadcrumbs in the navbar above.

'Healthiness' being discussed in #1004 

<img width="821" alt="Screenshot 2021-10-13 at 15 32 56" src="https://user-images.githubusercontent.com/92439/137142838-4891f88c-b550-4549-8881-5192a049cdf6.png">

**Comment by sympatheticmoose** [comment]
@bia spike already raised :) https://github.com/weaveworks/weave-gitops/issues/1004
