### ISSUE TITLE
Application graph node styling and positioning

### ISSUE THREAD

**Issue by bia** [weaveworks/weave-gitops#1017]
Relates to #876

- Each node should have a more subtle drop shadow, more of an outline like `drop-shadow(rgb(189,189,189) 0px 0px 1px)`.
 
- Each circle should also be larger to be able to display more text and to improve #899 
<img width="868" alt="Screenshot 2021-10-13 at 15 05 15" src="https://user-images.githubusercontent.com/92439/137138209-1405d149-56ac-47c3-8bb2-db78e092d0a2.png">

- Nodes should be radially distributed to save space and to be less similar to Argo. Weave Scope's radial rendering on focus, but [was built in d3](https://github.com/weaveworks/scope/blob/a3597c9639bc32c06b05e149c7e09ab3ec958f42/client/app/scripts/charts/nodes-chart.js).
Maybe we can use [d3 for npm](https://www.npmjs.com/package/c3) to build something similar to the following design

![20211013app-graph](https://user-images.githubusercontent.com/92439/137141089-bf1afd26-437a-4250-9b71-23c1d4ce588c.png)

- When I scroll down on the page, I am most often accidentally zooming out the graph instead. The graph should be completely zoomed out (such that all nodes are visible) on page load.

**Comment by joshri** [comment]
@bia is it possible for me to have the concentric circles relate to their actual depth in the hierarchal tree? That way I can just distribute all the nodes at that depth evenly across the circle. My pod-info repo has six direct children right now in the graph, and I'm just thinking about how to space them all in a way that looks right - the three children of the root in your pic have three different edge lengths, and I'm not sure how to code that in a way that will look correct for any number of children besides dividing up those cool circles you have.  Am I making any sense at all?

**Comment by bia** [comment]
You mean something like this? Sounds like a good start!
![20211108app-graph](https://user-images.githubusercontent.com/92439/140769883-d5959c20-b543-4fff-b4da-5f07fabff71c.png)

**Comment by jpellizzari** [comment]
> Nodes should be radially distributed to save space and to be less similar to Argo. Weave Scope's radial rendering on focus, but was built in d3.
Maybe we can use d3 for npm to build something similar to the following design

Let's split this into a separate ticket. I will create it. Let's leave it out of scope for now.
