### ISSUE TITLE
Upgrading to Enterprise fails - missing GitRepository object

### ISSUE THREAD

**Issue by LutzLange** [weaveworks/weave-gitops#1028]
**Describe the bug**
My goal is to install WGE. The supported outlined way is to first install Core and then upgrade to Enterpriese.

**What is the severity of the bug**
serverity/Major

**Environment**
 - gitops: [e.g. v0.4.1]
 - kubernetes:  [e.g. 1.20.4]
    - [ EKS ] 

**To Reproduce**
# Some Credentials are required
source ~/.wge/credentials
# Install Weave GitOps Core
gitops install
# This will not be required soon
pctl install --flux-namespace wego-system 
# apply the entitlement
kubectl apply -f "$ENTITLEMENTFILE"
# Checkout the management repository
cd $HOME/git/demos
git clone https://github.com/"$GITORG"/"$GITREPO".git
# change into the repository
cd $GITREPO
# Do the upgrade
gitops upgrade
Deriving org/repo for PR as weavegitops/demo2-repo
Deriving name of GitRepository Resource as wego-system/demo2-repo
Error: failed to build upgrade configs: couldn't find GitRepository resource "wego-system/demo2-repo" in the cluster, please specify

**Expected behavior**
It feels like there is a step missing. I'm following our documentation here : https://docs.gitops.weave.works/docs/enterprise/upgrading

How is the GitRepository Object created? What did I miss?

**Comment by LutzLange** [comment]
A workaround is installing an app first.

**Comment by sympatheticmoose** [comment]
https://docs.gitops.weave.works/docs/next/enterprise/upgrading#4-upgrade references:
> Run the upgrade command from a local copy of git repo that is sync'd to the cluster 

To have a git repo sync'd to the cluster you need to run `gitops add app`

**Comment by sympatheticmoose** [comment]
@foot perhaps the guidance could be clearer in the documentation here?
