### ISSUE TITLE
Spike: design multi-cluster querying machinery

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#1030]
Notes:

During GitOps Install:
1. Create a service account on the remote cluster with a cluster admin role+binding
2. Add the service account `kubeconfig` to the management cluster as a config map
3. Add cluster Custom Resource to the management cluster

Spike outcome: Convert this into a design doc/ADR ^^ with the goal of communicating the architecture to anyone who works on it

**Comment by JamWils** [comment]
The notion of a `GitOpsCluster` was created in our enterprise offering.
