### ISSUE TITLE
Add standard table to Applications page

### ISSUE THREAD

**Issue by bia** [weaveworks/weave-gitops#1032]
Relates to #876

The Applications page should use the same table style as the Clusters page.

The title of that table should be something more descriptive like 'Installed GitOps Applications,' and each item will have a status/health metric displayed. ('Healthiness' being discussed in #1004)

![20211013applications](https://user-images.githubusercontent.com/92439/137141677-e004c366-26d8-48b4-a841-9f9e6642601b.png)

**Comment by sympatheticmoose** [comment]
@foot when you show a pending cluster is that when the PR has been raised but not yet merged? (Thinking similar behaviour would be nice to steal for here)

**Comment by joshri** [comment]
@jpellizzari Blocked by the current state of the Application object - we're missing the status, version, latest commit, and repo link. Is the checkbox functionality tied to the remove app button, and if so, does that mean that we're moving the button out of the AppDetail page, and adding the functionality to delete multiple apps at once?

**Comment by bia** [comment]
@rokshana-b and I also talked about showing whether an app is suspended or not here.

**Comment by sympatheticmoose** [comment]
@bia what about last successful reconciliation? Latest commit is on the repo... would we want to show latest fetched/applied?

**Comment by JamWils** [comment]
There is no context for this table to be run in Core today.  When we have those options we can revisit this issue.
