### ISSUE TITLE
Error pulling ghcr image on a local build

### ISSUE THREAD

**Issue by J-Thompson12** [weaveworks/weave-gitops#1035]
**Describe the bug**
When using a local build the ghcr image fails to pull showing the error:
`Failed to pull image "ghcr.io/weaveworks/wego-app:vv0.0.0": rpc error: code = Unknown desc = Error response from daemon: manifest unknown `
 

| Label | Description |
| --- | --- |
| severity/Critical | Weave GitOps is crashing or experiencing data loss, and there is no known workaround |
| severity/Major | Weave Gitops functionality is broken, there is a workaround, and the workaround requires significant effort |
| severity/Minor | Weave Gitops functionality is broken, but there is a workaround |
| severity/Low | Doesn’t affect primary flow/functionality but would be good to fix |

**Environment**
 - gitops: [e.g. v0.0.0]
 - kubernetes:  [e.g. 1.20.4]
    - [ ] KinD - _version_]
    - [ ] k3s - _version_
    - [ ] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_
 - Browser + version: [e.g. chrome 74, safari 12, firefox 87]
 -
**Affects versions**
local build

**To Reproduce**
1. build weave-gitops locally
2. run gitops install
3. See error on pod

**Expected behavior**

**Config and Logs**
If applicable, add logs to help explain your problem. _please compress the output before attaching_
- [ ] gitops config
- [ ] `gitops` cli call output (and parameters)
- [ ] gitops-controller logs
- [ ] Events from wego-* namespaces
- [ ] `kubectl cluster-info dump`
- [ ] Prometheus alerts
- [ ] Flux logs

**Screenshots**

**Additional context**

**Comment by mnowster** [comment]
tested, no longer a bug.
