### ISSUE TITLE
Adding App to EKS cluster fails

### ISSUE THREAD

**Issue by LutzLange** [weaveworks/weave-gitops#1039]
**Describe the bug**
It should be easy to add an app to an EKS cluster. It does not work for me.

**What is the severity of the bug**
severity/Major

**Environment**
 - gitops: [e.g. v0.4.1]
 - kubernetes:  [e.g. 1.20.4]
    - [ EKS ] cloud [e.g., EKS, AKS]  _version_

**To Reproduce**
- Setup an EKS cluster.
Install Weave GitOps Core
$ gitops install
$ pctl install --flux-namespace wego-system 
apply the entitlement file
$ kubectl apply -f "$ENTITLEMENTFILE"
go to your git checkout
$ cd ~/git/demos/demo2-repo 
we need to add an application first ( GitRepository Object is needed by upgrade )
$ gitops add app .
 Checking cluster status
✔ GitOps installed
Adding application:

Name: demo2-repo
URL: ssh://git@github.com/weavegitops/demo2-repo.git
Path: ./
Branch: main
Type: kustomize

✚ Generating Source manifest
✚ Generating GitOps automation manifests
✚ Generating Application spec manifest
► Cloning ssh://git@github.com/weavegitops/demo2-repo.git
Pull Request created: https://github.com/weavegitops/demo2-repo/pull/7

► Applying manifests to the cluster
Error: failed to add the app : could not apply manifests to the cluster: could not apply manifest: failed applying {"apiVersion":"kustomize.toolkit.fluxcd.io/v1beta2","kind":"Kustomization","metadata":{"name":"arn:aws:eks:eu-west-2:482649550366:cluster/wge-demo2-demo2-repo","namespace":"wego-system"},"spec":{"interval":"1m0s","path":".wego/targets/arn:aws:eks:eu-west-2:482649550366:cluster/wge-demo2/demo2-repo","prune":true,"sourceRef":{"kind":"GitRepository","name":"demo2-repo"}}}: kustomizations.kustomize.toolkit.fluxcd.io "arn:aws:eks:eu-west-2:482649550366:cluster" not found

**Expected behavior**
The app should be added. 

**Config and Logs**
$ k describe kustomization 
...
Events:
  Type     Reason  Age    From                  Message
  ----     ------  ----   ----                  -------
  Warning  error   6m10s  kustomize-controller  kustomization path not found: stat /tmp/demo2-repo-apps-dir075294006/.wego/apps/demo2-repo: no such file or directory
  Warning  error   5m11s  kustomize-controller  kustomization path not found: stat /tmp/demo2-repo-apps-dir371611933/.wego/apps/demo2-repo: no such file or directory
  Warning  error   4m11s  kustomize-controller  kustomization path not found: stat /tmp/demo2-repo-apps-dir306179032/.wego/apps/demo2-repo: no such file or directory
  Warning  error   3m11s  kustomize-controller  kustomization path not found: stat /tmp/demo2-repo-apps-dir056335191/.wego/apps/demo2-repo: no such file or directory
  Warning  error   2m11s  kustomize-controller  kustomization path not found: stat /tmp/demo2-repo-apps-dir369765066/.wego/apps/demo2-repo: no such file or directory
  Warning  error   71s    kustomize-controller  kustomization path not found: stat /tmp/demo2-repo-apps-dir720503713/.wego/apps/demo2-repo: no such file or directory
  Warning  error   11s    kustomize-controller  kustomization path not found: stat /tmp/demo2-repo-apps-dir062356108/.wego/apps/demo2-repo: no such file or directory

**Additional context**
I do suspect that this is some kind of permission problem. On EKS there is a aws-auth config map in kube-system that is used to allow additional access to the cluster. I did try the same flow with a kind cluster and it worked fine.

**Comment by LutzLange** [comment]
Here are the Event Logs from wego-system.

Might this point to the problem? 
20m         Warning   FailedMount         pod/source-controller-ccfc7b976-hn4nj                   MountVolume.SetUp failed for volume "source-controller-token-t9kdm" : failed to sync secret cache: timed out waiting for the condition

[events-wego-system.log](https://github.com/weaveworks/weave-gitops/files/7480573/events-wego-system.log)

**Comment by LutzLange** [comment]
I did find the PR on the repo and merged it. Is the cluster name that 'gitops' uses the problem here?

https://github.com/weavegitops/demo2-repo/tree/main/.wego/targets/arn:aws:eks:eu-west-2:482649550366:cluster/wge-demo2/demo2-repo

**Comment by iahmad9** [comment]
We do have `app add tests` for `EKS` and they are passing but the difference is they are just using the core app add to add an app 
https://github.com/weaveworks/weave-gitops/runs/4112031753?check_suite_focus=true#step:15:7410

**Comment by LutzLange** [comment]
Please see the commands in the initial post. 
The command $ gitops add apps . fails. This is before attempting to upgrade.

**Comment by LutzLange** [comment]
@jpellizzari What do you need?

**Comment by LutzLange** [comment]
These are my scripts to setup the cluster : 
https://github.com/weaveworks/cx-presales/tree/main/lutzdemo/scripts
I did run https://github.com/weaveworks/cx-presales/blob/main/lutzdemo/scripts/build-eks.sh with one of the config files e.g. https://github.com/weaveworks/cx-presales/blob/main/lutzdemo/demo3.conf

The pctl flux installation is what our documentation tells me I should do. Is that wrong?

Might this be an issue with permissions on the cluster?
You can ping me any time. We can take a look together.

**Comment by LutzLange** [comment]
I found that the cluster name that eksctl creates for me is problematic. I did edit the cluster name in the context in ~/.kube/config to work around the issue.

**Comment by jpellizzari** [comment]
> I found that the cluster name that eksctl creates for me is problematic. I did edit the cluster name in the context in ~/.kube/config to work around the issue.

Does this mean we need to change how we handle cluster names? Can you elaborate on what you changed your cluster name to?

**Comment by LutzLange** [comment]
Indeed it does. EKS cluster names can look like this : arn:aws:eks:eu-west-2:482649550366:cluster/lutzwkp1
This will result in all kinds of issues. You can't use this as a name in yaml.

**Comment by iahmad9** [comment]
It may be related to this one? https://app.zenhub.com/workspaces/weaveworks-foss-603cb6b1d4dff9000e242dc4/issues/weaveworks/weave-gitops/508

**Comment by palemtnrider** [comment]
@LutzLange please re-test with the latest code.  https://github.com/weaveworks/weave-gitops/issues/1213 was fixed in the last release which should address this issue.

**Comment by jpellizzari** [comment]
This should be fixed via #1213. Closing.
