### ISSUE TITLE
Can't add 2 apps from the same repo into one Cluster

### ISSUE THREAD

**Issue by LutzLange** [weaveworks/weave-gitops#1045]
**Describe the bug**
It should be easy to use gitops add app --path $DIR to add apps that reside in different paths of the same repo to one and the same cluster. It is not, as gitops add app will name to files exactly the same and put them in the same path. 

**What is the severity of the bug**
severity/Major

**Environment**
 - gitops: 0.4.1
 - kubernetes:  [e.g. 1.20.4]
    - [ X ] KinD - _version_]

**To Reproduce**

 $ kind create cluster --name satest
 $ gitops install
 $ git clone https://github.com/weavegitops/satest-apps.git
 $ cd satest 
 $ gitops add app --path marketing/
 $ gitops add app --path development/
Merge Pull request. First will work, 2nd will clash in this way : 

![Screenshot from 2021-11-08 15-27-07](https://user-images.githubusercontent.com/2788194/140761218-7710097d-3a98-4d51-944b-2a7fca30c70b.png)

app.yaml and satest-apps-gitops-deploy.yaml have the same name and path and thus clash!

**Expected behavior**
It should be easy to deploy multiple apps from the same git repository.

**Comment by LutzLange** [comment]
The PR number could be part of the file names, could it not? Or we include an application name that the customer decides.

**Comment by sympatheticmoose** [comment]
@LutzLange I got this working by giving the two apps distinct names. If you do not specify a `--name` flag, then the repository name will be taken as default and the app name needs to be unique. 

so my commands were:
`gitops add app . --name "dev" --path "/development"
`gitops add app . --name "mrk" --path "/marketing"

The second failed to deploy as it was expecting a marketing namespace which wasn't on my cluster, but adding this manually then had both apps reconciling and reporting as ready

**Comment by sympatheticmoose** [comment]
I'll close this bug as working as designed. If a user attempts to add a second app twice in the manner originally attempted, that would be a valid approach to correcting a mistake in the originally set path. Therefore I do not believe this is something we can prevent. However, we need to ensure clear guidance exists to the user regarding the use of `--name` and how to add two applications which exist in the same repo. I will raise new tickets for these.
