### ISSUE TITLE
Add example using --name to the add app help

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#1057]
To help mitigate errors such as https://github.com/weaveworks/weave-gitops/issues/1045 I propose we add something like this to the help text for `add app`:

```
Examples:
...

# Add an application from a directory within a repository and provide a unique name
gitops add app --url git@github.com:myorg/podinfo --name "application-a" --path "/folder"

Flags:
...
--name     Name of an application; defaults to application repository name. Must be unique.
```

Would appreciate assistance in describing the extent to which it must be unique.

**Comment by sympatheticmoose** [comment]
(yes there are a ludicrous number of edits due to me second guessing whether `an unique` or `a unique` is correct)

**Comment by sympatheticmoose** [comment]
@palemtnrider - assigned you the docs issue, adding you here as well as probably makes sense to tackle together

**Comment by sympatheticmoose** [comment]
worth noting we have 3 different issues where help text for add app could be improved, others are #1205 and #1207

**Comment by palemtnrider** [comment]
How does this sound:

```
# Add an application from a directory within a repository and provide a unique name
gitops add app --url git@github.com:myorg/podinfo --name "application-a" --path "/folder"

Flags:
...
--name     Name of an application; defaulting to the application repository name. The 
           name must be unique in the config repo, consisting of up to 63 lowercase 
           alphanumeric characters and `-`, starting and ending with an alphanumeric 
           character.
```
Basically taking the text from https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names

**Comment by sympatheticmoose** [comment]
From conversation we will just end at unique in config repo and provide the additional guidance in docs. If we encounter issues as a result of long repo names, we will revisit how we want to handle - error/truncate/hash etc

**Comment by palemtnrider** [comment]
`--name string                            Name of application; defaults to the application repository name if not specified; must be unique in the config repo.`
