### ISSUE TITLE
gitops beta install --app-config-url git@github.com:weavegitops/prod1-repo.git Fails

### ISSUE THREAD

**Issue by LutzLange** [weaveworks/weave-gitops#1059]
**Describe the bug**
I'm trying to install with a management cluster. I'm using the new --app-config-url. I can't make it work. I did try the http and ssh variants. Both fail. 

For the SSH variant : 
gitops beta install --app-config-url git@github.com:weavegitops/prod1-repo.git
....
Error: failed to store cluster manifests: failed to create source manifest: could not create git source for repo "git@github.com:weavegitops/prod1-repo.git" : failed to create source git: failed to run flux with output: ✗ git URL parse failed: parse "git@github.com:weavegitops/prod1-repo.git": **first path segment in URL cannot contain colon
 and error: exit status 1**

And here the http variant as well : 
$ gitops beta install --app-config-url https://github.com/weavegitops/prod1-repo.git
...
Error: failed to store cluster manifests: failed to clone configuration repo: failed cloning user repo: https://github.com/weavegitops/prod1-repo.git: **invalid auth method**

**Affects versions**
gitops version
Current Version: 0.4.1
GitCommit: c0d130b40ff6996c409973aa69573aea5d0751ea
BuildTime: 2021-11-03T20:02:35Z
Branch: HEAD
Flux Version: v0.21.0

**Comment by jpellizzari** [comment]
Looks like the `beta install` command does not use a `gitproviders.RepoURL` that would have converted the input. Changing this at the `InstallParams` could be a good way to fix it:

https://github.com/weaveworks/weave-gitops/blob/d63d9ff2a50766db69b9320402a7530cefb3acae/pkg/services/gitops/install.go#L23

**Comment by LutzLange** [comment]
The workaround is to use an URL with like "ssh://git@github.com/weavegitops/prod1-repo"

**Comment by josecordaz** [comment]
@jpellizzari This doesn't seem to be an issue in the main branch at this moment. I tested both types of URLs and they worked fine. `gitprovider.RepoURL` is being used here already https://github.com/weaveworks/weave-gitops/blob/main/pkg/services/factory.go#L120. That is why it is not failing in the current main. Want me to change it to `gitprovider.RepoURL` anyways?  I wonder if we should change these two URL fields to `gitprovider.RepoURL` as well?

**Comment by jpellizzari** [comment]
@josecordaz Could you double check that we have acceptance test coverage for the format of URL that was originally mentioned? If not, please add a test for it. I just want to be sure it is covered.

**Comment by josecordaz** [comment]
It seems we don't have acceptance test for beta commands. But as we use `getGitClients` in many places it will be just a matter of changing one of the urls in one of the tests from `ssh://` to `git@...`. As we are using only `ssh://` urls types across all integration tests.

**Comment by sympatheticmoose** [comment]
changing severity since this is on the `beta` commands.
