### ISSUE TITLE
2nd cluster does not pick up / run apps from the same cluster config repository.

### ISSUE THREAD

**Issue by LutzLange** [weaveworks/weave-gitops#1061]
**Describe the bug**
I'm trying to use --app-config-url to have the same configuration running on multiple clusters. The 2nd cluster will not pick up / run my app. 

**What is the severity of the bug**
serverity/Major

**Environment**
 - gitops:  v0.4.1
    - [ ] KinD - _version_]

**To Reproduce**
# prod1
kind delete cluster --name prod1 
kind create cluster --name prod1 
gitops beta install --app-config-url ssh://git@github.com/weavegitops/prod1-repo 
gitops add app --name podinfo --url ssh://git@github.com/weavegitops/podinfo-app --app-config-url ssh://git@github.com/weavegitops/prod1-repo

# prod2 - same config cluster
kind delete cluster --name prod2 
kind create cluster --name prod2 
gitops beta install --app-config-url ssh://git@github.com/weavegitops/prod1-repo

This results in prod1 running the app, but prod2 not running the app. 

**Expected behavior**
Both cluster should run the same apps.

**Comment by sympatheticmoose** [comment]
@LutzLange clusters can share the same configuration repo, this does not mean that all applications will be deployed across all clusters. You still need to add an application whilst targeting the second cluster. If this is using the same application, it wont create a new app.yaml in the cluster, but it will add another target for your new cluster. I will spin up a couple of clusters and share an example.

**Comment by sympatheticmoose** [comment]
Ok, so this repo https://github.com/sympatheticmoose/mono2 was populated by doing:
- `kind create cluster`
- `gitops install`
- `gitops add app --url https://github.com/sympatheticmoose/podinfo-deploy --app-config-url https://github.com/sympatheticmoose/mono2`
- merge PR on config repo
- `minikube start`
- `gitops install`
- `gitops add app --url https://github.com/sympatheticmoose/podinfo-deploy --app-config-url https://github.com/sympatheticmoose/mono2`

It's not using the beta commands, but effectively same workflow/outcome. Hope it helps.
