### ISSUE TITLE
gitops beta install --app-config-url ssh://git@github.com/weavegitops/demo3-repo fails on EKS

### ISSUE THREAD

**Issue by LutzLange** [weaveworks/weave-gitops#1068]
I'm trying to set up a new demo WGE environment. I thought starting with gitops beta install would be a good idea. It does not work :

**Describe the bug**
gitops beta install --app-config-url ssh://git@github.com/weavegitops/demo3-repo

✚ generating manifests
✔ manifests build completed
► installing components in wego-system namespace
CustomResourceDefinition/alerts.notification.toolkit.fluxcd.io created
CustomResourceDefinition/buckets.source.toolkit.fluxcd.io created
CustomResourceDefinition/gitrepositories.source.toolkit.fluxcd.io created
CustomResourceDefinition/helmcharts.source.toolkit.fluxcd.io created
CustomResourceDefinition/helmreleases.helm.toolkit.fluxcd.io created
CustomResourceDefinition/helmrepositories.source.toolkit.fluxcd.io created
CustomResourceDefinition/imagepolicies.image.toolkit.fluxcd.io created
CustomResourceDefinition/imagerepositories.image.toolkit.fluxcd.io created
CustomResourceDefinition/imageupdateautomations.image.toolkit.fluxcd.io created
CustomResourceDefinition/kustomizations.kustomize.toolkit.fluxcd.io created
CustomResourceDefinition/providers.notification.toolkit.fluxcd.io created
CustomResourceDefinition/receivers.notification.toolkit.fluxcd.io created
Namespace/wego-system created
ServiceAccount/wego-system/helm-controller created
ServiceAccount/wego-system/image-automation-controller created
ServiceAccount/wego-system/image-reflector-controller created
ServiceAccount/wego-system/kustomize-controller created
ServiceAccount/wego-system/notification-controller created
ServiceAccount/wego-system/source-controller created
ClusterRole/crd-controller-wego-system created
ClusterRoleBinding/cluster-reconciler-wego-system created
ClusterRoleBinding/crd-controller-wego-system created
Service/wego-system/notification-controller created
Service/wego-system/source-controller created
Service/wego-system/webhook-receiver created
Deployment/wego-system/helm-controller created
Deployment/wego-system/image-automation-controller created
Deployment/wego-system/image-reflector-controller created
Deployment/wego-system/kustomize-controller created
Deployment/wego-system/notification-controller created
Deployment/wego-system/source-controller created
NetworkPolicy/wego-system/allow-egress created
NetworkPolicy/wego-system/allow-scraping created
NetworkPolicy/wego-system/allow-webhooks created
◎ verifying installation
✔ helm-controller: deployment ready
✔ image-automation-controller: deployment ready
✔ image-reflector-controller: deployment ready
✔ kustomize-controller: deployment ready
✔ notification-controller: deployment ready
✔ source-controller: deployment ready
✔ install finished
Deploy key generated and uploaded to git provider
Error: failed to store cluster manifests: failed to create source manifest: could not create git source for repo "ssh://git@github.com/weavegitops/demo3-repo" : failed to create source git: failed to run flux with output: ✗ mkdirtemp wego-arn:aws:eks:eu-central-1:482649550366:cluster/wge-demo3-demo3-repo: pattern contains path separator
 and error: exit status 1

**What is the severity of the bug**
Please add a label for this ticket indicating the severity of this bug.  

Please advise. This was tested on EKS.
gitops 0.4.1

**Comment by LutzLange** [comment]
The errors results from my kubectl context containing a / 
arn:aws:eks:eu-central-1:482649550366:cluster/wge-demo3

**Comment by LutzLange** [comment]
I tried changing the name of the context, but it actually is the name of the cluster in ~/.kube/config that contains the / that is used here. Turns out, I don't need that long cluster name. But it is a hassle to change that.

**Comment by palemtnrider** [comment]
@LutzLange how did you create the eks cluster initially?  Was it via eksctl?  If not, how did you get the kubeconfig for the cluster?

Also, can you post the output of `kubectl config view --minify`

**Comment by jpellizzari** [comment]
Looks like we need to sanitize the cluster name when trying to figure out which path to write for a `tmp` dir. We will need to clean up the cluster name (if that is what we are passing to Flux).

Problematic tmp dir name: `mkdirtemp wego-arn:aws:eks:eu-central-1:482649550366:cluster/wge-demo3-demo3-repo`

Could also be something that Flux would want to handle better, but I would bet this is a `path` argument we are passing to the Flux binary.

**Comment by LutzLange** [comment]
Indeed the '/' was the problem. You can't escape a / it is the only character that can't be in a file name. Could you think of a different way to get the Cluster Name?

**Comment by palemtnrider** [comment]
This was fixed when we moved the beta install code into the install command.  Closing.
