### ISSUE TITLE
Spike: Find a Graphing Algorithm to Revamp Graph in Application Detail

### ISSUE THREAD

**Issue by joshri** [weaveworks/weave-gitops#1070]
The continuation of #1017 (and #876)

Remixing the graph is going to be quite the project. Since the data is tailored to fit dagre-d3 (which doesn't allow for radial node distribution), it's going to require some rewrites on how we transform application data into nodes and render the graph.

The main improvements we're going for here are:

1. Increased visibility of node data
2. Zoom control with button/slider (and better default zoom positioning)
3. Radial distribution (or some other different node distribution to separate us more from Argo - a top-to-bottom presentation was mentioned as a possible solution in refinement).

Images from #1017:

![image](https://user-images.githubusercontent.com/65822698/141496518-3a634e3f-5206-482d-83a1-80fd0691c872.png)

![image](https://user-images.githubusercontent.com/65822698/141497673-3720d5a6-78d3-4219-87f4-150fca47901b.png)

Spike outcomes:
1. Find a graphing algo that works for us (must be a known algorithm with an existing library)
2. Try it out on an example data set

Timebox to 8h

**Comment by jpellizzari** [comment]
Note for our future selves: The current approach of using a `<foreignObject />` tag makes styling the embedded HTML easier, but after a zoom, refreshes might cause weird issues (odd overflows will happen).

The fix would be to convert all text in the graph rendering to `svg`.

**Comment by joshri** [comment]
Results:

I started refactoring code from this link: https://embed.plnkr.co/plunk/1YghOs to see if it could work for us. It only uses d3, no other libraries/modules/whatever are needed.

Here it is running in wego on branch 1070-graph-fun: ![image.png](https://images.zenhubusercontent.com/617c4a20ede496b2fae35baf/07991eac-0dda-4e3c-96b4-654fc6d9d0aa)

Action Items for implementation:
1. Continue refactoring `Graph` class to remove excess features that we don't need (drag nodes, highlight nodes, etc) and get zoom working (`this` scoping issue)
2. Fix the styling and size of individual nodes + lines to plug in our HTML with data and icon
3. Manipulate our `reconciledObjectKinds` data into nodes and edges
4. Plug it in, and remove existing graph code.
5. Tie new graph zoom to the existing zoom slider.
6. Retire from coding.

**Comment by joshri** [comment]
@bia - very early days on this obviously, but I want to make sure that something like this is going to be okay!

**Comment by bia** [comment]
LGTM!
