### ISSUE TITLE
Spike: Look into using React Storybook (or equivalent)

### ISSUE THREAD

**Issue by joshri** [weaveworks/weave-gitops#1074]
Goals:

1. What would it take to implement this in wego and would it be worth it?
2. Is React Storybook the right version of this kind of tool, or should we go with something else?

React Storybook allows you to develop components without running the app itself - in theory this streamlines testing, development, and also organizes things in a nice way...but does it really? Cue spike. 

3-5 hours

**Comment by joshri** [comment]
Results:

Here are the alternatives to Storybook that I found:

Pattern Lab: https://patternlab.io/ - looks great but you have to write your components in either Twig (PHP) or Handlebars which is a LOT of refactoring so I think it's out. 

Atellier: https://scup.github.io/atellier/ - You access it from a specific route in React Router - which seems weird considering a large part of the benefit of this type of thing is being able to look at the UI without the app fully building. It's a lot less setup than Storybook but that seems like the only benefit, plus last update was in 2016 so.....yeah. 

Bit: https://bit.dev/ - Similar to Storybook EXCEPT that it essentially holds all your components as node-module-like packages in the cloud, which you then import into your app. Which means we'd be relying on their servers, which means we'd have to pay for an enterprise account....and Storybook just kind of seems more flexible anyway. Bit DOES have a lot of pre-built components which is cool.

InVision DSM: https://www.invisionapp.com/design-system-manager - Seems to be more for designers to create a cohesive vision rather than development. Plus you have to pay for it. 

In terms of Storybook itself (https://storybook.js.org/) - what's most exciting to me about it is that we can easily develop components relying on data that requires multiple deployed apps, or data that doesn't exist in the backend yet. I wouldn't have to authenticate with GitHub ever again. Writing that is nice. Even though the setup would take a lot of effort, we can keep all of our existing code. I think not having to rely on a dev server is worth it - we'd have a flexible way for the design to be seen at all times, with docs to back it up. Plus it's open source and well maintained. Hooray!

**Comment by jpellizzari** [comment]
:thumbsup: on storybook
