### ISSUE TITLE
Failed to deploy an application to GKE

### ISSUE THREAD

**Issue by steveww** [weaveworks/weave-gitops#1076]
**Describe the bug**
`gitops add app --app-config-url=git@github.com:foo/bar --url=git@github.com:foo/foo`

```
{
    "level": "error",
    "ts": "2021-11-16T11:36:55.004Z",
    "logger": "controller.kustomization",
    "msg": "Reconciliation failed after 25.715815ms, next try in 1m0s",
    "reconciler group": "kustomize.toolkit.fluxcd.io",
    "reconciler kind": "Kustomization",
    "name": "podinfo-deploy-apps-dir",
    "namespace": "wego-system",
    "revision": "main/874f6159867ba20a227b88d0e132ca4b3efff884",
    "error": "kustomization path not found: stat /tmp/podinfo-deploy-apps-dir580883519/apps/podinfo-deploy: no such file or directory"
  },
  {
    "level": "error",
    "ts": "2021-11-16T11:36:55.006Z",
    "logger": "controller.kustomization",
    "msg": "Reconciliation failed after 27.842629ms, next try in 1m0s",
    "reconciler group": "kustomize.toolkit.fluxcd.io",
    "reconciler kind": "Kustomization",
    "name": "gke-weave-marketing-europe-west2-b-enterprise-podinfo-deploy",
    "namespace": "wego-system",
    "revision": "main/874f6159867ba20a227b88d0e132ca4b3efff884",
    "error": "kustomization path not found: stat /tmp/gke-weave-marketing-europe-west2-b-enterprise-podinfo-deploy439324818/targets/gke-weave-marketing-europe-west2-b-enterprise/podinfo-deploy: no such file or directory"
  }
```

Tree of app config

```
├── README.md
├── apps
│   └── podinfo-deploy
│       └── app.yaml
└── targets
    └── gke-weave-marketing-europe-west2-b-enterprise
        └── podinfo-deploy
            ├── podinfo-deploy-gitops-deploy.yaml
            └── podinfo-deploy-gitops-source.yaml
```

**What is the severity of the bug**
Please add a label for this ticket indicating the severity of this bug.  

| Label | Description |
| --- | --- |
| severity/Critical | Weave GitOps is crashing or experiencing data loss, and there is no known workaround |
| severity/Major | Weave Gitops functionality is broken, there is a workaround, and the workaround requires significant effort |
| severity/Minor | Weave Gitops functionality is broken, but there is a workaround |
| severity/Low | Doesn’t affect primary flow/functionality but would be good to fix |

**Environment**
 - gitops: [v0.4.1]
 - kubernetes:  [e.g. 1.20.4]
    - [ ] KinD - _version_]
    - [ ] k3s - _version_
    - [X] cloud [GKE]  Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10-gke.1600", GitCommit:"ef8e9f64449d73f9824ff5838cea80e21ec6c127", GitTreeState:"clean", BuildDate:"2021-09-06T09:24:20Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
    - [ ] other - _name_ _version_
 - Browser + version: [e.g. chrome 74, safari 12, firefox 87]
 -
**Affects versions**

**To Reproduce**

**Expected behavior**
Application deployed

**Comment by jpellizzari** [comment]
`stat /tmp/gke-weave-marketing-europe-west2-b-enterprise-podinfo-deploy439324818/targets/gke-weave-marketing-europe-west2-b-enterprise/podinfo-deploy`

 ^^ Appears to be missing a `.yaml` at the end of the path :thinking:

**Comment by jpellizzari** [comment]
Might be solved by the new directory structure

**Comment by iahmad9** [comment]
@steveww would you please confirm if you are still seeing this issue?
