### ISSUE TITLE
Remove app in the UI not working with the new directory structure

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#1082]
**Describe the bug**
I added an app via the CLI, then tried to remove it via the UI.  The remove says it succeeded, however, the app is still listed on the application page.  One interesting note is the commits for the app are now displayed and so I'm wondering if the authentication steps went to the application repo instead of the gitops repo

**What is the severity of the bug**
Please add a label for this ticket indicating the severity of this bug.  

| Label | Description |
| --- | --- |
| severity/Minor | Weave Gitops functionality is broken, but there is a workaround |

**Environment**
 - gitops: 
> Using config file: /Users/me/.beta.yaml
Current Version: v0.0.0
GitCommit: dfac8b0b
BuildTime: 2021-11-16_13:58:29
Branch: main
Flux Version: v0.21.0

    - [ ] KinD - kind v0.11.1 go1.16.4 darwin/amd64
 - Browser + version: Chrome + Version 95.0.4638.54 (Official Build) (x86_64)
 -
**Affects versions**
main branch

**To Reproduce**
1. Add an app `bin/gitops add app . --app-config-url ssh://git@github.com/palemtnrider/qb8.git`
2. Approve and merge the PR.
3. Open the UI `bin/gitops ui run`
4. Go to the application list
5. select the application
6. click the Remove App button
7. complete the GH auth flow
8. reload the application page

**Expected behavior**
* App is removed from the repo
* App is removed from the cluster

If applicable, add logs to help explain your problem. _please compress the output before attaching_
- [ ] gitops config
- [ ] `gitops` cli call output (and parameters)
- [ ] gitops-controller logs
- [ ] Events from wego-* namespaces
- [ ] `kubectl cluster-info dump`
- [ ] Prometheus alerts
- [ ] Flux logs

**Screenshots**

**Additional context**

**Comment by jpellizzari** [comment]
Did some digging and this is not really a bug with an app not being removed. Removing an app is not atomic, and it takes some time for the kustomization to reconcile that the app has been removed.

Because we redirect to the app list page after remove, it would appear to the user that the app was NOT removed, when a refresh a few seconds later shows it gone.

I will clean up the UX on this.
