### ISSUE TITLE
Verbose flag on install does nothing

### ISSUE THREAD

**Issue by steveww** [weaveworks/weave-gitops#1085]
**Describe the bug**
`gitops install` failed during verification with exit status 1. Not very helpful.
Tried `gitops install --verbose` exactly the same output. Still not very helpful.

**What is the severity of the bug**
Please add a label for this ticket indicating the severity of this bug.  

| Label | Description |
| --- | --- |
| severity/Critical | Weave GitOps is crashing or experiencing data loss, and there is no known workaround |
| severity/Major | Weave Gitops functionality is broken, there is a workaround, and the workaround requires significant effort |
| severity/Minor | Weave Gitops functionality is broken, but there is a workaround |
| severity/Low | Doesn’t affect primary flow/functionality but would be good to fix |

**Environment**
 - gitops: [e.g. v0.4.1]
 - kubernetes:  [e.g. 1.21.1]
    - [X] KinD - 0.11.1]
    - [ ] k3s - _version_
    - [ ] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_
 - Browser + version: [e.g. chrome 74, safari 12, firefox 87]
 -
**Affects versions**

**To Reproduce**

**Expected behavior**
Use the `--verbose` flag I expect to see **much** more detail on what actions it is taking and the results of individual actions. This might give me an idea why the install fails.

**Config and Logs**

**Screenshots**

**Additional context**

**Comment by jpellizzari** [comment]
There are two things at play here:
1. We change behavior when the `--verbose` flag is present. We should remove it.
2. The `gitops install` command should have given a user-friendly error message

@steveww Could you add more detail on the command you are using to reproduce this bug?

**Comment by steveww** [comment]
Run `gitops install` and see the detail in the output.
Run `gitops install --verbose` and see the detail in the output.
They are identical. The `--verbose` does not add more detail, it is generally accepted that a verbosity flag when present will result in more verbose i.e. more detailed output. Generally useful when attempting to debug a problem.

As an example try `ssh some.host` and then `ssh -v some.host`.

**Comment by sympatheticmoose** [comment]
@steveww I think Jordan was asking for detail on the scenario which led you to hitting an error with the install process so we can reproduce and improve the error message. If you can recall and provide this that would be fantastic.

**Comment by steveww** [comment]
Sorry I can't remember what broke during the install attempt. However, the point remains that `--verbose` on the install command does nothing. It should provide more debugging information whether anything breaks or not.

**Comment by sympatheticmoose** [comment]
gitops install has been removed
