### ISSUE TITLE
Proposal - rename `.weave-gitops` folder to `weave-gitops`

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#1094]
We have had feedback that having the `weave-gitops` folder hidden is unnecessary, particularly as we move to more strongly recommending an external configuration repo, others still favour hiding it. I would like to bring that discussion into the open.

Options are:
1) leave hidden
2) only have as hidden folder when someone issues `gitops add app .` without specifying external config repo (namely that the application source and the gitops repo have the same value). 
3) change to `weave-gitops` in all cases

Unsure on complexity involved in 2 - perhaps @jrryjcksn could comment.

**Comment by bia** [comment]
Option 3 is the simplest case, giving the most clarity as to what is going on in the directory structure.
Let's uncomplicate this. :)

**Comment by davidstauffer** [comment]
Advocating for option 3. to have it visible in all cases. GitOps moves the interaction with your cluster to Git. Therefore the folder and files provide high value for the user. Especially if you have an external configuration repo it makes almost no sense at all. Why would you want an "empty" repo?

**Comment by steveww** [comment]
There is a 4th way.
Let the user specify it with an additional switch at install time.
`gitops install --app-config-url=git@github.com:foo/bar --path=my-gitops-stuff`
If not specified then it falls back to the default of option 3 `weave-gitops`.
