### ISSUE TITLE
Rename `--app-config-url` to `config-repo`

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#1095]
I believe the term `app-config-url` is unintuitive, and can be problematic when used outside of a `add app` context, i.e. for `install`. The repo used contains the automation objects for clusters, infrastructure and applications. My proposal is to have a fairly generic term, `config-repo` which has at least some external references and is currently used in the web UI.

Alternatives considered
- gitops-repo
- management-repo

**Comment by tomhuang12** [comment]
To me the confusion is between `app-config-url` and `url` flags as the description is very similar. I prefer `config-repo` as that's clearer to me that the repository is storing the configuration of the cluster. `gitops-repo` may still be a little confusing as it can mean the application repo that's being synced on.

**Comment by sympatheticmoose** [comment]
@rokshana-b there will be a number of references to this in the docs which are outside of any auto-generation, i.e. the getting started guide and sock shop example. These will need updating as well before we could release.

**Comment by sympatheticmoose** [comment]
given deadlines - i've raised https://github.com/weaveworks/weave-gitops-docs/pull/176
