### ISSUE TITLE
Folder Structure Updates

### ISSUE THREAD

**Issue by markramm** [weaveworks/weave-gitops#11]
- Mental model where workloads are in their own folder, and pipelines are kept separately. 
- Flux follows "minimalAPI" we should provide a more full featured api.  
- Application primitive

**Comment by palemtnrider** [comment]
@markramm @palemtnrider Will add to the WEP the proposed layout.

**Comment by markramm** [comment]
![Gitops at Scale (Fleet Repositories)](https://user-images.githubusercontent.com/455123/115723987-850e1000-a34e-11eb-8af4-75aee3191f55.jpg)

**Comment by pzfreo** [comment]
@markramm @palemtnrider will update

**Comment by palemtnrider** [comment]
![Gitops at Scale (Fleet Repositories) - repo-layout.jpg](https://images.zenhubusercontent.com/5d519a1d90a91718ac2d649b/1090a540-23a0-4ca3-825a-2f25605c3cb4)
