### ISSUE TITLE
Wego API server creates a GitRepository and Kustomization based in a wego Application definition

### ISSUE THREAD

**Issue by luizbafilho** [weaveworks/weave-gitops#110]
**Short description**
As a user, I want to apply an Application definition into the cluster so that the controller will create the Flux custom resources necessary to manage that application

**Acceptance criteria**
- [ ] The controller watches for Application definitions and creates a Flux `GitRepository` and `Kustomization`.

**Design materials**
- Screenshots
- Design diagrams
- WEP 
- PR/FAQ

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by palemtnrider** [comment]
I'm thinking this will need to perform everything that `wego app add` does.  i.e. in addition to creating the GitOps runtime resources, it will need to commit those into the application repo.

**Comment by JamWils** [comment]
Should we spike this so we are clear on the expectations of what we want to deliver @luizbafilho and @jpellizzari?  I know it's already in the "ready" column, but it feels abstract at the moment on what we need to deliver.

**Comment by jpellizzari** [comment]
Moving to Refine. I don't understand what this means.

**Comment by jpellizzari** [comment]
No longer relevant since we don't have a controller
