### ISSUE TITLE
Cloning a repo relies on settings in the user's environment

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#1100]
**Describe the bug**
Cloning a repo complains about ` knownhosts: key mismatch`

**To Reproduce**
1. Add an app after the GitHub deprecation of certain ssh keys

**Expected behavior**
The app gets added using the ssh keys stored on the cluster

**Additional context**
Slack thread: https://weaveworks.slack.com/archives/C0140SWQ94M/p1637258875492700

`go-git` issue: https://github.com/go-git/go-git/issues/411

Possible fixes:
1. Fix the bug in `go-git`
2. Ensure we have an `known_hosts` file in the docker container that the app runs in

This will be problematic because it will be to change that `known_hosts` file in the docker container if we have to.

**OR**

Use `go-git-providers` for all repo ops since that does not clone the repo, but instead uses the providers' HTTP API to do operations.

**Comment by J-Thompson12** [comment]
Related to #1278

**Comment by jpellizzari** [comment]
Closing. We are sticking with `go-git` for now.
