### ISSUE TITLE
Ability to skip flux installation on `gitops install`

### ISSUE THREAD

**Issue by josecordaz** [weaveworks/weave-gitops#1102]
**Short description**
As a user, I want to be able to skip flux installation on `gitops installl` so that I can use my already installed flux environment.

**Desired UX**
The user should be able to do these commands, in this order (without unstinalling flux):
1. Run `flux bootstrap <some flags here>`
2. Run `gitops install --skip-flux-install`
3. Run `gitops add app .`

**Acceptance criteria**
1. If the flux namespace is detected via checking for the namespace annotation and the user has not provided the `--skip-flux-install` command, we should fail the command and give the user instructions on how to proceed.
2. If the `--skip-flux-install` flag is present, we still need to validate that the Flux version is compatible with WeGO (warn on a non-exact match for flux version). Prompt the user to continue with the mismatch.
3. If the `--skip-flux-install` flag is present, check for the required flux CRDs on the cluster
4. Create an empty `wego-system` namespace (maybe via `client.Create()` first)
5. Docs are added describing how to move runtime yamls from a flux "bootstrapped" repo to a GitOps repo

After running these commands, all Flux kustomizations and sources should be healthy, as well as the WeGO `Application` that was added

**Comment by jpellizzari** [comment]
@josecordaz What do you think about adding this user journey to the acceptance criteria:

```
The user should be able to do these commands, in this order (without unstinalling flux):

1. Run `flux bootstrap <some flags here>
2. Run `gitops install <some flags>`
3. Run `gitops add app .`

After running these commands, all Flux kustomizations and sources should be healthy, as well as the WeGO `Application` that was added
```

**Comment by JamWils** [comment]
What happens if they run gitops install without the flag and they have flux already installed?

**Comment by josecordaz** [comment]
@JamWils The current behavior is that it prints out this message `Weave GitOps does not yet support installation onto a cluster that is using Flux.\nPlease uninstall flux before proceeding:\n  $ flux uninstall` but only if flux is installed in `flux-system` namespace.
