### ISSUE TITLE
Ability to check if current flux installation is compatible with wego

### ISSUE THREAD

**Issue by josecordaz** [weaveworks/weave-gitops#1103]
**Short description**
As a user, I want to be able to check if my current flux installation is compatible with wego so that I don't have to reinstall it on `gitops install`.

`flux version` returns the version of every controller used by flux. We would need to compare those versions with what `gitops flux version` returns to see if they match.

**Acceptance criteria**
- [ ] There is new command called `gitops check --pre`
- [ ] When running the new command it should print out `current flux version is compatible` if flux is compatible.
- [ ] When running the new command it should print out `current flux version is not compatible` if flux is not compatible.
- [ ] Check for kubernetes version compatibility (delegate to Flux)

**Comment by josecordaz** [comment]
It is possible to detect the namespace in which flux is installed by querying namespaces labels. Should we autodetect when running this command ? or add a flag so the user can specify in which namespace they have flux running already? or both?

**Comment by JamWils** [comment]
@hiddeco or @stefanprodan might have some insights here.  I believe there is an annotation we can query for to see whether flux is installed.  I would also imagine we can detect which version is on the cluster as well.

**Comment by stefanprodan** [comment]
To detect Flux:
- query the Kubernetes API for Flux CRDs
- check that all the CRDs needed by we wego are registered on the cluster
- query the Kubernetes API for namespaces with the `app.kubernetes.io/part-of: flux` label
- run `flux version --namespace <found> -ojson`
- parse the json, extract the controllers version and validate against wego requirements using semver ranges

PS. @JamWils we shouldn't post zenhub links in a public repo, I don't have access to that nor does anyone else outside WW that's reading this.

**Comment by JamWils** [comment]
Thanks @stefanprodan for the info.  I updated the link in my above comment, I'll remember not to use Zenhub links moving forward.

**Comment by jpellizzari** [comment]
Related to #1102

**Comment by josecordaz** [comment]
What would be the expected behaviour for `gitops check` (without `--pre` flag)?

**Comment by josecordaz** [comment]
This is an example of how flux would output if the kubernetes version is not supported:
```
flux check --pre                                                                                                                                      ─╯
► checking prerequisites
✗ flux 0.24.0 <0.24.1 (new version is available, please upgrade)
✗ Kubernetes version v1.17.17 does not match >=1.19.0-0
```
