### ISSUE TITLE
Document how to install wego in a cluster where flux is already installed

### ISSUE THREAD

**Issue by josecordaz** [weaveworks/weave-gitops#1104]
**Short description**
As a user, I want to see the documentation on how to install wego when flux is already installed in my cluster.

**Acceptance criteria**
- [ ] It mentions the existence of the validate command
- [ ] It mentions the existence of the skip-flux flag
- [ ] It mentions a new repo needs to be created first
- [ ] It mentions the optional step of creating the file `gitops-runtime.yaml` using the file `gotk-components.yaml` from the old repo and add a warning if this is not done.
- [ ] It mentions all previously added apps need to be added using `wego add app ...` command.

**Comment by josecordaz** [comment]
Should we include how to get rid of the flux components that live in the flux namespace that are pointing to the old repo? Otherwise there would be duplicates.

**Comment by jpellizzari** [comment]
Related to #1102 #1103

**Comment by jpellizzari** [comment]
Out of scope: not migrating "apps" from Flux to WeGO in this ticket
