### ISSUE TITLE
Flux to Weave GitOps Upgrade

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#1106]

**Comment by JamWils** [comment]
@sympatheticmoose something that isn't captured in this epic is the difference between how the `flux bootstrap` default works versus `gitops install`.  For example, the image and automation controllers are not installed by default with Flux, but we install them with Weave GitOps.  I think the side effect is that today this would have no impact on those users, but one day in the future it could if we build features into Weave GitOps that leverages those controllers.  

IMO, we shouldn't solve this problem now, but think about a UX when a particular "controller" isn't installed that is required for particular feature.

**Comment by bigkevmcd** [comment]
We don't configure the image or automation controllers tho'?
