### ISSUE TITLE
Move `pctl get` command to `gitops get profile/profiles` command

### ISSUE THREAD

**Issue by Himangini** [weaveworks/weave-gitops#1108]
### Description
As a weave gitops user
I want to run a command `gitops get profile/profiles` on the CLI
So that I can see the list of available profiles for me

### Scope
The command should be added in `weave-gitops` and behave similar to `pctl get` command
Testing and documentation should be added for the new command in `weave-gitops`

### Acceptance Criteria
As a weave gitops user
When I run CLI command `gitops get profile/profiles`
Then I should get list of all available profiles from a catalog for me
Output:
```
gitops get profile/profiles
PACKAGE CATALOG  
CATALOG/PROFILE                                   VERSION DESCRIPTION
nginx-catalog-1/weaveworks-nginx                  0.0.1   This installs nginx.
nginx-catalog-1/bitnami-nginx                     1.0.1   This installs bitnami nginx.
nginx-catalog-1/some-other-nginx                  1.0.1   This installs some other nginx.
prometheus-catalog-1/weaveworks-prometheus        0.0.4   This installs prometheus.
```

### Technical Notes
- This will be implemented using the proxy mechanism to the Kube API now and revisit auth and all services including profiles at a later point. 
- Flags for the command from UX sheet , we're not implementing these atm
```
                     No flag and no second noun shows both of the above
(-o|--output=)json|yaml|

-v|--version=0.0.1
If this is missing, then we list all available versions. make sure to remove the 'v'  prefix from the version number output.
```
- Talk to Bianca about the new output of the command

**Comment by davidstauffer** [comment]
LGTM. @bia happy from a UX perspective?

**Comment by Himangini** [comment]
How do we want the user from the CLI to be able to access the profiles API? - needs investigation. 
Might be blocked for authentication support :P

**Comment by aclevername** [comment]
Example of how we do this in profiles acceptance tests https://github.com/weaveworks/weave-gitops/blob/a75be1d88ee76f0ab8f5650fc18005485eb4a46f/test/acceptance/test/profiles_test.go#L146-L164:

```
func kubernetesDoRequest(namespace, serviceName, servicePort, path string, clientset *kubernetes.Clientset) ([]byte, int, error) {
	u, err := url.Parse(path)
	if err != nil {
		return nil, 0, err
	}

	responseWrapper := clientset.CoreV1().Services(namespace).ProxyGet("http", serviceName, servicePort, u.String(), nil)

	data, err := responseWrapper.DoRaw(context.TODO())
	if err != nil {
		if se, ok := err.(*errors.StatusError); ok {
			return nil, int(se.Status().Code), nil
		}

		return nil, 0, err
	}

	return data, http.StatusOK, nil
}
```

**Comment by bia** [comment]
LGTM.

One nit, why does it say
```
PACKAGE CATALOG  
CATALOG/PROFILE  
```
?

Why not just 
```
PACKAGE CATALOG
PROFILE  
```
?

```
gitops get profile/profiles
PACKAGE CATALOG
PROFILE                                   VERSION DESCRIPTION
nginx-catalog-1/weaveworks-nginx                  0.0.1   This installs nginx.
nginx-catalog-1/bitnami-nginx                     1.0.1   This installs bitnami nginx.
nginx-catalog-1/some-other-nginx                  1.0.1   This installs some other nginx.
prometheus-catalog-1/weaveworks-prometheus        0.0.4   This installs prometheus.

```

**Comment by aclevername** [comment]
@bia sorry some context was lost from planning- the output above is just an example of how it used to be. It will definitely be  different now that we are presenting the chart information. I image something loosely like `helm search`:
```
helm search repo nginx
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION
bitnami/nginx                           9.3.0           1.21.0          Chart for the nginx server
bitnami/nginx-ingress-controller        7.6.11          0.47.0          Chart for the nginx Ingress controller
bitnami/kong                            3.7.5           2.4.1           Kong is a scalable, open source API layer (aka ...
```

I also think the word `catalog` is getting dropped? Its less applicable now
