### ISSUE TITLE
Wego API creates a Flux HelmRepository based in an Application definition

### ISSUE THREAD

**Issue by luizbafilho** [weaveworks/weave-gitops#111]
**Short description**
As a user, I want to apply an Application definition into the cluster so that the controller will create the Flux HelmRepository.

**Acceptance criteria**
- [ ] The controller watches for Application CRs and creates a Flux HelmRepository.

**Design materials**
- Screenshots
- Design diagrams
- WEP 
- PR/FAQ

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by jpellizzari** [comment]
Not doing a controller at the moment, closing as irrelevant.
