### ISSUE TITLE
Can't add public repo that is not under the ownership of the user

### ISSUE THREAD

**Issue by josecordaz** [weaveworks/weave-gitops#1111]
**Describe the bug**
Trying to add an app coming from a repo that is public fails with error `Error: failed to get git clients: error setting up deploy keys: error uploading deploy key: no permissions to access this repository or repository doesn't exists`

**Environment**
 - gitops: v0.4.1
 - kubernetes: 
    - [x] KinD - v0.11.1
    - [ ] k3s - _version_
    - [ ] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_
 - Browser + version: [e.g. chrome 74, safari 12, firefox 87]
 -
**Affects versions**
v0.4.1

**To Reproduce**
1. Having wego installed
2. Run `gitops add app --url git@github.com:stefanprodan/podinfo.git --auto-merge --app-config-url ssh://git@github.com/foo/test-config-repo`

**Expected behavior**
It should not try to create a deploy key and succeed.

**Comment by jpellizzari** [comment]
Probably just need to check the repo visibility value from `go-git-providers`.
