### ISSUE TITLE
Homebrew error on release

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#1123]
**Describe the bug**
Got this error when doing a release: 
```
release failed after 488.59s error=homebrew tap formula: failed to publish artifacts: PUT https://api.github.com/repos/weaveworks/homebrew-tap/contents/Formula/gitops.rb: 404 Not Found []
```
https://github.com/weaveworks/weave-gitops/runs/4292549431?check_suite_focus=true#step:9:126

**Comment by jpellizzari** [comment]
Jake from @weaveworks/pitch-black might be able to help here

**Comment by aclevername** [comment]
> Jake from @weaveworks/pitch-black might be able to help here

A lot of the eksctl brew things pre-date me joining, but I might be able to help a bit :smile:

**Comment by aclevername** [comment]
@jpellizzari does the workflow have a `GITHUB_TOKEN` exported with write-permissions to `weaveworks/homebrew-tap`? It looks like our automation just pushes directly to the repo https://github.com/weaveworks/homebrew-tap/commits/master/Formula/eksctl.rb. I would guess thats whats causing the 404 (although really should be a 401?)

**Comment by J-Thompson12** [comment]
Brew apparently needs the extra permission for write:packages. I updated the permissions on WEAVE_GITOPS_TEST_WEAVEWORKS_WEAVE_GITOPS_BOT_TOKEN to include write:packages. I confirmed this works by getting a token with the previous permissions on a test repo and confirming failure. Then tested on the same repo with the updated permissions.

**Comment by J-Thompson12** [comment]
This is still an issue. The same error is still occurring. We have temporarily removed brew because we were unable to find a quick solution. Things that we tried:
1. Not having a token
2. Double checked the token permissions matched
3. Verifying that the commit author matched the token
4. Added debug flag (which gave no extra information)

**Comment by sympatheticmoose** [comment]
@J-Thompson12 to confirm, this is still an error and we will be unable to update our brew release unless resolved before our next WGO release?

**Comment by J-Thompson12** [comment]
@sympatheticmoose That is correct. I am still able to update it manually so we do still support brew but its just not automatic.
