### ISSUE TITLE
Require the value for app-config-url be a weave gitops repo

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#1126]
**Short description**
As an SRE, I want Weave GitOps to enforce that application developers are adding applications into repositories that are Weave GitOps repositories so that I don't have applications added to invalid repositories.

**Acceptance criteria**
- [ ] `gitops add app .` only succeeds if the repo I'm app adding has a .weave-gitops directory
- [ ] help text for app-config-url on add app informs the user that this must match the value used in `gitops install`

**Design materials**
- Help text for app-config-url parameter on add app `URL of external repository which will hold automation manifests.  This value needs to match the value used when installing the cluster`

**Comment by palemtnrider** [comment]
CC @sympatheticmoose

**Comment by sympatheticmoose** [comment]
Looks good, do we need to specify external? For instance the docs for `upgrade` including cloning the config repo locally so this would be your local repository.

**Comment by palemtnrider** [comment]
In the latest version of the code, upgrade is using the --app-config-url parameter so I don't believe we need to specify anything about cloning locally.

**Comment by sympatheticmoose** [comment]
yes... my point is that it doesn't _have_ to be external to anything though. You could have you app manifests in there, you could have the repo locally. So in either interpretation, external seems an unnecessary point

**Comment by palemtnrider** [comment]
good point.  The critical part is to ensure the config repo is one that has .weave-gitops in it.  If a user decides to store everything in a single repo, that's OK.

**Comment by palemtnrider** [comment]
Adding label customer issue label as I've heard confusion due to this behavior from outside development.

**Comment by sympatheticmoose** [comment]
@palemtnrider I'm wondering... If `config-repo` is set/configured/queryable following a `gitops install`, is there any value in `gitops add app .` taking the local repo as both `url` and `config-repo`?

**Comment by palemtnrider** [comment]
> I'm wondering... If `config-repo` is set/configured/queryable following a `gitops install`, is there any value in `gitops add app .` taking the local repo as both `url` and `config-repo`?

I don't think so.  I think we only default the config-repo to the value from install.  The `.` in the `app add` command indicates the user has cloned the app repo locally and wants to use the `git remote get-url origin` as the `--url` parameter to add.

**Comment by jpellizzari** [comment]
We want to take a look at this after doing the "config repo persistence" ticket here: https://github.com/weaveworks/weave-gitops/issues/1271

We still need to check to make sure that the repo stored here ^^ is still a valid repo. Our estimation will assume this work is done.
