### ISSUE TITLE
Create kustomize files to deploy wego controller as a component in the cluster

### ISSUE THREAD

**Issue by luizbafilho** [weaveworks/weave-gitops#113]
**Short description**
As a platform operator, I want to install wego so that it contains all flux controllers and wego controller as well

**Acceptance criteria**
Scenario: Installing wego
When: the user has installd wego
Then: wego-controller be deployed together with the flux controllers. 

**Design materials**
We can take a look at how flux handles that today: https://github.com/fluxcd/flux2/blob/main/manifests/bases/source-controller/kustomization.yaml

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by markramm** [comment]
This would block the "convention over configuration -- but configuration possible" strategy from Cornelia.
