### ISSUE TITLE
error adding app: failed to clone application repo: failed cloning user repo: ssh://git@github.com/user/podinfo-deploy.git: ssh: handshake failed: knownhosts: key mismatch

### ISSUE THREAD

**Issue by dev-wolfy** [weaveworks/weave-gitops#1132]
**Error adding app: failed to clone application repo: failed cloning user repo: ssh://git@github.com/user/podinfo-deploy.git: ssh: handshake failed: knownhosts: key mismatch**

I installed weave-gitops on an up to date K8s cluster.
After following the documentation with the example from the Getting started section [https://docs.gitops.weave.works/docs/getting-started](https://docs.gitops.weave.works/docs/getting-started)

After validating the authentication on github ![https://docs.gitops.weave.works/assets/images/github-device-flow-complete-f9a2e700c850d2f6c8dcfcff15db9988.png](https://docs.gitops.weave.works/assets/images/github-device-flow-complete-f9a2e700c850d2f6c8dcfcff15db9988.png)
I get the following error message : error adding app: failed to clone application repo: failed cloning user repo: ssh://git@github.com/wolfgit53/podinfo-deploy.git: ssh: handshake failed: knownhosts: key mismatch.

 know that gitops is based on flux and after some research I found this issue on the github of flux2 : fluxcd/flux2#2097. The is the same problem, and the solution is to update the known_hosts in the flux-system secret with the ecdsa-sha2-nistp25 value:

```none
github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
```
I found the right secret in the wego namespace but I have the good value : 
```bash
$ kubectl -n wego-system get secrets  wego-wolfy-k8s-podinfo-deploy -o json | jq '.data | map_values(@base64d)'

"known_hosts": "github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
```
So is it a bug from the weaveworks gitops tool?

![issue](https://user-images.githubusercontent.com/27728415/143252747-d2c91ddf-e303-44a3-bedb-278dea42d05f.png)

**What is the severity of the bug**
severity/Minor

| Label | Description |
| --- | --- |
| severity/Major | Weave Gitops functionality is broken, can't add any application |

**Environment**
 - gitops: v0.4.1
 - kubernetes:  v1.21.5
    - [ ] KinD
    - [ ] k3s
    - [ ] cloud [e.g., EKS, AKS]
    - [x] other - RKE 1.3.1
 - Browser + version: 94.0

**Affects versions**
v0.4.1

**To Reproduce**
1. Install latest version of gitops
2. Click on Add Application
3. Follow the getting started section of the documentation
4. When github allow the device connection
4. See error on the gitops's dashboard

**Expected behavior**
The possibility to add new applications without ssh errors

**Config and Logs**
If applicable, add logs to help explain your problem. _please compress the output before attaching_
- [ ] gitops config
- [ ] `gitops` cli call output (and parameters)
- [ ] gitops-controller logs
- [ ] Events from wego-* namespaces
- [ ] `kubectl cluster-info dump`
- [ ] Prometheus alerts
- [ ] Flux logs

**Screenshots**

**Additional context**
Sorry for my English :grimacing:

**Comment by palemtnrider** [comment]
Thanks, @dev-wolfy for reporting this 👍   This was fixed in a subsequent release to the version you reported. Closing.

**Comment by LongBeachHXC** [comment]
Hey @palemtnrider I don't know if this was fixed...I'm seeing this behavior in 0.6.2. Could be user error here but I even created a new secret and used the files in my local .ssh directory to populate the values and I'm still getting `ssh: handshake failed: knownhosts: key mismatch` trying to clone the repo

```
Current Version: 0.6.2
GitCommit: 35945c8b13e8762d1b083c5e7e978bbbd0558cdc
BuildTime: 2022-01-25T22:01:28Z
Branch: HEAD
Flux Version: v0.24.1
```

**Comment by coryschwartz** [comment]
I'm also seeing this. Same version. 0.6.2.

**Comment by DanielRejniak** [comment]
I also see the issue on version `v0.24.1`

**Comment by olivercp3** [comment]
generate new ECDSA host key doesn't work
