### ISSUE TITLE
Unable to add Application through the UI

### ISSUE THREAD

**Issue by LutzLange** [weaveworks/weave-gitops#1133]
**Describe the bug**
I'm trying to add an application through the UI. I'm pretty certain that I have all parameters right. I go through the authentication flow. Buy the part where keys are added to the source repository fails. It looks like the key add api call does not work. Please advise : 
![Screenshot from 2021-11-24 16-02-29](https://user-images.githubusercontent.com/2788194/143262973-ae36118f-8f14-44a2-b466-b8f753b693a2.png)

**Comment by LutzLange** [comment]
For easier review : 
Source Git : [https://github.com/weaveworks/cx-presales](https://github.com/weaveworks/presales/) Path wkp-demo-applications/sock-shop/
Cluster Git: [https://github.com/weavegitops/demo2-repo](https://github.com/weavegitops/demo2-repo)

**Comment by sympatheticmoose** [comment]
@LutzLange can you confirm if you are still encountering this issue?

**Comment by jpellizzari** [comment]
I was unable to reproduce this. I tried with HTTPS URLs and everything seemed to work OK. Deploy keys were added in the correct places.

@LutzLange Feel free to re-open this if you are still hitting this issue.
