### ISSUE TITLE
Add gitops update profile/profiles command

### ISSUE THREAD

**Issue by Himangini** [weaveworks/weave-gitops#1138]
### Description
As a weave gitops user
I want to run a command `gitops update profile/profiles` on the CLI
So that I can upgrade my profile installation 

### Scope

- The command should be added in `weave-gitops` and behave similarly to `pctl upgrade` command
- The command should create PR as the default. [see technical notes section]
- Testing and documentation should be added for the new command in `weave-gitops` 

### Acceptance Criteria
Given that I am a weave gitops user
When I run CLI command `gitops update profile/profiles <profile-name> --cluster <cluster-name> <version>`
Then my profile should be upgraded to the specified version on a specified cluster 
And I should get a PR link on my terminal `Created pull request: <link>`

Given that I am a weave gitops user
When I run CLI command `gitops update profile/profiles <profile-name> --cluster <cluster-name> <version>`
And I have made manual changes to the preexisting helm release
Then my profile should be upgraded to the specified version on a specified cluster 
And my manual changes should be preserved
And I should get a PR link on my terminal `Created pull request: <link>`

### Technical Notes
- The current flags for creating pr should be mapped to the following. If these flags are not provided the PR should be created using default values
```
repo-name=my_repo
pr-title=my_pr 
branch=my_branch 
commit=my_commit
```
- `--latest` flag is completely optional. We need to weigh the effort required for this functionality. If it gets too complicated then we should opt-out of this.

**Comment by davidstauffer** [comment]
LGTM.

**Comment by Himangini** [comment]
Get Profiles endpoint needs clear documentation that the list of profiles returned are in order of the version.

**Comment by bigkevmcd** [comment]
It should be returning profiles, with _ordered versions_ e.g.

```json
{
  "profiles": [
    {
      "name": "my-profile",
      "versions": [
        "0.0.1",
        "0.1.0",
        "0.2.0"
      ]
    },
    {
      "name": "other-profile",
      "versions": [
        "0.0.1",
        "0.1.0"
      ]
    }
  ]
}

**Comment by Himangini** [comment]
@aclevername is this unblocked now that the `gitops get profiles` pr is merged?
