### ISSUE TITLE
Reposition `authenticate with git provider` button in UI

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#1139]
Suggest next to the `Submit` button, but could also be config repo instead of source (as this is where we will _definitely_ require credentials). I believe submit makes the form cleaner (imo), however I've yet to give thought to if source and config repos are stored in separate git provider. So depends if we want to have buttons next to both entries or additional buttons appear for second provider if required.

<img width="1477" alt="Screenshot 2021-11-27 at 20 20 29" src="https://user-images.githubusercontent.com/19860021/143721176-7b9f4cbb-05cf-407c-b85d-5a534f418e3c.png">

**Comment by sympatheticmoose** [comment]
@bia interested in your views here

**Comment by bia** [comment]
In-line authentication buttons make sense to me, especially if there are multiple. 
What would happen if authentication failed on an in-line button? We would just highlight that line in red?

Should the ‘Submit’ button not be ‘Create PR’?

**Comment by sympatheticmoose** [comment]
some relation to #1247

**Comment by jpellizzari** [comment]
Closing in favor of #1031
