### ISSUE TITLE
Add install target to the Makefile

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#114]
I like to have my go projects put binaries in $GOPATH/bin.  We have used `make install` previously to perform this action.

**Comment by sachindavra** [comment]
Hi @palemtnrider , Could you tell me more details about it. 
I am new to open source and want to contribute.

**Comment by D3nn** [comment]
Currently, `make install` puts wego and wego_ui in .../weave-gitops/bin/wego/, which isn't in most developer's paths.  These should be installed in ${GOPATH}/bin.

**Comment by D3nn** [comment]
PR merged
