### ISSUE TITLE
Unable to remove application from UI

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#1140]
**Describe the bug**
After authenticated and seeing a successful message. I am still unable to remove an application

<img width="453" alt="Screenshot 2021-11-28 at 19 55 43" src="https://user-images.githubusercontent.com/19860021/143783867-09999b9a-f024-4548-ba4a-479173c5ce78.png">

<img width="436" alt="Screenshot 2021-11-28 at 19 55 16" src="https://user-images.githubusercontent.com/19860021/143783852-6cf42697-c6e7-4428-a5ee-512f17dff965.png">

**What is the severity of the bug**
Please add a label for this ticket indicating the severity of this bug.  

| Label | Description |
| --- | --- |
| severity/Critical | Weave GitOps is crashing or experiencing data loss, and there is no known workaround |
| severity/Major | Weave Gitops functionality is broken, there is a workaround, and the workaround requires significant effort |
| severity/Minor | Weave Gitops functionality is broken, but there is a workaround |
| severity/Low | Doesn’t affect primary flow/functionality but would be good to fix |

**Environment**
 - gitops: [e.g. v0.5 rc]
 - kubernetes:  [e.g. 1.20.4]
    - [ ] KinD - _version_]
    - [ ] k3s - _version_
    - [ ] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_
 - Browser + version: [e.g. chrome 74, safari 12, firefox 87]
 -
**Affects versions**

**To Reproduce**
1. Add app via UI
2. Merge PR
3. Try to remove application via UI

**Expected behavior**
Web UI should be able to remove application after authenticating

**Config and Logs**
If applicable, add logs to help explain your problem. _please compress the output before attaching_
- [ ] gitops config
- [ ] `gitops` cli call output (and parameters)
- [ ] gitops-controller logs
- [ ] Events from wego-* namespaces
- [ ] `kubectl cluster-info dump`
- [ ] Prometheus alerts
- [ ] Flux logs

**Screenshots**

**Additional context**

**Comment by jpellizzari** [comment]
Related to #1082
