### ISSUE TITLE
Instructions in README to get `gitops` binary don't work for 0.5.0-rc.2

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops#1142]
**Describe the bug**
Artifact format seems to have changed from `gitops` to `gitops.tar.gz` so instructions in README and user-guide on https://docs.gitops.weave.works/docs/next/installation won't work with the next release.

**Affects versions**
- 0.5.0-rc2

**Comment by jpellizzari** [comment]
Closed per @J-Thompson12
