### ISSUE TITLE
Profile Notifications

### ISSUE THREAD

**Issue by Himangini** [weaveworks/weave-gitops#1143]
### Description
As suggested [here](https://gist.github.com/bigkevmcd/0ff7197e0a902c3dcde4a1e7bfc3984c#notifications), we want to generate notifications when there is a new profile version is available

### Scope
- We will use [Flux Notifications API](https://fluxcd.io/docs/components/notification/api/) to achieve this 
- The notifications should be sent to Flux notifications, we don’t care how Flux notifications then forward the information
- This will only track updates to Profiles, this does not solve the problem of out-of-date Helm charts that are dependencies of a Profile.

### Acceptance Criteria
Given that I am a developer
When I encounter a new version of the profile available on a watched helm repository
Then a notification should be sent to the Flux Notifications API 
So that it can be consumed later by different providers

**Comment by davidstauffer** [comment]
LGTM.

**Comment by Skarlso** [comment]
This ticket is dependent on https://github.com/weaveworks/weave-gitops/issues/1144
