### ISSUE TITLE
Acceptance tests do not specify the precise line of the error

### ISSUE THREAD

**Issue by josecordaz** [weaveworks/weave-gitops#1164]
**Describe the bug**
When acceptance tests fail in CI, ginkgo doesn't provide the exact line of the test failure.

Failure in CI:
![image.png](https://images.zenhubusercontent.com/606389311ead0cc4788a9a72/c2a2d421-3ea2-4388-bbf4-bb63fea83665)

**To Reproduce**
1. This is a link in CI where this is happening already https://github.com/weaveworks/weave-gitops/runs/4402760349?check_suite_focus=true#step:3:8886

**Expected behavior**
It should fail like this:
![image.png](https://images.zenhubusercontent.com/606389311ead0cc4788a9a72/3e02ee36-1b90-49eb-ace9-4091bd780dd9)
https://github.com/weaveworks/weave-gitops/runs/4402991107?check_suite_focus=true#step:3:9011

**Comment by aclevername** [comment]
I've noticed this too. I think something must be going wrong with how the suite it setup for the lines to be incorrect
