### ISSUE TITLE
Profiles API should inherit `PassCredentials`

### ISSUE THREAD

**Issue by hiddeco** [weaveworks/weave-gitops#1166]
Providing more context to https://github.com/weaveworks/weave-gitops/pull/1148#pullrequestreview-821572298

In Helm [`v3.6.1`](https://github.com/helm/helm/releases/tag/v3.6.1) a security patch was introduced which prevents the configured credentials being automatically passed on to a chart download URL if the hostname (or port) of this URL differs from the repository hostname.
While at first this may seem like an edge case issue, our experience from source-controller user feedback is that both solutions like Artifactory (non-port vs port) as privately hosted chart repositories on GitHub (hostname difference) may require this configuration.

The Helm CLI allows you to ignore this difference by explicitly setting `--pass-credentials`, which the `HelmRepository` object has support for as well using the `PassCredentials` field. It would be wise to inherit this configuration flag to ensure smooth operations, which can be set on [`ChartPathOptions`](https://pkg.go.dev/helm.sh/helm/v3/pkg/action#ChartPathOptions).

**Comment by Himangini** [comment]
we would use the defaults for this field

**Comment by Skarlso** [comment]
>we would use the defaults for this field

No, we need to pass in to the ChartOptions whatever Flux has set up.
