### ISSUE TITLE
gitops delete app fails

### ISSUE THREAD

**Issue by LutzLange** [weaveworks/weave-gitops#1169]
This is what I tried : 
```
lutz@dellbook:~/git/weave-gitops-docs/docs$ gitops get apps
NAME
podinfo
podinfo-deploy
podinfo-policy
lutz@dellbook:~/git/weave-gitops-docs/docs$ gitops delete app podinfo-deploy
Error: failed to remove the app podinfo-deploy: failed to retrieve default branch for repository: error getting org repository multiple errors occurred: 
- validation error for OrgRepositoryRef.Organization: field is required
- validation error for OrgRepositoryRef.RepositoryName: field is required
```
And this is the error. This was done on http://demo.weavegitops.com . Interesting side note podinfo-deploy and podinfo-policy do reference the same source repository. 

Please advise how to delete one of these apps.
$ gitops version
Current Version: 0.5.0-rc2
GitCommit: 4555d5f88437dafc11f37b8b1c8b058ee7d7a2df
BuildTime: 2021-11-22T22:02:18Z
Branch: HEAD
Flux Version: v0.21.0

I'm interacting with WGE 0.0.16

**Comment by palemtnrider** [comment]
Adding customer issue label

**Comment by sympatheticmoose** [comment]
Hi @LutzLange, i've tried to reproduce but am unable to do so. Could you confirm you are still experiencing this issue and if so whether you are able to reproduce? If so it would help to have details on the `podinfo-deploy` and `podinfo-policy` apps (if you can share the config repo that would be ideal).

My attempt to reproduce was:
```
gitops install --config-repo <config-url>
gitops add app --url <podinfo-deploy-url> --config-repo <config-url>
<merge pr>
gitops add app --url <podinfo-url> --name podinfo-2 --path / --config-repo <config-url> (changed path so valid as a different resource)
<merge pr 2>
gitops delete app podinfo-deploy
<merge pr 3>
```

all worked fine as shown in screenshot below.
<img width="1429" alt="Screenshot 2022-01-05 at 10 05 05" src="https://user-images.githubusercontent.com/19860021/148199957-12eba39e-0c4f-44f7-9523-b97d337ac19f.png">
