### ISSUE TITLE
Enterprise UI Cleanup Sizes and Colors

### ISSUE THREAD

**Issue by joshri** [weaveworks/weave-gitops#1178]
Related to #1096 - I've implemented what I can in Core, but it has to be done separately in Enterprise (as far as I know). For clarity, I'm closing #1096 and copying it over here to open it under the team/pesto label.

A list of nits, with reference to our new design system colors :

 All dark/black text should be #1A1A1A, with no transparencies
![](https://user-images.githubusercontent.com/92439/142422894-a7640e37-c886-4c32-8dfa-433e74a46d76.png)

 All grey text should be #737373, with no transparencies
![](https://user-images.githubusercontent.com/92439/142424826-7755f508-0ccf-4f54-92f3-f7423de9f98f.png)

 grey and dark icons should also be #737373 and #1A1A1A
![](https://user-images.githubusercontent.com/92439/142426700-32bb3e01-6c80-48a5-8d50-90b39987d9e0.png)

 Buttons in color #00A7CC should be #006B8E (dark primary color) with white semibold capitalised text
![](https://user-images.githubusercontent.com/92439/142421812-e52f83cc-d8fe-4d46-aa7c-9220e6319282.png)

 Provider dropdown should have a bold label and table width should be equal to tile page width in order to have a smooth transition
![](https://user-images.githubusercontent.com/92439/142419908-5a498964-0f5d-425c-93e9-00e587983161.gif)

 This random pink slider should be blue
![](https://user-images.githubusercontent.com/92439/142419087-24b35811-6c1e-410d-95e3-7f59a5a17425.png)

 Menu item marker should be #00B3EC instead of #00d2ff
![](https://user-images.githubusercontent.com/92439/142426095-eea2f74c-2ba0-49f6-a248-95df2d83f909.png)
34

**Comment by JamWils** [comment]
Out of date.
