### ISSUE TITLE
Storybook is empty when running it

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#1185]
**Describe the bug**
When I run `npm run storybook` I am presented with a blank page.  Fix storybook so I can see the existing components.

**Comment by joshri** [comment]
Storybook took a second to load, but it looks like it does appear after a second or two - I added some Typescript config options in `.storybook/main.js` that could help, as well as formatted components so their auto-importing for docs actually works. Removed some Button styling that was made redundant by new defaults as well.
