### ISSUE TITLE
Zoom on Graph in App

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#1189]
As a user, I want to be able to use a slider to zoom in/out of the graph.  Add a new slider on the page that will transform the SVG to give it a zooming in/out effect.  

### Acceptance Criteria
1. Go the application detail page for an application
2. Slide the slider to the bottom and the graph zooms out (I.e. the nodes shrink)
3. Slide the slider to the top and the graph zooms in (I.e. the node grow)

**Comment by sympatheticmoose** [comment]
Updated description to reflect vertical zoom slider based on the design from @bia 
https://user-images.githubusercontent.com/92439/137141089-bf1afd26-437a-4250-9b71-23c1d4ce588c.png

**Comment by sympatheticmoose** [comment]
@bia we still need a decision on whether scroll to zoom should be disabled after adding this capability?

**Comment by bia** [comment]
This will not be such a big issue once we fix the layout of the graph nodes (or at least lay them horizontally), which should be a priority.
Depending on the scroll direction that the person has set, [I thought](https://github.com/weaveworks/weave-gitops/issues/876#issue-1025261717) :

>When I scroll down on the page, I am most often accidentally zooming out the graph instead. It would make sense if the graph was completely zoomed out (such that all nodes are visible) on page load.

To make it simpler, let's disable scroll to zoom for now.

**Comment by sympatheticmoose** [comment]
@bia can you find/recreate the issue to lay out horizontally given radial seemed further out?

**Comment by bia** [comment]
The current issue that is open is #1070. 
Let’s comment on it to clarify horizontal distribution as the next step?

**Comment by sympatheticmoose** [comment]
I'd rather keep tasks discrete so they can be closed out. 1070 is for the radial work, I'll create a new issue since we can't find one for horizontal.

**Comment by sympatheticmoose** [comment]
new issue https://github.com/weaveworks/weave-gitops/issues/1194
