### ISSUE TITLE
App add fails silently

### ISSUE THREAD

**Issue by steveww** [weaveworks/weave-gitops#1193]
**Describe the bug**
Add an application does nothing. No error but also no app deployed. See video attached

**Environment**
 - gitops: [0.5.0]
 - kubernetes:  [1.21.1]
    - [X] KinD - 0.11.1]
    - [ ] k3s - _version_
    - [ ] cloud [e.g., EKS, AKS]  _version

https://user-images.githubusercontent.com/5420958/145184701-3733505d-296b-48b8-ba2b-8187422ee532.mp4

**Comment by sympatheticmoose** [comment]
When you run `gitops install --app-config-url <repo>` this installs the runtime onto your cluster and sets up reconciliation between the specified repository and the cluster. 

You then ran `gitops add app` **without** specifying the configuration repo, so the automation objects were added to the application source repo and therefore nothing will be reconciled. 

If you want to do `gitops add app .` this is possible, however, it needs to be the same repository as you ran the install with

This is working as designed, but we can improve the experience to prevent users falling into this trap.
