### ISSUE TITLE
Support on-prem gitlab

### ISSUE THREAD

**Issue by davidstauffer** [weaveworks/weave-gitops#1203]
As a User, I want to use my on-prem GitLab that uses an URL like (gitlab.mycustomdomain.com/myorg/myrepo.git)  so that I can use Weave GitOps.

We need to support onprem gitlab for engagements we have with current customers. 
Currently commands like `gitops install --app-config-url https://gitlab.mycustomdomain.com/myorg/myrepo.git` with a onprem gitlab URL will fail.
 
`Error: error creating git clients: error normalizing url: could not get provider name from URL https://gitlab.mycustomdomain.com/myorg/myrepo.git: no git providers found for "https://gitlab.mycustomdomain.com/myorg/myrepo.git"`

We need to make sure a custom URL can be provided.

**Comment by LutzLange** [comment]
We are running a Trial with Amgen and this blocks them. They are currently trying to work around by using https://gitlab.com.

**Comment by foot** [comment]
- We derive provider from the URL right now (in core), needs some work to have extra flags / env to override auto-detection!
  - Update the `getProvider(url string)` fn to look for env var override? (cheap and easy)
  - EE we have an env var for PROVIDER right now (and can be set in values.yaml)
- known_hosts is generated at build time for EE (and derived from users terminal in core)
  - Need a way to add additional entries to known_hosts.
  - Update core: Grab the known_hosts from the GitRepository CR when add apping etc.

**Comment by foot** [comment]
Also need to pass a flag through to flux boostrap (`--hostname`) , maybe for known_hosts?
