### ISSUE TITLE
gitops add app --help output is wrong --url or <repository directory> at least one is required

### ISSUE THREAD

**Issue by LutzLange** [weaveworks/weave-gitops#1205]
```
./gitops version
Current Version: 0.5.1-rc3
GitCommit: b9e1433c0c1a5ee82481e1beb16f0a5bff66a42c
BuildTime: 2021-12-08T20:51:00Z
Branch: HEAD
Flux Version: v0.21.0
```
Getting the help output for add app :
```
./gitops add app --help
Associates an additional application in a git repository with a gitops cluster so that its contents may be managed via GitOps

```
Usage:
  gitops add app [--name <name>] [--url <url>] [--branch <branch>] [--path <path within repository>] <repository directory> [flags]

This is wrong one of --url or <repository directory> is required. The correct syntax guidance could look like this : 
```
Usage:
  gitops add app [--name <name>] (--url <url> [--branch <branch>] [--path <path within repository>] | <repository directory>) [flags]
```
Though it might be better to include two lines to keep readability : 

```
Usage:
  gitops add app [--name <name>] --url <url> [--branch <branch>] [--path <path within repository>] [flags]
  gitops add app [--name <name>] <repository directory> [flags]
```

**Comment by sympatheticmoose** [comment]
Thanks for raising @LutzLange. Minor point of clarification is that path and branch can also be set when using a local repository i.e. `gitops add app --path ./deploy/kubernetes/helm-chart --app-config-url https://github.com/sympatheticmoose/tmp-gitops --branch blah `

So I believe the usage should be:
 ```
 gitops add app [--name <name>] (--url <url> | <repository directory>) [--branch <branch>] [--path <path within repository>] [flags]
 ```

**Comment by LutzLange** [comment]
I'm not sure which lib you are using for parsing cmd options, and did not test ordering of options.
