### ISSUE TITLE
It should be possible to add an application to a cluster multiple times with different configurations e.g to different namespaces

### ISSUE THREAD

**Issue by LutzLange** [weaveworks/weave-gitops#1208]
Bug or Feature Request?

If an application aka a Source Repo is already added to a WGE cluster, you can't add it again. I would like to be able to add an application / a source multiple times to the same cluster with different configuration e.g. into a different namespace.

**Comment by sympatheticmoose** [comment]
This proposal may also be of interest https://github.com/weaveworks/weave-gitops/issues/1003
