### ISSUE TITLE
GitOps cannot delete an app deployed via GitLab from UI

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#1212]
**Describe the bug**

An app that has been deployed from GitLab repo is not getting deleted from the UI. Clicking on the `Remove App` button displays an error message on the UI.

**What is the severity of the bug**

| severity/Major | Weave Gitops functionality is broken, there is a workaround, and the workaround requires significant effort |
| --- | --- |

**Environment**
 - gitops: [v0.5.0]

**To Reproduce**

1. Run `gitops install --config-repo=git@gitlab`
2. Run `gitops add app --config-repo=<git@gitlab> --url=<git@gitlab>`
3. Run `gitops ui run`
4. Click on app link and see app status page
5. Click on `Remove App` button
6. See error on page

**Expected behavior**

**Screenshots**

﻿![Screen Shot 2021-12-10 at 01.15.47.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/1eb98c9c-e77a-4463-ad49-f1bb290bd791)

**Comment by J-Thompson12** [comment]
I am unable to replicate this error on main. @rokshana-b can you still see this error?

**Comment by rokshana-b** [comment]
I cannot recreate this issue anymore, seems like the problem got solved somehow. Closing this issue.
