### ISSUE TITLE
No longer able to see helm app status from UI

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#1214]
**Describe the bug**

The status page for an upstream helm app shows an error message now. Although the app installation is successful from the CLI and I'm able to see app status from the CLI, the UI page only gives an error. 

**What is the severity of the bug**

| severity/Major | Weave Gitops functionality is broken, there is a workaround, and the workaround requires significant effort |
| --- | --- |

**Environment**
 - gitops: [v0.5.0]

**To Reproduce**

1. Run `gitops install --config-repo=<>`
2. Run `gitops add app --config-repo=<> --url=https://charts.kube-ops.io --chart=loki --auto-merge`
3. Run `gitops ui run`
4. See apps listed in the dashboard
5. Click on `loki` app link
6. See error message displayed on the page

**Expected behavior**

UI should navigate to app status page and display health of the app

**Screenshots**

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/235bea01-6513-41f2-a703-e8f919f8a8e2)

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/161d0fdf-d8ac-41dd-9820-f318688cc963)

## Testing
Verify that the helm application renders via UI for helm and git repositories.

**Comment by J-Thompson12** [comment]
One big issue for this is that the page was designed for git repos. The call to ParseRepoUrl is designed to get git information to get the commits. Neither of these actions should be run for a helm repo. 
![Screen Shot 2021-12-14 at 11.25.28 AM.png](https://images.zenhubusercontent.com/5f45671c0e03ccbad5072566/2cd5f40e-5ead-4427-900d-85b2edf1754a)

@bia We need to decide if we need a different design for when it is a helm chart or just remove certain elements if it is.

**Comment by JamWils** [comment]
I think we could just hide the commit block when it's a helm repository.

**Comment by bia** [comment]
@J-Thompson12 what is that a screenshot of?

**Comment by sympatheticmoose** [comment]
Ack. Thinking about options

**Comment by J-Thompson12** [comment]
> @J-Thompson12 what is that a screenshot of?

@bia That is a screenshot of the application details page.
