### ISSUE TITLE
Fix positioning on UI buttons

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#1215]
**Describe the bug**

UI buttons used to look a lot more colorful before. I've provided screenshots. 

**What is the severity of the bug**

| severity/Low | Doesn’t affect primary flow/functionality but would be good to fix |
| --- | --- |

**Environment**
 - gitops: [v0.5.0]

**To Reproduce**

1. Run `gitops install --config-repo=<url>`
2. Run `gitops ui run`
3. See pale `Add Application` button

**Expected behavior**

All UI buttons should be saturated with color.

**Screenshots**

**THEN**

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/01252324-10bf-4bad-9158-07f22fd847de)

**NOW**

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/e1125c12-3c5d-41c4-8a14-7c122f5d8a83)

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/e01cb485-3b31-4957-8ca7-96e984f53b43)

**Comment by joshri** [comment]
@bia I think the buttons aren't even in the right place right now according to the docs - maybe we can make a button overhaul issue so I can get them exactly where we want them?

**Comment by bia** [comment]
Yes, the buttons need to move and the text within the buttons is also not centered and the [icon needs to come before the text](https://material.io/components/buttons#anatomy).

**Comment by bia** [comment]
However the buttons still need to moved to the position shown in the [Weave GitOps Core figma flow](https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/?node-id=4046%3A2032) : 
![20211214applications](https://user-images.githubusercontent.com/92439/146042544-74f8e9b3-ed0d-431e-a035-7a3ecbee18a0.png)

**Comment by joshri** [comment]
Addressed in #1228 - closing issue
