### ISSUE TITLE
UI - Add Application name needs additional validation to avoid submitting invalid names

### ISSUE THREAD

**Issue by owainperry** [weaveworks/weave-gitops#1216]
**Describe the bug**
The application name should have some additional validation on it in the Add Application UI. 

The application name can only be in RFC1123 format:

'[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'

At present it's possible to create applications with invalid names

**What is the severity of the bug**
severity/Low

**Environment**
 - gitops: [e.g. v0.1.0]
 - kubernetes:  [e.g. 1.20.4]
    - [ ] KinD - _version_]
    - [ ] k3s - _version_
    - [ ] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_
 - Browser + version: [e.g. chrome 74, safari 12, firefox 87]
 -
**Affects versions**

**To Reproduce**
1. Go to Add Application
2. Click on application name and enter something like: "foo " or "foo_bar_*" 
3. Make everything else valid on the form and submit. 
4. See error in the Kustomize pod logs : 

Kustomization/wego-system/podinfo_*_dave dry-run failed, reason: Invalid, error: Kustomization.kustomize.toolkit.fluxcd.io \"podinfo_*_dave\" is invalid: metadata.name: Invalid value: \"podinfo_*_dave\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')\n"}

**Expected behavior**
I would expect a validation error to bubble up either when loss of focus on the application name text box or when clicking submit or any other method that seems appropriate.

**Comment by jpellizzari** [comment]
I would like to keep the validation logic in the back-end, so doing this `onBlur` will require a new endpoint to validate the name.

I think we can just add this to the list of server validation tasks and return an error on form submission instead of `onBlur` as described here.

**Comment by palemtnrider** [comment]
Without enforcing the name, it's trivial to make mistakes like I did - extra space in the name.  This causes flux to fail syncing, which means the application isn't listed and additionally prohibits resources after this application from being applied.  Here is the flux error:
> kustomization/kind-kind-user    False   Kustomization/wego-system/phlegm  dry-run failed, reason: Invalid, error: Kustomization.kustomize.toolkit.fluxcd.io "phlegm " is invalid: metadata.name: Invalid value: "phlegm ": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')   

Which blocks my other application deployment.

CC @sympatheticmoose

**Comment by jpellizzari** [comment]
AC:
* Error out when a user tries to add an app with an invalid name
