### ISSUE TITLE
UI - first node is not centered in the loading behaviour

### ISSUE THREAD

**Issue by bia** [weaveworks/weave-gitops#1224]
![podinfo-4-centred-loading](https://user-images.githubusercontent.com/92439/145981619-e4df16aa-4d12-46f7-96ac-286ccf373f51.gif)

There is a jarring jump now that the application graph is loading horizontally in the center (#1202, #1195).

I think that we should avoid showing that first node in the first place, show a loading gif, and have the entire graph appear at once.

**Comment by opudrovs** [comment]
Closed as resolved in #2476
