### ISSUE TITLE
Graph can not zoom and maintain drag status

### ISSUE THREAD

**Issue by joshri** [weaveworks/weave-gitops#1225]
After dragging the graph to a new position, using the zoom slider will reset the graph to its original position. Both positions use the x and y properties of the svg's `transform: translate` style so it's going to take some investigation to find a workaround.

| severity/Minor | Weave Gitops functionality is broken, but there is a workaround |

**To Reproduce**
1. Go to Application Detail for an app in the UI
2. Drag the graph to a new position
3. Use the zoom slider

**Expected behavior**
Graph should be able to maintain drag position while changing zoom.

**Additional context**
Graph is rendered w/ zoom setup in a `useEffect`, making the zoom functions impossible to access in a way that doesn't trigger a render on every position change.

**Comment by opudrovs** [comment]
Closed as resolved in #2476
