### ISSUE TITLE
App Detail graphs for GitLab apps only display one node

### ISSUE THREAD

**Issue by joshri** [weaveworks/weave-gitops#1226]
**Describe the bug**
A wego GitLab app somehow loses its child nodes - or more likely never gets them, which results in only one node being displayed on the graph.

**What is the severity of the bug**
| severity/Minor | Weave Gitops functionality is broken, but there is a workaround |

**To Reproduce**
1. Add a GitLab app to the wego ui
2. Click on the app
3. Frown as you see only one node displayed on the graph

**Expected behavior**
I would expect GitLab apps to appear in the same way that GitHub apps do, with multiple nodes.

**Screenshots**
![image](https://user-images.githubusercontent.com/65822698/146036603-fb2b7605-5ef1-443f-b08e-527209067cab.png)

**Context**
Check the result of getApplication, and how it is processed through ReconciliationGraph and DirectedGraph

**Comment by sympatheticmoose** [comment]
Cannot reproduce.
