### ISSUE TITLE
Application Deployments

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#1231]
## Deploying Applications

As a user, I want to be able to manage my Applications in new ways via the CLI and UI.  

- Create an Application w/o deploying to a cluster (Core)
- Deploy an existing Application to a cluster of my choice (Core)
- Remove an application from a specific cluster (Core)

**Comment by palemtnrider** [comment]
We need to consider application updates as well. 
* if the application is deployed from a branch, likely no changes are necessary here.
* if the application is deployed from a tag or sha, we will need a way to specify that. (or decide that is an operation outside the scope of the API i.e., user updates the manifests in git directly
* Utilizing the image updater
