### ISSUE TITLE
Refresh application details graph when sync button is pressed.

### ISSUE THREAD

**Issue by J-Thompson12** [weaveworks/weave-gitops#1236]
Currently if a user presses sync the graph in the application details page will not update. 
Steps:
- Load application details page
- Update number of replicas for application
- Click sync button
- Graph does not change
- Reload page
- Graph is now correct

The graph needs to update when a user clicks the sync button.

**Comment by sympatheticmoose** [comment]
Perhaps regular polling similar to the applications summary page?

**Comment by sympatheticmoose** [comment]
Related comment from an internal exercise:
- Had to page reload the UI to see the updated commits (the list was cached showing older commit as the last synced)
  - Pressing the sync button doesn’t seems to update the source/kustomization commits list
