### ISSUE TITLE
Application page polling message doesn't update

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#1246]
The message "last updated 30 seconds ago" seems to be a static string so is only accurate for a second.

I _suspect_ the intent behind @bigkevmcd and @jpellizzari 's comments in https://github.com/weaveworks/weave-gitops/pull/1154 was that relative time is the easiest to understand for a user, but would therefore expect the message to update, i.e. every 10 seconds like "last updated 10 seconds ago, last updated 20 seconds ago, last updated 30 seconds ago". 

Given it is every 30 seconds, personally I would just hide this message as it is a small refresh window, the spinner gives some indication of the refresh occurring, and particularly at the moment when this page is sparse, it is more eye-grabbing than it warrants.

<img width="554" alt="Screenshot 2021-12-16 at 14 21 31" src="https://user-images.githubusercontent.com/19860021/146584441-8d821ccf-a512-4157-978c-a5d63c10e90e.png">

**Comment by sympatheticmoose** [comment]
@bia please update if you disagree

**Comment by bigkevmcd** [comment]
What I outlined in that issue is really common, https://www.npmjs.com/package/javascript-time-ago might help
