### ISSUE TITLE
When authenticating with Github, if link is not valid user needs to be shown an error

### ISSUE THREAD

**Issue by AlinaGoaga** [weaveworks/weave-gitops#1250]
**Describe the bug**
At the moment, if the Github link in Github Auth is not valid, the user is not provided feedback and the auth goes into a loop where the user is shown the modal to authenticate. 

**What is the severity of the bug**
| Label | Description |
| severity/Low | Doesn’t affect primary flow/functionality but would be good to fix |

**Expected behavior**
The user should be shown an error if the Github link is not valid.

**Comment by sympatheticmoose** [comment]
Hi @AlinaGoaga could you provide a little more detail (and maybe an example) on the manner in which the URL is invalid?
