### ISSUE TITLE
Consensus on how to address breaking changes related field changes

### ISSUE THREAD

**Issue by josecordaz** [weaveworks/weave-gitops#1253]
**Short description**
As a developer I want to have some guide/rules/considerations so that we have our code base understandable without adding breaking changes.

There was a resent change in one of our fields called `AppConfigURL`. It was renamed to `ConfigRepo`. But now we have this in our code base:

```
ConfigRepo string 'json:"config_url,omitempty"'
```

Which is a bit confusing as the fields do not match. 

**Acceptance criteria**
- [ ] The description of the field `config_url ` matches the actual name of the field in the wego app spec.
- [ ] There is no braking changes for users that already have the field `config_url`

- One suggestion was adding support for both fields

**Comment by jpellizzari** [comment]
The work for this ticket will be to fix the inconsistency in the description.
