### ISSUE TITLE
Have a single source to describe the use of the flag `auto-merge`.

### ISSUE THREAD

**Issue by josecordaz** [weaveworks/weave-gitops#1254]
**Short description**
As a user I want to see the same description of the flag `auto-merge` so that I do not get confused by the meaning of it.

**Acceptance criteria**
- [ ] See the same description for `auto-merge` flag in install, add and delete comamnds

**Comment by jpellizzari** [comment]
@josecordaz Can you enumerate the different places where the flag is described?

**Comment by jpellizzari** [comment]
Should be `Add`, `Install` and `Remove` commands that need to be looked at.
