### ISSUE TITLE
Move to corporate Snyk account

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#1262]
We are currently using the `dinosk` org for Snyk scans. Maybe we can also evaluate if Snyk is necessary. It seems to add a lot of heft to our CI pipelines; I'm wondering if we can use some built-in GH functionality for vulnerability scanning.

**Comment by mnowster** [comment]
I have org admin privs, so I can take a look. we have a corp account so happy to help fix this.

**Comment by mnowster** [comment]
This now uses our org token, it should have better performance. 

I have some other questions about how our snyk github action workflow is configured but we'll open seperate issue on that after some security discussion.

so I'm going to close this as Done ✅ , please open any new ones and include me if there are other snyk issues 👍🏻
