### ISSUE TITLE
Allow for multiple HelmRepositories to be Profile repos

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/weave-gitops#1306]
After https://github.com/weaveworks/weave-gitops/issues/1144 has been finished, we have the ability to get profile related values for all HelmRepositories not just the ones configured. Since the watcher is watching and caching data from all repositories not just one.

This is, however, a breaking change as we will, remove or change, the following things:

- The configurable HelmRepository namespace and name from the profiles server in wego-core
- The UI component of GetProfileValues to use the HelmRepository from the previous call in order to find out which repository a profile belongs to and list values for that in wego-enterprise
- The CLI command line arguments which define helmrepository values when starting in wego-core

These changes can be introduced after the Watcher and the Cache is finish to isolate the breaking changes as much as possible.

This is a relatively small change but spans two repositories so it is being left out from 1144.

**Comment by bigkevmcd** [comment]
We can hopefully incrementally move this forward:

 1. scanning all, returning the repository in the responses
 2. if no repository is provided in client calls, we default to the configured one
 3. fail if no repository is provided (i.e. remove the defaulting)
