### ISSUE TITLE
Performing `gitops install` fails with bad credentials

### ISSUE THREAD

**Issue by richardcase** [weaveworks/weave-gitops#1310]
**Describe the bug**
I am following the [getting started guide](https://docs.gitops.weave.works/docs/getting-started) and when i do this:

```bash
gitops install --config-repo git@github.com:richardcase/gitops-config.git
```

I get the following error:

![image](https://user-images.githubusercontent.com/198425/149897085-d2dae05c-53ae-4fbe-8442-73460d7c694e.png)

**Environment**
 - gitops: 0.6.0
 - kubernetes:  1.21.1
    - [x] KinD - v0.11.1

 - Browser + version: n/a
 -
**Affects versions**

**To Reproduce**
Following the quickstart guide

**Expected behavior**
I would expect the `gitops install` command to succeed. Also i see nothing in the quickstart guide around credentials/auth for GitHub.

**Config and Logs**
If applicable, add logs to help explain your problem. _please compress the output before attaching_
- [ ] gitops config
- [ ] `gitops` cli call output (and parameters)
- [ ] gitops-controller logs
- [ ] Events from wego-* namespaces
- [ ] `kubectl cluster-info dump`
- [ ] Prometheus alerts
- [ ] Flux logs

**Screenshots**

**Additional context**

**Comment by sympatheticmoose** [comment]
this _looks_ like you have `$GITHUB_TOKEN` set in your environment, but the token is not valid (expired perhaps). Without this set, you would be directed to login via your browser - hence why no mention in the getting started guide (less pre-requisites). The CLI would prompt on any use of the device flow login that you can avoid this by setting `$GITHUB_TOKEN`. However, we should add a specific page/topic detailing the setting of the token.

**Comment by richardcase** [comment]
It was `GITHUB_TOKEN` being set in the environment. I've unset it and the device login flow starts. I think some sort of docs in this area will help.

Oh dear now i have an `knownhosts: key mismatch` error :(

**Comment by richardcase** [comment]
@sympatheticmoose - should i close this and create a new issue around the docs?

**Comment by sympatheticmoose** [comment]
@richardcase were you able to resolve the known_hosts issue and was there any guidance we could add / changes we could make as a result?

For docs around the setting of `GITHUB_TOKEN` yes a new issue in the docs repo would be great to track.

**Comment by richardcase** [comment]
Closing and will create an issue in the docs repo
