### ISSUE TITLE
Add deploy key only when needed

### ISSUE THREAD

**Issue by J-Thompson12** [weaveworks/weave-gitops#1323]
The issue #1278 reported a bug where we are unable to install or add a repo if the config repo is public because there is no deploy key. This causes wego to be unable to clone the repo. #1301 is a temporary fix to allow us to do a release and be able to deploy. That fix is not the desired fix. We need to find a better interface to handle if a deploy key should be added or not. RepoUrl is not the right place.

Acceptance criteria:
- Deploy key is only added when it is needed like on install or for private repos
- The quick fix #1301 has been removed

**Comment by rokshana-b** [comment]
﻿
![Screen Shot 2022-01-27 at 23 00 43](https://user-images.githubusercontent.com/76788247/151841127-cb7d75aa-45fb-4e25-a261-541676811b6f.png)
![Screen Shot 2022-01-27 at 23 03 04](https://user-images.githubusercontent.com/76788247/151841128-a18fe485-219f-4db0-91f7-59780d0f647d.png)
![Screen Shot 2022-01-27 at 23 10 14](https://user-images.githubusercontent.com/76788247/151841129-66717844-2ed5-47b6-a135-b1127cd4c458.png)

**Comment by rokshana-b** [comment]
@J-Thompson12 ^^
