### ISSUE TITLE
Error adding application : error adding app: can not determine cluster status... exiting

### ISSUE THREAD

**Issue by mtparet** [weaveworks/weave-gitops#1354]
**Describe the bug**
Got "Error adding application : error adding app: can not determine cluster status... exiting" when adding a new application through the wego-app app UI.

**What is the severity of the bug**
| severity/Major | Weave Gitops functionality is broken, there is a workaround, and the workaround requires significant effort |

**Environment**
 - gitops: 0.6.2
 - kubernetes:  1.21.7
    - [ ] KinD - _version_]
    - [ ] k3s - _version_
    - [ ] cloud [e.g., EKS, AKS]  _version_
    - [x] minikube
 - Browser + version: chrome 97
 -
**Affects versions**

**To Reproduce**
1. `minikube start`
2. `~/App/bin/gitops install --config-repo git@github.com:mtparet/testigops.git`
3. `kubectl port-forward service/wego-app 9001:9001 -n wego-system`
4. Go to http://127.0.0.1:9001/application_add
5. Fill all the things
6. Click on "Submit"

**Expected behavior**
No errors

**Config and Logs**
If applicable, add logs to help explain your problem. _please compress the output before attaching_
- [ ] gitops config
- [ ] `gitops` cli call output (and parameters)
- [ ] gitops-controller logs
- [x] Events from wego-* namespaces
```
kubectl logs -f wego-app-5f5f4fddf7-ddhmd -n wego-system
2022-01-27T14:43:45.517Z	INFO	app/add.go:118	
2022-01-27T14:43:45.517Z	INFO	kube/kube.go:71	Checking cluster status
2022-01-27T14:43:45.536Z	ERROR	middleware/middleware.go:39	server error	{"error": "error adding app: can not determine cluster status... exiting"}
github.com/weaveworks/weave-gitops/pkg/server/middleware.WithGrpcErrorLogging.func1
	/app/pkg/server/middleware/middleware.go:39
github.com/grpc-ecosystem/grpc-gateway/v2/runtime.HTTPError
	/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.7.1/runtime/errors.go:81
github.com/weaveworks/weave-gitops/pkg/api/applications.RegisterApplicationsHandlerServer.func11
	/app/pkg/api/applications/applications.pb.gw.go:993
github.com/grpc-ecosystem/grpc-gateway/v2/runtime.(*ServeMux).ServeHTTP
	/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.7.1/runtime/mux.go:300
github.com/weaveworks/weave-gitops/pkg/server/middleware.WithLogging.func1
	/app/pkg/server/middleware/middleware.go:53
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
github.com/weaveworks/weave-gitops/pkg/server/middleware.WithProviderToken.func1
	/app/pkg/server/middleware/middleware.go:115
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
net/http.(*ServeMux).ServeHTTP
	/usr/local/go/src/net/http/server.go:2425
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2879
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1930
2022-01-27T14:43:45.537Z	DEBUG	middleware/middleware.go:66	server error	{"uri": "/v1/applications", "status": 500}

```
- [ ] `kubectl cluster-info dump`
- [ ] Prometheus alerts
- [ ] Flux logs

**Screenshots**

![image](https://user-images.githubusercontent.com/754770/151381876-e970d9e5-3e34-468c-8236-d5791e773f71.png)

**Additional context**

**Comment by mtparet** [comment]
It's working using `~/App/bin/gitops ui run`

**Comment by talaverant** [comment]
Thanks @mtparet !!!! Good that it works with ui run! Could you clarify what you mean with "is not shown"? It's no showing in the web UI?

**Comment by mtparet** [comment]
Ok I found `Releases` is not an acceptable name that why it does not synced but we should see an error in the gitops UI.

**Comment by mtparet** [comment]
It is fixed
