### ISSUE TITLE
wego flux command prints unhelpful message when wrong flag is used

### ISSUE THREAD

**Issue by iahmad9** [weaveworks/weave-gitops#137]
**Describe the bug**
wego flux command prints unhelpful message when wrong flag is used

**Environment**
 - wego: v0.0.0
 - 
**Affects versions**
- wego: v0.0.0

**To Reproduce**
1. Download or build the latest `wego` binary
2. Run command `wego flux abcd`
3. Observe that it prints an error message `Error: exit status 1`

**Expected behavior**
 Expected Results: It should display a more descriptive error message. e.g. `invalid flag for flux command` along with help text

**Comment by luizbafilho** [comment]
I've fixed that issue, now it should proxy everything to flux and that will make it print a helpful message.

https://github.com/weaveworks/weave-gitops/pull/154
