### ISSUE TITLE
Migrate UI build from npm to yarn

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#1373]
We should migrate the UI build from npm to yarn so that we can use built-in capabilities such as `yarn why` and resolutions to force package versions when security issues are encountered. For the latter, we are using npm-force-resultions but it is an addon package and doesn't provide the same flexibility as the one provided by Yarn.  https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

We currently build with 
```shell
/opt/hostedtoolcache/node/14.18.3/x64/bin/node --version
v14.18.3
/opt/hostedtoolcache/node/14.18.3/x64/bin/npm --version
6.14.15
```
And these are older versions for node/NPM and require the developer to install these older versions to ensure they are building the same way the CI system does.

## Acceptance
* Ensure all the current resolutions defined in package.json produce the same package-lock.json file.
* CI builds are updated to yarn
* Update the readme so new developers know how to set up their environments 
* communicate to the wide development group about the change.

**Comment by mnowster** [comment]
Can we change this to a spike/discussion to be had please? This is not a decision that's a done deal. 

It needs some facilitation and input from wider group of frontend engineering around choices, as with anything, there's trade offs all around.
