### ISSUE TITLE
Helm Chart for Weave Gitops

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#1379]
Create a helm chart for Weave GitOps.  The criteria is that we will be able to install Weave GitOps Core via a Helm Release.

Initial Criteria
* Do not include anything from Flux bootstrap
* Each yaml file should be separate and not lumped into a single file.
* You should be able to configure the namespace value via a "value parameter"

**Comment by mnowster** [comment]
We have one: https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/Chart.yaml
