### ISSUE TITLE
Docker Push Timing Out

### ISSUE THREAD

**Issue by joshri** [weaveworks/weave-gitops#1389]
Running `./tools/kind-with-registry.sh` and `make cluster-dev` ends with this error on Tilt `Build Failed: docker push: pushing image "localhost:5000/weaveworks/wego-app": Get "[http://localhost:5000/v2/":](http://localhost:5000/v2/) net/http: request canceled (Client.Timeout exceeded while awaiting headers)`, and I'm also getting the timeout when running `docker login` just to test things out.

| severity/Critical | Weave GitOps is crashing or experiencing data loss, and there is no known workaround |

**Environment**
 - gitops: 0.6.2
 - kubernetes:  1.22.2
 - kind: 0.11.1
 - MacOS: Monterey 12.1
 - Docker Desktop: 4.3.2

**To Reproduce**
1. Run `./tools/kind-with-registry.sh`
2. Run `make cluster-dev`
3. Check out Tilt output in browser

**Expected behavior**
Docker is able to push the image to localhost

**Screenshots**
![image](https://user-images.githubusercontent.com/65822698/152393059-728c8b61-a584-470d-bdbd-c15b17c506c4.png)

**Comment by josecordaz** [comment]
It didn't work for me either on macOS Monterey `12.1` and docker `20.10.11`

**Comment by aclevername** [comment]
@Skarlso is this the AirPlay issue?

**Comment by Skarlso** [comment]
Yes. @josecordaz Disable AirPlay under System Preferences -> Sharing.

**Comment by joshri** [comment]
We both turned off Airplay to clear up port 5000 and we still get the error

**Comment by Skarlso** [comment]
Ok, no idea at the top of my head. I'll need to look into it tomorrow.

**Comment by Skarlso** [comment]
Try to find out if anything else might be listening on 5000? Although, frankly, it would have failed starting probably:


```
netstat -an | grep "5000" | grep "LISTEN"

netstat -vanp tcp | grep 5000

lsof -i tcp:5000
```

**Comment by Skarlso** [comment]
<img width="1920" alt="Screenshot 2022-02-07 at 21 45 35" src="https://user-images.githubusercontent.com/182850/152869140-02ee062a-0c0a-4104-94c1-99c8d702d696.png">


Oh WOW. I actually reproduced this with main. I'll try another `make clean && make all` run but this looks interesting. I think it might be that Jake's incoming change to run the registry on 5001 might work, since tilt is apparently also using 5000. So they might be colliding.

**Comment by joshri** [comment]
Yeah we would get a different error when there was an issue with port 5000, but it seemed like unchecking airplay removed any processes that were running. Thanks for looking into this @Skarlso!!!

**Comment by Skarlso** [comment]
Looks like I'm right. There was a push to kind example 3 days ago:
https://github.com/kubernetes-sigs/kind/commit/bfce9c8ec29a777b06ce17210c65c50627036d69

Which changes the port to 5001.

**Comment by Skarlso** [comment]
That did not work. Huh.

**Comment by Skarlso** [comment]
Ah. I think I know what's up. The bridge network might be incorrect.
