### ISSUE TITLE
Feature Request - Support for self hosted Git servers

### ISSUE THREAD

**Issue by steveww** [weaveworks/weave-gitops#1399]
Gitlab can be run onsite. As such it may have an unusual URL e.g. https://src.acme.net:8443/ ssh://git@src.acme.net:2222/

Weave GitOps should be able to handle this through the full life cycle. At the moment it gets confused and tries to contact the public cloud for authorisation. There is an undocumented switch `--git-host-types` to tell it what type of repo it is. This should be clearly documented, perhaps a separate section on privately hosted Git servers.

**Comment by steveww** [comment]
Self hosted Gitlab may use a self signed certificate. This certificate needs to have `-addext "subjectAltName = DNS:host` entry. However, `gitops install` still fails with `certificate signed by unknown authority`. There should be an additional switch to ignore this condition like `curl -k`.

**Comment by steveww** [comment]
Got around the CA by installing my own.
However, gitops gets really confused when things are not on the normal ports. It tries to connect to SSH on the HTTPS ports or tries to connect to HTTPS on the SSH port. The logic is a bit screwed here.

**Comment by davidberglund** [comment]
Are self hosted Gitlab servers supported at this point?

**Comment by JamWils** [comment]
`gitops install` was deprecated.  Closing
