### ISSUE TITLE
/v1/profiles returns profile versions in ascending order

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops#1432]
**Describe the bug**

Response from `/v1/profiles` includes versions in ascending order

```
"availableVersions": [
"5.2.0",
"5.2.1",
"6.0.0",
"6.0.1"
]
```

**What is the severity of the bug**

**Affects versions**

0.6.2

**Expected behavior**

Return versions in descending order with the latest release first

**Comment by LappleApple** [comment]
Still an issue? cc @bigkevmcd

**Comment by foot** [comment]
No, don't think so
