### ISSUE TITLE
Failing acceptance tests

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/weave-gitops#1456]
Pended the acceptance test `SmokeTestLong - Verify that gitops can deploy an app with long name`, which was failing [here](https://github.com/weaveworks/weave-gitops/runs/5216969389?check_suite_focus=true) with:
```
• Failure [302.259 seconds]
Weave GitOps Add App Tests
/home/runner/work/***/***/test/acceptance/test/add_tests.go:29
  @skipOnNightly SmokeTestLong - Verify that gitops can deploy a single workload to multiple clusters with app manifests in config repo (Bug #810) [It]
  /home/runner/work/***/***/test/acceptance/test/add_tests.go:1404

  Unexpected error:
      <*errors.errorString | 0xc000139ab0>: {
          s: "Failed to delete app test-app-dvnup739",
      }
      Failed to delete app test-app-dvnup739
  occurred

  /home/runner/work/***/***/test/acceptance/test/add_tests.go:1522
```

Its failure was blocking one of the checks that are required for branch merging, which was in turn blocking https://github.com/weaveworks/weave-gitops/pull/1445 from being merged.

Seems related to #1449 and other `v2` work. 

Edit : [Gini] 
Another test seems to be failing when I tried to fix the broken main https://github.com/weaveworks/weave-gitops/pull/1458
https://github.com/weaveworks/weave-gitops/runs/5221157992?check_suite_focus=true

```
• Failure [155.910 seconds]
Weave GitOps Add App Tests
/home/runner/work/***/***/test/acceptance/test/add_tests.go:29
  @gitlabTests Test3 - Verify that gitops can deploy and delete a gitlab app in a subgroup [It]
  /home/runner/work/***/***/test/acceptance/test/add_tests.go:1169

  Unexpected error:
      <*errors.errorString | 0xc00043f260>: {
          s: "Failed to delete app test-app-idejv7a5",
      }
      Failed to delete app test-app-idejv7a5
  occurred

  /home/runner/work/***/***/test/acceptance/test/add_tests.go:1236
------------------------------
```

This ticket needs some investigation on why these tests fail. There's a suggestion about increasing wait time by @rokshana-b  https://github.com/weaveworks/weave-gitops/pull/1458#issuecomment-1042002113 , should be considered as part of this investigation. These all seem to be failing in the same file/suite.

**Comment by rokshana-b** [comment]
Closing this issue since these tests no longer exist.
