### ISSUE TITLE
Implement UI breadcrumbs

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#1460]
Make these, but don't do the number:

![Screenshot from 2022-02-16 14-51-13](https://user-images.githubusercontent.com/2802257/154370931-83b61c2e-7336-4d0d-838e-3e6287d793ce.png)

We can't do the number  because it would involve fetching data for pages that we are not currently looking at.

Notes: Steal from enterprise repo?

**Comment by LappleApple** [comment]
@jpellizzari ok to close this?

**Comment by jpellizzari** [comment]
Closing!
