### ISSUE TITLE
Removal

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#1475]
### Why?

1. We are removing the existing “application” from Weave GitOps which means removing all of the commands for interacting with that application.
2. We are no longer wrapping around the Flux binary, so those commands no longer need to exist as well.

### Out of Scope

1. Cluster and Profile commands.
2. Super User impersonation.
    1. Auth story being worked in Pesto - current working approach requires CLI to set up super user.  We need to follow-up with Pesto, but it looks like a secret is created on the cluster with a temporary password that the user should delete once they change the password.

### What does good look like?

The code is cleaned up and the following CLI commands, endpoints, and application Custom Resource are removed.  The majority of application code is removed from the codebase as well as Flux code.

- All CLI commands marked for deletion are removed.
- App CRD is removed
- Application UI code and gRPC endpoints are removed from the codebase.
- We no longer ship with a Flux binary in Weave GitOps.  All code and make commands, and auto PRs managing this is deleted.
- Remove auto PR for when a new Flux release occurs.

**Comment by JamWils** [comment]
1. FE will take ownership of removing their own code and dependencies such as proto files.
2. Once the Flux binary is removed then we could do another code sweep.

Note: auth is still being used for profiles.
