### ISSUE TITLE
Acceptance Tests

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#1479]
- What is the scope of removal?
  - 90% of the tests will go away as we're deleting CLI commands
- What are the new tests that need to be added?
  - From now on, tests will be UI-centric rather than CLI-centric
  - Once a level of stability is achieved, UI-based test writing will begin
 - Issues from past experiences:
   - Test slow down due to k8s resource deletions
   - Lack of test parallelism
   - Local test running difficulties
   - Noisy CLI outputs
 - Document capturing these issues in detail:
   - [LINK](https://docs.google.com/document/d/1QoOZdBGU5rcpzdz569-HowKpXzyXO-qyocXHxQlLlYw/edit#)

**Comment by JamWils** [comment]
Focus on low hanging fruit:
* Noisy outputs
* Flaky tests
* Failing early
* Get acceptance tests running on v2

More challenging bits:
* Parallel test runs
