### ISSUE TITLE
CI Pipeline

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#1480]
**What does good look like?**

Super smooth CI.  We understand what the workflows look like today and can eliminate waste.  Developers want feedback quick.  Flaky tests are flagged or better yet addressed.  Workflows need to be simplified.

Examples for feedback:

- Did I run gofmt?
- Did I update the generated code for protobufs?
- ...

Reasonable time threshold depending on the task that is being completed:

- Linting and vetting should be quick
- BE and FE unit tests take minutes
- Acceptance tests can be long

Errors are clear and the developer can easily find what to do next.

Any integration and acceptance tests can be run locally with ease.  Locally can be a docker container on your local machine.  I.e. they are easy to run and you don’t need to push to Github.

**Comment by SamLR** [comment]
I've sketched some thoughts here https://gist.github.com/SamLR/7fd3a307726cfeeece215167358badef

**Comment by LappleApple** [comment]
Closing this due to age and low priority.
