### ISSUE TITLE
Create a cluster client abstraction

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#1485]
From our discussion in this doc: https://docs.google.com/document/d/1eK4ACk0bruheV_dJawg9xeQiHhiqdcVxcfLimcZbyrY/edit

We should probably try to future-proof our cluster querying by abstracting the way we fetch data from clusters to make it easier to change things later.

We currently use a `controller-runtime` client in the `core/server` package.

Implementation Notes:
* Create a `ClusterClient` `interface` in a new `core/clusterclient` package
* It should roughly look like the `controller-runtime` client `interface` (`.Get` and `.List` for now)

Could be this:

```go
type ClusterClient interface {
  client.Client
}
```

**Comment by yitsushi** [comment]
What implements that (non-existing-yet) interface?

**Comment by jpellizzari** [comment]
> What implements that (non-existing-yet) interface? Or what would use that interface in our system?

The API server would (probably) consume this in place of the current `controller-runtime` client it uses.
