### ISSUE TITLE
Ensure we use TLS when serving API

### ISSUE THREAD

**Issue by richardcase** [weaveworks/weave-gitops#1499]
We need to ensure that the API is served with TLS so that the transport is encrypted. Without this tokens can be sniffed etc.

**Comment by jpellizzari** [comment]
We probably need to do an `--insecure` flag to disable this as well.

**Comment by jpellizzari** [comment]
Related https://github.com/weaveworks/weave-gitops-enterprise/issues/405

**Comment by josecordaz** [comment]
Some questions:
1.- Which domain the certificate would need to point to?
2.- Where can I get one for production? corp-it? Do we need one for local development? Or we just skip TLS locally?
3.- Should we store the certificate in the repository?

**Comment by richardcase** [comment]
> 1.- Which domain the certificate would need to point to?
This depends on the user who will be using Core. We can't stipulate anything here.

> 2.- Where can I get one for production? corp-it? Do we need one for local development? Or we just skip TLS locally?
I think we need to provide docs for generating self-signed certs using openssl and to specify these when installing core.  We could also write docs for using cert-manager/lets encrypt. Perhaps even the TLS certs feature directly in k8s as well.

For local dev we can rely on self-signed certs (and we could include a script/make target for generating them). And we should have the `--insecure` option where we don't use TLS. But the `--insecure` option shouldn't be the default....it needs to be an explicit decision by the user to run insecurely.

> 3.- Should we store the certificate in the repository?
I don't think you can unless you use sealed secrets or sops.

@josecordaz - shall we chat?

**Comment by josecordaz** [comment]
@richardcase  Thanks for answering. I'll try to address your last comments. I'll definitely reach out if I get some more questions.

**Comment by josecordaz** [comment]
@richardcase I just addressed your comments in this draft PR https://github.com/weaveworks/weave-gitops/pull/1537. Please take a look once you have a chance. Let me know if that would work.
