### ISSUE TITLE
Apply filtering and search to pages with a data table

### ISSUE THREAD

**Issue by joshri** [weaveworks/weave-gitops#1506]
The `<FilterBar />` component requires a couple things from the parent component in order to function properly -

1. Filtering options need to be grabbed from data and passed down in the format of `{<columnName>: [...options], }` - could be the job of a utils function. Do we want every column in every table to have every possible option filterable?

2. Active filters state needs to be stored in parent and passed down, and also applied to the data in the `rows` prop of `<DataTable />`.

3. Component needs to be rendered above `<DataTable />` - which brings up the question of potentially removing the `children` prop of `<DataTable />` and just rendering `<Pagination />` under the table to keep things consistent?

We also need to add the check/uncheck all option to each filter heading - along with the css changes to match.

The `<SearchInput />` is similar - but is only meant to filter the `Name` column of the table it's applied to - `search` and `setSearch` have to be passed down from the parent, and `search` has to be applied to `rows` like in step 2.

**Comment by joshri** [comment]
@JamWils @sympatheticmoose @bia tagging to start a discussion on which columns should be filterable on each page. Right now all I know is that `Name` is out since it's being handled by the search input.

**Comment by bia** [comment]
@joshri, seems like Name, Cluster, Status, Type are prioritised here in Notion : https://www.notion.so/weaveworks/Flux-Observability-22f24cf2573e4f888bb804750d543822#279793591dd6457b8aeab88240fbb49b

Might be good for @AlinaGoaga and @foot to know where we are at here too.
