### ISSUE TITLE
Turn CI workflows into 1 flow per type

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#1511]
The main branch CI workflow was captured by https://miro.com/app/board/uXjVONz103E=/?fromRedirect=1

The deep blue boxes represent separate files with separate flows. There's way too many of them.

There should be 1 flow per separate occasion. The separate occasions are approximately 3: "PR/merge", "nightly/periodic" and "release".

**Comment by JamWils** [comment]
Closed this since so much has changed since it was written.
