### ISSUE TITLE
'cannot list resource "helmrepositories" in API group "source.toolkit.fluxcd.io" at the cluster scope'

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#1535]
This error is shown in the wego logs which leads to an error on the UI.

We are possibly not scoping a call to a namespace, so the call is going cluster-wide, thus asking for a cluster scope.

**Comment by Callisto13** [comment]
The errors
```
cannot list resource "helmrepositories" in API group "source.toolkit.fluxcd.io" at the cluster scope
```
and
```
{"error": "list resource: deployments.apps is forbidden: User \"system:serviceaccount:flux-system:wego-app-service-account\" cannot list resource \"deployments\" in API group \"apps\" in the namespace \"flux-system\""}
```
are caused by [this bit](https://github.com/weaveworks/weave-gitops/blob/v2/cmd/gitops-server/cmd/cmd.go#L151-L168) around profiles 

we are not sure why profiles are in core, so for now i am going to leave this and come back round once i have finished the service account work

**Comment by Callisto13** [comment]
Update for those playing along at home:

So this profiles (helm) watcher is start on wego-app launch. This means that it will use whatever powers the wego-app SA has to look up resources. It does not impersonate at all, and I am not sure it can, since queries do not come from the user; the watcher is just "on" all the time. This gets in the way of our "impersonate all the things all the time plan". To maintain the current profiles feature, the wego SA would need to have Cluster scope access to the objects that profiles cares about.

**Comment by bigkevmcd** [comment]
It can run with its own ServiceAccount?

**Comment by bigkevmcd** [comment]
And for this, I think it's fine to not impersonate all the time, as you say, it's not the user that's doing the queries.

It does raise some interesting questions around which ones we can show data from tho'.

So, maybe we query for the `HelmReleases` with impersonation, and use that to look in the cache?

**Comment by Callisto13** [comment]
> It does raise some interesting questions around which ones we can show data from tho'.

Yeh that's an interesting thought.

I am going to close this ticket, as the error is solved, and will open a new ticket to do the "make sure people see profiles they are meant to" bit.

**Comment by Callisto13** [comment]
@bigkevmcd by "cache" are you talking about the disk-based profiles cache which I just spotted?

**Comment by bigkevmcd** [comment]
@Callisto13 yes, there's a cache of the parsed data extracted from the Helm charts repositories.

**Comment by Callisto13** [comment]
👍  coolio
