### ISSUE TITLE
@jpellizzari TODO: rework these tests helpers to not be so cumbersome to use

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#1552]
@jpellizzari TODO: rework these tests helpers to not be so cumbersome to use

_Originally posted by @jpellizzari in https://github.com/weaveworks/weave-gitops/pull/1550#discussion_r816346499_

**Comment by sympatheticmoose** [comment]
@jpellizzari still valid?

**Comment by jpellizzari** [comment]
Nope
