### ISSUE TITLE
gitops delete app x is not working using CLI

### ISSUE THREAD

**Issue by talaverant** [weaveworks/weave-gitops#1554]
**Describe the bug**
After trying to delete an app using the UI ( which didn't work), we tried to delete an app using the CLI and the gitops delete app. This command is not working either and the app is still showing on the UI and also when I run gitops get app. The merge was completed successfully and the app files are not present in the repo anymore.

**What is the severity of the bug**
Not being able to delete an app via UI nor gitops CLI could have a big impact on cluster management!

| Label | Description |
| --- | --- |
| severity/Major | Weave Gitops functionality is broken, there is a workaround, and the workaround requires significant effort |
There is no workaround afaik!

**Environment**
 - gitops: [e.g. v0.6.2]
 - kubernetes:  []
    - [ ] cloud [EKS] 
**Affects versions**

**To Reproduce**
1. Go to the cluster running the app

2. Run command gitops delete app x
3. Merge PR
4. Run command gitops get apps
5. Check the Apps UI
6. App will still show there.

**Expected behavior**
After running the delete command, we expect the app to be deleted from the UI and not show using gitops get apps.

**Config and Logs**
Which logs will be required?

**Screenshots**
![image](https://user-images.githubusercontent.com/53871388/156132439-65337921-2813-4d5a-8263-c9a9c6c0010b.png)

**Additional context**
Deleting the app thru the UI was tested before and didn't work either.

**Comment by sympatheticmoose** [comment]
Unfortunately I've been unable to reproduce this with WGC v0.6.2, both deleting via the UI and CLI successfully removed the manifests from the repo and the cluster reconciled this appropriately.
