### ISSUE TITLE
Add deployment type flag to add commmand

### ISSUE THREAD

**Issue by josecordaz** [weaveworks/weave-gitops#157]
**Short description**
As a usue I want to be able to set the deployment type of the app repo I'm adding so that we can support kustomize and helm options.

**Acceptance criteria**
- [ ] user should be able to specify the flag `--deployment-type` and accept the values `kustomize` or `helm`.
- [ ] if the flag it is not provided it should default to `kustomize` type.
- [ ] if the value isn't any of the accepted options. It should let the user know the available options.

**Comment by luizbafilho** [comment]
Hahah I added everything but forgot to the command flag. 🤦 

One comment tho, we should just default to Kustomize, which also applies plain yaml,
