### ISSUE TITLE
Add docs page to left menu nav

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#1575]
<img width="263" alt="Screenshot 2022-03-03 at 11 21 16" src="https://user-images.githubusercontent.com/19860021/156554991-40f81f52-73b7-4793-a9a3-38a009302381.png">

Link to https://docs.gitops.weave.works/ (force open in new tab) @bia any thoughts on whether need to indicate this behaviour somehow, and please confirm that you no longer want docs to appear in the footer as with the previous design.

<img width="646" alt="Screenshot 2022-03-03 at 11 31 43" src="https://user-images.githubusercontent.com/19860021/156556466-dece4314-5ea6-4aec-baf4-1c190b641407.png">

**Comment by bia** [comment]
Good shout, it's a common pattern for docs to be external links, so I don't think that we need a visual representation of that unless we end up adding another external link to this sidebar.
