### ISSUE TITLE
URL text is smaller than other elements in table

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#1578]
<img width="777" alt="Screenshot 2022-03-03 at 11 27 05" src="https://user-images.githubusercontent.com/19860021/156555775-59520bd7-6048-4449-858f-1b600c976fe1.png">

I believe the design calls for 14px throughout the table entries, @bia can you confirm?

It appears the name is 14px and the others (type namespace status etc) are all 16px which is very jarring to me

**Comment by jpellizzari** [comment]
Weird, probably related to the use of a `<Link />` component there

**Comment by bia** [comment]
Yes, all table text is `14px` in the design.
