### ISSUE TITLE
Sort arrow is off center on details pages

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#1579]
From applications > sources (correct)
<img width="125" alt="Screenshot 2022-03-03 at 11 28 45" src="https://user-images.githubusercontent.com/19860021/156556062-66c61e1d-b6d3-4177-8e18-2df2d2544502.png">

From applications > sources > source (incorrect)
<img width="301" alt="Screenshot 2022-03-03 at 11 28 43" src="https://user-images.githubusercontent.com/19860021/156556065-8fcb82fa-f9ee-48dd-9668-3caa16b2c1ae.png">

**Comment by joshri** [comment]
Hey @sympatheticmoose - I can't reproduce 

![image.png](https://images.zenhubusercontent.com/617c4a20ede496b2fae35baf/59c00f87-4f9c-48ee-b6df-9c959028699c)

@jpellizzari do you see this on your system?

**Comment by jpellizzari** [comment]
No mine looks good. Chrome on linux. @joshri Check it out in Safari?

**Comment by sympatheticmoose** [comment]
Mine was chrome on Mac
