### ISSUE TITLE
Develop UI for application creation that invokes the Api Server

### ISSUE THREAD

**Issue by jrryjcksn** [weaveworks/weave-gitops#159]
**Short description**
As a WeGO user, I would like to create my applications via the UI.

MORE INFO COMING

**Acceptance criteria**
- [ ] _does X_
- [ ] _displays Y_
- [ ] _..._

**Design materials**
- Screenshots
- Design diagrams
- WEP 
- PR/FAQ

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by markramm** [comment]
We need create application implementation to work behind an API.

**Comment by jpellizzari** [comment]
https://balsamiq.cloud/s5qd59g/pks8dty/r0B98

**Comment by markramm** [comment]
Needs technical definition of how we manage API's and authentication.

**Comment by jpellizzari** [comment]
Waiting on auth story to reach consensus

**Comment by jpellizzari** [comment]
Closing as part of an issue cleanup effort discussed with @JamWils and @markramm
