### ISSUE TITLE
Bug: attempting to sort via message column in release details view causes error

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#1591]
<img width="725" alt="Screenshot 2022-03-03 at 12 11 50" src="https://user-images.githubusercontent.com/19860021/156562832-a9f8282f-b31f-45a1-a29b-b2fa9733ce49.png">

**Comment by jpellizzari** [comment]
From standup: check the `short` flag on `KubeStateIndicator`
