### ISSUE TITLE
Smooth out development setup

### ISSUE THREAD

**Issue by luizbafilho** [weaveworks/weave-gitops#1594]
Currently, development [setup instructions](https://github.com/weaveworks/weave-gitops/tree/v2#cliapi-development) don't work out of the box. 

We need to do a couple of manual interventions applying some manifests to get it to work.

Make sure the process is more automated and minimize the setup steps, including making use of the chart in the repo: https://github.com/weaveworks/weave-gitops/tree/v2/charts/weave-gitops and if doable make tilt to installed it instead of just applying a deployment manifest.

**Comment by Callisto13** [comment]
I am already doing this as part of https://github.com/weaveworks/weave-gitops/issues/1454 so i can take this
