### ISSUE TITLE
Bug: Kustomization details page shows top level object within the table

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#1597]
<img width="1189" alt="Screenshot 2022-03-03 at 15 44 16" src="https://user-images.githubusercontent.com/19860021/156600093-9848a9b3-0093-4603-a10f-4a280d9cfcb0.png">

When viewing the details for a kustomization, in this case `flux-system`, you can see this object within the table of objects it is meant to be reconciling (self referential), but without status associated.

**Comment by jpellizzari** [comment]
The old code from which this was copied was trying to draw a directed tree graph, so it incorporated the top level parent node in the data model.

We probably just need to remove that from the data or filter it out in the UI layer.

**Comment by opudrovs** [comment]
@sympatheticmoose @jpellizzari

Could you please provide a working link to a page in the current staging dashboard where I can see this issue?

I only see some pages with errors for flux-system and do not see an object of type Kustomization or KindKustomization at all in staging.

**Comment by jpellizzari** [comment]
@opudrovs You will need to set up a local cluster to reproduce this. Then, I would recommend going through the [Flux Getting Started Guide](https://fluxcd.io/docs/get-started/)

**Comment by opudrovs** [comment]
@jpellizzari thanks, got through the guide yesterday and today.

Testing locally with the podinfo sample workload (from the development guide), almost everything is broken too.

**Comment by opudrovs** [comment]
@jpellizzari maybe this @ozamosi 's PR is related to the issues and will hopefully fix something:
#2193

**Comment by jpellizzari** [comment]
> @jpellizzari maybe this @ozamosi 's PR is related to the issues and will hopefully fix something: #2193

That looks unrelated. @opudrovs if you would like to put some time on my calendar, I can help you get a local environment running.

**Comment by opudrovs** [comment]
@jpellizzari OK, thank you! I am free today after 12 PM PST or tomorrow after 10 AM PST.
