### ISSUE TITLE
Implement a Dev mode 

### ISSUE THREAD

**Issue by luizbafilho** [weaveworks/weave-gitops#1598]
To help the developers to work on the project but without having to handle the hassle of setting up the authentication using OIDC, we need to implement a development mode to the gitops server.

**Acceptance Criteria**
- the developer can make changes to the code and reload the page without having to login every time

**Comment by luizbafilho** [comment]
With the super admin user this should not be necessary

**Comment by Callisto13** [comment]
👍  I already have this as part of https://github.com/weaveworks/weave-gitops/issues/1454

**Comment by Callisto13** [comment]
@luizbafilho are we okay to close this?
