### ISSUE TITLE
Implement ClustersClientsMiddleware

### ISSUE THREAD

**Issue by luizbafilho** [weaveworks/weave-gitops#1600]
Implement the middleware responsible for fetching the cluster and creating clients for each and injecting them in the context.

That work should be based of https://github.com/weaveworks/weave-gitops/pull/1556

Implementation Notes
- If no `clusters` configmap is present, we understand that as running in a non-multi-cluster setup, so just return that single cluster client in the clusters clients' lists

**Comment by Callisto13** [comment]
Recapping what was discussed in our planning meeting:
- Multi-cluster is *not* a feature of core
- So core cannot have any way to add multiple clusters
- So we will be doing the multi bit in Enterprise
  - Including all the config map hack bits
- From core's side we need to:
  - Define the clusters fetcher interface
  - Fulfil that interface by adding a single, in-memory cluster to a pool which is added to the context (basically doing what we do now, but putting the client somewhere else.

More tickets will be coming up for the rest 👍
