### ISSUE TITLE
Fonts are loading on navigation

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#1601]
Reproduce:
1. Open your browser console network tab
2. Load the page
3. Navigate to another page
4. See the fonts getting downloaded again
![Screenshot from 2022-03-03 09-25-12](https://user-images.githubusercontent.com/2802257/156618452-cc58f91d-d402-4f78-90a2-2d4210ac5e40.png)

**Comment by joshri** [comment]
@jpellizzari if you have disable cache checked the fonts will load every time right?

**Comment by jpellizzari** [comment]
They should only be loading once per refresh, if that makes sense.

**Comment by joshri** [comment]
I tried moving `<Fonts />` and the theme provider as high as possible (aka outside of `QueryContextProvider`) in `App` with no results. Also tried deleting the `typography` field from the Mui theme...why would `<Fonts />` get re-rendered if it's outside of the `Router`?

**Comment by jpellizzari** [comment]
> ...why would `<Fonts />` get re-rendered if it's outside of the `Router`?

We may have two nested routers now? That is my hunch

**Comment by jpellizzari** [comment]
I think this is a non issue or only happening in dev with hot reloading
