### ISSUE TITLE
Deploy a new version of the app from the UI (Deploy Button)

### ISSUE THREAD

**Issue by markramm** [weaveworks/weave-gitops#161]
List outstanding PR's against the branch for a target in a branch.   Merge via github UI, and watch the app be deployed via the status page.

**Comment by markramm** [comment]
Ready for design.

**Comment by jpellizzari** [comment]
Design for deploying a new version of the app: https://balsamiq.cloud/s5qd59g/pks8dty/rFE77

**Comment by jpellizzari** [comment]
Closing in favor of #550
