### ISSUE TITLE
Document GitLab OAuth configuration

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#1629]
https://weaveworks.slack.com/archives/C0140SWQ94M/p1646660907718879

Add the GitLab app account to an official weaveworks app instead of @jpellizzari's.

**Comment by JamWils** [comment]
I might turn this into an epic and it might not be picked up by this team.

**Comment by Callisto13** [comment]
@JamWils do we have a plan for this yet?

**Comment by sympatheticmoose** [comment]
@davidstauffer / @JamWils unsure if still valid?

**Comment by jpellizzari** [comment]
Still valid so long as we are using GitLab auth (unsure of this)

**Comment by LappleApple** [comment]
Moving this to WGE, as it references a private Slack link.
