### ISSUE TITLE
User/Account icon should be right aligned and is offsetting page title

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#1665]
<img width="879" alt="Screenshot 2022-03-10 at 13 28 27" src="https://user-images.githubusercontent.com/19860021/157671657-3f799f3d-a3cd-46c6-95ca-96f8880d17b7.png">

Example design:
<img width="1059" alt="Screenshot 2022-03-10 at 13 29 56" src="https://user-images.githubusercontent.com/19860021/157671771-4056f952-6556-43e9-82f1-7b3b5bf765ba.png">

**Comment by jpellizzari** [comment]
Fixed here: https://github.com/weaveworks/weave-gitops/commit/84bdc98c96de742e153bed9389021fb0f47a458b
