### ISSUE TITLE
Scrolling down on page causes odd behaviour in left menu

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#1666]
<img width="1197" alt="Screenshot 2022-03-10 at 12 05 08" src="https://user-images.githubusercontent.com/19860021/157671847-1f6e94f1-8370-4ca3-a531-a8261ff24244.png">

Seems to result from these two classes and their background colour
<img width="546" alt="Screenshot 2022-03-10 at 13 31 39" src="https://user-images.githubusercontent.com/19860021/157672237-0b37f301-ccbe-4a99-9ca6-55e191c84a9a.png">

Can see on the details page for the `flux-system` kustomization having bootstrapped https://github.com/sympatheticmoose/gitops-error-scenarios

**Comment by jpellizzari** [comment]
Fixed here https://github.com/weaveworks/weave-gitops/commit/0bdb98f79506f6a4fd3ff3fff34492fb5af38500
