### ISSUE TITLE
Investigate: Can we test RBAC at the integration test level

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#1670]
**Question**
The envtest setup we are using in our int tests runs a lightweight facsimile of a k8s; does it also mirror the RBAC behaviour of a real k8s api server?

**Short description**
It would be handy if we would test that we are RBACing properly in a tighter loop (ie not running kind and wego-manually and clicking things).
We'd like to find out whether envtest lets us set rbac and assume different users.

**Timebox**
2 days?

---

**Outcome**
One of:
- Can't be done :( 
- Can be done, ticket to do the thing

**Comment by jpellizzari** [comment]
yes we can
