### ISSUE TITLE
dev: Create a less powerful user for dev purposes

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#1671]
# Claudia needs to update this, ignore until then

**Short description**
The Chart deployed by Tilt in out dev cycle creates an Admin user.
This role will get gradually more powerful, so we want to make sure that we are still doing restrictions properly.

Create a new role which is deployed *only in a dev environment* as part of our Tilt set up, which has only the most basic powers. Basically it should be able to `get` and `list` a selection of objects in a specific namespace.

**Will require pulling https://github.com/weaveworks/weave-gitops/pull/1624 into v2 so that we are able to set usernames.**

**Acceptance criteria**
- [ ] I run `make cluster-dev`
- [ ] I navigate to UI
- [ ] I log on as the `anti-hero` user
- [ ] I see that I can only see some resources in a specific namespace
- [ ] I cannot see or do anything in other namespaces.

**Comment by jpellizzari** [comment]
This role would be something we login with to test out how things might look for users.

**Comment by Callisto13** [comment]
May be blocked on https://github.com/weaveworks/weave-gitops/issues/1722

**Comment by SamLR** [comment]
This will likely need updates to the `admin-user.yaml` helm chart

**Comment by Callisto13** [comment]
@luizbafilho are you still on this?

**Comment by luizbafilho** [comment]
sounds good to me
