### ISSUE TITLE
Update core namespace endpoint to use client pool 

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#1675]
**Short description**
Following on from https://github.com/weaveworks/weave-gitops/issues/1600 and based on https://github.com/weaveworks/weave-gitops/pull/1556, this is to update the endpoint in `core/server/namespace` to:
- Pull a list of clients from the `ctx`
- Loop over those and query each

**Acceptance criteria**
Everything which currently works should still work

**Comment by Callisto13** [comment]
I don't think it is _exactly_. Looks like it is using a single client. But is worth noting that this one should probably wait for #1780 to be merged, just to avoid complications

**Comment by yitsushi** [comment]
The scope of this ticket changes with my PR on namespace cache (https://github.com/weaveworks/weave-gitops/pull/1780) because I replaced the namespace grpc endpoints to use the cache instead. So it's more like:

> update cache/namespace to use client pool, pull and store data respectively.
