### ISSUE TITLE
Implement WeaveCluster ClustersFetcher interface in Enterprise

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#1691]
**Short description**
Following https://github.com/weaveworks/weave-gitops/issues/1690, implement a fulfilment of the ClustersFetcher interface which will:
- Watch for CRs of the type `WeaveCluster` (check that this is still what they are)
- Parse the objects, and fetch the referenced secrets, to build a list of cluster configs
- Use this list of cluster configs to build a pool of clients
- Which will be added to the `ctx`s of requests

**Notes:**
- This will supersede the previously implemented `ConfigMap` solution, which can now be removed
- This work will be PRd into **Enterprise**. The interface definition and eventual usage of the clients in the context will live in Core

**Acceptance criteria**
- [ ] A user creates a secret per leaf cluster, containing auth data
- [ ] The user defines 'n' `WeaveCluster` CRs (for 'n' leaf clusters) containing relevant information and reference to the associated secret
- [ ] The user applies those to the management cluster
- [ ] The user navigates to their clusters dashboard
- [ ] And sees runtime/source/kustomization/etc information for resources on each cluster
- [ ] The user can also still see that information for resources running on the management cluster

**Comment by jpellizzari** [comment]
Waiting on a CRD for this one

**Comment by Callisto13** [comment]
We have a CRD now, and all but one of the Core mutli-cluster tickets done, so I am going to start looking at this.
