### ISSUE TITLE
Users should be able to set their own TLS certs

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#1703]
**Short description**
Currently TLS is only really usable in the dev env: the certs are built into the image.

For the actual release, we do not want to build certs into the image.

Users should be able to set their own certs.

Users should also have a nice way to enable/disable TLS without editing the Chart (which they can't really anyway unless they clone it).

Using a [configMap as a volume](https://kubernetes.io/docs/concepts/storage/volumes/#configmap) (or secret) may be a nice and easy way to get cert values into the pod, but you don't have to do this if you find something better.

**Acceptance criteria**
As a User I can:
- [ ] Generate my own certs
- [ ] Add them to a config map/pass them to my wego Chart values in some way/ add them to my cluster by some other method
- [ ] And see that wego is running over HTTPS

If I don't want to use TLS:
- [ ] I can set some value in my Chart values
- [ ] And see that my wego app is served over HTTP

**Comment by JamWils** [comment]
In Kubernetes this would be considered the downward api approach.  We should be able to make this pretty customizable via the helm chart.
