### ISSUE TITLE
Cannot view helm release page

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#1705]
I am getting the following error when trying to view a helm release.

```
Cannot read properties of undefined (reading 'helmChart')
```

Is this due to invalid permissions?  If so, I would expect to see a different error notifying me that I am not allowed to view the helm release.

![Screen Shot 2022-03-14 at 9.45.20 AM.png](https://images.zenhubusercontent.com/60f5a90306cf76325d5accdc/70291a5d-6371-4956-a4b6-189515886fe6)

**Comment by joshri** [comment]
Will be fixed once #1700 merges https://github.com/weaveworks/weave-gitops/pull/1700
