### ISSUE TITLE
UI: filter options appear within table

### ISSUE THREAD

**Issue by bia** [weaveworks/weave-gitops#1708]
Currently the filter is implemented as an overlay floating above the table, but it would fit better with material design styling if our filters were a [side sheet](https://material.io/components/sheets-side#anatomy)
![sidesheet](https://user-images.githubusercontent.com/92439/158211686-137d3d26-bf16-4d0c-90e1-3ab877010ab1.png)

Compressing the table as in my original design might be problematic, it might be better to keep the filter menu content hovering above and horizontally scroll the table below : 

https://user-images.githubusercontent.com/92439/158212198-2f4a876e-0905-42f2-b189-911c31d042bf.mov

**Comment by jpellizzari** [comment]
This appears to require an upgrade to `v5` of Material UI. I cannot find the `SideSheet` component in `v4`.
