### ISSUE TITLE
Policy UI integration 

### ISSUE THREAD

**Issue by fire-ant** [weaveworks/weave-gitops#171]
**Short description**

As a Platform operator I want to audit the policies which are applied during the lifecycle of cluster templates and clusters to ensure that my infrastructure is in compliance with regulations and requirements. As a customer I would like to make use of OPA policies which are contractually restrictive regarding the configuration data and the templates with which these are expanded. There is a fair reason to believe that I could source my policies from a private/internal git repository, from an integration with a cloud service, such as Styra DAS and ensure these are enforced at both the point of config generation and at the point of application. For convenience I would like to be able to navigate to the source of my policies via URL, whether they are from a service or a flat file. 

Noted here but appreciate this could be listed/referenced elsewhere (notion)

**Comment by jpellizzari** [comment]
@fire-ant This issue is out of scope for Weave GitOps core. Closing. Please reach out to me directly if you feel this has been closed in error.
