### ISSUE TITLE
favicon.ico for Weave Gitops

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#1711]
In my browser I use vertical tabs, it would be nice to have a favicon.ico to quickly find Weave GitOps.  This should be the logo in the top left corner.

![Screen Shot 2022-03-14 at 3.12.47 PM.png](https://images.zenhubusercontent.com/60f5a90306cf76325d5accdc/5a57cb5c-f914-425b-a257-df85c5ce7358)

**Comment by JamWils** [comment]
@bia can you supply the artifact so this can be added by the FE team.

**Comment by bia** [comment]
Hi James and team, here is the logo in .svg
![gitops-LOGO](https://user-images.githubusercontent.com/92439/158355221-6efd8a26-27ea-4d17-ba17-bc62465dc381.svg)

Github doesn't support .ico, it's on drive [here](https://drive.google.com/file/d/1gjJI-4Hq-TIn4WM_Aq0644EyZtZ4kdyu/view?usp=sharing).
