### ISSUE TITLE
Sources page takes you to the wrong page

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#1712]
As a user, when I go to the source detail page and click a Kustomization or Helm Release I am taken back to the source page.  The bug seems to be that it appends the URL instead of replacing it:

`http://localhost:8082/git_repo?name=flux-system&namespace=flux-system#/kustomization?name=flux-system&namespace=flux-system`

Expectation, when I click the `kustomization` or `helm releases` name I am taken to the correct detail page.

![Screen Shot 2022-03-14 at 3.17.45 PM.png](https://images.zenhubusercontent.com/60f5a90306cf76325d5accdc/f3e9e649-fb86-4405-abc8-f1fc5f1eff85)

Click `flux-system` on table:

![Screen Shot 2022-03-14 at 3.18.06 PM.png](https://images.zenhubusercontent.com/60f5a90306cf76325d5accdc/c59322b6-e228-4772-a8ff-645c3d694b1b)

**Comment by jpellizzari** [comment]
@JamWils  This will be made irrelevant by point 3 on #1704, correct?

**Comment by JamWils** [comment]
No, it is when I click the name of the `kustomization` not the link under the source column.
