### ISSUE TITLE
Flux Runtime page shows too many things

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#1713]
The Flux Runtime will show any pods running within the flux-system namespace.

1. As a user, it isn't always guaranteed that the controllers will be in `flux-system`.
2. As a user, I could  want to install more than one set of controllers installed on a cluster.  E.g. I don't want two apps teams sharing the same controller set for reliability and blast radius purposes.  Or certain apps rely on a specific version of a controller to be running.
3. As a user, I want to see the runtime health and not other resources that happen to fall under the `flux-system` namespace.

The deployments have labels for the controllers.  Is this good enough?  I feel like this is something that could bite us in the future.
```
app.kubernetes.io/part-of=flux
control-plane=controller
```

The screenshot below shows `podinfo` and `wego-app`.
![Screen Shot 2022-03-14 at 3.19.59 PM.png](https://images.zenhubusercontent.com/60f5a90306cf76325d5accdc/0ba8b2bc-60ea-4339-a6f6-6fc80e60ffff)

**Comment by jpellizzari** [comment]
> As a user, it isn't always guaranteed that the controllers will be in flux-system

This is a cross-namespace querying concern, correct?

> app.kubernetes.io/part-of=flux

This label does not exist on the controllers, as far as I can tell.

> control-plane=controller

We could use this, but then `wego-app` won't show up.

**Comment by JamWils** [comment]
Yes, do all of the above.  I don't think it is an issue that `wego-app` doesn't show up on that screen.  The intent of this screen is to show that the controllers themselves are running healthy.  Yes, there is a cross-namespace concern as well.  Imagine, I have multiple sets of controllers installed on my cluster for availability concerns and to reduce the blast radius of something going wrong.  When I go to this screen I would expect to see all controllers across multiple namespaces.

> This label does not exist on the controllers
That is interesting because I do see it on mine.  I installed via `flux bootstrap` did you do something different?

```
Labels:                 app.kubernetes.io/instance=flux-system
                        app.kubernetes.io/part-of=flux
                        app.kubernetes.io/version=v0.26.3
                        control-plane=controller
Annotations:            deployment.kubernetes.io/revision: 1
```
