### ISSUE TITLE
Random error message instead of being logged out

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#1717]
As a user, when my session is no longer valid I see a random error message (see screenshot below) instead of

a. Automatically being redirected to the login screen. (Preferred situation)
b. Simply seeing an error that my session has expired. (Less ideal)

If you check the console logs the error message first appears after the session expires.  Upon hitting refresh I am then taking to the login screen.

![Screen Shot 2022-03-15 at 8.24.59 AM.png](https://images.zenhubusercontent.com/60f5a90306cf76325d5accdc/db38f46c-3c6e-4450-97e4-d01a72c82672)

![Screen Shot 2022-03-15 at 8.25.42 AM.png](https://images.zenhubusercontent.com/60f5a90306cf76325d5accdc/3065a8e1-bd17-45f9-9863-0ee0cfd45dc2)

**Comment by jpellizzari** [comment]
Might be related to this: https://github.com/weaveworks/weave-gitops/pull/1699

You will get that message when the server is dead. We may be able to do something on the first `401` on `/v1/kustomizations`, however.
