### ISSUE TITLE
Horizontal scrollbar appears during filtering animation

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#1765]
https://user-images.githubusercontent.com/19860021/159262551-d4e4b12e-7418-4bdd-8d50-b5a1fd5ec17d.mov

If not a quick fix, be sure to consider when we're implementing https://github.com/weaveworks/weave-gitops/issues/1708

**Comment by rokshana-b** [comment]
**This issue has been fixed:**

https://images.zenhubusercontent.com/342592099/f0193fb2-9dc2-429c-9053-c13062f43b33/screenshare___2022_04_14_4_15_41_pm.mp4
