### ISSUE TITLE
Expose all production configuration options via the helm chart

### ISSUE THREAD

**Issue by SamLR** [weaveworks/weave-gitops#1784]
Currently the only explicitly expose configuration option is `logLevel`. There are many others which should be correctly exposed in the helm chart (e.g. https://github.com/weaveworks/weave-gitops/blob/f1c4bb312fdac77828fcae7db85e5ec0bf9cba02/cmd/gitops-server/cmd/cmd.go#L70-L91) 

These weren't exposed as part of #1779 as I was unsure exactly what these all do, which are needed and how they should be configured.

**Acceptance Criteria**

* All flags and environment-variables that it is reasonable (cc @sympatheticmoose/@JamWils for what qualifies as 'reasonable')  to expect an end-user to set are exposed via `values.yaml`
* They are exposed with reasonable defaults
* `values.yaml` documents what the various flags mean & do.
* Where possible values are validated to ensure correct configuration (this can be done via a [values.schema.json file](https://helm.sh/docs/topics/charts/#schema-files)  and/or flow control)

**Comment by JamWils** [comment]
@SamLR and @ozamosi should we do this or close it?

**Comment by SamLR** [comment]
@JamWils I'm honestly not sure because I'm not sure which of the [flags](https://github.com/weaveworks/weave-gitops/blob/main/cmd/gitops-server/cmd/cmd.go#L70-L88) should be exposed (e.g. `devMode` shouldn't, but should `mtls`?)

I think the main things that users will likely want to change are exposed and new ones should be picked up and checked as part of PRs so I think we can mark this as closed.
