### ISSUE TITLE
Stick all profiles stuff behind a feature flag

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#1785]
**Short description**
As a wego user who wants to deploy profiles, I can set a feature flag and see that the profiles mechanism is turned on.

**Context**
See:
- https://weaveworks.slack.com/archives/C03244W0C8H/p1648038251044219?thread_ts=1648033973.061309&cid=C03244W0C8H
- https://weaveworks.slack.com/archives/C03244W0C8H/p1648033973061309
- https://github.com/weaveworks/weave-gitops/pull/1779#discussion_r833191849

**Acceptance criteria**
This can probably be done in 2 prs if you like

As a wego user who DOES NOT want to deploy profiles:
- [ ] I deploy the wego helm chart with `envVars[x].WEAVE_GITOPS_PROFILES_ENABLED` set to `false` (or whatever mechanism fits with the Chart)
- [ ] I see that the wego app is started with only the basic perms required for the wego server to do impersonation
- [ ] I cannot apply profiles to my cluster (in enterprise. there is no way to do/show this in core yet)

As a wego user who wants to deploy profiles:
- [ ] I deploy the wego helm chart with `envVars[x].WEAVE_GITOPS_PROFILES_ENABLED` set to `true` (or whatever mechanism fits with the Chart)
- [ ] I see that the wego app is started with the correct perms required by the profiles mechanism
- [ ] I can apply profiles to my cluster (in enterprise. there is no way to do/show this in core yet)

**Comment by JamWils** [comment]
Hmmm, I wonder if we change the scope of this work.  Can we pull the server component out completely and have it be a separate binary called `profiles-controller`.  Then we can set up the helm chart to make this easy to include or not include when installing?  This will make it more portable for Enterprise as well.  cc: @Himangini

**Comment by Callisto13** [comment]
Lol that is my long-term goal 😄 

Happy to increase the scope, or make it a part 2.

**Comment by Callisto13** [comment]
@jmickey I think James mentioned that you were taking this one, that correct or am I making things up?

**Comment by JamWils** [comment]
@jmickey, can we close this issue?

**Comment by JamWils** [comment]
@ozamosi and @jmickey is this story relevant anymore?  My understanding is that all of this was moved.
