### ISSUE TITLE
Get back to basics with the Admin User

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#1787]
**Short description**
As a user whose OIDC is f’d or cnba to set up OIDC right this second, I can log in as a hardcoded Admin user and get access to my stuff.

**Context**
This is basically unwinding some of the extensions that have been made to the AdminUser feature. We **do not** want it so that we end up supporting our own auth provider. We can handle a single Admin user for emergency purposes only. Otherwise we encourage users to have OIDC https://github.com/weaveworks/weave-gitops/issues/1786. 

The feature was introduced here https://github.com/weaveworks/weave-gitops/pull/1490 and extended https://github.com/weaveworks/weave-gitops/pull/1624. There is a further PR here #1755.

We basically want to get back to where we were after #1490.

See conversation [here](https://weaveworks.slack.com/archives/C03244W0C8H/p1647967858091769).

**Acceptance criteria**
As a user whose OIDC is f’d or cnba to set up OIDC right this second:
- [ ] I can enable the auth env var flag
- [ ] I can create a k8s user, with a role binding and suggested scope of roles per the wego docs. This user must be labelled `gitops.weave.works/entity: admin-user`
- [ ] I can navigate to (or be redirected to) the wego /sign_in page
- [ ] I can enter just the password of the emergency/admin user (the name field defaults to `admin` and is uneditable)
- [ ] I am able to log in to my dash

**Comment by SamLR** [comment]
This will likely need updates to the admin-user.yaml helm chart (this may also be impacted by #1789 as namespace and name of the resources created in k8s should probably be configurable NB this doesn't mean the username has to be, just that the resources being injected into potentially congested namepaces should be controllable)

**Comment by Callisto13** [comment]
@AlinaGoaga Does pesto want this one or shall we take it?

**Comment by davidstauffer** [comment]
Hi, I think we need to separate the UX in the GUI from the mechanism that provides those identities. My takeaway from the mentioned [conversation](https://weaveworks.slack.com/archives/C03244W0C8H/p1647967858091769) is that we agreed:

**Comment by Callisto13** [comment]
I would note that it is likely that we will end up changing this UX as it is simply not good. Literally just now I had this conversation:

person: "I set up my admin user, how do I create another user?"
me: "Good question. May I ask what makes you think you can do that?"
person: "... there is a username and password field. What else would I think?"
me: "Well you can't :)"
