### ISSUE TITLE
Fix Docker builds in the release workflow

### ISSUE THREAD

**Issue by dhwthompson** [weaveworks/weave-gitops#1812]
Running the [`release` workflow against `v0.7.0-rc2`](https://github.com/weaveworks/weave-gitops/runs/5695928485?check_suite_focus=true), the following error crops up in the “Build and push Docker image” stage:

```
buildx failed with: error: failed to solve: failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount530813440/Dockerfile: no such file or directory
```

**Comment by jpellizzari** [comment]
Closed by #1820
