### ISSUE TITLE
Add guidance on how to contribute to the website

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#1827]
We should ensure it is easy for folks to contribute to the website. The "edit this page" capability would only edit the versioned docs so still requires a project maintainer to step in typically.

Guidance should be in GitHub at least, maybe the public docs as well.

**Comment by Callisto13** [comment]
Some guidance exists in the repo https://github.com/weaveworks/weave-gitops/tree/main/website#readme, but there is little in the way of contribution in general.

A dedicated section in the docs would be good to develop.
