### ISSUE TITLE
Investigate: What do we do with users who do not want auth?

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#1831]
**Question**
Do we want to accommodate users who, for local dev reasons, do not want any auth at all?

**Short description**
- All queries impersonate by default
- This means users need to have some form of auth set up or nothing will work (if may even fail)
- But it feels weird to tell people playing about with local dev that they need auth

So

Are we fine making auth a hard requirement (basically erroring on pod start if auth is not configured)?

Or

Do we want to accommodate users who, for local dev reasons, do not want any auth at all?

Do we care? If the Chart comes with the Admin user always on, is this a problem? Maybe not, but I am certainly getting tired of needing to auth every time Tilt refreshes. (for this we could also have an option which skips token verification in dev mode, thanks Luiz)

Or do we want to fiddle with the ClientGetter (whatever it is called) and only impersonate when asked to Auth. Otherwise users can set their Wego pod to have all the powers they like.

**Goal**
A decision on what we want to do: to mandatory auth or not to mandatory auth?
Ticket(s) created to either make Auth a hard requirement or to create a dev mode.

**Timebox**
2 days

---

Write up outcome in comments on this thread

**Comment by Callisto13** [comment]
we will find out after people have used it

**Comment by sympatheticmoose** [comment]
closing as stale - will recreate should this be something we want to explore in the future pending more feedback
