### ISSUE TITLE
Switch wego commands to `noun verb` format rather than `verb noun`

### ISSUE THREAD

**Issue by jrryjcksn** [weaveworks/weave-gitops#185]
**Short description**
As a wego user who uses both the CLI and UI, I would like them to be consistent in their models and use the object being modified as the context for operations.

**Given** a wego binary
**When** I run a command operating on a specific wego type (e.g. application, cluster, etc.)
**Then** the command expects the type of the object being operated on before the operation
               Example: `wego application add .` instead of `wego add application .`

**Comment by markramm** [comment]
Switch cluster install to runtime install 

https://docs.google.com/spreadsheets/d/1jcC_PheM6oEJGdKvkJu4Hp3bYMqeMUN7YhhNBGgcKfA/edit#gid=0

**Comment by luxas** [comment]
Can you elaborate on why? `kubectl` started with `noun verb`, but that would never have allowed CRDs, for example, so they settled on `verb noun` to build commands based on what the user wanted to do, and let the noun, i.e. resource be dynamic and eventually extended.
