### ISSUE TITLE
Create a PR on a new branch by default for each successive `wego add` invocation for same cluster and repo

### ISSUE THREAD

**Issue by jrryjcksn** [weaveworks/weave-gitops#187]
**Short description**
As a wego user, I would like to have a PR created on a new branch of the wego repo when I `wego add` an application

**Given** a cluster with wego installed
**And** an application in a user repository
**When** I run `wego application add` for the application
**Then** I get a new PR on a new branch in the wego repository

**Comment by markramm** [comment]
Automerge (current first app add behavior) or PR should be available for all application add.
