### ISSUE TITLE
Make ALL wego commands inform the user if a new wego version is available

### ISSUE THREAD

**Issue by jrryjcksn** [weaveworks/weave-gitops#189]
**Short description**
As a wego user, I would like to know if there is a later version of wego than the one I'm using.

**Given** a wego binary other than the most recent version
**And** a cluster with wego installed
**And** I'm connected to the internet
**And** I did not explicitly override the version check
**When** I invoke `wego application add` or `wego install`
**Then** the command tells me that a newer version is available

**Comment by J-Thompson12** [comment]
@markramm I was wondering where the information would appear best. So when you do a command and the version is out of date it can inform the user before the command or after the command. I personally think before the command doesnt really work unless the command takes some time to work. I imagine the user wont really see it unless its the last they see after running a command.
