### ISSUE TITLE
`gitops get profiles` don't work in reloaded

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#1899]
**Describe the bug**
`gitops get profiles` makes a query to the gitops API, using a hard-coded service name, `wego-app`. Not only is that the old name (we call the service `weave-gitops` now) but we also use helm which prefixes its own name to the resources it creates (so your service is likely called something like `weave-gitops-weave-gitops`), and finally the user can configure both the HelmRelease name and the service name.

(`add` or `update` aren't affected by this, because they deal with your git repo directly)

**Is this a UI bug or a server bug?**
- [ ] UI
- [x] Server

**What is the severity of the bug**

- [ ] `severity/Critical`: Weave GitOps is crashing or experiencing data loss, the UI is inaccessible or a key feature is unusable. There is no known workaround
- [ ] `severity/Major`: Weave Gitops functionality is broken, there is a workaround, but the workaround requires significant effort
- [ ] `severity/Minor`: Weave Gitops functionality is broken, but there is a fairly straightforward workaround
- [ ] `severity/Low`: Doesn’t affect primary flow/functionality but would be good to fix

**Environment**
 - gitops: `main`
 - How you deployed the Weave GitOps server: Helm Chart
 - kubernetes:  1.21.1
    - [x] KinD - 0.11.1
    - [ ] k3s - _version_
    - [ ] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_
 - Browser + version: [e.g. chrome 74, safari 12, firefox 87]

**To Reproduce**
```
$ gitops get profiles
Error: failed to make GET request to service flux-system/wego-app path "/v1/profiles" status code: 404
```

**Expected behavior**
I should see profiles

**Comment by Callisto13** [comment]
Not surprised about this. We have had no profiles-related reloaded work so we have largely been ignoring it / wishing it was not there.
