### ISSUE TITLE
UI temporarily shows an empty page on the background

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#1907]
**Describe the bug**

When navigating to UI dashboard, an empty page temporarily pops up before it is replaced by login page. 

**Is this a UI bug or a server bug?**
- [x] UI
- [ ] Server

**What is the severity of the bug**

- [ ] `severity/Critical`: Weave GitOps is crashing or experiencing data loss, the UI is inaccessible or a key feature is unusable. There is no known workaround
- [ ] `severity/Major`: Weave Gitops functionality is broken, there is a workaround, but the workaround requires significant effort
- [ ] `severity/Minor`: Weave Gitops functionality is broken, but there is a fairly straightforward workaround
- [x] `severity/Low`: Doesn’t affect primary flow/functionality but would be good to fix

**Environment**

 - How you deployed the Weave GitOps server: [e.g. Tilt, Helm Chart, etc]
 - kubernetes:  [e.g. 1.20.4]
    - [x] KinD - _version_]
    - [ ] k3s - _version_
    - [ ] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_

**To Reproduce**

1. Open browser and navigate to http://localhost:9001/
2. Watch an empty page load before login page appears

**Expected behavior**

User should not see any other page than login — even if it is empty.

**Screenshots**

https://user-images.githubusercontent.com/76788247/163033955-a92897c7-9e93-4ca2-9f8b-e2f19981ba34.mp4

**Comment by Callisto13** [comment]
apparently solved by #1932
