### ISSUE TITLE
Make all wego commands idempotent

### ISSUE THREAD

**Issue by jrryjcksn** [weaveworks/weave-gitops#192]
**Short description**
As a wego user, I would like to be able to re-run commands with impunity in the event of issues so a command that had successfully completed will not change the system if run again.

**Given** a cluster without wego installed
**And** a wego install is run successfully**
**When** the same command is run again
**Then** the system should be unchanged

--

**Given** a cluster with a partially completed wego install
**And** a wego application add is run successfully**
**When** the same command is run again
**Then** either another error, or the install should carry on towards the expected goal state

**Comment by markramm** [comment]
Version, and status, **and all other commands should be idempotent as well.**  

Of course as read commands they are fine :)

**Comment by markramm** [comment]
A failed call should be fixable and then re-run.   (Idempotent and goal state oriented)

**Comment by markramm** [comment]
What about things like _`wego application add`_?

Creation of the PR is allowed, even though it is not technically idempotent. 

Could we separate out the repo management steps from the Pull Request Creation?
 --Make one set declarative state, and the other imperative change in repo structure.
