### ISSUE TITLE
Update Getting Started docs to be a bit more brief

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#1925]
The Getting Started section of the docs includes a bunch of stuff which is not necessary any more.

- `Configure access to the dashboard` can be slimmed down a bit to have `docker run -it golang:1.17 go install github.com/bitnami/bcrypt-cli@v1.0.2 && echo -n "super secret password" | bcrypt-cli`
- `Install Weave GitOps` can be shortened to only push the commits once.

**Comment by SamLR** [comment]
Is there a reason to separately generate the brcypt password and secret rather than using the helmchart to do it all?

**Comment by Callisto13** [comment]
see thread https://weaveworks.slack.com/archives/C03244W0C8H/p1649949498981179?thread_ts=1649949075.430179&cid=C03244W0C8H apparently it was decided

**Comment by ozamosi** [comment]
When I say it was decided, I was referring to the big disclaimers added in 6a4cf955b and 88ee41890 - @SamLR if that's not what you meant, then please clarify.

**Comment by SamLR** [comment]
ah right. Those were written when I had a different understanding of what the admin user should do/was for.

I think there's a product decision here WRT how much risky behaviour/complexity to add to the getting started guide.

For 'quick poke about' / trial purposes having a bcrypt-hashed password in git is probably reasonable (my understanding of the algorithm is that it's very computationally expensive to try and reverse and not a likely attack vector) but for a production system we'd should steer people towards configuring their admin user creds via sops or some other secret mechanism which encrypts the hash itself.
