### ISSUE TITLE
Spike: How do we add feature flag support to wego?

### ISSUE THREAD

**Issue by jrryjcksn** [weaveworks/weave-gitops#193]
**Short description**
As a wego developer, I would like to add functionality to the system before it's ready for general release hidden behind a feature flag so that it may be tested by a subset of users.

**Given** new wego functionality ready for testing
**And** an alpha or beta user group to test it
**When** the next wego version is released
**Then** the new functionality may be placed behind a feature flag
**And** it can be exposed to the alpha or beta customers 

Note:  
There may be some pre-existing tooling we can use here?

**Comment by markramm** [comment]
@palemtnrider mentioned launch darkly

**Comment by markramm** [comment]
@palemtnrider Is there any update on the design for this?
