### ISSUE TITLE
Applications sub-page alignment is off

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#1933]
**Describe the bug**

Sub-pages that lead to applications are not properly aligned like the rest of the pages. The tables are truncated and the position of the details section is off.

**Is this a UI bug or a server bug?**
- [x] UI
- [ ] Server

**Screenshots**

https://user-images.githubusercontent.com/76788247/163510051-2ea3fcb9-f176-4b9b-9d72-91f09f186b4b.mp4

**What is the severity of the bug**

- [ ] `severity/Critical`: Weave GitOps is crashing or experiencing data loss, the UI is inaccessible or a key feature is unusable. There is no known workaround
- [ ] `severity/Major`: Weave Gitops functionality is broken, there is a workaround, but the workaround requires significant effort
- [ ] `severity/Minor`: Weave Gitops functionality is broken, but there is a fairly straightforward workaround
- [x] `severity/Low`: Doesn’t affect primary flow/functionality but would be good to fix

**Environment**
 - gitops: v0.7.0
 - How you deployed the Weave GitOps server: Helm Chart
    - [x] KinD
    - [ ] k3s - _version_
    - [x] cloud: GKE
    - [ ] other - _name_ _version_

**To Reproduce**

1. Go to UI dashboard
2. Click on any of the available applications
3. See page misaligned

**Expected behavior**

Application sub-pages should look like the rest of the pages in the UI, like so:

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/76788247/163510133-374b9f4c-2f66-46e7-8f12-24f0c9f892ef.png">

**Comment by joshri** [comment]
Fixed in above PR - closing
