### ISSUE TITLE
Tie All Errors to App Context

### ISSUE THREAD

**Issue by joshri** [weaveworks/weave-gitops#1934]
Follow up to #1932 - now that we have this functionality we can get errors exclusively from context (instead of each individual request) and make sure they only display in one location!

This is where errors appear as of now (`<Page />` component in the code) - they also  appear within the tabs on a detail page, which needs to be removed. 
![image](https://user-images.githubusercontent.com/65822698/163582333-7daecc13-68ac-4a4b-8ade-60d75aed9269.png)

**Comment by sympatheticmoose** [comment]
@joshri is this still valid?

**Comment by joshri** [comment]
> @joshri is this still valid?

It's not going to be prioritized by team denim but it is a possible improvement - I think the error handling in general is part of a larger conversation that's happening and I'll close this issue until we decide how to move forward.

**Comment by sympatheticmoose** [comment]
Thanks - that makes sense
