### ISSUE TITLE
Clarify and/or conosolidate `pkg` and `core` directories

### ISSUE THREAD

**Issue by SamLR** [weaveworks/weave-gitops#1981]
**Short description**
As an engineer I want to be able to easily find where code is/should be put so that I can write good code.

**Acceptance criteria**
* Either:
  - [ ] `pkg` and `core` have been merged and redundancies removed
  - [ ] _or_ the difference between these directories and what they do is clearly documented and the code cleaned up to match this  

**Notes**

This is probably a large task but it should be captured if possible. This is particularly useful in the case of repeated modules, e.g. without deep reading of the code I can't tell the difference between `pkg/server/server.go` and `core/server/server.go` let alone why you would use one over the other

**Comment by Callisto13** [comment]
The "reclaiming of pkg" came up recently, now feels like a good time.

> I can't tell the difference between pkg/server/server.go and core/server/server.go let alone why you would use one over the other
The original "server" is poorly named. I did an incomplete "burn it all" example PR of how we could change things https://github.com/weaveworks/weave-gitops/pull/1842

**Comment by Callisto13** [comment]
Just for clarification for whoever picks this up/cares:

- We run one server from `cmd/gitops-server/cmd/cmd.go`.
- This is an HTTP server
- To that server we add the following handler groups:
  - The `core/server/*` GRPC handlers (basically a wrapper around various k8s client calls)
  - The `pkg/server/server.go` GRPC handlers (these are the OG handlers which now pretty much just amount to authing against Git providers)
  - The `pkg/server/profiles.go` GRPC handlers (profiles)
  - The `pkg/server/auth/*` HTTP handlers (user auth n stuff)
  - And a whole bunch of GRPC and HTTP middleware

So really we could rename `pkg/server` -> `pkg/handlers`, move `core/server` under that (rename everything to fit), and move the rest of `core/*` into `pkg`.
