### ISSUE TITLE
Create follow up tickets for Pagniation work

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#1982]
1 ticket per next feature, 1 ticket per outstanding TODO

IDK if you are already on this @josecordaz, just making sure it is tracked 😄

**Comment by josecordaz** [comment]
@sympatheticmoose and I had a conversation, this was the outcome: We concluded on 3 things. First, we would hold a bit on keep working on this as we are uncertain how the new teams are going to be formed, and this change is happening soon. Second, I would update my initial pagination proposal with the latest changes so whoever picks up this work in the future can have as more context as possible (already updated https://docs.google.com/document/d/1jnivnTeElV3FP0N81NGiQE-HlWpb5TliWgF6oSdbtME/edit). And lastly we would need to do more investigation/spike on how to address properly the issues exposed in the document, if it ever becomes slow for a specific case. So far the current logic is great enough as we can fetch resources asynchronously and the UI is doing the sorting/filtering. I'll reopen original issue https://github.com/weaveworks/weave-gitops/issues/1697 as a reminder to after the new teams form.

**Comment by Callisto13** [comment]
👍 sounds good, great work on this @josecordaz
