### ISSUE TITLE
Weave GitOps username is hard-coded

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#2001]
**Describe the bug**

GitOps username is hard-coded to `wego-admin`. Since we're configuring users with user-specified names, the names should show up for the UI user icon. 

**Is this a UI bug or a server bug?**
- [ ] UI
- [x] Server

**What is the severity of the bug**

- [ ] `severity/Critical`: Weave GitOps is crashing or experiencing data loss, the UI is inaccessible or a key feature is unusable. There is no known workaround
- [ ] `severity/Major`: Weave Gitops functionality is broken, there is a workaround, but the workaround requires significant effort
- [x] `severity/Minor`: Weave Gitops functionality is broken, but there is a fairly straightforward workaround
- [ ] `severity/Low`: Doesn’t affect primary flow/functionality but would be good to fix

**Environment**
 - gitops: main
 - How you deployed the Weave GitOps server: Helm Chart
 - kubernetes:  [e.g. 1.20.4]
    - [x] KinD - _version_]
    - [ ] k3s - _version_
    - [x] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_
 - Browser + version: [e.g. chrome 74, safari 12, firefox 87]

**To Reproduce**

1. Configure username and password using GitOps HelmRelease yaml
2. Run `flux bootstrap`
3. Navigate to UI dashboard
4. Login using configured credentials
5. Click on user icon
6. See `wego-admin` username

**Expected behavior**

User specified username should appear

**Config and Logs**

**Screenshots**

https://images.zenhubusercontent.com/342592099/50078b92-0815-42fa-bb93-efebc41e9caa/screenshare___2022_04_25_11_38_54_am.mp4

**Additional context**

What does this mean for `Dev` environment?

**Comment by Callisto13** [comment]
Do you know if the `--dev-mode` and `--dev-user` flags are set on this instance? If they are, could you try removing them and seeing if the issue still persists?

**Comment by yitsushi** [comment]
It's not a UI issue.

```diff
❯ git diff
diff --git a/Tiltfile b/Tiltfile
index 0195ee10..a7ecfc33 100644
--- a/Tiltfile
+++ b/Tiltfile
@@ -26,9 +26,7 @@ docker_build_with_restart(
         './bin',
     ],
     dockerfile="dev.dockerfile",
-    entrypoint="/app/build/gitops-server --log-level=debug --insecure --dev-mode --dev-user {dev_user}".format(
-        dev_user=os.getenv("DEV_USER", "wego-admin")
-    ),
+    entrypoint="/app/build/gitops-server --log-level=debug --insecure",
     live_update=[
         sync('./bin', '/app/build'),
     ],
```
With these changes, if I log in as `dev`/`dev`, then `/oauth2/userinfo` returns with `{"email":"wego-admin","groups":null}`

At the same time, I don't think it's an issue. With OIDC login, everything looks good, the username changes based on the logged in user.

I don't think it's a bug, it's more how we implemented (intentionally) the system around static user login.

We check static user by username / password from a Secret:
```go
if err := s.kubernetesClient.Get(r.Context(), ctrlclient.ObjectKey{
        Namespace: v1alpha1.DefaultNamespace,
        Name:      ClusterUserAuthSecretName,
}, &hashedSecret); err != nil {
        s.Log.Error(err, "Failed to query for the secret")
        JSONError(s.Log, rw, "Please ensure that a password has been set.", http.StatusBadRequest)

        return
}
```

In this case we don't have a user at all, we don't get a Group or User, therefore we have to match for a user. We do it by generating a claim for user `wego-admin`:

```go
func (sv *HMACTokenSignerVerifier) Sign() (string, error) {
claims := AdminClaims{
        StandardClaims: jwt.StandardClaims{
                IssuedAt:  time.Now().UTC().Unix(),
                ExpiresAt: time.Now().Add(sv.expireAfter).UTC().Unix(),
                NotBefore: time.Now().UTC().Unix(),
                Subject:   v1alpha1.DefaultClaimsSubject,
        },
}
```

And we bind it to `wego-admin` because the subject of the default RoleBinding is `User:wego-admin`:
```yaml
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: wego-admin
```

**Comment by yitsushi** [comment]
Changing the value in the `AdminClaims` to match with the Username in the login request would tell the system to "Use user XXXX" but that user has zero access.

**Comment by yitsushi** [comment]
Based on the discussion above and [under a related PR](https://github.com/weaveworks/weave-gitops/pull/2086#issuecomment-1117148039), it looks like a "wontfix". 

@rokshana-b : Can you confirm you are satisfied with the explanations and results?

**Comment by yitsushi** [comment]
As a potential resolution, maybe we can just change the default user created to `wego-admin` and that's not configurable?

**Comment by yitsushi** [comment]
How about this fake username display https://github.com/weaveworks/weave-gitops/pull/2087?

**Comment by Callisto13** [comment]
yeah that works 👍

**Comment by yitsushi** [comment]
Reopened https://github.com/weaveworks/weave-gitops/pull/2086
