### ISSUE TITLE
Research how to leverage the Flux CLI from the Weave GitOps CLI

### ISSUE THREAD

**Issue by jrryjcksn** [weaveworks/weave-gitops#2003]
# Leveraging the Flux CLI Functionality from Weave GitOps Core

## History
During the original implementation of WGCore, we researched the possibility of calling directly into the `flux` code base to invoke flux functionality. This turned out to be a non-starter since the flux2 code base is not structures as a set of libraries. It's organized as a set of commands, most of which either construct resources or query system state. So, the initial implementation directly executed the `flux` command in order access the flux functionality.

In retrospect, we made some choices that led to increased complexity and made things a bit less user-friendly:
* The GitOps binary _embedded_ a flux binary that it installed during GitOps installation and the state of the flux installation was mostly hidden from the user.
* Access to flux command other than the ones used internally was provided via a `gitops flux` subcommand.
* GitOps used the `wego-system` namespace rather than `flux-system`.

## New Approach
Going forward, we would like to:
* Make the handling of the flux CLI more transparent and less error-prone
* Make flux and Weave GitOps Core more consistent (e.g. use `flux-system` everywhere)
* Make everything from flux that is useful to Weave GitOps directly accessible via the `gitops` CLI

### New Handling of the Flux CLI
Rather than embedding a flux binary inside of the Weave GitOps binary, we can simply let the Weave GitOps binary call out the flux version range it supports and look in the PATH for flux. If no binary is available, or the available binary doesn't match the specified range, Weave GitOps will exit with a useful error message.

### Exposing Flux CLI Functionality through the Weave GitOps CLI
There are three pass-through cases to consider when exposing an underlying CLI through a "wrapper" CLI:
1. The wrapper provides access to an unmodified command from the underlying CLI
2. The wrapper provides a command absent from the underlying CLI
3. The wrapper provides a modified version of an underlying command

In case (1), other than invoking the command via the underlying CLI, the only extra work is dealing with `help`. Since the wrapper CLI has no knowledge of the underlying command, it can't provide help on its own. The prototype associated with this issue covers this by running the underlying help and replacing the underlying CLI name with the wrapper name in the three places the CLI name shows up:
* Usage
* Examples
* Final line

In case (2), nothing needs to be done. The normal Cobra machinery will work correctly. This leaves only case (3). In case (3) we have to deal with both the help issue _and_ getting access to the underlying command output if extra processing must be done by the wrapper. In the prototype, this is handled by performing a `WrapCommand` on the modified command:

```go
func init() {
	Cmd.Flags().BoolVarP(&zeta, "zeta", "z", true, "perform only the pre-installation checks")

	internal.WrapCommand(
		Cmd,
		internal.BackingCLI{CmdName: "flux", Alias: "gitops", VersionPath: "version", Version: "v0.27.3"},
		internal.Wrapper{
			Before: func(fs *pflag.FlagSet, args []string) error {
				fmt.Printf("BEFORE...\n")
				return nil
			},
			After: func(fs *pflag.FlagSet, args []string, wrappedOutput []byte) error {
				fmt.Printf("AFTER...\n%s\n", wrappedOutput)
				return nil
			},
		},
		[]string{"endpoint", "git-host-types", "insecure-skip-tls-verify", "override-in-cluster", "zeta"})
}
```

The arguments are:
1. The Cobra command
2. A description of the underlying CLI
3. A function to run _before_ the underlying command
4. A function to run _after_ the underlying command that gets passed the output from the underlying command
5. A list of flags being added to the command (so that we know which flags to _not_ pass on

Invoking a wrapped command consists of:

1. Running the _before_ command
2. Checking for the proper version of the underlying CLI and, if found, invoking the underlying command -- both capturing and displaying the output
3. Running the _after_ command with the captured output.

The branch: `gitops-support-for-flux-cli` (https://github.com/weaveworks/weave-gitops/tree/gitops-support-for-flux-cli) contains a prototype for this support. The "cmd/gitops/bootstrap" provides an example of case (3). Case (1) may be examined by invoking any flux command for which gitops has no counterpart.

The main pass-through support is in `cmd/gitops/main.o`.

**Comment by JamWils** [comment]
I am closing this issue, we are exploring other options for making the Flux CLI commands available in the CLI application.
