### ISSUE TITLE
No deployment details are shown for Helm Releases

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2016]
For example the Weave GitOps app itself:
<img width="1420" alt="Screenshot 2022-04-27 at 10 08 41" src="https://user-images.githubusercontent.com/19860021/165484081-757525d9-50db-467b-85ff-2ae35fa85ba0.png">

This is using wego-admin

**Comment by Callisto13** [comment]
what do the server logs say here? i would guess it is a "cluster scope" error and we need to pass the namespace for this object

**Comment by sympatheticmoose** [comment]
this was from the staging cluster, I can try and bring up locally

**Comment by steveww** [comment]
I have the same issue. I got a pop box with `secrets sh.helm.release.v1.prometheus.v1 not found`
This is for a Prometheus Helm chart. Similar messages for other Helm charts.

**Comment by sympatheticmoose** [comment]
@josecordaz I'm not convinced this is fixed. The issue is not (just) the source details page, the issue is that no deployments are showing up for HelmReleases. This still appears to be the case:
<img width="3347" alt="Screenshot 2022-05-12 at 10 15 02" src="https://user-images.githubusercontent.com/19860021/168036613-3999914e-3d9a-407e-95d8-a1aa99ccf193.png">

**Comment by josecordaz** [comment]
@sympatheticmoose This is probably related to #2097

**Comment by sympatheticmoose** [comment]
<img width="3318" alt="Screenshot 2022-05-13 at 09 25 41" src="https://user-images.githubusercontent.com/19860021/168242898-b839934b-7837-4a9f-a93e-c920106b6473.png">

Great to see this working!
