### ISSUE TITLE
Either fix or remove the repostats workflow

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#2019]
From what I can see it has not worked in about 2 months.

If we need it, fix it.

If not, remove it.

https://github.com/weaveworks/weave-gitops/actions/workflows/repostats.yaml

**Comment by sympatheticmoose** [comment]
Could try rebasing on what Flux have moved to since this was originally based on what they use - https://github.com/fluxcd/stats/blob/main/.github/workflows/repostats.yaml

**Comment by JamWils** [comment]
Let's determine the LOE for fixing this.

**Comment by ozamosi** [comment]
LoE: lower than creating a follow up ticket, so I fixed it instead.

**Comment by dholbach** [comment]
Thanks for that. @mewzherder is collecting metrics for Weave GitOps.
