### ISSUE TITLE
Last updated field is empty

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#2026]
**Describe the bug**

Last updated columns are empty for some of the Applications objects and for all of the Sources objects.

**Is this a UI bug or a server bug?**
- [x] UI
- [ ] Server

**What is the severity of the bug**

- [ ] `severity/Critical`: Weave GitOps is crashing or experiencing data loss, the UI is inaccessible or a key feature is unusable. There is no known workaround
- [x] `severity/Major`: Weave Gitops functionality is broken, there is a workaround, but the workaround requires significant effort
- [ ] `severity/Minor`: Weave Gitops functionality is broken, but there is a fairly straightforward workaround
- [ ] `severity/Low`: Doesn’t affect primary flow/functionality but would be good to fix

**Environment**
 - gitops: main
 - How you deployed the Weave GitOps server: Tilt, Helm Chart
 - kubernetes:  [e.g. 1.20.4]
    - [x] KinD - _version_]
    - [ ] k3s - _version_
    - [x] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_

**To Reproduce**

1. Go to `Applications Page`
2. Check `Last Updated` fields for listed objects
3. Navigate to `Sources Page`
4. Check `Last Updated` fields for listed objects

**Expected behavior**

Last Updated status should be populated for all objects listed on the page.

**Config and Logs**
If applicable, add logs to help explain your problem. _please compress the output before attaching_
- [ ] Logs from the `wego-app` pod
- [ ] Events from `flux-system` namespace (Or the namespace you deployed flux and/or Weave GitOps)
- [ ] `kubectl cluster-info dump`
- [ ] Prometheus alerts
- [ ] Flux logs

**Screenshots**

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/6fc59231-2d78-4d7d-8c20-bcb370d2966f)

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/a96109e1-c255-453e-9092-26da16eb81e2)

**Comment by sympatheticmoose** [comment]
There is still a question around the value being reported here, given this bug, we may be better to remove this column from the next release and revisit.

**Comment by jpellizzari** [comment]
@josecordaz Let's remove the field from the top-level object, but make sure it is populated for each of the conditions. Then, the UI can decide when it is appropriate to show that value.

**Comment by josecordaz** [comment]
@jpellizzari I only see the problem in the HelmRelease object, is that the top-level object you are referring to?. What would be the logic to follow so the UI can decide which date to use from the conditions?

**Comment by jpellizzari** [comment]
I see this used in lots of places: https://github.com/weaveworks/weave-gitops/blob/cb587d0803635bb8ec7136d6ac29e0543e647b8d/core/server/types/kustomization.go#L43

**Comment by josecordaz** [comment]
@jpellizzari Ah you are right. I guess then only Kustomizations and HelmReleases are the ones having the empty value issue. The rest of the entities(GitRepository, HelmChart, HelmRepository, Bucket) are using this function https://github.com/weaveworks/weave-gitops/blob/main/core/server/types/utils.go#L39 which takes the date from the Artifact field which seems to be populated properly.

**Comment by josecordaz** [comment]
@jpellizzari and I agreed to delete the field `lastHandledReconciledAt` from Kustomization and `lastUpdatedAt` from HelmRelease as there is no way to populate those anymore using the latest updates from flux over those primitives. The UI will use the information from the field `conditions` to figure that information out. I'll create a ticket for the UI side work.
