### ISSUE TITLE
Last updated field is empty

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#2027]
**Describe the bug**

Last updated columns are empty for some of the Applications objects and for all of the Sources objects.

**Is this a UI bug or a server bug?**
- [x] UI
- [ ] Server

**What is the severity of the bug**

- [ ] `severity/Critical`: Weave GitOps is crashing or experiencing data loss, the UI is inaccessible or a key feature is unusable. There is no known workaround
- [ ] `severity/Major`: Weave Gitops functionality is broken, there is a workaround, but the workaround requires significant effort
- [ ] `severity/Minor`: Weave Gitops functionality is broken, but there is a fairly straightforward workaround
- [ ] `severity/Low`: Doesn’t affect primary flow/functionality but would be good to fix

**Environment**
 - gitops: main
 - How you deployed the Weave GitOps server: Tilt, Helm Chart
 - kubernetes:  [e.g. 1.20.4]
    - [x] KinD - _version_]
    - [ ] k3s - _version_
    - [x] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_

**To Reproduce**

1. Go to `Applications Page`
2. Check `Last Updated` fields for listed objects
3. Navigate to `Sources Page`
4. Check `Last Updated` fields for listed objects

**Expected behavior**

Last Updated status should be populated for all objects listed on the page.

**Config and Logs**
If applicable, add logs to help explain your problem. _please compress the output before attaching_
- [ ] Logs from the `wego-app` pod
- [ ] Events from `flux-system` namespace (Or the namespace you deployed flux and/or Weave GitOps)
- [ ] `kubectl cluster-info dump`
- [ ] Prometheus alerts
- [ ] Flux logs

**Screenshots**

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/6fc59231-2d78-4d7d-8c20-bcb370d2966f)

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/a96109e1-c255-453e-9092-26da16eb81e2)

**Comment by Callisto13** [comment]
@rokshana-b is this a dupe of #2026?

**Comment by rokshana-b** [comment]
@Callisto13 yes, page reloaded when I created this issue - zenhub must've created the original and then recreated a dupe 🤦‍♀️ closing this issue and keeping the last one open 🙃
