### ISSUE TITLE
Validate Multi-Cluster stuff

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#2029]
Get a full setup going with a couple of clusters. Kind is fine.

We have focussed a lot on k8s rbac authorization, but have not thought much about how this plays with OIDC authentication. What trust relationships do we want/expect here?

**Comment by SamLR** [comment]
Hopefully can set the staging cluster up with a partner for to help testing this as well (although those don't have OIDC configured yet)

**Comment by Callisto13** [comment]
That would be awesome, happy to pair on this

**Comment by SamLR** [comment]
excellent, I'm currently trying to get enterprise running on the single cluster at the moment but once that's cleared might be worth grabbing some time to figure out strategy there

**Comment by Callisto13** [comment]
👍  also happy to pair on the enterprise bit; have no idea what is going on there 😁

**Comment by Callisto13** [comment]
closing in favour of #2107 and #2108
