### ISSUE TITLE
doc: provide guidance on changing an existing cluster user password

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2064]
Probably under https://docs.gitops.weave.works/docs/configuration/securing-access-to-the-dashboard/ it would make sense to detail any required steps should the user already have configured a password and has either forgotten or wishes to change it.

**Comment by gberche-orange** [comment]
Seems the dashboard password is bcrypt encoded 

https://github.com/weaveworks/weave-gitops/blob/ca873176ad365a97e4d328a2616eb980fbb70c6c/pkg/run/install/install_dashboard.go#L45-L53

and then passed in the HelmRelease.spec.values

However, did not find an easy bcrypt implementation on linux ubuntu yet

**Comment by makkes** [comment]
@gberche-orange The gitops CLI has a command for that:

```
$ gitops get bcrypt-hash -h
Generates a hashed secret

Usage:
  gitops get bcrypt-hash [flags]

Examples:

PASSWORD="<your password>"
echo -n $PASSWORD | gitops get bcrypt-hash
```

**Comment by Callisto13** [comment]
This is done
