### ISSUE TITLE
Make sure our impersonation works for groups

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#2066]
Just to be totally sure we are passing that right

**Comment by yitsushi** [comment]
Writing the OIDC/Dex documentation (#1786), I used Groups for testing ([weaveworks](https://github.com/yitsushi/gitops-config/blob/main/clusters/kind/groups/weaveworks.yaml), [quick-silver](https://github.com/yitsushi/gitops-config/blob/main/clusters/kind/groups/quick-silver.yaml)) and it worked as expected.

Or is it a different impersonation?

**Comment by Callisto13** [comment]
that is what i understood, maybe pesto is referring to a different "groups"?

all looks good from here tho, closing
