### ISSUE TITLE
Add namespace to list resources error message

### ISSUE THREAD

**Issue by luizbafilho** [weaveworks/weave-gitops#2075]
Add the `namespace` in the error message of `clustersmngr.Client.ClusteredList` (https://github.com/weaveworks/weave-gitops/blob/main/core/clustersmngr/client.go#L122)  to make clear what calls are being made, otherwise, the errors look repeated.

![Screenshot 2022-05-03 at 15.17.01.png](https://images.zenhubusercontent.com/57393dbdbf93871ccd9b0f07/12a22cc3-4b94-4594-92c7-9bf5578183d7)

**Comment by sympatheticmoose** [comment]
Believe we've improved the response here, please re-open if still a requirement.
