### ISSUE TITLE
Add ui alert recommending Chrome

### ISSUE THREAD

**Issue by joshri** [weaveworks/weave-gitops#2080]
As a response to #2049 - Safari doesn't respond well to `foreignObjects` inside svgs - we don't officially support Safari (and there have also been some issues with Firefox), so for now we will add an alert for the user that recommends use of Chrome.

**Comment by joshri** [comment]
OKAY - so I did some digging here - I thought this was pretty simple since I had detected the browser by using the `userAgent` feature before, but when looking it up all I see are recommendations to NOT USE IT: https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent

I was initially going through the quick fixes outlined here to try and fix the graph in Safari with no quick and easy results:
https://stackoverflow.com/questions/51313873/svg-foreignobject-not-working-properly-on-safari

@sympatheticmoose Is the graph the only place (that we know of) where we have issues? @jpellizzari looping you in cause I just know you have a brilliant solution in mind.

**Comment by sympatheticmoose** [comment]
@joshri with Core thats the only issue I've encountered

**Comment by jpellizzari** [comment]
Sniffing the user agent to do hax is a Frontend tradition as old as time.
Looks like some people have had luck with applying different CSS.

We can always just convert things to SVG text.

Reported in 2009:
https://bugs.webkit.org/show_bug.cgi?id=23113

A message recommending Chrome is not the way, IMO. On mobile iOS,
everything is Safari (webkit).

**Comment by jpellizzari** [comment]
Closing this, as recommending another browser won't work on mobile, and is not a great UX. #2049 still remains, however.
