### ISSUE TITLE
Old version of Flux being used?

### ISSUE THREAD

**Issue by bigkevmcd** [weaveworks/weave-gitops#2089]
This looks like a pretty old (and unsupported version?)

Should we bump this to a v0.30.x version?

https://github.com/weaveworks/weave-gitops/blob/761982b9be689655d3554943fe9d6cc005e539cd/gitops.dockerfile#L1

**Comment by sympatheticmoose** [comment]
why is this even in here? I was under the impression we removed Flux from the CLI?

**Comment by JamWils** [comment]
Since we are bringing it back in anyway we might as well update this and move it forward.

**Comment by chanwit** [comment]
We need to upgrade Flux ASAP as Flux < v0.30 contains 3 CVEs.
Please also note that Source controller CRDs are v1beta2 in v0.30.

**Comment by ozamosi** [comment]
This file isn't used for anything, and this argument would be overriden by the makefile if we were to use it.

**Comment by JamWils** [comment]
That is good to know.  Do we need to keep the file around then?
