### ISSUE TITLE
Tilt jobs hit ulimit on Mac

### ISSUE THREAD

**Issue by joshri** [weaveworks/weave-gitops#2095]
I was hitting a ulimit error on Mac when working with Tilt to develop the UI (too many open files). Increasing my ulimit to 524288 and restarting my computer got things going again, but maybe this is something that needs to be known for dev setup / an indicator of something else?

**Comment by Callisto13** [comment]
Do you know whether it was Tilt claiming all the fds, or something else did and Tilt was just the first to notice?

**Comment by joshri** [comment]
> Do you know whether it was Tilt claiming all the fds, or something else did and Tilt was just the first to notice?
> 
> (Fine if you didn't grab that before rebooting)

Absolutely did not grab that before setting my limit to 524288 and rebooting sadly.

**Comment by jpellizzari** [comment]
Probably an issue with the `inotify` settings on the "node" which in this case is a docker container: 

https://github.com/kubernetes/kubernetes/issues/64315#issuecomment-904103310

**Comment by Callisto13** [comment]
Nice find

**Comment by sympatheticmoose** [comment]
closing as seems stale
