### ISSUE TITLE
Empty automations list on Source detail page

### ISSUE THREAD

**Issue by josecordaz** [weaveworks/weave-gitops#2097]
**Describe the bug**

There is an edge case where the Source detail page doesn't show any items in the automations list.

**Is this a UI bug or a server bug?**
- [X] UI
- [ ] Server

**What is the severity of the bug**

- [ ] `severity/Critical`: Weave GitOps is crashing, the UI is inaccessible or a key feature is unusable. There is no known workaround.
- [ ] `severity/Major`: Weave Gitops functionality or a key feature is broken. There is a workaround, but the workaround requires significant effort.
- [X] `severity/Minor`: A non-key feature or functionality is broken. There is a fairly straightforward workaround.
- [ ] `severity/Low`: Doesn’t affect primary flow/functionality but would be good to fix.

**Environment**
 - Weave-Gitops Version, commit sha or image tag: b27097b0f1084e94756673015cfcdbb237221c3a [e.g. `v0.1.0`, `3499ba2a`, or `1651069883-3499ba2a2c78a7c04c47c56c58eb77eede4b21f4`]
 - How you deployed the Weave GitOps server: tilt [e.g. Tilt, Helm Chart, etc]
 - Kubernetes version: 1.21.1 [e.g. 1.20.4]
 - Where are you running your cluster?
    - [X] KinD - _version_
    - [ ] k3s - _version_
    - [ ] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_
 - Browser + version: Firefox 99.0.1 (64-bit) [e.g. chrome 74, safari 12, firefox 87]

**To Reproduce**
1. Having a kind cluster ready with flux installed(no bootstrap).
2. Initialize tilt `make cluster-dev`
3. Run:
```
flux create source git podinfo-git-source \
  --url=https://github.com/stefanprodan/podinfo \
  --branch=master \
  --interval=30s
```
to create the git source
4. Run 
```
flux create kustomization podinfo \
  --target-namespace=flux-sytem \
  --source=podinfo-git-source \
  --path="./kustomize" \
  --prune=true \
  --interval=5m
``` 
to create the kustomization
5. Go to Sources
6. Refresh page
6. Click on `podinfo-git-source`
7. Notice the empty list
![image.png](https://images.zenhubusercontent.com/606389311ead0cc4788a9a72/98624620-73ce-4410-a51f-ea64aed34f57)
7. Refresh the page a second time
8. Notice the list is empty no more
![image.png](https://images.zenhubusercontent.com/606389311ead0cc4788a9a72/b5300fb4-8eed-4dc2-bdfb-412f591edc8e)

**Expected behavior**
It should show elements on the list all the time.

**Screenshots**
Video [https://app.zenhub.com/files/342592099/6b5fac26-42d9-4c41-a769-37361589dba9/download](https://app.zenhub.com/files/342592099/6b5fac26-42d9-4c41-a769-37361589dba9/download)

**Comment by jpellizzari** [comment]
@josecordaz Can you check the API response to see if this is a server-side issue or UI issue?

**Comment by josecordaz** [comment]
@jpellizzari Sorry for the delay. API responses seem ok, they are being triggered properly and responses return with expected data in both cases.
