### ISSUE TITLE
Consider our impersonation model

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#2108]
We currently impersonate the Principal directly, and therefore expect the cluster operator to have set up a mirrored kubernetes user in **every** cluster with the correct bound role.

This presents some overhead for both us (we have to cache principal:namespace:cluster access for each user) and for the cluster operator (they have to deal with and maintain a lot of yaml for every user which interacts with wego).

Sam has been noodling on a model which may be easier for both parties. Find the gist [here](https://gist.github.com/SamLR/575e779b4f43f0839047a8263935a9cd).

The tasks for this ticket are:
- [ ] Decide whether we are happy with the current state of affairs. If we are, comment with a reason and close this issue.
- [ ] If we want to change this, take Sam's idea as a starting point and expand on it
- [ ] Build a spike for review, and spin off further tickets or investigations
- [ ] If we want to change something but don't want to change it this way, come up with come other solution, spike it, etc

_Note: for the purposes of this ticket you can (if you want) assume the current OIDC trust relationship will stay the same. That is scoped in another ticket. Or you can do that other one first and come back to this. Or do them both together. Whatever you like._

**Comment by bigkevmcd** [comment]
We don't require a user, we require `RoleBindings`.

But, we really don't want to build a new RBAC mechanism for Kubernetes if we can avoid it, yes, K8s RBAC is hard, and yes, there may be a need at some point, but not right now.
