### ISSUE TITLE
Flaky tests in core/server/sync_test.go

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#2114]
**Describe the bug**

CI failed on `core/server/sync_test.go` in `TestSync`
```
panic: send on closed channel

goroutine 11395 [running]:
github.com/weaveworks/weave-gitops/core/server_test.TestSync.func1.1()
	/home/runner/work/weave-gitops/weave-gitops/core/server/sync_test.go:105 +0x6b
created by github.com/weaveworks/weave-gitops/core/server_test.TestSync.func1
	/home/runner/work/weave-gitops/weave-gitops/core/server/sync_test.go:103 +0x245
```

**Is this a UI bug or a server bug?**
- [ ] UI
- [ ] Server
- [x] Test!

**What is the severity of the bug**

- [ ] `severity/Critical`: Weave GitOps is crashing, the UI is inaccessible or a key feature is unusable. There is no known workaround.
- [ ] `severity/Major`: Weave Gitops functionality or a key feature is broken. There is a workaround, but the workaround requires significant effort.
- [ ] `severity/Minor`: A non-key feature or functionality is broken. There is a fairly straightforward workaround.
- [x] `severity/Low`: Doesn’t affect primary flow/functionality but would be good to fix.

**Environment**
`make unit-tests` at `d74794b8`

**To Reproduce**
`go test -run 'TestSync$' ./core/server`

**Expected behavior**
Should pass and not fail.

**Additional context**
This is a very rare flake so there is zero need to rush and fix this unless a) it comes back again and frequently, or b) you are very bored.

**Comment by opudrovs** [comment]
Another flake in the same file:
Sample run:
https://github.com/weaveworks/weave-gitops/actions/runs/4552810725/jobs/8028618207?pr=3562

Run logs:
INFO GET OBJECT Bucket: gitops-run-logs Object: session-id/20230329-101725.17336.txt
INFO CREATE OBJECT: gitops-run-logs session-id/20230329-101725.17726.txt
► round 2 - test action
INFO CREATE OBJECT: gitops-run-logs session-id/20230329-101725.17751.txt
✗ round 2 - test failure
INFO LIST BUCKET
INFO bucketName: gitops-run-logs prefix: prefix:"session-id" page: {Marker:session-id/20230329-101725.17336.txt HasMarker:true MaxKeys:1000}
INFO GET OBJECT Bucket: gitops-run-logs Object: session-id/20230329-101725.17726.txt
INFO GET OBJECT Bucket: gitops-run-logs Object: session-id/20230329-101725.17751.txt
--- FAIL: TestSync (12.22s)
    --- FAIL: TestSync/helm_release_with_source (2.02s)
        sync_test.go:148: Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io "myapp": the object has been modified; please apply your changes to the latest version and try again
        
It might be related to the issue we tried to reproduce here and misread the logs:
https://github.com/weaveworks/weave-gitops/issues/3192

I ran all files in the `core/server` folder to reproduce the issue, so if those flakes in sync_test were more common, they would have been replicated.

**Comment by LappleApple** [comment]
Will reopen if we see this again
