### ISSUE TITLE
Link to kustomization / Helm Release location in git

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2115]
**Short description**
As an application operator I want to be able to easily navigate to the location of a given kustomization so that I can apply changes and fix issues.

Consider the Weave GitOps app as an example, say I've pinned a version in the HelmRelease and I need to change this value. I want to quickly navigate to where the object is defined so that I may take this action. 

From the Applications details page this is what I can see:
<img width="589" alt="Screenshot 2022-05-06 at 13 58 05" src="https://user-images.githubusercontent.com/19860021/167136189-33ebd103-ec46-4526-aed2-1a8f60718b27.png">

There is nothing here which would help me navigate to the appropriate location in GitHub. Neither is this apparent through the source (HelmChart or HelmRepository)

<img width="674" alt="Screenshot 2022-05-06 at 14 08 45" src="https://user-images.githubusercontent.com/19860021/167137677-286ec212-dbc8-4d1d-9331-4d2e9b221ef8.png">
<img width="522" alt="Screenshot 2022-05-06 at 14 08 30" src="https://user-images.githubusercontent.com/19860021/167137681-e6c1c528-0d5e-4dfa-8c9e-00f401ba1147.png">

A similar experience exists for kustomizations

This information could _potentially_ be surfaced through the same mechanism as `flux trace`:

```
flux trace -n test helmrelease ww-gitops

Object:        HelmRelease/ww-gitops
Namespace:     test
Status:        Managed by Flux
---
Kustomization: flux-system
Namespace:     flux-system
Path:          ./clusters/rbac-test
Revision:      main/1312da654b66006bd8074d728a1dda3d80af0335
Status:        Last reconciled at 2022-05-06 13:59:50 +0100 BST
Message:       Applied revision: main/1312da654b66006bd8074d728a1dda3d80af0335
---
GitRepository: flux-system
Namespace:     flux-system
URL:           ssh://git@github.com/sympatheticmoose/fleet-infra
Branch:        main
Revision:      main/1312da654b66006bd8074d728a1dda3d80af0335
Status:        Last reconciled at 2022-05-05 00:25:01 +0100 BST
Message:       stored artifact for revision 'main/1312da654b66006bd8074d728a1dda3d80af0335'
```

Other mechanisms may exist - perhaps the same as the related automations view we build, but flipping the relationship. It would be _fantastic_ if we could get a direct link to the given object's location.

**Acceptance criteria**
- [ ] From a Kustomization / HelmRelease page, there is a link which takes the user to where this object is defined, or a way to navigate this path. For example a link to the kustomization which deployed this object and from there the source location.

**Comment by sympatheticmoose** [comment]
@sympatheticmoose to update based on current UX

**Comment by sympatheticmoose** [comment]
@bia I think we could use some help here

**Comment by bia** [comment]
@sympatheticmoose could the UI solution here be as simple as adding a URL field above the Source field ?

<img width="1512" alt="Screenshot 2022-11-20 at 21 442" src="https://user-images.githubusercontent.com/92439/203023104-2b9fc144-0b69-4410-8de3-faf4a1d4559f.png">

**Comment by LappleApple** [comment]
Per @bigkevmcd: "while this would be great there’s no simple answer to 'where' a file comes from except for really simple cases. Fundamentally, when you render the files, they get built from multiple sources, and returned as a set of resources, You don’t get the files. We would need to build some sort of “ingester” similar to Backstage, but that would suffer from the same problem. Backstage can do this, because it has a simpler model. 

cc @squaremo @yiannis: Based on what K's said, I'd close--but wanted to tag you first in case you disagreed.
