### ISSUE TITLE
OIDC Auth error calling /oauth2/userinfo

### ISSUE THREAD

**Issue by uberbrodt** [weaveworks/weave-gitops#2125]
**Describe the bug**

**Is this a UI bug or a server bug?**
- [ ] UI
- [x] Server

**What is the severity of the bug**

- [x] `severity/Critical`: Weave GitOps is crashing, the UI is inaccessible or a key feature is unusable. There is no known workaround.
- [ ] `severity/Major`: Weave Gitops functionality or a key feature is broken. There is a workaround, but the workaround requires significant effort.
- [ ] `severity/Minor`: A non-key feature or functionality is broken. There is a fairly straightforward workaround.
- [ ] `severity/Low`: Doesn’t affect primary flow/functionality but would be good to fix.

**Environment**
 - wgo-app:v0.8.0/docker-pullable://ghcr.io/weaveworks/wego-app@sha256:07ad5e9b00cd96a1daf728385b831f691804017501ae15f539de046e52775c83 
    + This can be found by going to `/v1/version` on your server. 
 - How you deployed the Weave GitOps server:helmchart
 - Kubernetes version:  1.21
 - Where are you running your cluster?
    - [ ] KinD - _version_
    - [ ] k3s - _version_
    - [x ] cloud [EKS]  _version_
    - [ ] other - _name_ _version_
 - Browser + version: [e.g. chrome 74, safari 12, firefox 87] Firefox latest

**To Reproduce**
1. Setup OIDC auth secrets and OIDC client (using keycloak auth server)
2. Login, redirected to oauth2/callback.
3. Dashboard appears, some requests completed
4. app makes XHR request to /oauth2/userinfo and receives following error:
```
{"message":"failed to query user info endpoint: 401 Unauthorized: {\"error\":\"invalid_token\",\"error_description\":\"Token verification failed\"}","code":401}
```

Browser is then redirected to login page. 

**Expected behavior**
the OIDC exchange is successful and the tokens in the headers seem correct to me. I can send via email if you like.

**Config and Logs**
If applicable, add logs to help explain your problem. _please compress the output before attaching_
- [ ] The yaml of the object you are viewing
- [x] Logs from the `wego-app` po
- [ ] Events from `flux-system` namespace (Or the namespace you deployed flux and/or Weave GitOps)
- [ ] `kubectl cluster-info dump`
- [ ] Prometheus alerts
- [ ] Flux logs

```
2022-05-08T22:09:35.684Z    INFO    gitops    middleware/middleware.go:58    request success    {"uri": "/v1/featureflags", "status": 200}                                                                                                                                                               │
│ 2022-05-08T22:09:41.107Z    INFO    gitops.auth-server    auth/jwt.go:120    attempt to read token from cookie                                                                                                                                                                                           │
│ 2022-05-08T22:09:41.107Z    INFO    gitops.auth-server    auth/jwt.go:64    attempt to read token from auth header                                                                                                                                                                                       │
│ 2022-05-08T22:09:41.107Z    INFO    gitops.auth-server    auth/jwt.go:38    attempt to read token from cookie                                                                                                                                                                                            │
│ 2022-05-08T22:09:41.108Z    INFO    gitops.auth-server    auth/jwt.go:120    attempt to read token from cookie                                                                                                                                                                                           │
│ 2022-05-08T22:09:41.108Z    INFO    gitops.auth-server    auth/jwt.go:64    attempt to read token from auth header                                                                                                                                                                                       │
│ 2022-05-08T22:09:41.108Z    INFO    gitops.auth-server    auth/jwt.go:38    attempt to read token from cookie                                                                                                                                                                                            │
│ 2022-05-08T22:09:41.193Z    INFO    gitops    middleware/middleware.go:58    request success    {"uri": "/v1/kustomizations?", "status": 200}                                                                                                                                                            │
│ 2022-05-08T22:09:41.199Z    INFO    gitops    middleware/middleware.go:58    request success    {"uri": "/v1/helmreleases?", "status": 200}                                                                                                                                                              │
│ 2022-05-08T22:09:42.935Z    INFO    gitops    middleware/middleware.go:58    request success    {"uri": "/v1/featureflags", "status": 200}       
```

**Screenshots**

**Additional context**

**Comment by ozamosi** [comment]
Hello, and thank you for your report!

I haven't quite been able to reproduce what's going on, so if you could send me any extra logs to robin.sonefors@weave.works I'd really appreciate it.

> Dashboard appears, some requests completed
> app makes XHR request to /oauth2/userinfo and receives following error:

How long is it between these two steps? Like, is it a second or two, or is it more than that?

**Comment by uberbrodt** [comment]
Just sent an email screenshots of the requests and some request/response data.

**Comment by ozamosi** [comment]
Thank you for the email!

I believe the issue is caused by a bit of confusion about how we use oidc. We erroneously requested a refresh token whereas we didn't actually use one - we just use the access token. Your access token was only issued for 5 minutes, so after 5 minutes, it stops being valid and you get logged out - you've also issued us a refresh token to use to get a new access token, but we don't have that functionality to use that right now.

You can remove the offline_access scope from weave gitops, but you will have to make the access token valid for longer, and I believe it will work.

**Comment by uberbrodt** [comment]
Hmmm, it's definitely hitting the error condition before 5 minutes is up, I've adjusted it up to 30 minutes am I'm still seeing the same error. I sent a quicktime video to your email of the behaviour.

I don't see a way to adjust the scopes via the Helm chart; is it possible?

**Comment by cr1cr1** [comment]
Having the same issue. Wasn't PR https://github.com/weaveworks/weave-gitops/pull/2152 supposed to fix this?

**Comment by makkes** [comment]
I'm pretty sure the reason for this happening is that the weave-gitops server uses the ID token (which it obtains from the `id_token` cookie from the client) in the `Authorization` header instead of the access token issued by the OIDC provider.
