### ISSUE TITLE
Tidy enterprise documentation

### ISSUE THREAD

**Issue by SamLR** [weaveworks/weave-gitops#2129]
**Short description**
As a user it should be clear to me which guides are part of the enterprise offering.

The 'enterprise' directory only contains an introduction, other docs (e.g. 'cluster management with CAPA') are mixed in with core documents. I'd assume that all enterprise documentation would live in its directory. 

**Possible solutions**

Everything that is enterprise only is moved into the 'enterprise' directory *or* the enterprise directory is removed and enterprise documents have a clear call-out at the start to make them clear they only apply to that version of the application

**Comment by sympatheticmoose** [comment]
closing based on upcoming changes to docs which should remove the enterprise directory 🤞
