### ISSUE TITLE
Deploy podinfo with kustomizations per environment

### ISSUE THREAD

**Issue by markramm** [weaveworks/weave-gitops#214]
**Short description**
As a application operator I want to deploy podinfo across several environments with kustomizations so that I know how to do the same with a real world app with different config per environent. 

**Given** two target clusters with WeGO GORT installed
**And** a `podinfo` app in a `git` repository
**And** unique kustomizations for each of the target clusters in different directories
**When** I `wego app add` the `podinfo` app to the two target clusters
**Then** the specific kustomizations are applied
**And** the kustomized apps are successfully deployed in the target clusters

**Comment by jpellizzari** [comment]
Not ready yet, requires multiple clusters in which we can deploy (multi-cluster)
