### ISSUE TITLE
Support partial success on UI

### ISSUE THREAD

**Issue by luizbafilho** [weaveworks/weave-gitops#2143]
**Short description**
With the addition of `errors` field in the Clustered List calls on the backend (https://github.com/weaveworks/weave-gitops/pull/2116), the UI should check for those and display the errors accordingly if they are present.  

**Acceptance criteria**
- [ ] UI list errors and partial success results at the same time.

**Comment by JamWils** [comment]
I am closing this issue for the time being.  It is important and we want to make sure that the user has a consistent experience when errors occur.  It sounds like there is some things we need to investigate as this has a bigger impact on the enterprise product and not so much the core product.
