### ISSUE TITLE
Revision field is empty for Helm Release objects

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2149]
**Describe the bug**
When viewing a HelmRelease object in the Applications view, the revision field appears empty as shown in the screenshot and request response below:

<img width="2822" alt="Screenshot 2022-05-12 at 10 46 38" src="https://user-images.githubusercontent.com/19860021/168043650-1d346159-14f8-4ba7-9b98-1badd385a1b0.png">

```
{"helmReleases":[{"releaseName":"podinfo", "namespace":"default", "name":"podinfo", "interval":{"hours":"0", "minutes":"1", "seconds":"0"}, "helmChart":{"namespace":"default", "name":"default-podinfo", "sourceRef":{"kind":"HelmRepository", "name":"podinfo", "namespace":""}, "chart":"podinfo", "version":">5.0.0", "interval":null, "conditions":[], "suspended":false, "lastUpdatedAt":"", "clusterName":""}, "conditions":[{"type":"Ready", "status":"True", "reason":"ReconciliationSucceeded", "message":"Release reconciliation succeeded", "timestamp":"2022-05-12T09:10:51Z"}, {"type":"Released", "status":"True", "reason":"InstallSucceeded", "message":"Helm install succeeded", "timestamp":"2022-05-12T09:10:51Z"}], "inventory":[{"group":"", "kind":"Service", "version":"v1"}, {"group":"apps", "kind":"Deployment", "version":"v1"}], "suspended":false, "clusterName":"Default", "helmChartName":"default/default-podinfo"}], "errors":[]}
```

The required information is available within the status/Last Applied Revision of the HelmRelease object:
```
Status:
  Conditions:
    Last Transition Time:          2022-05-12T09:10:51Z
    Message:                       Release reconciliation succeeded
    Reason:                        ReconciliationSucceeded
    Status:                        True
    Type:                          Ready
    Last Transition Time:          2022-05-12T09:10:51Z
    Message:                       Helm install succeeded
    Reason:                        InstallSucceeded
    Status:                        True
    Type:                          Released
  Helm Chart:                      default/default-podinfo
  Last Applied Revision:           6.1.4
  Last Attempted Revision:         6.1.4
  Last Attempted Values Checksum:  941f684021688ea1ca9b94e17b87c46b6f8d4e1f
  Last Release Revision:           1
  Observed Generation:             1
```

**Is this a UI bug or a server bug?**
- [ ] UI
- [x ] Server

**What is the severity of the bug**

- [ ] `severity/Critical`: Weave GitOps is crashing, the UI is inaccessible or a key feature is unusable. There is no known workaround.
- [ x ] `severity/Major`: Weave Gitops functionality or a key feature is broken. There is a workaround, but the workaround requires significant effort.
- [ ] `severity/Minor`: A non-key feature or functionality is broken. There is a fairly straightforward workaround.
- [ ] `severity/Low`: Doesn’t affect primary flow/functionality but would be good to fix.

**Environment**
 - Weave-Gitops Version, commit sha or image tag: Running off main, last commit 749fd0f95345d4631e45ca7f7535551d2b97fce6
    + This can be found by going to `/v1/version` on your server. 
 - How you deployed the Weave GitOps server: Tilt
 - Kubernetes version:  1.21.1
 - Where are you running your cluster?
    - [x ] KinD - 1.21.5
    - [ ] k3s - _version_
    - [ ] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_
 - Browser + version: [e.g. chrome 74, safari 12, firefox 87]

**To Reproduce**
1. Create a Helm based deployment. For example following the instructions here - https://github.com/stefanprodan/podinfo#continuous-delivery
2. Login to the dashboard and view under applications

**Expected behavior**
UI should report last applied revision

**Config and Logs**
If applicable, add logs to help explain your problem. _please compress the output before attaching_
- [ ] The yaml of the object you are viewing - 
- [ ] Logs from the `wego-app` pod
- [ ] Events from `flux-system` namespace (Or the namespace you deployed flux and/or Weave GitOps)
- [ ] `kubectl cluster-info dump`
- [ ] Prometheus alerts
- [ ] Flux logs

Please advise if further information required.

**Comment by ozamosi** [comment]
Helm releases don't have revisions. Would you like it to show the helm release version instead?

**Comment by sympatheticmoose** [comment]
Revision was chosen as the term since it seemed applicable across all Flux objects. As in the above, `  Last Applied Revision:           6.1.4`
