### ISSUE TITLE
Redundant flux-system namespace 

### ISSUE THREAD

**Issue by iahmad9** [weaveworks/weave-gitops#215]
**Describe the bug**
Running `wego install | kubectl apply -f -` creates two namespaces `wego-system` and `flux-system` when there should only be one namespace created.

**Environment**
 - wego: v0.0.0
 - 
**Affects versions**
 wego: v0.0.1

**To Reproduce**
1. Get or build the latest wego binary 
2. Run the command `wego install | kubectl apply -f -`
3. Observe the log and see there's two namespaces created 
Logs

**Expected behavior**
There should only be one namespace created either default `wego-system` or the name provided by `--namespace` flag

**Config and Logs**
```
namespace/flux-system unchanged
namespace/wego-system unchanged
customresourcedefinition.apiextensions.k8s.io/alerts.notification.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/buckets.source.toolkit.fluxcd.io configured
```

**Screenshots**

**Additional context**

**Comment by rokshana-b** [comment]
Since changes were made to `wego install`, the console output has changed into a different one. This bug is no longer an issue. New output screenshot has been provided.

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/b73179e2-5689-408d-85c9-cce94a3ff857)
