### ISSUE TITLE
Create endpoint to suspend/resume resources

### ISSUE THREAD

**Issue by opudrovs** [weaveworks/weave-gitops#2170]
As a user I want to be able to resume and suspend Flux primitives from the UI just like I can via the CLI using the `resume` and `suspend` commands.

As a FE engineer, I want an endpoint that I can call that will resume and and another endpoint that will suspend the following resources.

- Kustomization
- HelmRelease
- GitRepository
- HelmRepository
- Bucket

As a FE engineer, this endpoint should only be able to take one object at a time.  For example,

GET `v1/resume/{resource}/{namespace}/{name}`
GET `v1/suspend/{resource}/{namespace}/{name}`

So to pause the main flux reconciliation kustomization I can call the endpoint

GET `v1/suspend/kustomization/flux-system/flux-system`

To resume my application git repository which is in the "dev" namespace I can call the endpoint

GET `v1/suspend/gitrepository/dev/app`

These endpoints are expected to be idempotent.  When I call resume multiple times and an object is already "resumed", it just keeps the object resumed.

**Comment by JamWils** [comment]
@jpellizzari is the following description good?
