### ISSUE TITLE
Web UI fails to redirect to login screen

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#2171]
**Describe the bug**

Our official doc site has an example of the helm chart that does not provide the smoothest experience. When I tried to use the example yaml file, my UI was giving me problems. I did not see any login page; I was taken directly to the applications page with an error on top. The version on the bottom of the page showed v0.8.0.

**Environment**

- Weave-Gitops Version = v0.8.0
- Flux Version = v0.30.2
- Kubernetes version = v1.23.4

**To Reproduce**

1. Go to official doc site
2. Navigate to Installation page: https://docs.gitops.weave.works/docs/next/installation/
3. Scroll down to weave-gitops helm chart example
4. Use the example file during flux bootstrap
5. After bootstrapping flux, see the ww-gitops-weave-gitops service up and running
6. Run `kubectl port-forward svc/ww-gitops-weave-gitops -n flux-system 9001:9001`
7. Go to dashboard UI via http://localhost:9001
8. See error on page

**Expected behavior**

The example on the official doc site should be working properly. If there's some field missing or the helm chart version needs to be explicitly provided, then the doc should reflect that. If this is an issue with weave-gitops v0.8.0, then it needs to be resolved asap.

**Actual Behavior With Screenshots**

![Screen Shot 2022-05-18 at 09.12.56.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/5311c08e-5dc6-44aa-b708-6a7ca43359b4)

**Comment by sympatheticmoose** [comment]
@rokshana-b can you confirm whether you were asked to login or whether you were able to get to this page without logging in?

**Comment by rokshana-b** [comment]
That sounds critical - changing label
