### ISSUE TITLE
Application page shows error and blanks out after installing an upstream helm chart

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#2173]
**Describe the bug**

I tried adding helm charts from upstream helm repositories. Flux gave  no errors and installed the helm releases successfully. However, the Applications Page on the UI gave an error about missing secrets and blanked out. Previously listed applications objects could not be seen anymore. Even automation object list disappeared from sub-pages. This is also happening for faulty helm releases from git repos. The objects became visible again once I deleted the helm releases. 

**Environment**

- Weave-Gitops Version = v0.8.1-rc.4
- Flux Version = v0.30.2
- Kubernetes version = v1.23.4

**To Reproduce**

1. Run `flux create source helm kube-ops --interval=1h --url=https://charts.kube-ops.io`
2. Go to UI dashboard and click on `Sources` tab
3. See `kube-ops` source get added
4. Run `flux create helmrelease loki --interval=1h --target-namespace=loki --source=HelmRepository/kube-ops --chart=loki --chart-version=1.7.1`
5. Wait for flux to add `loki` successfully
6. Navigate to UI Applications page
7. See error message on top and other Applications objects list gone
8. Run `flux delete helmrelease loki`
9. Navigate to UI Applications page and see error gone and existing objects list show up again

**Expected behavior**

Applications object list should not just disappear. 

**Actual Behavior**

I followed the flux documentation to add various helm charts. Some scenarios failed, some passed. But no matter the pass/fail situation, the UI seemed to have a problem with any kind of addition of upstream helm-charts. Whatever the problem, existing applications objects list should not disappear.

**Screenshots**

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/0e66f770-c81e-41ce-9028-767b13bb0c1a)

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/7c5864e6-01ec-4065-9fcf-7349cc9ae0a3)

﻿![Screen Shot 2022-05-17 at 16.00.28.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/67516747-6493-4cb3-83fd-4650c36aab31)

**Comment by foot** [comment]
This one I thin #2132

**Comment by ozamosi** [comment]
Agree with @foot, let's only keep one.
