### ISSUE TITLE
Helmreleases missing events 

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#2175]
**Describe the bug**

Helm release objects are missing events in Applications sub page. Kubectl commands show events that are not reflected for helm releases on the UI

**Environment**

- Weave-Gitops Version = v0.8.1-rc.4
- Flux Version = v0.30.2
- Kubernetes version = v1.23.4

**To Reproduce**

1. Go to UI dashboard
2. Click on a helm release object
3. Navigate to subpage and click on `Events` tab
4. See empty list

**Expected behavior**

Events relating to the helm release object should be visible.

**Actual Behavior With Screenshots**

﻿![Screen Shot 2022-05-18 at 08.35.09.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/8a625c47-9162-4e37-95de-437980d93d3c)

![Screen Shot 2022-05-18 at 08.41.14.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/15d5f83a-864c-4410-bd38-fde1d8fdecdb)

**Comment by JamWils** [comment]
Another way to check this is to just use kubectl to get the events for that object.  If some return then you know it is a UI issue.

**Comment by rokshana-b** [comment]
@sympatheticmoose I'll recheck that

**Comment by sympatheticmoose** [comment]
Yup, looks like there is a bug here, good catch.

**Comment by ozamosi** [comment]
This doesn't just apply to HelmReleases, but also to all types of Sources.
