### ISSUE TITLE
Error message when trying to sync a suspended object

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#2177]
**Describe the bug**

When a kustomization is suspended and user tries to sync with sync button, an error message shows up saying the sync timed out. My expectation was to see the UI detect the suspended status and pop out a message informing that. Syncing should quit when suspended status is detected - it should not continue to try and sync, before finally timing out.

**Environment**

- Weave-Gitops Version = v0.8.0
- Flux Version = v0.30.2
- Kubernetes version = v1.23.4

**To Reproduce**

1. Run `flux suspend kustomization flux-system --namespace=flux-system`
2. Go to UI and see suspended status reflected for flux-system
3. Click on flux-system and navigate to sub page
4. Click on sync button
5. Wait for the sync to time out
6. See error message

**Expected behavior**

Suspended status should be detected and sync should quit.

**Actual Behavior With Screenshots**

![Screen Shot 2022-05-18 at 10.03.45.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/a606629c-8948-485e-b80d-b7a774a5c754)

**Comment by sympatheticmoose** [comment]
quick fix would be `✗ resource is suspended` error message as per Flux CLI

**Comment by alex-xnebulaliu** [comment]
The sync button still enable when check a suspended item in the list.
![image](https://github.com/weaveworks/weave-gitops/assets/141733649/f3d0d972-59b4-4c44-aa97-9a1b6474a764)
