### ISSUE TITLE
Automation Detail Pages

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2222]
As a user I want to go to the Kustomization or Helm Release detail page and on the detail tab see extra metadata information that is on the object.

**Considerations:** we should be able to use k8s annotations on the resource for accomplishing this task.

**Limitations:**
1. The key for annotations can only be 63 characters long.
2. We are limited to alphanumeric, `-`, `.`, and `_` characters for the key.

https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set

### Acceptance Criteria

Add annotations to a Kustomization and Helm Release in your git repository and have them sync with Flux.  When you open Weave GitOps and go to the detail pages of those specific Kustomization and Helm Release objects you will see the following behavior.

1. When I mark something with `metadata.weave.works/description` a key/value pair for that item appears below the default key value pairs in the UI. E.g. `metadata.weave.works/description: Hello` would appear as `Description: Hello` on the site under the Metadata group per the designs.

2. When I create an annotation with multiple words with `-` then I will format that appropriate.  E.g.`metadata.weave.works/created-by: Lone Star` then I will see `Created By: Lone Star` on the site under the Metadata group per the designs.

3. When I create an annotation with multiple words via lower camel case `createdBy` or upper camel case `CreatedBy` then no special formatting will occur. E.g. `metadata.weave.works/createdBy: Shrek` or `metadata.weave.works/CreatedBy: Boss Baby` then I will see `createdBy: Shrek` and `CreatedBy: Boss Baby` respectively.

4. When I create an annotation that is a url such as `metadata.weave.works/google: https://www.google.com` then I would expect to be able to see `Google: https://www.google.com` and to be able to click on the hyperlink and be taken to the appropriate page **on a new tab**.

5. When I have an additional weaveworks annotation such as `weave.works/surprise` or `random.weave.works/something` these are not registered as metadata and do not appear on the page.

6. When I have an additional arbitrary annotation such as `this.is.important/i-mean-it` these are not registered as metadata and do not appear on the page.

7. When there are multiple metadata key/values they are sorted alphabetically.  So even if the payload returns `metadata.weave.works/foo` before `metadata.weave.works/bar`.  I would expect to see `Bar` then `Foo` on the detail page in the metadata section.

8. If the user were to put some sort of code in the annotation that it would be plain text and we wouldn't process that code.  Put some HTML in as an annotation and ensure it comes back as plain text. E.g.  `<strong>This is text</strong>` would come back as it is written.  The text would not be bold.

9. We will not support non http/https hyperlinks.

10. If there is no metadata to display then do not show the Metadata header.

**Comment by bigkevmcd** [comment]
Can we write up why we are not supporting the k8s standard annotations?

**Comment by bigkevmcd** [comment]
> The key for annotations can only be 63 characters long.

`metadata.weave.works` uses 20 of those characters.

**Comment by bigkevmcd** [comment]
Also, I think this should call out explicitly the supported set of annotations.

**Comment by JamWils** [comment]
> Can we write up why we are not supporting the k8s standard annotations?

Please read the product initiative which will explain why we aren't supporting standard annotations.  It isn't a technical decision, it's simply about enabling the user to put metadata on the page and viewing that metadata.

> metadata.weave.works uses 20 of those characters.

That is alright, if this ever becomes an issue we can support a shorthand of this like `md.ww` or `metadata.ww` or something along those lines.  Until then this is out of scope.

> Also, I think this should call out explicitly the supported set of annotations.

What's so special about these annotations that we want to put them in the detail page along with the rest of the metadata?  This was really meant for putting dashboard links to grafana or some other 3rd party tools and not much else.  We aren't trying to overthink this feature.  There is room for it to evolve in the future.
