### ISSUE TITLE
Display CRDs on the Flux Runtime page

### ISSUE THREAD

**Issue by stefanprodan** [weaveworks/weave-gitops#2241]
As a cluster admin I want to see the Flux CRDs and their version so that I know which `apiVersion` I must use in my manifests.

### Acceptance Criteria
- Create two tabs on the page "Controllers" and "CRD"
- By default when I click on "Flux Runtime" the controllers page should be the active page.
- When I click the "CRD" tab I am shown a different table outlined below.
- the CRDs table would contain these columns "Name" "Kind" "Version"

| Name                                           | Kind                  | Version |
|------------------------------------------------|-----------------------|---------|
| alerts.notification.toolkit.fluxcd.io          | Alert                 | v1beta1 |
| buckets.source.toolkit.fluxcd.io               | Bucket                | v1beta2 |
| gitrepositories.source.toolkit.fluxcd.io       | GitRepository         | v1beta2 |
| helmcharts.source.toolkit.fluxcd.io            | HelmChart             | v1beta2 |
| helmreleases.helm.toolkit.fluxcd.io            | HelmRelease           | v2beta1 |
| helmrepositories.source.toolkit.fluxcd.io      | HelmRepository        | v1beta2 |
| imagepolicies.image.toolkit.fluxcd.io          | ImagePolicy           | v1beta1 |
| imagerepositories.image.toolkit.fluxcd.io      | ImageRepository       | v1beta1 |
 | imageupdateautomations.image.toolkit.fluxcd.io | ImageUpdateAutomation | v1beta1 |
| kustomizations.kustomize.toolkit.fluxcd.io     | Kustomization         | v1beta2 |
| providers.notification.toolkit.fluxcd.io       | Provider              | v1beta1 |
| receivers.notification.toolkit.fluxcd.io       | Receivers             | v1beta1 |

The `Name` rows could have a link that would open in pop-up the YAML content on the CRD.

![image.png](https://images.zenhubusercontent.com/60f5a90306cf76325d5accdc/2764d171-690f-4d57-84aa-0e0d6df46e32)

[Figma](https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?node-id=10539%3A59692)

**Comment by sympatheticmoose** [comment]
We may need "Cluster" (as in the current table) so that this can be used in WGE.

**Comment by bia** [comment]
@JamWils and I talked about putting this under the Flux Runtime tab

@sympatheticmoose do you mean the Cluster column in the Applications table?

**Comment by sympatheticmoose** [comment]
@bia the proposal describes two tables on the Flux Runtime page, the first is what we have today which I am referring to as the current table, the second is the new table which lists the CRDs and should have the same Cluster column IMO.

**Comment by stefanprodan** [comment]
Switching between clusters in the UI is a WGE exclusive feature? If so then the cluster column should be hidden on all pages in Weave GitOps Core.

**Comment by sympatheticmoose** [comment]
Thats an option, currently in Core as a single cluster UI we just show the cluster name as default.

**Comment by stefanprodan** [comment]
FYI: I've added CRDs listing to Flux CLI here https://github.com/fluxcd/flux2/pull/2823

**Comment by JamWils** [comment]
Moving this forward as is.  It's a good addition and I want to test whether we need designs all of the team now that we have consistent components in the application.

**Comment by sympatheticmoose** [comment]
@JamWils any thoughts on whether to hide the cluster column in Core? Something I think we should consider is adding the filtered table in WGE so users can filter down to the cluster(s) they care about, this wouldn't really be necessary in Core so would introduce a 'reason' to have a difference between tiers.

**Comment by ozamosi** [comment]
I created a (incomplete needs more detail) ticket #2456 to discuss the cluster column - the CRD bits are ready to work on (and, for consistency, should include cluster) - global changes to the cluster column are out of scope.

**Comment by sympatheticmoose** [comment]
thanks @ozamosi that approach makes sense

**Comment by JamWils** [comment]
Glad to see this conversation occurred as I was thinking about it during my run; I need to think about other things 😂 

So it is kind of silly to have it in Core and I agree with @ozamosi's approach for this being out of scope on this story.

**Comment by jpellizzari** [comment]
@ozamosi @JamWils The user will need to be a super admin to list CRDs, correct? Does our default user in Core have that ability?

This could work if the CRDs are in `flux-system`, but if they are elsewhere or in multiple namespaces, they will need to be a super user.

This will require some back-end changes.

**Comment by JamWils** [comment]
@jpellizzari that is a fair shout.  I think at this point all objects in the app just need to follow RBAC rules and we need to be able to handle the situation gracefully if they do not have the correct permissions to view the data.

**Comment by JamWils** [comment]
@joshri I added a screenshot with tabs.  Please note that the table in the image doesn't match the data.  This should be enough to complete the task.
