### ISSUE TITLE
graph: Hide ReplicaSets with zero pods

### ISSUE THREAD

**Issue by stefanprodan** [weaveworks/weave-gitops#2244]
After each deployment rollout, the previous ReplicaSets are displayed in the graph which means the page becomes cluttered with scaled to zero ReplicaSets. 

**Environment**

- Weave-Gitops Version v0.8.1-rc.5
- Flux Version v0.30.2
- Kubernetes version v1.23.5

<img width="1559" alt="Screenshot 2022-05-30 at 16 56 48" src="https://user-images.githubusercontent.com/3797675/171007201-54434f9b-9f4d-40c0-9ffd-93713fdb9937.png">

**Comment by JamWils** [comment]
1. Setup podinfo 5.0 on the cluster
2. Then upgrade podinfo to 6.0

You should see the 0 replica issue appear.
