### ISSUE TITLE
No overwrite option for re-running wego add command

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#225]
**Describe the bug**
Re-running `wego add` on a repo does not prompt any warning or alert. Wego should be able to: 
 - alert user what the effects of re-running `wego add` will have on existing files 
 - ask user if they _want_ to re-run `wego add` at all (y/n option)

This can cause serious issues with complex application repos.

**Environment**
 - wego: v0.0.0

**Affects versions**
 - wego: v0.0.1

**To Reproduce**
1. Have wego binary installed in your system
2. Run `wego install | kubectl appy -f -`
3. Run `wego add . --url=<url>` in your local directory
4. Rerun `wego add . --url=<url>` in the same directory

**Expected behavior**
Wego reruns the `add` command without prompting user with a y/n question

**Config and Logs**

**Screenshots**

**Additional context**

**Comment by markramm** [comment]
Two things that fix this: 

1) Commands are idempotent
2) Dry run allows preview.
