### ISSUE TITLE
Link to Flux resources in the details table for Kustomizations and Helm Releases

### ISSUE THREAD

**Issue by stefanprodan** [weaveworks/weave-gitops#2250]
As a user I want to click on a Flux resource in any table and this should redirect me to the details page.

For example, it is very common for a Flux Kustomization to contain other Sources, Kustomizations and HelmReleases.  Currently there are no links to them, so a user will have to go back to the Application page and search for them.

### Acceptance Criteria

When I go to the detail page of a `Kustomization` or `HelmRelease`.  The `name` field on the table in the detail view should be clickable if the object is one of the following:

- Kustomization
- Helm Release
- Git Repository
- Helm Repository
- Bucket

1. When I click on the hyperlink I should be taken to that object's detail page in the same tab that I am currently working in.

2. When I hit the back button I am taken back to the previous detail page I was on.

3. When the object in the row is not one of the objects listed above I should see black text that is not clickable.

<img width="1576" alt="Screenshot 2022-05-31 at 18 04 15" src="https://user-images.githubusercontent.com/3797675/171207987-e60e4229-4c53-43c8-bfec-27aadc6bd655.png">

**Comment by opudrovs** [comment]
@stefanprodan so, can I just add the links (pointing to these five kinds of objects) in the ReconciledObjectsTable on any details page without checking that this details page is of a Kustomization or a HelmRelease?

As far as I understood, if there is a ReconciledObjectsTable, links in it (if the object type in a row belong to the five types above) should be added, correct?
