### ISSUE TITLE
[UI] Add hover effect and click behaviour to sidebar

### ISSUE THREAD

**Issue by bia** [weaveworks/weave-gitops#2265]
**Short description**
As any Weave Gitops user, I want to highlight links (in this case only for the sidebar, but eventually all links) so that our application feels more responsive.

**Acceptance criteria**
See figma page [here](https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?node-id=10544%3A59510) for selected and hover states.

**Design materials**

Clusters [icon](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Adns%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048)
App [icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Asettings_applications%3A)
Flux [icon](https://drive.google.com/file/d/1A-lWhjhrpYFhpy4ZPMXNegpkkVAkmFg1/view?usp=sharing)
Policies [icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Apolicy%3A)
Docs [icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aarticle%3A)

![image](https://user-images.githubusercontent.com/1825111/181034113-a917e625-9177-4b9f-a034-9d7b14bf8ab9.png)

**Comment by joshri** [comment]
Can I look at this in Figma? I'd like to tackle the font changes, icons, and line-height as well in this issue as those changes will ripple across a couple other components.

**Comment by bia** [comment]
@joshri yes, of course. It's here https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?node-id=9536%3A50925

**Comment by JamWils** [comment]
@bia does this also include the icons being added as well or will that be in a separate issue for this epic?

**Comment by bia** [comment]
@JamWils yes, this comprises the icon addition, I'll link to each one in the issue description.

**Comment by JamWils** [comment]
During refinement there are concerns about what styling is actually available in the material component.  Adjusted the design for simplicity and FE will report on handling other states.

**Comment by joshri** [comment]
The clusters and policy icons will not be added as they are enterprise only (as far as I know). @bia if these aren't already in enterprise I think they'll need to be in a separate issue. If the best way for enterprise to use them IS for me to add them here I don't mind doing so but my instinct is to keep this repo as light as I possibly can - let me know!

**Comment by bia** [comment]
> If the best way for enterprise to use them IS for me to add them here I don't mind doing so but my instinct is to keep this repo as light as I possibly can - let me know!

cc @foot @AlinaGoaga what do you think?

**Comment by joshri** [comment]
@bia It looks like they have a completely separate nav component from us so if theirs needs to be restyled it needs a separate issue - they aren't importing it from us

**Comment by joshri** [comment]
This is a work in progress but wanted to call out that the 12px font size looks pretty small here - want to make sure it's what you want @bia 
![image.png](https://images.zenhubusercontent.com/617c4a20ede496b2fae35baf/40a714bd-340c-4725-8338-dfd3054644f5)

**Comment by bia** [comment]
> wanted to call out that the 12px font size looks pretty small here - want to make sure it's what you want @bia

It looks ok and legible to me. @mmoulian do you agree?

**Comment by mmoulian** [comment]
I also see it well. I think now you see it strange because it's blue and it should be Dark (1A1A1A) for the first level and Gray (737373) for the second level. Blues have less contrast than darks.

Also, the typo should have 1px space between letters
