### ISSUE TITLE
SPIKE: Behavior of OCI Helm Chart in Weave GitOps

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2266]
As a user,
I would like Helm with OCI support in Weave GitOps
so that I could see which Helm Release was installed from which OCI image.

## Technical bits

The new version of HelmRepository will support ".spec.type: oci" to indicate that the source of a HelmRelease will be an OCI image.

![image](https://user-images.githubusercontent.com/10666/172179527-4933f53f-16cf-470c-a642-380dcb3150e5.png)

**Comment by chanwit** [comment]
The behavior needed by this spike has been done in https://github.com/weaveworks/weave-gitops/issues/2274

**Comment by chanwit** [comment]
Flux v0.31.1 has been released. Please make sure that we spike against this version:
https://github.com/fluxcd/flux2/releases/tag/v0.31.1
