### ISSUE TITLE
Make it easy to find out the k8s and flux version

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#2285]
For reporting a bug, we expect users to provide k8s version and flux version. However, we don't really make those easy to find out at the moment.

We should add these to the version endpoint, so we can display them in the footer next to the gitops version.

The flux version is set in annotations on any flux object directly - you can see it, for example, in the `flux-system` namespace itself. It's theoretically possible for different components to come from different flux versions, but that's not normal and we don't consider that here.

The k8s version can be fetched by creating a [discovery client](https://pkg.go.dev/k8s.io/client-go/discovery) from an existing k8s client and calling `ServerVersion` on that. In a multi-cluster world these could be different, but as long as the `Default` cluster is queried, that's sufficient for this ticket.

### Acceptance Criteria
1. When I open Weave GitOps I see the version of Weave GitOps that is running on the footer with the same behavior as today.
2. To the left of the Weave GitOps version I will see the flux versions as `flux: v0.20.0`.
3. To the left of the Flux version I will see the `k8s: v1.23.0`.

There should be enough spacing to make them all legible.

**Comment by JamWils** [comment]
![Screen Shot 2022-06-14 at 8.47.00 PM.png](https://images.zenhubusercontent.com/60f5a90306cf76325d5accdc/a40dd080-e7c2-4313-9180-6e6663649460)

@opudrovs here is a quick design for you.  I think we're going to need to make a dedicated settings page in the app moving forward for some of this data.

**Comment by opudrovs** [comment]
@JamWils thank you, got it!
