### ISSUE TITLE
Sync icon during reconciling

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2286]
As a user when I am viewing any page within Weave GitOps my reconcilers (automations and sources) will suddenly show a red error symbol, but it is simply reconciling.  I shouldn't have that moment of panic seeing red for a reconciliation.

I would expect that a get a different color and symbol during the reconciliation process.  A pleasant blue and "refresh" icon would make it clear that the current automation or source is updating.

![Screen Shot 2022-06-14 at 9.00.04 PM.png](https://images.zenhubusercontent.com/60f5a90306cf76325d5accdc/9a18f1ab-51a1-4677-bdf1-494fef8d6e8c)

# Acceptance Criteria

When a relevant flux object is reconciling I expect to see the following behavior.   see the blue icon above showing that the item is reconciling.  Upon successful completion I will see a green circle with a check mark or a red circle with a horizontal line across the center for an error.  Finally, when a flux automation is "paused" when I see the yellow circle.

I expect to see this behavior on the following pages:

1. On the application table view
2. On the sources table view
3. On detail pages in the header for all flux objects
4. On detail pages in the detail tab for relevant flux objects in the data table
5. On the detail pages graph tab where they are flux objects.  These will also have a node with the left side as blue.

**Comment by joshri** [comment]
@JamWils can you point me to the Figma tab that has this icon in it?
