### ISSUE TITLE
Update docs with alternative to bcrypt-cli which is now deprecated

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2290]
Our documentation currently recommends the use of https://github.com/bitnami/bcrypt-cli/ here:
- https://docs.gitops.weave.works/docs/getting-started/#configure-access-to-the-dashboard
- http://localhost:3000/docs/next/configuration/securing-access-to-the-dashboard/#login-via-a-cluster-user-account

`bcrypt-cli` has recently been marked as read-only and deprecated, with alternatives suggested here https://github.com/bitnami/bcrypt-cli/issues/15.

We should remove this and recommend the command we are creating in #2367

**Comment by SamLR** [comment]
I /think/ ` htpasswd -nbBC10 n/a password | cut -d ':'  -f2` should be an appropriate replacement (and not require installing anything else).
