### ISSUE TITLE
As a user I would like to be able to suspend/resume multiple flux objects

### ISSUE THREAD

**Issue by mtparet** [weaveworks/weave-gitops#2317]
**Short description**
In the gitops way we could have some big changes impacting lot of resources and we like to control the application instead of applying 10000 changes at one time.

Opening a new PR for each change is not always wanted or possible so this should be possible by using gitops tools.

Once the synchronisation is suspended for all resources we could sync again each resource individually or all the resources.

**Acceptance criteria**
~- [ ] _does suspend synchronisation for all resources_~
~- [ ] _does reactivate synchronisation for all resources_~
~- [ ] _does reactivate synchronisation individually for each resource_~

The criteria applies to the application and source pages within Weave GitOps.  This functionality should extend to the enterprise dashboard as well.

- [ ] Given I have no checkboxes selected on the list view, when I take no action, then I should see both buttons "sync" and "suspend" disabled at the top.
- [ ] Given I have no checkboxes selected on the list view, when I hit the checkbox on one or more line items, then I should see both buttons "sync" and "suspend" enabled at the top.
- [ ] Given I have one or more checkboxes selected on the list view, when I uncheck the checkboxes for those line items, then I should see both buttons "sync" and "suspend" disabled at the top.
- [ ] Given I have checkboxes selected, when I hit the "sync" button on the page, then I should see those items run a "reconciliation" in the app.
- [ ] Given I have checkboxes selected, when I hit the "pause" button on the page, then I should see those items turn to suspended state in the app.
- [ ] Given I have checkboxes selected, when I hit the "play" button on the page, then I should see those items turn to green or red depending on their healthy state.
- [ ] Given I have checkboxes selected, when I hit the "play" button on the page and some of those items cannot be resumed, then I should see an error indicated that they were unable to be resumed.
- [ ] Given I have checkboxes selected, when I hit the "pause" button on the page and some of those items cannot be resumed, then I should see an error indicated that they were unable to be suspended.

**Design materials**
- Screenshots

<img width="1007" alt="Screen Shot 2022-07-18 at 9 24 24 PM" src="https://user-images.githubusercontent.com/1825111/179644401-76453185-a021-4f2f-92c5-33beee3920e0.png">

https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?node-id=10323%3A59752

- Design diagrams
- WEP 
- PR/FAQ

**Comment by JamWils** [comment]
@mtparet thanks for the request.  We will pull it into the Core team and evaluate it.

**Comment by JamWils** [comment]
So we are going to enable the application to update multiple sources and workloads at a time.



<img width="1150" alt="Screen Shot 2022-07-18 at 8 45 15 PM" src="https://user-images.githubusercontent.com/1825111/179641855-e842ca7e-651e-446d-bdf4-730a7c1308ed.png">

**Comment by JamWils** [comment]
Alternative with play and pause instead of resume and suspend.

<img width="1007" alt="Screen Shot 2022-07-18 at 9 24 24 PM" src="https://user-images.githubusercontent.com/1825111/179643954-7df0adeb-ae2a-4ad8-8bb1-744c1990a416.png">

**Comment by JamWils** [comment]
@mtparet I made some updates here.  I am happy to here if this solves your problem.  If not then I would like to learn more about the problem you are trying to solve.

**Comment by JamWils** [comment]
@joshri and @opudrovs we can chat about the designs at stand up.  I wanted to get your initial thoughts about the design and goal for this story.

**Comment by mtparet** [comment]
Thank you ! :heart:
