### ISSUE TITLE
SPIKE: How do we link to docker images?

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#2326]
Where we display docker images, we should link to a web page for them. However, there are different cases:
* An image can be specified as e.g. `weaveworks/eksctl` which would (barring tricks, I'm willing to ignore tricks right now) pulls from docker.io
* An image can be pulled from `docker.io/weaveworks/eksctl`,  but you can't open that in a web browser - https://hub.docker.com/r/weaveworks/eksctl is the URL you want. The `r` in there can be other characters (I know of `u` and `_`) - does `r` always work?
* There are many other reasonably common docker registries. For example, quay.io, github's GHCR, google's GCR, amazon's ECR. For these registries, does visiting the image URL in a browser work? Does the URL need to be rewritten first?

Investigate a few registries and how they behave, and suggest what our approach to linking to images should be.
For example, if the outcome is "dockerhub is odd, everything else just works", then we can just implement that, whereas if the outcome is "everything is weird in different ways", then we might need to e.g. whitelist know repository providers.

**Comment by chanwit** [comment]
>  does `r` always work?
  * `/r` always work for every registry, including the global ones which will be redirected to "_/<image name>".
  * For the namespace registry, for example: `weaveworks/eksctl` can be translated to `https://hub.docker.com/r/weaveworks/eksctl`
  * For the global registry, for example: `nginx` can be translated to `https://hub.docker.com/r/_/nginx`

**Comment by chanwit** [comment]
### Quay.io

Query.io repository for example quay.io/jitesoft/nginx should be converted to http://quay.io/repository/jitesoft/nginx

**Comment by chanwit** [comment]
### GitHub's GHCR

GitHub GHCR does not require any conversion. All links work out of the box, for example https://ghcr.io/weaveworks/charts/weave-gitops

**Comment by chanwit** [comment]
### AWS ECR 

tbd.

**Comment by chanwit** [comment]
### GitLab Repository

tbd.

**Comment by ozamosi** [comment]
Summed up findings into #2267 - closing. Thank you!
