### ISSUE TITLE
SPIKE: GitOps Toolkit for Pipelines

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2329]
We want to enable developers to go about their day-to-day business and not worry about deploying their software.  However, with GitOps there are a sequence of events that need to occur to roll out software from environment to environment.  We want to automate these events and enable engineers to have PRs opened for them once their software has been successfully deployed.

We want to integrate with existing git services and enable customers to choose CI pipelines of their choice.  

The Flux team has built the GitOps Toolkit and we want to understand if they already have existing capabilities for opening PRs.

https://github.com/fluxcd/go-git-providers

1. Which git services does the GitOps toolkit support?
2. Of those services which ones will work for on-prem instances?
3. Out of the services listed above, can the GitOps toolkit open PRs for those services?
4. Out of the services listed above which ones support auto merge?

**Comment by rparmer** [comment]
Per the [docs](https://github.com/fluxcd/go-git-providers/blob/main/README.md).  GitHub and GitLab (cloud and on-prem) and Bitbucket (on-prem)

**Comment by rparmer** [comment]
It appears they all also support opening PR's.  However auto merge seems to have a lot of conditionals around it (requires specific repo rules, can be blocked by branch protection rules, etc).  I don't think that part can be easily automated on the WG side, but it would not be too hard for a consumer to setup if they wanted to enable auto merge.

**Comment by rparmer** [comment]
Also the `go-git-providers` package only seems to be used as part of the fluxcli.  After bootstraping the controllers use the more generic `go-git` or `libgit2` packages.  Makes sense, but something to be aware of.
