### ISSUE TITLE
SPIKE: Create a pipeline for PodInfo

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2330]
Build a pipeline for pod-info that can leverage Github actions.  This pipeline should be a dev->staging->prod path.

https://github.com/stefanprodan/podinfo
https://fluxcd.io/docs/use-cases/gh-actions-helm-promotion/

1. What were the pain points for building out the pipeline?
2. How do you kick-off the process for getting this to flow.  I.e. what manual steps do you take to start rolling out this process to dev and document subsequent steps.
3. What flux objects came into play to define the environments?

**Comment by rparmer** [comment]
I still need to document the pain points.  But here is a basic deployment pipeline that will automatically build and deploy changes to dev and create PR's for the other environments. https://github.com/rparmer/podinfo

Chose kustomize over helm for simplicity as well as I felt image updates where more applicable to deployments anyway.  But I think this is a good starting point.
