### ISSUE TITLE
Replace --path flag with --app-path

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#235]
**Describe the bug**
The `wego add --path=<path>` flag is confusing. From a user's perspective, it is not clear what this path specifies. It would be much clearer if we could change the flag name into something more understandable, like `--manifests-path`. The usage/help text for `--path` flag is not clear either.  The help text says:

`--path string  Path of files within git repository (default "./")`

This does not clarify what the exact usage of the flag should be.

**Environment**
 - wego: [v0.0.0]

**Affects versions**
- wego: [v0.0.1]

**To Reproduce**
1. Download wego binary
2. Run `wego add -h`

**Expected behavior**

**Config and Logs**

**Screenshots**

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/c7c820b8-c128-46ca-844e-715ed3ba6c09)

**Comment by markramm** [comment]
Define the UX more clearly

**Comment by markramm** [comment]
We may move path to the main argument of the command.
