### ISSUE TITLE
Updating Weave GitOps from 0.9.0-rc.1 to 0.9.0 results in Helm error

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2353]
**Describe the bug**
Updating my helm release to the latest image tag triggers an update, but a potentially incorrect error is reported.

I have not tested with non RC image, but have no reason to believe why this would be the root cause. 

**Environment**

- Weave-Gitops Version 0.9.0
- Flux Version 0.31.0
- Kubernetes version Kind (1.21.1)

**To Reproduce**

Eg:
1. Install Weave GitOps as described https://docs.gitops.weave.works/docs/installation/#install-the-helm-chart but specify an image tag in the HelmRelease values:

```
image:
  tag: "0.9.0-rc.1"
```

2. Wait for everything to be running succesfully

3. Update Weave GitOps by altering the tag to `0.9.0`

4. Wait a bit, see error:
<img width="3360" alt="Screenshot 2022-06-22 at 14 14 42" src="https://user-images.githubusercontent.com/19860021/175037946-0b23bdc5-ca37-44dd-a734-cc9643fae13a.png">

<img width="2961" alt="Screenshot 2022-06-22 at 14 15 47" src="https://user-images.githubusercontent.com/19860021/175038207-2b586fac-19db-4657-9be9-3086d1a1f7c3.png">
<img width="2962" alt="Screenshot 2022-06-22 at 14 15 40" src="https://user-images.githubusercontent.com/19860021/175038216-e2303c5a-0a6f-4670-a18c-35d21137c0c6.png">
<img width="1178" alt="Screenshot 2022-06-22 at 14 15 20" src="https://user-images.githubusercontent.com/19860021/175038345-5dbbb939-eb50-41ba-9042-ff8354e1effc.png">

```

```

https://github.com/sympatheticmoose/fleet-infra/commit/d8e70bf365942a5f4cd76ba730d1299d3dd417cb#diff-8b39235d5b4c1b04278a6546f5777f1a0e50db60713e299c6f7c36a8b3e95949 is an example of this change resulting in my error

**Expected behavior**

No error :)

**Actual Behavior**

**Additional Context (screenshots, logs, etc)**

**Comment by opudrovs** [comment]
@sympatheticmoose I have not been able to reproduce the error.

Are you also installing WGE (have not tried it, can it be related to your error?) or is installing just WG via the HelmRelease enough to reproduce the issue? And how do you log into the dashboard?

If I log into the dashboard with

`kubectl port-forward svc/ww-gitops-weave-gitops -n flux-system 9001:9001`

then I see and error in terminal when I change the image form RC to stable release and back, but I think it's expected?

```
macbook-pro:weave-gitops-3 olga$ kubectl port-forward svc/ww-gitops-weave-gitops -n flux-system 9001:9001
Forwarding from 127.0.0.1:9001 -> 9001
Forwarding from [::1]:9001 -> 9001

Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
E0727 02:42:26.591034   61671 portforward.go:406] an error occurred forwarding 9001 -> 9001: error forwarding port 9001 to pod bdc72a8e6c9e406bb1223113414d583a9d9fd65c31f32de1af99024b32e80a82, uid : failed to find sandbox "bdc72a8e6c9e406bb1223113414d583a9d9fd65c31f32de1af99024b32e80a82" in store: not found
E0727 02:42:26.591043   61671 portforward.go:406] an error occurred forwarding 9001 -> 9001: error forwarding port 9001 to pod bdc72a8e6c9e406bb1223113414d583a9d9fd65c31f32de1af99024b32e80a82, uid : failed to find sandbox "bdc72a8e6c9e406bb1223113414d583a9d9fd65c31f32de1af99024b32e80a82" in store: not found
E0727 02:42:26.594252   61671 portforward.go:234] lost connection to pod
macbook-pro:weave-gitops-3 olga$ 
macbook-pro:weave-gitops-3 olga$ kubectl port-forward svc/ww-gitops-weave-gitops -n flux-system 9001:9001
Forwarding from 127.0.0.1:9001 -> 9001
Forwarding from [::1]:9001 -> 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
E0727 02:46:13.142116   61923 portforward.go:406] an error occurred forwarding 9001 -> 9001: error forwarding port 9001 to pod 7c91b5b809b8be57d6247b80253ce27d08552f50ce06d7d60d1aa49110c405ad, uid : network namespace for sandbox "7c91b5b809b8be57d6247b80253ce27d08552f50ce06d7d60d1aa49110c405ad" is closed
E0727 02:46:13.142635   61923 portforward.go:234] lost connection to pod
macbook-pro:weave-gitops-3 olga$ kubectl port-forward svc/ww-gitops-weave-gitops -n flux-system 9001:9001
Forwarding from 127.0.0.1:9001 -> 9001
Forwarding from [::1]:9001 -> 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
^Cmacbook-pro:weave-gitops-3 olga$ kubectl port-forward svc/ww-gitops-weave-gito -n flux-system 9001:9001
Forwarding from 127.0.0.1:9001 -> 9001
Forwarding from [::1]:9001 -> 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
E0727 02:48:08.807194   62218 portforward.go:406] an error occurred forwarding 9001 -> 9001: error forwarding port 9001 to pod d7df043cfa8f832d3f53a60973d626cd74bf516b5bca7d229803d93a805b9073, uid : network namespace for sandbox "d7df043cfa8f832d3f53a60973d626cd74bf516b5bca7d229803d93a805b9073" is closed
E0727 02:48:08.807737   62218 portforward.go:234] lost connection to pod
```

If I install the WG with the HelmRelease and log into the dashboard after `tilt up`, changing the image version in the HelmRelease does not cause an error, it becomes green after switching from RC to release and back, what is reflected on the YAML tab in the dashboard.

Could you please try to replicate the issue again and let me know the exact steps to do it, maybe I am missing smth.?

**Comment by sympatheticmoose** [comment]
> Are you also installing WGE

No - this is just Core using helmrepo and helmrelease objects to install.

> And how do you log into the dashboard?

I believe the dashboard is irrelevant to the error, as its just reading from the underlying flux objects. But it was using the cluster user and a port-forward on the service.

I can only assume theres a timing issue, if for whatever reason it takes longer than normal for the pod to become available, then flux will report an error state. Slow network + new image may cause this 🤷 

I need to install the latest RC anyway so will try again.

**Comment by sympatheticmoose** [comment]
I can't seem to reproduce. I know others have hit similar issues where the node has been under resourced supposedly. But I'm yet to be convinced we need to up the timeout etc. Closing.

**Comment by opudrovs** [comment]
@sympatheticmoose 

> I believe the dashboard is irrelevant to the error, as its just reading from the underlying flux objects. But it was using the cluster user and a port-forward on the service.

Quite possible/most likely the dashboard is irrelevant, but I thought maybe there was some sort of an observer effect, because we used a part of WG to observe WG.

> I can't seem to reproduce. I know others have hit similar issues where the node has been under resourced supposedly. But I'm yet to be convinced we need to up the timeout etc. Closing.

OK, great, thanks for confirming it. Yes, if the issue keeps getting reported, we can always reopen it and increase timeout.
