### ISSUE TITLE
Create sync between local filesystem and source on cluster

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2357]
As a user, when I start a `gitops run` and pass a file path then all yaml files I create within that folder should be synced with my cluster.  I.e. if I were to create a config map, deployment, and service within the specified file path then I will see those appear on the cluster.  I will also see a `Kustomization` that shows a source.  That source is what syncs with the local file system.

### Acceptance Critera

Given I have the `gitops beta run ./my-path` running

1. When I add a new manifest file such as a config map in my local directory `./my-path`.  I should see that config map appear on the cluster.
2. When I add a `GitRepository` manifest file such as for pod info in my local directory `./my-path`.  I should see that source appear on the cluster.  Flux will also recognize this source and reconcile it.
3. When I add a `Kustomization` manifest file such as for pod info in my local directory `./my-path`.  I should see that automation appear on the cluster.  Flux will also recognize this automation and will product the output of that kustomization.
4. When I update the config map from step 1 with additional values, I should see that the config map is replaced on the cluster and that the additional values now appear.

**Comment by ozamosi** [comment]
Out of scope: "raw" helm charts. If you're managing your application with helm, you'd need to template the chart first. As in, I can't run `gitops beta run ./charts/gitops-server` for weave-gitops.

Right?
