### ISSUE TITLE
Install GitOps Dashboard for gitops beta run

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2358]
Offer to install gitops dashboard using an interactive prompt if it's not installed already.

If the user answers yes, let them enter a password and use that for the installation.

**Comment by chanwit** [comment]
the dashboard would be installed with HelmRelease.
A tricky thing would be around the init secret generation which is currently depending on an external bcrypt-cli program.

**Comment by opudrovs** [comment]
Also added a dashboard port opening a port for the dashboard automatically based on @chanwit 's suggestion.
