### ISSUE TITLE
(**Edit: Absent wego logic**) Persisting `--namespace string` help text under irrelevant wego flags 

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#236]
**Describe the bug**
The `--namespace string` flag is showing up under all of the wego flags help text when it should be confined within `wego install` help text. This message shows up under all these commands:
 - `wego -h`
 - `wego add -h`
 - `wego flux -h`

It gives the impression that this flag could be used like so:

`wego --namespace <my-namespace>`
`wego add --namespace <my-namespace>`

Since `--namespace string` is only relevant when installing controllers, this help text should not show up anywhere else.

**Environment**
 - wego: [v0.0.0]

**Affects versions**
 - wego: [v0.0.1]

**To Reproduce**
1. Download wego binary
2. a. Run `wego -h` command
2. b. Run `wego add -h` command
2. c. Run `wego flux -h` command

**Screenshots**

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/f517b593-a2cf-4b31-83b5-5709c97f8fdc)

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/2ebd0d86-6e9a-4c8e-ae14-fa1998dc60a0)

**Comment by rokshana-b** [comment]
As per my conversation with @jrryjcksn and @josecordaz:

Currently during the `wego install` stage, when flux components are installed in a user-defined namespace, `wego` cannot detect the components. By default, `wego` is set to look for flux components under `wego-system` namespace. Ergo, for a custom namespace, user will have to use the `--namespace string` flag with any future commands.

From a user POV, this piece of information is not obvious and somewhat affects the experience of using `wego`.

Plan of Action:
- [ ] Add a note about this issue in the final ReadMe file for the benefit of the user. 
- [ ] For future releases, add a logic in the code where `wego` can detect the custom namespace containing all components so that the user does not have to painstakingly attach `--namespace string` flag with all commands.

**Comment by markramm** [comment]
Add a way to set a default namespace?

**Comment by markramm** [comment]
.wego config file?

**Comment by jpellizzari** [comment]
Related to https://github.com/weaveworks/weave-gitops/issues/472

Closing this issue to continue the discussion here ^^
