### ISSUE TITLE
Referencing manifests outside of the run path

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2360]
As a user I am going to be working with tools such as kustomize.  I am going to start running the gitops run command down a certain path such as `gitops beta run ./deploy/overlays/dev`.  This path will contain a `kustomization.yaml` file that has multiple references to other local paths in my repository.

As an engineer working with `gitops beta run`, I would expect to see these referenced files also get synced during the run phase.  This would ensure I am not forced to keep all of my manifests in one folder structure.  For a platform operator this is useful for structuring my files in different ways; especially when working with Flux primitives where I am trying to abstract away the concept of "applications" and placing those workloads on clusters.

### Acceptance Criteria

1.  When I am running an overlay and I have a `kustomization.yaml` file with file paths under "resources" such as `./my-path`.  I would expect for those file paths to also be synced with the cluster so they appear in the cluster.  Otherwise, the kustomization will not be able to be build since it will be missing manifests.
    1. When I add a new manifest file such as a config map in my local directory `./my-path`. I should see that config map appear on the cluster.
    2. When I add a `GitRepository` manifest file such as for pod info in my local directory `./my-path`. I should see that source appear on the cluster.
    3. When I add a `Kustomization` manifest file such as for pod info in my local directory `./my-path`. I should see that automation appear on the cluster.
    4. When I update the config map from step 1 with additional values, I should see that the config map is replaced on the cluster and that the additional values now appear.
3. When I remove a file path from the resources section of "kustomize" it will no longer sync via the file system.  **Note:** this seems like good hygiene but happy to hear why we shouldn't really care since when kustomization gets processed on the cluster then the files wouldn't be picked up in the first place.
4. If a `--root-dir` flag is not used then we will default the root directory to be the main directory of the git repository that the command is run in.
5. If a `--root-dir` flag is used with a valid path then we will set the root directory to be that path.
6. If a `--root-dir` is not a valid path then we will inform the user with an error.

**Comment by chanwit** [comment]
We would need an extra parameter for this case. Maybe: `gitops beta run --root-dir=$PWD ./deploy/overlays/dev`
because we have to sync everything from the `--root-dir` into the bucket so that the Kustomization in the `./deploy/overlays/dev` can refer to everything in the scope of the root dir.

**Comment by chanwit** [comment]
in the `gitops beta run .` command, we would assume that --root-dir and the dir for the dev Kustomization object would be the same.

**Comment by ozamosi** [comment]
Capturing standup comments:
Robin: This feels like docker build, where the context and the docker file directory can be different. `docker build . -f ./deploy/overlays/dev` would mean that `.` is the context (e.g. `root-dir` in chanwit's example above, e.g. the thing that is synced) and `./deploy/overlays/dev` is where the docker file is to "start from".
Chanwit: There's also docker-compose which has `--project-directory` to set the "root-dir" or the "context".

**Comment by chanwit** [comment]
definitely out-of-scope, yes.

but beyond this MVP, we would do something like `helm pack` and `helm push` to a local registry, then we would support live reloading of Helm chart dev.
