### ISSUE TITLE
SPIKE: Cloud Native Bucket solutions

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2364]
We need to evaluate an alternative to MinIO S3 bucket, which is AGPL.

We will evaluate GoFakeS3 as the first alternative.
  - How to implement a Bucket server?
  - Is it compatible with standard AWS SDK?
  - What is its performance characteristic?

**Comment by chanwit** [comment]
- GoFakeS3 would be a straightforward implementation.  
  - It's compatible with AWS SDK.
