### ISSUE TITLE
SPIKE: Filesystem watcher solution

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2365]
We need to evaluate a solution for file system watcher. A notable one in the Golang space is github.com/fsnotify/fsnotify.

## How to evaluate

  1. we create a Go program that uses fsnotify lib.
  2. we compile it for 2 major platforms, Linux, mac.
  3. we test the program on all mentioned platforms.
  4. we check the performance of the watcher
      1. a whole podinfo repo + directory structure
      2. msdemo yaml files + directory structure

## Out of scope
We don't currently support windows. We don't necessarily don't _want_ to support windows, but don't test it here.

**Comment by chanwit** [comment]
## Definitions
  - **Local Directory** is the directory of a Git repository on our local machine.
  - **Bucket** is an S3-compatible bucket managed by a feature implemented in this epic.
  - **Object** is an object inside a Bucket.  An object consists of the key and the value.  In our implementation, an Object represents a copy of a file in the Local Directory.  The key of each Object is the relative path of a file, whose content is kept as the value.
  - We don't have a semantic of Directory in the Bucket, and a Directory can be seen as a common prefix string of some keys.
