### ISSUE TITLE
Change background image and remove blue header colour

### ISSUE THREAD

**Issue by bia** [weaveworks/weave-gitops#2376]

**Comment by joshri** [comment]
@bia 
- Can I get a link to the image / is it safe to rip from Figma (I'm assuming it's in the dark mode tab)
- Are we still expecting the header to be fixed as you scroll? May or may not look odd with how it blends into the background with the changes.

**Comment by bia** [comment]
@joshri sorry this is a duplicate that github accidentally created of #2377 

We are not expecting the header to be fixed as you scroll - unless we get a good idea about how to style it.
