### ISSUE TITLE
Change background image and remove blue header background

### ISSUE THREAD

**Issue by bia** [weaveworks/weave-gitops#2377]
New [background image](https://drive.google.com/open?id=12uiUhIvQfffiWn3YfCqZZVm3qFj2YY3f&authuser=bianca%40weave.works&usp=drive_fs), new look : 
![20220712new-bg](https://user-images.githubusercontent.com/92439/178525812-fbbbc928-4b28-480d-861d-cb34fc8c946a.png)

### Acceptance Criteria

1. This does not change the existing scrolling behavior within the application.  I would still expect the content to scroll under the header as well as the left/right scrolling to remain independent of each other.
2. Header text is `20px` Proxima Nova 'Neutral 30' (`#1a1a1a`) in `bold` and `regular` with `16px` padding separating the titles with a number count (`2px` roundrect in 'Primary -10' `#98E0F7`) and a right-facing [chevron icon](https://fonts.google.com/icons?selected=Material%20Icons%3Achevron_right%3A).

Note: we might need to modify the opacity in the app across the board depending on how the new background works.

Note: this is a screenshot of the enterprise version so (total count in bread crumb) and extra menu items will not exist.

### References

[Figma](https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?node-id=9469%3A50766)
[background image](https://drive.google.com/open?id=12uiUhIvQfffiWn3YfCqZZVm3qFj2YY3f&authuser=bianca%40weave.works&usp=drive_fs)

**Comment by JamWils** [comment]
@bia it looks like there is also an updated logo here (I like it a lot).  Is that part of this story?  I don't see it in the epic?

**Comment by JamWils** [comment]
Why all lowercase?  That kind of is the opposite of how we write it in all of our marketing material.

**Comment by bia** [comment]
<img width="876" alt="Screenshot 2022-07-12 at 11 20 19" src="https://user-images.githubusercontent.com/92439/178456803-fe7d7614-9781-4c2c-88ff-713c89d7cd40.png">
@JamWils but our homepage logo is all lowercase

**Comment by mmoulian** [comment]
Hi; Good news. I asked to marketing and @cezzaine is fine with the logo (:

**Comment by JamWils** [comment]
@joshri please do not put the count in the header.  Thanks for clarifying.

**Comment by joshri** [comment]
Neither of these colors (best I could find in the figma) blended the header with the new background. We can't make it transparent as it needs to scroll over content so we need a color. 

 ![image.png](https://images.zenhubusercontent.com/617c4a20ede496b2fae35baf/e2cbf840-ccd4-46dd-a285-1a62b581ae1d)

this is #e5e9ed which is the closer of the two:
![image.png](https://images.zenhubusercontent.com/617c4a20ede496b2fae35baf/f981e73d-5e13-404c-9222-cd2e778c6af4)

**Comment by mmoulian** [comment]
Hi @joshri, the header background color is Back Grey #EEF0F4. See it in the image below:
![Neutral](https://user-images.githubusercontent.com/95616291/183615055-27e92bbc-ec3e-443e-9c73-b579f6815185.png)
