### ISSUE TITLE
Change user icon to 'Person'

### ISSUE THREAD

**Issue by bia** [weaveworks/weave-gitops#2380]
instead of 'Account Circle' to match current designs.
Inactive color is `Neutral 30` `#737373`

Material icon file is here : https://fonts.google.com/icons?selected=Material%20Icons%3Aperson%3A

![20220621WIP Release Detail View - SIDE BAR 02 Icons](https://user-images.githubusercontent.com/92439/176476533-d2e86aa9-4091-4ba2-9daf-fec9ba41e212.png)

### Acceptance Critiera

![1 header -User enabled](https://user-images.githubusercontent.com/95616291/182904652-df929678-f469-4d9a-8c08-26edc4cbfccc.png)
![2 header-User hover](https://user-images.githubusercontent.com/95616291/182904643-37144bb5-205d-4680-bb5c-187c0f0b6654.png)
![3 Header-user active](https://user-images.githubusercontent.com/95616291/182904631-ee902183-d235-4c8e-8bb5-f5a47fab7964.png)

https://user-images.githubusercontent.com/95616291/182905531-d782d48d-74da-4c65-8116-d99476e22954.mov

**Comment by bia** [comment]
> @bia can you outline what it should look like when the user clicks the button and the menu is open.

@JamWils which menu?

**Comment by JamWils** [comment]
@bia, when they click the user profile menu: 

![Screen Shot 2022-07-18 at 8.53.19 AM.png](https://images.zenhubusercontent.com/60f5a90306cf76325d5accdc/6b5361e0-ea43-48f4-8a02-dedb96ef04bd)

**Comment by JamWils** [comment]
No, I mean what should the state of the button be when the menu is opened "active".  I.e. highlighted?

**Comment by mmoulian** [comment]
In these images we can view the differents states of User Button (Enabled, Hover & Active with dropdown)


![1 header -User enabled](https://user-images.githubusercontent.com/95616291/182904652-df929678-f469-4d9a-8c08-26edc4cbfccc.png)
![2 header-User hover](https://user-images.githubusercontent.com/95616291/182904643-37144bb5-205d-4680-bb5c-187c0f0b6654.png)
![3 Header-user active](https://user-images.githubusercontent.com/95616291/182904631-ee902183-d235-4c8e-8bb5-f5a47fab7964.png)

**Comment by mmoulian** [comment]
If you want to see the button in action watch the movie...

https://user-images.githubusercontent.com/95616291/182905531-d782d48d-74da-4c65-8116-d99476e22954.mov

.

**Comment by JamWils** [comment]
Brilliant @mmoulian.  Thank you!!!

**Comment by joshri** [comment]
@JamWils I'm basing my work off of what's in these last screenshots + video and not the acceptance criteria right?

**Comment by bia** [comment]
@joshri yes I've updated the acceptance criteria
