### ISSUE TITLE
Document supported browsers

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#2384]
We need to document which browsers we support.  We will only support the latest and prior two versions of the following browsers:
* Edge
* Firefox
* Chrome
* Safari

What about ESRs for Firefox and Edge?

**Comment by JamWils** [comment]
Ideally it would be nice if we could support the latest 3 versions of Chrome, Edge, and Firefox.  I don't want to leave Safari out, but I would rather tackle those first.

**Comment by JamWils** [comment]
I don't know what an IE is and I never will :joy:  

Also the combination of IE and the number 6 is a figment of everyone's imagination.
