### ISSUE TITLE
Insufficient error message for invalid Git URL

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#239]
**Describe the bug**
When `wego add` cannot find the repo for an invalid URL format, the error message displayed does not fully explain the issue. User should see a better, more detailed error message with examples for valid URL formats. 

**Environment**
 - wego: [v0.0.0]

**Affects versions**
 - wego: [v0.0.1]

**To Reproduce**
1. Download wego binary
2. Install wego controllers
3. Run `wego add . --url=github.com/github-user`
4. See error message on console output

**Config and Logs**

`wego add . --url github.com/iahmad9`

`Updating parameters from environment... using URL: 'github.com/iahmad9' of origin from git config...`

`done`

`Checking cluster status... Unknown`

`wego repo does not exist, it will be created...`
`Reinitialized existing Git repository in /Users/iahmad/.wego/repositories/test-gke-ubuntu-latest-wego/.git/`
`ERROR: Repository not found.`
`fatal: Could not read from remote repository.`

`Please make sure you have the correct access rights
and the repository exists.`
`could not add remote: exit status 1`

**Screenshots**

**Additional context**
- Ideally, wego should perform a pre-flight check on the URL format before trying to run `wego add`.
- Error message with example of accepted formats should also be provided.

**Comment by markramm** [comment]
Error has changed.   Perhaps we can re-run this test and see if the output is better.
