### ISSUE TITLE
Insufficient error message for deleted wego controllers

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#240]
**Describe the bug**
When user tries to run `wego add` after removing 

**Environment**
 - wego: [v0.0.0]
 
**Affects versions**
 - wego: [v0.0.1]

**To Reproduce**
1. Download wego binary
2. Run `wego install | kubectl apply -f -`
3. Run `wego install | kubectl delete -f -`
4. Run `wego add .`
5. See error message in console

**Config and Logs**

`wego add . --url github.com/iahmad9`

`Updating parameters from environment... using URL: 'github.com/iahmad9' of origin from git config...`

`done`

`Checking cluster status... Unknown`

`wego repo does not exist, it will be created...`
`Reinitialized existing Git repository in /Users/iahmad/.wego/repositories/test-gke-ubuntu-latest-wego/.git/`
`ERROR: Repository not found.`
`fatal: Could not read from remote repository.`

`Please make sure you have the correct access rights
and the repository exists.`
`could not add remote: exit status 1`

**Screenshots**

**Additional context**
Discussion in slack: https://weaveworks.slack.com/archives/C0140SWQ94M/p1622659257381800?thread_ts=1622652563.371800&cid=C0140SWQ94M

**Comment by markramm** [comment]
Fixed in more recent versions.
