### ISSUE TITLE
App's portforwarding and gitops run

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#2405]
I emulated the behavior of gitops run with Tilt and found a gap.
here's the scenario:

A Dev had an Nginx program. The dev also had Deployment yaml for nginx.
The dev put the deployment yaml into ./dev
The dev run gitops run ./dev
then the Dev would ask what's next?
The missing puzzle in the above scenario was the port-fwd element (cc @ozamosi)

gitops run ./dev should expect a port-fwd parameter for a resource (a Service, a Pod etc)

for example `gitops run ./dev --port-forward port=8080:80,resource=svc/nginx,namespace=default`.

It is a bit hard for this command to "infer" the service name or port number automatically, so the inference capability should be out-of-scope.

**Comment by chanwit** [comment]
improve the port forward spec to support the following format:
`--port-forward port=8080:80,resource=svc/nginx,namespace=default`.
