### ISSUE TITLE
Extra Components install for Flux

### ISSUE THREAD

**Issue by chanwit** [weaveworks/weave-gitops#2423]
After applying Flux via SSA, the `gitops run` command needs to wait for all Flux controllers to be ready before proceeding to the next steps.

We can do this by polling and checking the ready replica for each Flux deployment object.

**Comment by JamWils** [comment]
@chanwit can you have this filled out and ready for Wednesday morning planning?  Move it to the refine column when it is ready for review by the team.

**Comment by chanwit** [comment]
Thank you @JamWils 
I think it's partially tackled by PR #2443

**Comment by JamWils** [comment]
@ozamosi and @chanwit what if we have an `--extra-components` flag <-- or whatever it is in Flux?

**Comment by chanwit** [comment]
Yes, it would do.
