### ISSUE TITLE
Add flags to `gitops run`

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#2426]
We need to add more flags to `gitops run` to make it more useful

* --flux-version, to set the version of manifests we install.

* --components & --components-extra to specify the flux components

* Use global --namespace

* A --timeout to override the default flux timeout the same way as flux's --timeout

~~* Hook up --insecure-skip-tls-verify from gitops global flag to the flux flags~~
Based on @chanwit 's research: "it's been deprecated for a quite sometime and removed in 1.24" So, the `gitops run` command would not use this flag. But it is still available in the global flags of the `gitops` command and the decision if it should be removed from other commands requires more research.

* There's a bunch like --kubeconfig, --context ~~and --cluster~~ which would help if you have multiple contexts - see if they can be supported.

**Comment by opudrovs** [comment]
@ozamosi , @chanwit suggested adding a string flag to the `gitops run` command to re-add explicit support for remote clusters:
`--allow-k8s-cluster=staging`

So, I will add the flag in PR for the current issue and will skip the `isLocalCluster` check introduced in #2404 (which prevents the `gitops run` command from working with remote clusters) if `--allow-k8s-cluster` equals to the context name/cluster name on the kube client.

It should be pretty similar to other flags.

**Comment by opudrovs** [comment]
Today's discussion let to a decision not to add the `--cluster` flag for now. It will be added later, together with the `--allow-k8s-cluster` flag, when it is determined how it should be used.
