### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by bia** [weaveworks/weave-gitops#2435]
**Short description**
Update the top left product logo, related to #2377 
![20220712new-bg](https://user-images.githubusercontent.com/92439/178525812-fbbbc928-4b28-480d-861d-cb34fc8c946a.png)

**Acceptance criteria**
- [ ] new logo

**Design materials**
[Logo](https://drive.google.com/file/d/13R_kYK5H2Ump73LrZ6Eq4WQSy6B15PEH/view?usp=sharing)

**Comment by opudrovs** [comment]
@bia @joshri for updating the logo, we also need to change the header height from 60px to 72px (or 71px?) for WG OSS too, correct?

Even the header will be reworked in another ticket, we probably need to set the new height in the current PR to properly position the logo.

**Comment by opudrovs** [comment]
@bia @joshri  It looks like there are some issues with sizing/positioning the logo image because it was exported with too much whitespace from Figma, Figma exports can be quirky. Maybe we could just export the logo image without whitespace and set its height to 32px to avoid using various hacks?

Image exported with whitespace in Adobe Illustrator:

![logo](https://user-images.githubusercontent.com/8824708/181383331-982f5ab2-b9d0-4ccc-b21e-2c6158ced602.svg)

Just the image exported without whitespace:

![logo_trimmed](https://user-images.githubusercontent.com/8824708/181383345-d8a94ad1-16a0-485b-9d37-fa7034aa9581.svg)

**Comment by JamWils** [comment]
<svg width="150" height="32" viewBox="0 0 150 32" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M46.6432 20.832L44.3968 13.5872L42.1504 20.832H39.1552L35.9189 10.1973H38.8245L40.8064 17.3525L43.1403 10.1973H45.6278L47.9616 17.3525L49.9435 10.1973H52.8491L49.6128 20.832H46.6411H46.6432Z" fill="#32314A"/>
<path d="M52.7959 15.5029C52.7959 12.4203 55.0636 9.9328 58.2999 9.9328C61.5362 9.9328 63.629 12.3115 63.629 15.7888V16.4053H55.725C55.902 17.7493 56.9794 18.8715 58.7863 18.8715C59.6887 18.8715 60.9431 18.4747 61.6258 17.8155L62.8588 19.6203C61.8028 20.5888 60.1282 21.0965 58.477 21.0965C55.2407 21.0965 52.7959 18.9163 52.7959 15.5051V15.5029ZM58.2999 12.1557C56.5612 12.1557 55.8124 13.4549 55.6802 14.5109H60.9196C60.8535 13.4976 60.1495 12.1557 58.2999 12.1557Z" fill="#32314A"/>
<path d="M71.4584 20.832V19.7312C70.7309 20.5888 69.4765 21.0965 68.0898 21.0965C66.3938 21.0965 64.3906 19.9509 64.3906 17.5744C64.3906 15.1979 66.3938 14.1397 68.0898 14.1397C69.5 14.1397 70.7544 14.6027 71.4584 15.4389V14.0075C71.4584 12.928 70.5346 12.224 69.1245 12.224C67.9789 12.224 66.9229 12.6421 66.0205 13.4784L64.9645 11.6075C66.2637 10.4619 67.9362 9.93494 69.6109 9.93494C72.0322 9.93494 74.2573 10.9035 74.2573 13.9648V20.8341H71.4605L71.4584 20.832ZM71.4584 18.2784V16.9579C70.9954 16.3413 70.1144 16.0341 69.212 16.0341C68.1112 16.0341 67.2088 16.6059 67.2088 17.6405C67.2088 18.6752 68.1112 19.2043 69.212 19.2043C70.1144 19.2043 70.9954 18.8949 71.4584 18.2805V18.2784Z" fill="#32314A"/>
<path d="M78.7817 20.832L74.5107 10.1973H77.5059L80.2793 17.5957L83.0526 10.1973H86.0691L81.7982 20.832H78.7817Z" fill="#32314A"/>
<path d="M85.707 15.5029C85.707 12.4203 87.9748 9.9328 91.211 9.9328C94.4473 9.9328 96.5401 12.3115 96.5401 15.7888V16.4053H88.6361C88.8132 17.7493 89.8905 18.8715 91.6974 18.8715C92.5998 18.8715 93.8542 18.4747 94.5369 17.8155L95.77 19.6203C94.714 20.5888 93.0393 21.0965 91.3881 21.0965C88.1518 21.0965 85.707 18.9163 85.707 15.5051V15.5029ZM91.211 12.1557C89.4724 12.1557 88.7236 13.4549 88.5913 14.5109H93.8308C93.7646 13.4976 93.0606 12.1557 91.211 12.1557Z" fill="#32314A"/>
<path d="M98.1935 23.5392L98.8549 22.6581C99.7786 23.7589 100.792 24.1557 102.377 24.1557C104.314 24.1557 106.01 23.1872 106.01 20.7424V19.0699C105.261 20.1493 103.896 21.0517 102.311 21.0517C99.4927 21.0517 97.5557 18.9163 97.5557 15.5029C97.5557 12.0896 99.4927 9.9328 102.311 9.9328C103.83 9.9328 105.15 10.7029 106.01 11.9147V10.1973H107.177V20.7211C107.177 23.9787 104.975 25.1477 102.377 25.1477C100.594 25.1477 99.4479 24.8171 98.1935 23.5413V23.5392ZM106.01 18.0779V12.9045C105.394 11.8699 103.983 10.9675 102.509 10.9675C100.154 10.9675 98.7887 12.928 98.7887 15.5029C98.7887 18.0779 100.154 20.0171 102.509 20.0171C103.986 20.0171 105.394 19.1147 106.01 18.08V18.0779Z" fill="#32314A"/>
<path d="M109.705 7.64159C109.705 7.15733 110.123 6.78186 110.586 6.78186C111.049 6.78186 111.467 7.15519 111.467 7.64159C111.467 8.12799 111.07 8.52266 110.586 8.52266C110.102 8.52266 109.705 8.12586 109.705 7.64159ZM110.014 20.8299V10.1952H111.16V20.8299H110.014Z" fill="#32314A"/>
<path d="M114.425 18.784V11.2107H112.663V10.1973H114.425V7.29175H115.592V10.1973H117.749V11.2107H115.592V18.6091C115.592 19.4667 115.944 20.0619 116.693 20.0619C117.199 20.0619 117.64 19.8187 117.881 19.5563L118.321 20.4374C117.903 20.8342 117.397 21.0987 116.516 21.0987C115.106 21.0987 114.425 20.239 114.425 18.7862V18.784Z" fill="#32314A"/>
<path d="M118.642 15.5029C118.642 12.3989 120.645 9.9328 123.751 9.9328C126.857 9.9328 128.882 12.3989 128.882 15.5029C128.882 18.6069 126.9 21.0944 123.751 21.0944C120.602 21.0944 118.642 18.6069 118.642 15.5029ZM127.646 15.5029C127.646 13.1477 126.26 10.9675 123.749 10.9675C121.238 10.9675 119.873 13.1477 119.873 15.5029C119.873 17.8581 121.283 20.0597 123.749 20.0597C126.215 20.0597 127.646 17.8795 127.646 15.5029Z" fill="#32314A"/>
<path d="M131.928 19.1147V24.8832H130.782V10.1973H131.928V11.8699C132.677 10.7904 134.042 9.9328 135.627 9.9328C138.466 9.9328 140.382 12.0896 140.382 15.5029C140.382 18.9163 138.466 21.0944 135.627 21.0944C134.129 21.0944 132.788 20.3243 131.928 19.1125V19.1147ZM139.149 15.5029C139.149 12.9259 137.805 10.9675 135.429 10.9675C133.952 10.9675 132.544 11.8485 131.928 12.8619V18.1248C132.544 19.1381 133.954 20.0619 135.429 20.0619C137.807 20.0619 139.149 18.08 139.149 15.5051V15.5029Z" fill="#32314A"/>
<path d="M141.331 19.4219L142.014 18.5621C142.696 19.4219 143.951 20.1259 145.448 20.1259C147.232 20.1259 148.288 19.2021 148.288 17.9691C148.288 15.0635 141.572 16.6912 141.572 12.8832C141.572 11.2533 142.959 9.9328 145.359 9.9328C147.187 9.9328 148.397 10.6368 149.169 11.4965L148.531 12.3115C147.915 11.4752 146.769 10.9013 145.361 10.9013C143.71 10.9013 142.696 11.7376 142.696 12.8384C142.696 15.5029 149.412 13.8731 149.412 17.9691C149.412 19.6864 148.092 21.0965 145.427 21.0965C143.71 21.0965 142.389 20.5909 141.331 19.424V19.4219Z" fill="#32314A"/>
<path d="M13.0368 27.0891C8.22827 25.9413 4.6272 21.4037 4.6272 15.9979C4.6272 9.72587 9.472 4.62507 15.4261 4.62507C18.9312 4.62507 22.2336 6.43414 24.2603 9.46347L27.9339 6.63467C25.1328 2.61547 20.5739 0 15.4261 0C6.90774 0 0 7.16374 0 15.9979C0 23.9893 5.6512 30.6134 13.0347 31.8059V27.0912L13.0368 27.0891Z" fill="#32314A"/>
<path d="M30.8117 15.0635H20.4991V19.7099H29.2607L17.9775 31.7739C18.001 31.7696 18.0245 31.7654 18.0479 31.7611C18.1973 31.7355 18.3445 31.7056 18.4938 31.6758C18.5514 31.663 18.609 31.6502 18.6666 31.6374C18.7733 31.6139 18.8799 31.5883 18.9866 31.5627C19.0698 31.5435 19.1509 31.5222 19.2341 31.5008C19.2895 31.4859 19.345 31.471 19.4026 31.4539C25.7045 29.7131 30.417 23.9339 30.8159 16.9515C30.8245 16.8107 30.8287 16.6699 30.8351 16.5355C30.8351 16.5163 30.8351 16.4971 30.8351 16.48C30.8351 16.4352 30.8373 16.3925 30.8394 16.3499C30.8415 16.2411 30.8437 16.1323 30.8437 16.0213C30.8437 15.6992 30.833 15.3792 30.8138 15.0613L30.8117 15.0635Z" fill="#32314A"/>
<path d="M13.0366 20.64L9.16029 24.384V6.74133C6.42322 8.80213 4.63335 12.1749 4.62695 15.9787V27.424C5.53789 28.3648 6.53416 29.0731 6.62802 29.1435C8.12562 30.2336 9.26269 30.6709 9.31602 30.6944L13.0366 27.1019V20.6421V20.64Z" fill="#FF4B19"/>
<path d="M22.9356 19.712L17.9372 25.216V9.95203L13.0391 14.4214V31.8059C14.0055 31.9958 15.3004 31.9936 15.422 31.9979C16.2732 32.0192 17.4913 31.8742 17.9777 31.7803L29.2631 19.712H22.9356Z" fill="#00D2FF"/>
<path d="M16.7895 4.71679C16.3393 4.65706 15.8807 4.62506 15.422 4.62506C14.6028 4.62506 13.8049 4.72106 13.0391 4.90666V8.14079L16.7895 4.71893V4.71679Z" fill="#00D2FF"/>
<path d="M16.7898 4.7168L9.16309 11.6779V17.9605L21.562 6.64533C20.1476 5.61706 18.5135 4.94933 16.7919 4.7168H16.7898Z" fill="#576A92"/>
</svg>

**Comment by mmoulian** [comment]
yes, I take note and in the future I will adjust the canvas to the size of the logo
