### ISSUE TITLE
AWS Marketplace - remove code for billing

### ISSUE THREAD

**Issue by josefaworks** [weaveworks/weave-gitops#2441]
The AWS Marketplace offering is now free so we need to remove code related to the billing process so that no one accidentally gets charged

**Comment by JamWils** [comment]
@josefaworks and @davidstauffer this is no longer necessary, right?

**Comment by josefaworks** [comment]
i believe we need to put a new "version" of core on the aws marketplace and remove the existing one entirely since we cannot remove the pricing model from the existing one. @davidstauffer and i were going to look at getting the new version up

**Comment by JamWils** [comment]
Oh, I got very confused about that conversation at stand up.  I thought the issue was we couldn't offer a free version at all.  It sounds like the really issue is you cannot change an "existing" app from paid to free.  Do I have that right?

**Comment by josefaworks** [comment]
yeah exactly :)

**Comment by josefaworks** [comment]
Closing because we realized we can put 'normal' OSS on the marketplace rather than spend the time deprecating a specific part of the code base. we will no longer need the aws marketplace code base once we have OSS up on the marketplace
