### ISSUE TITLE
Limit page height to 2x screen height

### ISSUE THREAD

**Issue by bia** [weaveworks/weave-gitops#2474]
Pagination of table items should start by default when the table is two times the height of the screen (as in Gmail).

**Comment by JamWils** [comment]
Pagination might not be possible.  This was explored during the app refresh.  It is due to how `etcd` the underlying database works on a cluster.  

@luizbafilho I think you helped work on that and we backtracked from it right?  I don't want to go down the same path again.

**Comment by luizbafilho** [comment]
Pagination is possible, but not in the way we are used to. 

For instance, we cannot have page numbers below the table, it will need to be a "Next" button at max. If we decide to enable a "Previous" button, we'll need to cache the data in memory on the page when we fetch more items, that way we can "go back" to the previous page, cause in k8s you can't specify a "page" you wanna fetch, you can only ask more data with a limited number of items.

**Comment by JamWils** [comment]
There is also the issue of sorting/ordering too, right @luizbafilho?  If we were to have this pagination even as you describe above then sorting kind of becomes impossible given how the data is cached, etc.

**Comment by luizbafilho** [comment]
Yes, sorting on k8s api is not doable at all. Any kind of sorting can only be done on the client side after that data has been fetched.

**Comment by JamWils** [comment]
I'm closing this for now since we are not prioritizing pagination anytime soon.

**Comment by bigkevmcd** [comment]
We're seeing customer performance issues because we're not paginating results.

We can't have "jump to page X" but we can have _next_ and _previous_ buttons.

When you query a `List` of resources, you do get an approximate number of items remaining.

**Comment by ozamosi** [comment]
There's things we can do, but they require that the UI is built around it.

Our current query pattern is:
* For each namespace:
  * For each cluster:
    * `List`
* Aggregate and return results

So we issue `O(N*M)` `List` requests, and sort and filter on the frontend. If we limit each request, we'd have `N*M` different approximate numbers remaining. 

If we were to push down the filters into the backend we wouldn't have to return data that's been filtered out. Then, if we didn't need to sort, we could just stop querying when we'd reached e.g. 25 results, and return a token that represents where we were so we can request next.

But a very large part of our UI is built around sorting. I know most uses of sorting are actually an attempt to use filtering (e.g. nobody wants to sort by status, they want to find objects with non-OK status; nobody wants to sort by name, they want to find a name they either know or vaguely know) but I think we'd need to make the filtering better before we can remove sorting.

**Comment by JamWils** [comment]
🤔 ok.  This does need to be fixed in general.  The last time this was done by an engineer it didn't go well hence my hesitation.

@ozamosi let's set up some time on finding a path forward for this.  @bigkevmcd, is it safe to assume that the work we do here in OSS will makes its way to Enterprise?

**Comment by ozamosi** [comment]
Also see https://github.com/weaveworks/weave-gitops-enterprise/issues/1308 for the customer performance issue that triggered these comments.

**Comment by bigkevmcd** [comment]
Multi-cluster paginated results are pretty complex.

For example, if you have a page size of 20, and one cluster...you get 20 results from the one cluster, all's fine.

If you have two clusters, do you get 10 from each, and all's fine?

If you have 20 clusters, do you get 1 from each?

If you have 21 clusters...what do you do?
