### ISSUE TITLE
Store application events for debugging purpose

### ISSUE THREAD

**Issue by souleb** [weaveworks/weave-gitops#2475]
**Short description**

As a User I would like to be able to use weave gitops provided application events for debugging purpose.

**Context**

The current implementation queries the list of events for a given application (helmrelease, kustomization) from the APIServer.
The problem is that the `kube-api-server` retention time for server is short (by default 1h, this can be extended with the flag `--event-ttl`).

This lead to cases where I have only one event listed for applications running for days. 

The idea is not to add long term storage. But we should have a long enough list of events (aggregated?) for debugging purpose.

**Acceptance criteria**
- [ ] display the last 24h of events
- [ ] enable filtering events

**Design materials**

The proposal is to add a new interface

```go
type Store interface {
        // ListEvents return a slice of events from target
	ListEvents(ctx context.Context, target string, opts ...ListOption) ([]*v1.Event, error)
	GetEvent(ctx context.Context, involvedObj runtime.Object, target string, opts ...GetOption) (*v1.Event, error)
	AddEvent(ctx context.Context, e *v1.Event, target string) error
        AddEvents(ctx context.Context, e []*v1.Event, target string) error

	CreateEventPermissionSet(ctx context.Context, name string) error
	AddNameSpaceToEventPermissionSet(ctx context.Context, name, namespace string) error
}
```

We would then have an in-memory implementation (for testing or local) and a redis implementation to store the events.

The events would be pulled for the apiServer with `client.Watch` in a backgroung go routine (the same way we do with NS but without polling)
```go
go func(ctx context.Context, kubeClient client.WithWatch, list *v1.EventList) {
  	w, err := kubeClient.Watch(ctx, list)
	if err != nil {
		return err
	}

	_, err = watchUntil(ctx, w, get)
	if err != nil {
		return err
	}

	return nil
}()
```

In order to deal with permissions, we need to know if the user has the rights to get events from the given application namespace. In order to do that we can use the `k8s.io/api/authorization/v1` and the [SelfSubjectAccessReview](https://github.com/kubernetes/api/blob/v0.24.3/authorization/v1/types.go#L54) coupled with impersonation.

We would use the `Store` to keep the `set` of namespaces where a user can get events from. The `set` would be identified by `wego:events_ns_access:<bearer_token>`. Using the bearer token ensure that the set is valid only for the session duration. So we would need a new `set` cached for every session and updated when we update the application list for a user.

Then in order to pull events for a given application, we would have something like this in redis:
```go
// pull a list of events
//
// Input:
// KEYS[1] -> wego:events_ns_access:<bearer_token>
// KEYS[2] -> wego:{<stream_name>} where stream_name in namespace/kind/name
// --
// ARGV[1] -> app namespace
// ARGV[2] -> first event ID
// ARGV[3] -> last Event ID
//
var listEventsCmd = redis.NewScript(`
if redis.call("SISMEMBER", KEYS[1], ARGV[1]) == 0 then
	return redis.error_reply("NOT AUTHORIZED")
end
return redis.call("XRANGE", KEYS[2], ARGV[2], ARGV[3], COUNT 50)
`)
```

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by JamWils** [comment]
Per the conversation with @ozamosi.  

How does RBAC and permissions fit into this?

Does the `Store` interface verify if a user has permission to `events` in the namespace where `involedObj` is? If so, how does it do that?

**Comment by souleb** [comment]
I have updated the issue to address access rights to the events.

**Comment by LappleApple** [comment]
Heya, going to close this out for now due to age and likely effort required. We can reopen in the future if necessary.
