### ISSUE TITLE
Refined table style with standardised spacing

### ISSUE THREAD

**Issue by bia** [weaveworks/weave-gitops#2477]
![Table filtered selectable](https://user-images.githubusercontent.com/92439/180438573-9f1206eb-545f-4aa3-81dd-d90828d3d172.png)
![Table filtered selectable 2](https://user-images.githubusercontent.com/92439/180438565-8fd40c5c-7055-4dac-a712-bde256010b25.png)
![Table with Sub-table Open](https://user-images.githubusercontent.com/92439/188669998-134c90a4-9ee4-4799-a12f-b514c911c7dd.png)

cc @TheGostKasper 

### Acceptance Criteria

- [ ] Column title text is `semi-bold` `12px` Proxima Nova with the sorting column title in 'Neutral 40' (`#1a1a1a`) and all other column titles in 'Neutral 30' (`#737373`)
- [ ] height of title row should be `32px` with `#F6F7F9` background
- [ ] height of content row should be `40px` with white background
- [ ] sub-tables are indented by `24px`
- [ ] closed sub-tables have a right-facing [chevron icon](https://fonts.google.com/icons?selected=Material%20Icons%3Achevron_right%3A)
- [ ] expanded sub-tables have a downward-facing [chevron icon](https://fonts.google.com/icons?selected=Material%20Icons%3Achevron_right%3A)
- [ ] page elements should be separated by `16px`, `24px`, or `48px` as described above
- [ ] `theme.ts` reflects these semantic choices in 
```  spacing: {
    // 16px
    base: `${baseSpacingNumber}px`,
    // 32px
    large: `${baseSpacingNumber * 2}px`,
    // 24px
    medium: `${baseSpacingNumber * 1.5}px`,
    none: "0",
    // 12px
    small: `${baseSpacingNumber * 0.75}px`,
    // 48px
    xl: `${baseSpacingNumber * 3}px`,
    // 8px
    xs: `${baseSpacingNumber * 0.5}px`,
    // 64px
    xxl: `${baseSpacingNumber * 4}px`,
    // 4px
    xxs: `${baseSpacingNumber * 0.25}px`,
  },
```

### References

[Figma](https://www.figma.com/file/gnodK9xtoOahXBqa6ONsA5/WW-Design-System?node-id=1042%3A4123)

**Comment by opudrovs** [comment]
@bia The link to Figma is broken for me, it says "file not found" and that either the file does not exist or I have no permissions to view it.

Could you please check the link to Figma and make it viewable by all members of @weaveworks/denim ?

**Comment by bia** [comment]
hi @opudrovs , it seems that you did not have access to the Figma design system. Who else needs access besides @TheGostKasper ?

**Comment by opudrovs** [comment]
@bia thanks, please give access to me, @joshri ,  @ozamosi , @chanwit and @katya-makarevich please.

**Comment by joshri** [comment]
These three parts of the acceptance criteria are confusing to me - we don't have sub-tables and a couple of the elements in the designs here don't exist in oss. 
 - closed sub-tables have a right-facing chevron icon
 - expanded sub-tables have a downward-facing chevron icon
 - page elements should be separated by 16px, 24px, or 48px as described above

The theme that is posted in the AC is exactly what it is already in oss so we should be good there

**Comment by bia** [comment]
> expanded sub-tables have a downward-facing chevron icon
We don't have sub-tables in oss - was this meant for enterprise?

Sub-tables are something that we have been further refining this week for Enterprise. @joshri should I follow up on the final design here, or should I create a separate issue for it?

**Comment by bia** [comment]
I have now updated this issue with our latest sub-table design
