### ISSUE TITLE
Doesn't work on Raspberry Pi arm64 & arm/v7 arch

### ISSUE THREAD

**Issue by grglzrv** [weaveworks/weave-gitops#2480]
**Environment**

- Weave-Gitops Version - v0.9.0
- Flux Version :
   ```
       flux: v0.31.3
       helm-controller: v0.22.1
       kustomize-controller: v0.26.2
       notification-controller: v0.24.0
       source-controller: v0.25.9
   ```
- Kubernetes version - 1.23.8+k3s1

The image is built only for amd64 arch, could you please built for arm64 and arm/v7?

Thanks a million for your cooperation.

**Comment by makkes** [comment]
Tracking issue: #2055

**Comment by kingdonb** [comment]
I see that the tracking issue has closed:

* #2055 

I think I see arm64 images are part of the Weave GitOps distro now. So I believe this issue can be closed. (Do we have anyone who has tested it on a Raspberry Pi?)

I think that arm/v7 support was not on the list. I wouldn't have any expectation that it's going to be added later, unless there is a business need I didn't anticipate. So it would have to be a 64 bit distro and board, (Raspberry Pi 3 or 4 +)

**Comment by makkes** [comment]
I'm running it on my home Rpi cluster (all 3+) just fine. I suppose we want to add some e2e testing on ARM beforee we close this? Otherwise support might just break anytime w/o anyone noticing.

**Comment by sympatheticmoose** [comment]
we can raise a separate task to add e2e tests, but I'm not sure its something we'll tackle right away.
