### ISSUE TITLE
Graph lines to extend at lines when branching out horizontally

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2484]
As a user, I would like to see the lines of the graph extend out horizontally from the lines instead of from the sides of the node.

In addition, there should be equal spacing between child nodes.

![image](https://user-images.githubusercontent.com/1825111/180852860-05936e32-8550-4381-87e0-9620fff230cc.png)

**Comment by opudrovs** [comment]
@JamWils about

> In addition, there should be equal spacing between child nodes.

I suppose, equal spacing means horizontal spacing between columns, not vertical spacing between child nodes in the same column (because it is already equal)?
