### ISSUE TITLE
Dependency Tab on Workloads page

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2486]
As a user I want to understand the dependencies between my `kustomizations` and `helm releases`.  This is often done by going through the yaml and building a mental map so I can understand what precedes what.  This is a challenge in multiple ways as I jump from yaml file to yaml file.  I could also use the `flux cli` to figure this info out as well.  It would be nice to have a visualization that lets me understand the dependencies in a diagram that flows.

### Acceptance Criteria

When I go to the detail page for a `Kustomization` or `Helm Release` and click on the `Dependencies` tab I can see:

1. Given I have no dependencies for the particular object then I should see a nice onboarding message.

![image](https://user-images.githubusercontent.com/1825111/180863951-3c1a8603-eb31-414d-8a10-f3cdb1d8ebc9.png)

[Figma](https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?node-id=10531%3A59448)

2. If there are dependencies then draw them out from the parent (i.e. no `dependsOn` value) down. 

Note: the selected `Kustomization` or `Helm Release` may not necessarily be the parent node.  It might sit somewhere in the middle of the dependency graph or at the bottom depending on the location.

So let's draw out an example.  From a UI perspective the nodes should look like the nodes from the normal `trace` graph.  With the distinct difference that arrows should point down to the next node.  Let's say we are looking at the detail page of Kustomization `C`.

1. Kustomization `A` has no depends on value.
2. Kustomization `1` has no depends on value.
3. Helm Release `B` and Kustomization `C` both depends on A.
4. Kustomization `D` depends on `B`.
5. Kustomization `E` depends on `A` and `1`.

```mermaid
flowchart TB
  A --> B
  A --> C
  B --> D
  A --> E
  1 --> E
```

**Comment by opudrovs** [comment]
@JamWils

- Is the "trace graph" like a regular graph on the Graph tab but with arrows?

- Is there a separate Figma for graph design or should I use the same design as the current graph? And how should the lines go between nodes? Like in the current graph or in a different way?

- @ozamosi was the `dependsOn` fields added to the response objects? I only see the description of this field in some yamls at `tools/testcrds`. Or should it be somehow added to the objects?

- So, as we discussed, on each dependency tab I need to call list all available Kustomizations and HelmReleases and build the graph on this data based on the `dependsOn` field?

**Comment by JamWils** [comment]
> Is the "trace graph" like a regular graph on the Graph tab but with arrows?

Yes

> Is there a separate Figma for graph design or should I use the same design as the current graph? And how should the lines go between nodes? Like in the current graph or in a different way (without joining into one line when going out of the parent node, for example)?

Yes, use the existing design pattern in the current graph including how the lines are drawn out (unless LOE is super high).

**Comment by opudrovs** [comment]
According to the API specs, Kustomizations can only depend on other Kustomizations and HelmReleases on otherHelmReleases, so there cannot be a mixed dependency "tree" (directed acyclic graph data structure, to be precise) and I only list automations of the same kind when building the tree.

```
// KustomizationSpec defines the configuration to calculate the desired state from a Source using Kustomize.
type KustomizationSpec struct {
	// DependsOn may contain a meta.NamespacedObjectReference slice
	// with references to Kustomization resources that must be ready before this
	// Kustomization can be reconciled.
	// +optional
	DependsOn []meta.NamespacedObjectReference `json:"dependsOn,omitempty"`
	
...

// HelmReleaseSpec defines the desired state of a Helm release.
type HelmReleaseSpec struct {
	...

	// DependsOn may contain a meta.NamespacedObjectReference slice with
	// references to HelmRelease resources that must be ready before this HelmRelease
	// can be reconciled.
	// +optional
	DependsOn []meta.NamespacedObjectReference `json:"dependsOn,omitempty"`	
```

**Comment by JamWils** [comment]
I believe that is true.  @stefanprodan do you mind validating the statement above about Kustomization and HelmRelease depends on?
