### ISSUE TITLE
Make wego CLI understand ~ in folder paths

### ISSUE THREAD

**Issue by pzfreo** [weaveworks/weave-gitops#251]
**Describe the bug**
At the moment, file paths do not correctly work with ~

e.g. 

```
wego app add . --private-key=~/.ssh/wego
failed reading ssh keys: open ~/.ssh/wego: no such file or directory
```

**Environment**
 - wego: latest build 

**Affects versions**

**To Reproduce**
Try using a private key with ~ in the path.

**Expected behavior**
Expect ~ to be replaced by $HOME

**Comment by markramm** [comment]
It already does for private keys.
