### ISSUE TITLE
SPIKE: How do we complete the bootstrap?

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#2528]
We need to complete the bootstrap, without having to maintain the code for bootstrapping.

Is there an easy way to do that, or do we need to look for the flux CLI/the docker command?

**Comment by chanwit** [comment]
There are 3 options to do Flux bootstrap.
 1. Use Flux CLI
 2. Use Flux CLI image via Docker
 3. Use Flux codes (copy-n-paste from Flux's internal packages)

**Comment by chanwit** [comment]
## Conclusion:

We would mix Option 2 and Option 1 into Option 4.

## Option 4 - Download Flux CLI, cache it in an isolated directory, and use it on the fly

This approach is similar to what's done by HashiCorp's tf-exec for its `terraform` binary.
We would also take the design of tf-exec and implement it for Flux CLI.

**Comment by ozamosi** [comment]
Outcome in #2592
