### ISSUE TITLE
Race condition in unit tests

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#2530]
The unit tests are more and more often failing with an error like `FATAL [core] grpc: Server.RegisterService after Server.Serve for "wego_server.v1.Applications"` - see for example [this run](https://github.com/weaveworks/weave-gitops/runs/7656110871)

The test suite shouldn't randomly fail.

**Comment by opudrovs** [comment]
I can confirm it, especially during the last week.

**Comment by ozamosi** [comment]
I ran the racy test locally approximately 100 times, and it wouldn't fail - yet it keeps happening in CI much more regularly.

**Comment by ozamosi** [comment]
This seems to have been related to profiles code, and that code isn't there any more.
