### ISSUE TITLE
Source URL hyperlink should respect reference

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2535]
For users trying to navigate to their defined source, it would make things a lot simpler if they could follow the hyperlink and that take them to the correct fetched reference - a branch, tag or semver-tag. 

The URL display text could match `spec.url` i.e. https://github.com/stefanprodan/podinfo

The hyperlink should be informed by the `status.revision` of the deployed source. Crucial for the semver example.

`ref.commit=<example>` or `ref.branch=<example>` = https://github.com/stefanprodan/podinfo/tree/\<example\>

`ref.tag=<example>` or `ref.semver=<example>` = https://github.com/stefanprodan/podinfo/tag/\<example\>

**Comment by sympatheticmoose** [comment]
Somewhat relevant issue for consideration https://github.com/weaveworks/weave-gitops/issues/2115

**Comment by ozamosi** [comment]
Which git forges are in scope for this ticket?

**Comment by sympatheticmoose** [comment]
fair point, I see how that would increase complexity and in which case @JamWils would need to weigh in on priority order. My suggestion would be github.com > gitlab.com > gitlab on prem > ghe. Others unsupported for now.

**Comment by JamWils** [comment]
🤔 I definitely agree on GitHub and GitLab.  Also it would be nice to be taken to the correct ref.  I think we just need to be clear about the level of scope before this gets picked up.

**Comment by JamWils** [comment]
This has been open a long time now.  I'm going to close this for the moment as it could be some time until we get to it.
