### ISSUE TITLE
docs: search result links don't work consistently

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2561]
For example, searching for `support@weave.works` to update potential references, and clicking to see all results: 
[https://docs.gitops.weave.works/search/?q=support%40weave.works](https://docs.gitops.weave.works/search/?q=support%40weave.works)

For me returns 6 results, but there seems to be a strange duplication going on and the duplicate is an invalid location
- https://docs.gitops.weave.works/docs/next/help-and-support/#weaveworks-materials ✅ 
- https://docs/next/help-and-support/#weaveworks-materials ❌ 
- https://docs.gitops.weave.works/docs/next/help-and-support/#community ✅ 
- https://docs/next/help-and-support/#community ❌ 
- https://docs.gitops.weave.works/docs/next/help-and-support/#commercial-support ✅ 
- https://docs/next/help-and-support/#commercial-support ❌

**Comment by ozamosi** [comment]
Fixed in the referenced PR
