### ISSUE TITLE
Notifications UI table view

### ISSUE THREAD

**Issue by josefaworks** [weaveworks/weave-gitops#2564]
As a platform operator, if I have notifications set up, I will see a list with the providers, namespace, cluster and severity so that I can quickly understand where notifications are being sent 
Figma Link: https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?node-id=4908%3A9125

**Comment by joshri** [comment]
In discussions with @JamWils, we decided that the menu under the user icon will say "Notifications" (not Settings), and the breadcrumb will always be "Notifications" (not Alerts & Providers). Slight differences from the Figma designs.

**Comment by josefaworks** [comment]
i think that makes sense! in the future when we have other settings we can always move it
