### ISSUE TITLE
Add Provider tab details

### ISSUE THREAD

**Issue by josefaworks** [weaveworks/weave-gitops#2568]
As a platform operator, I can click into the `YAML` tab to see a yaml file of  how events are encoded and the webhook address where they are being sent so that I can make sure the notification is configured correctly

Figma Link: https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?node-id=4908%3A9125
Note: screenshot is alert data below but it should display provider data.
![image](https://user-images.githubusercontent.com/1825111/186908540-cea07731-7275-4b6c-a5d1-46235c5da06b.png)

**Comment by opudrovs** [comment]
As i said, I see it for the Alerts column, if it's not a general filtering issue:, it must be related to this PR:

<img width="1505" alt="Screenshot 2022-09-12 at 21 51 05" src="https://user-images.githubusercontent.com/8824708/189744064-dcac11cc-031d-4f20-aec5-39af07681815.png">
