### ISSUE TITLE
Add Event tab details

### ISSUE THREAD

**Issue by josefaworks** [weaveworks/weave-gitops#2569]
As a platform operator, I can click into the Event tab to see the K8s event of what information a report of an event issued by a controller should contain so that I can make sure the notification is configured correctly
Figma Link:https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?node-id=4908%3A9125
Note: screenshot is of alerts tab, but should look the same for Events
![Screen Shot 2022-08-09 at 2.09.22 PM.png](https://images.zenhubusercontent.com/6138b1b3d7038f238a0ab7fb/2035ef9c-e142-46c2-a1fd-54c054dcb9fb)

**Comment by JamWils** [comment]
Thanks for the write up @joshri!
