### ISSUE TITLE
OIDC Sessions cannot be stored with big Tokens

### ISSUE THREAD

**Issue by Robbilie** [weaveworks/weave-gitops#2602]
**Describe the bug**

In case an oidc provider returns fairly large tokens login using oidc does not work (without any error) because the size of cookies in chrome is limited to 4096 characters which results in the id_token and access_token cookies not being stored. Applications like oauth2-proxy note that and provide alternate session mechanisms like redis storage.

**Environment**

- Weave-Gitops Version v0.9.1
- Flux Version v0.32.0
- Kubernetes version v1.24.3+rke2r1

**To Reproduce**

1. Create an azure ad client
2. Create several hundred groups and make a person a member
3. Setup DEX IDP using azure ad settings
4. Connect Weave Gitops to DEX IDP
5. Try to login using the user

**Expected behavior**

A warning is shown or an alternate session storage mechanism is provided

**Actual Behavior**

Login page just "reloads"

**Additional Context (screenshots, logs, etc)**

**Comment by eloo** [comment]
Hi,
looks i'm also affected by this "bug".
Took me hours to find the issue.

At least a warning or error log should be added when a cookie content reaches this limit.
Silently drop that mandatory cookies is really a pity here

**Comment by mukulgit123** [comment]
@bigkevmcd - Can this be the same issue as https://github.com/weaveworks/weave-gitops/issues/2955 ?

**Comment by ahussein3** [comment]
Proposed Solution: 
- Split Token over several cookies
- Gzipping the token to fit in one Cookie

**Comment by Robbilie** [comment]
the most common solution is to have a session store like redis…

**Comment by leosunmo** [comment]
Also affected by this. Using Gitlab OAuth -> Dex and the list of groups is _huge_ when certain admin users authenticate, which leads to https://github.com/weaveworks/weave-gitops/issues/2955 with a "Named Cookie can't be found" error. Would love a workaround in the meantime, please!

**Comment by bigkevmcd** [comment]
We are working on replacing the existing Cookie storage with Session based storage (session-cookie, rather than ID token in Cookie).

**Comment by daniel-ciaglia** [comment]
@bigkevmcd - do you people have a recommendation for a workaround?
I am blocked by this as the `groups` claim gets quite huge (using AzureAD as an OIDC provider).

**Comment by bigkevmcd** [comment]
Unfortunately there's no easy workaround, we're not very sure how the groups claims get _so_ big, 4096 bytes is a lot of data, but we are testing a fix for this.

**Comment by daniel-ciaglia** [comment]
> [..] we're not very sure how the groups claims get _so_ big, 4096 bytes is a lot of data
Azure does not provide the `name` of a group but the `id` - here's an example: `"ec49c802-580b-454b-8536-37f3a52fd455"`
This is probably blowing up the token.

**Comment by bigkevmcd** [comment]
@daniel-ciaglia That's what I suspected, I don't have access to it to discover this.

Initial phase of this branch will support in-memory only, but, the plan is to then allow for out-of-process storage.

One caveat around any sort of out-of-process storage is that the ID tokens should really be encrypted.

**Comment by bigkevmcd** [comment]
@daniel-ciaglia @Robbilie We have released a change that should solve this.

https://github.com/weaveworks/weave-gitops/releases/tag/v0.31.0

Please feel free to reopen this issue if you are still experiencing the problem.

We are looking to add support for external session storage, so if this is something that you want support for, please feel free to open an issue.
