### ISSUE TITLE
Several references found to deprecated helm/charts repo

### ISSUE THREAD

**Issue by devmage** [weaveworks/weave-gitops#2607]
**Describe the bug**

The `weave-gitops` codebase makes [a couple references](https://github.com/weaveworks/weave-gitops/search?q=%22https%3A%2F%2Fgithub.com%2Fhelm%2Fcharts%22) to the [helm/charts](https://github.com/helm/charts) repository. This repository is deprecated. The canonical source for Helm charts is the [Artifact Hub](https://artifacthub.io/).

I would simply offer this as a fix, however you all might want to point somewhere else. So, this is just a docs Issue. 🙂 

**Environment**

n/a

**To Reproduce**

https://github.com/weaveworks/weave-gitops/search?q=%22https%3A%2F%2Fgithub.com%2Fhelm%2Fcharts%22

**Expected behavior**

Links reflect currently maintained repositories for Helm charts.

**Actual Behavior**

Links reflect deprecated previous repository for Helm charts.

**Additional Context (screenshots, logs, etc)**

I think that's it. 🙂

**Comment by sympatheticmoose** [comment]
Thanks for the fix!
