### ISSUE TITLE
No descriptive text for `app` flag

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#266]
**Describe the bug**
There's no text for the the description of `wego app` command. This issue has been seen before but no bug has been logged for it. 

**Environment**
 - wego: [v0.0.4]

**To Reproduce**
1. Download wego binary
2. Run `wego` command or `wego -h` command

**Expected behavior**

**Screenshots**
![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/d4512410-628b-428c-adff-444fc3b4686d)

**Comment by D3nn** [comment]
Closed by PR 314
