### ISSUE TITLE
Error no matches for kind "OCIRepository" in version "source.toolkit.fluxcd.io/v1beta2"

### ISSUE THREAD

**Issue by grglzrv** [weaveworks/weave-gitops#2695]
**Describe the bug**
We are getting error - no matches for kind "OCIRepository" in version "source.toolkit.fluxcd.io/v1beta2" in our Weave UI

<img width="1614" alt="image" src="https://user-images.githubusercontent.com/19932357/188275804-ab63a912-ead6-445e-bdb3-02327753badf.png">

<img width="1586" alt="image" src="https://user-images.githubusercontent.com/19932357/188275817-f460daea-b046-4f91-b3c8-42fb7b9fc2ca.png">

**Environment**
Stage and PROD

- Weave-Gitops Version - [HEAD-c26a1c39](https://github.com/weaveworks/weave-gitops/commit/c26a1c39) helm chart version - 3.0.3  
- Flux: v0.31.5
- Kubernetes: v1.20.15-eks-18ef993

**To Reproduce**

**Additional Context (screenshots, logs, etc)**
<img width="1614" alt="image" src="https://user-images.githubusercontent.com/19932357/188275804-ab63a912-ead6-445e-bdb3-02327753badf.png">

<img width="1586" alt="image" src="https://user-images.githubusercontent.com/19932357/188275817-f460daea-b046-4f91-b3c8-42fb7b9fc2ca.png">

**Comment by chanwit** [comment]
Hi @grglzrv 

Thank you for filing the issue.
Please use Flux v0.32.0+.

Flux v0.31.x has Helm OCI support, but not OCIRepository.

**Comment by sympatheticmoose** [comment]
Closing based on the guidance above, please re-open if you require any further assistance.
