### ISSUE TITLE
When gitops run is started, create an empty entrypoint kustomization if the target directory doesn't exist

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#2698]
If the workload directory (the directory the user specifies on the CLI) doesn't exist, create it, and put an empty kustomization in it.

If a user:
* Creates a new initialized repository in github (initialized in order to remove a couple of steps)
* Clones it.
* cd into it, and runs `gitops beta run ./workload` even though that directory does not exist.

Then:
* By the time gitops run is started, the directory `./workload` should exist.
* It should contain an empty placeholder k8s kustomization file (e.g. similar to [this](https://github.com/ozamosi/scenario-2-gitops-run-dotdot-workload/blob/main/workload/kustomization.yaml)).
* When the user adds files to it, they should be automatically updated.

**Comment by JamWils** [comment]
@ozamosi there is a bug where `gitops run` hangs when you run against an empty directory.  Would this in theory fix that too?  If not, I can file a separate issue.

**Comment by ozamosi** [comment]
I wasn't going to check for empty directories, but it's a tiny extra check to add - I'll add it.
