### ISSUE TITLE
Take the user through a bootstrap wizard when they close gitops run

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#2699]
Flux bootstrap's per-git forge support allows a user to handle flux authentication in a secure way - we need to support these.

However, that means we need to support things that are difficult to auto-detect - e.g. whether `git.mycompany.com` is an enterprise installation of github, gitlab or something else, or whether `github.com/weaveworks` is a personal github account or an organisation account.

There are probably libraries to help us do this.

**Acceptance Criteria**

* Allow defining a tree of questions. E.g.:
  * What type of git forge is this? [github, gitlab, bitbucket, generic] github
    * Is this a personal or an organizational account? [personal, organizational]
    * Is this a private or public repository? [private, public]
* Specify a way to try to auto-detect an answer. E.g.:
 * Parse the git remote - if the host is `github.com` then use that answer as the git forge type, and don't ask the question
 * If the environment variable `GITOPS_GITHUB_ACCOUNT_TYPE=personal` is set, then we don't ask question about account type.

The outcome of this wizard should be an unambiguous `flux bootstrap` command.

Note that flux already has some of this - if you run `flux bootstrap github` without a `GITHUB_TOKEN` environment variable, it will ask you for a PAT. We are not looking to replace this specific UI - we are looking to extend this wizard thinking so that we can construct the command in the first place.

**Comment by chanwit** [comment]
+1
This would make the whole UX more attractive.
The command could be as simple as `gitops run` and launch the wizard.

**Comment by ozamosi** [comment]
I want this ticket to be specifically for transitioning from run mode to gitops mode - though there's nothing saying we can't use the same way of thinking to transitioning from snowflake mode to run mode.

**Comment by ozamosi** [comment]
To be more specific, I see our flow as having these three phases (I've tried to keep it legible, so only flux-y boxes included):

```mermaid
flowchart LR
  start
  subgraph first [transition snowflake to run]
  direction TB
  start --> fluxInstall["flux install"]
  end
  ctrlC
  subgraph runMode [gitops run mode]
  start --> gitopsRun
  fluxInstall --> gitopsRun["gitops run main loop"]
  gitopsRun --> fileChanged
  fileChanged --> gitopsRun
  gitopsRun --> ctrlC["ctrl+c"]
  end
  subgraph last [transition run to gitops]
  ctrlC --> configureBootstrap
  configureBootstrap --> fluxBootstrap["flux bootstrap"]
  fluxBootstrap --> configureBootstrap
  end
  ctrlC --> finished
  fluxBootstrap --> finished
```
In the first phase, exiting and printing an error is OK. Once we got past that phase, we can't really go backwards, we can just restart the current phase.

"flux bootstrap" runs in the last phase and takes many fiddly arguments. We don't want you to have to re-start the whole gitops run at the very end. So when something goes wrong, we have to re-run this phase only, which means we need to let you change the options we assumed, which means we need some kind of wizard.

**Comment by opudrovs** [comment]
I systematized the flags of all four `flux bootstrap <provider>` commands.

Commands:

```
flux bootstrap github
flux bootstrap gitlab
flux bootstrap git
bitbucket-server
```

All command flags (without global flags)

```
allow-insecure-http		-	- 	G	-
group					-	-	-	BB
hostname 				GH 	GL 	-	BB
interval 				GH 	GL 	G 	BB
owner 					GH 	GL 	- 	BB
password				-	- 	G	-
path 					GH 	GL 	G 	BB
personal 				GH 	GL 	- 	BB
private 				GH 	GL 	- 	BB
read-write-key 			GH 	GL 	- 	BB
reconcile 				GH 	GL 	- 	BB
repository 				GH 	GL 	- 	BB
silent					-	-	G	-
team 					GH 	GL 	- 	-
url						-	-	G	-
username				-	-	G	BB
```

Command flags used in examples

```
hostname			GH	GL	-	BB
owner				GH	GL	-	BB
password			-	-	G	-
path				GH	GL	-	BB
personal			GH	GL	-	BB
private				GH	GL	-	BB
repository			GH	GL	-	BB
team				GH	-	-	-
url					-	-	G	-
username			-	-	-	BB
```

Global flags used in examples

```
branch				GH	GL	-	BB
private-key-file	-	-	G	-
ssh-hostname		GH	-	-	-
token-auth			GH	GL	-	BB
```

So, I plan to initially focus on the flags used in examples.
