### ISSUE TITLE
Mis-numbered List Item 9 as 8 in Getting Started Docs

### ISSUE THREAD

**Issue by sbernheim** [weaveworks/weave-gitops#271]
**Describe the bug**
List item 9 is mis-numbered as item 8 in the Getting Started documentation.

**Environment**
Getting Started documentation site https://docs.gitops.weave.works/docs/intro

**Affects versions**
v0.0.4-rc0

**To Reproduce**
1. Go to https://docs.gitops.weave.works/docs/getting-started/#getting-started-with-a-kind-cluster-and-podinfo-workload
2. Scroll down to list item 8
3. Observe that list item 9 is also numbered as list item 8.
4. Subsequent items items should also be incremented.

**Screenshots**
<img width="1339" alt="WeGo Getting Started Duplicate Item 8" src="https://user-images.githubusercontent.com/1707604/121212521-7078cf00-c84b-11eb-85e8-caed007ffe92.png">

**Additional context**
List item 10 starts within a mis-formatted block of fixed-width text ( see #270 )

**Comment by pzfreo** [comment]
Fixed! Thanks
