### ISSUE TITLE
Add some sort of design in how chip text is displayed

### ISSUE THREAD

**Issue by joshri** [weaveworks/weave-gitops#2725]
This is a follow up from #2714 

Right now chips display like `<column>:<value>`. Do we even want them to display in this way?

This pattern causes undefined values to display nothing - `<column>:` - how should we handle this case?

This is likely to cause us to either change up how the filters are passed to the ChipGroup, or create some overrides for the Mui chip component.

**Comment by JamWils** [comment]
@joshri why are values `undefined`?  Shouldn't there always be a "column"?

**Comment by joshri** [comment]
@JamWils Certain objects have fields which are allowed to be undefined like `tenant` or `channel`. The table and filter dialog displays these as `-` but the chips don't

**Comment by JamWils** [comment]
Thanks, what if we just put `category:null`?
