### ISSUE TITLE
Update dashboard commands for Pendo

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2771]
As a user, when I run `gitops run` or `gitops create dashboard` I should have the analytics of the helm chart set to the appropriate value based on my response to providing "feedback" when I first run a CLI command.

### Acceptance Criteria

GIVEN I run `gitops get config` and I see `analytics: true`

1. WHEN I run `gitops run` and I am asked whether to install the GitOps Dashboard THEN I should have the value WEAVE_GITOPS_FEATURE_TELEMETRY set to true.
2. WHEN I run `gitops create dashboard` THEN I should have the value WEAVE_GITOPS_FEATURE_TELEMETRY set to true. 
3. WHEN I run either of the above commands and I am unable to parse the config file THEN I should just set WEAVE_GITOPS_FEATURE_TELEMETRY to false.  The commands should not be interrupted.

The place to put this is under `values`, so it shows up as 
```
envVars:
  - name: WEAVE_GITOPS_FEATURE_TENANCY
    value: "true"
```

**Comment by katya-makarevich** [comment]
blocked by legal work

**Comment by opudrovs** [comment]
Based on @ozamosi 's suggestion, if the config cannot be read, the value of the telemetry key will be unset not "false".
