### ISSUE TITLE
ChipGroup styling on overflow

### ISSUE THREAD

**Issue by joshri** [weaveworks/weave-gitops#2784]
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/65822698/192038126-3a4126a8-1206-457e-8bc5-3eb3fe4b1800.png">

This marvelous screenshot contains a couple unfortunate bugs:
- a user can submit an empty input in the search input resulting in an empty chip (you can see this in the first chip)
- chip.search(filterSeparator) needs to be true before making the comparison between lengths. Lengths of 1 character return -1, which is equal to a false chip.search return (see cnull chip)
- Most egregious - ChipGroup is somehow allowed to push CheckboxActions and the search and filter buttons out of view. This is actually breaking some functionality of the app, although what you gain from having that many text filters active I do not know.

**Comment by JamWils** [comment]
cc @bia, I am adding this bug to the design board.

**Comment by bia** [comment]
@joshri why is the sync button in two places?

<img width="1624" alt="Screenshot 2022-10-05 at 12 59 58" src="https://user-images.githubusercontent.com/92439/194045375-2aca01db-6ddc-46a4-a193-b2239942201d.png">
