### ISSUE TITLE
Incorrect message from computeMessage function

### ISSUE THREAD

**Issue by joshri** [weaveworks/weave-gitops#2796]
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/65822698/192570666-3abbb8ea-fd2a-49a4-8177-82d8f117ed15.png">

This is displaying the message from the first conditions object (type `AbleToScale`) which has `status: "True"` instead of the second (type: `ScalingActive`) which has `status: "False"`. 

The `computeMessage` function is only looking for "Ready" and "Available" which can lead to an incorrect message. It should look for the message based on computeReady's ReadyType, and handle message for Ready, NotReady, and Reconciling.

**Comment by joshri** [comment]
<img width="2047" alt="image" src="https://user-images.githubusercontent.com/65822698/192886016-1712b044-a205-4f1e-bc0a-c7cc417a1a6d.png">

It gets weirder - CRDs in the reconciled objects table are showing the wrong status. Screenshot shows interesting conditions array with no failures and status is coming out as not ready

**Comment by joshri** [comment]
UPDATE sending out an 🆘 to @ozamosi @JamWils

Starting looking into this - the `computeMessage` function actually IS working as intended. It searches for the condition of type `Ready` and only uses that one. The problem with this is that both CRDs and HorizontalPodAutoscaler here don't have a condition of type `Ready`, so the function just returns false, which obviously does not tell the full story. 

Looking into a better way to process `conditions` didn't lead to great results - you can't rely on the order of the different conditions to signify importance, and although there is apparently a `phase` field on objects you're not supposed to use it? Maybe. Could be outdated. 

If ANY condition in the array has a status of "False" should that override everything else? I'm not entirely sure, although it seems like you'd rather know that one thing is failing than if three are succeeding.  Could this flip the other way, where you could have the Ready condition failing but things being fine overall? Users can even make their own conditions right? 

Maybe instead of `Not Ready` we display something like `<number> failing conditions` with the message column being able to display multiple messages.

**Comment by ozamosi** [comment]
`phase` is interesting - `phase` tells you what we're currently doing, but not whether we were successful at it or not. So `phase: running` doesn't mean that we _are_running, just that we've completed the previous phases - it could still mean that we're failing to run. So, it kinda tells you which condition to look at. But, not all object types have a phase.

> Users can even make their own conditions right?

Yes - each Kind can have their own states.

> If ANY condition in the array has a status of "False" should that override everything else?

If any condition has False (or Unknown), then I think it's reasonable to say it's not "ready". It doesn't mean it's failing - it could still be starting up, so reconciling - but that's what I'd like to see, yeah.

> Maybe instead of Not Ready we display something like <number> failing conditions with the message column being able to display multiple messages.

It's a good thought, but I'm a little concerned about what the variable row height would do when rolling things out - would it cause the whole table to move around like an accordion when you roll something out across large environments?
