### ISSUE TITLE
Should weave-gitops leaverage or integration with the flux terraform provider?

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#28]
Flux can be installed into an environment using terraform - see https://github.com/fluxcd/terraform-provider-flux

Should Weave GitOps also support this type of install?

**Comment by jpellizzari** [comment]
I would like to close this as out-of-scope for now. There may be a "Distribution" initiative in the future where we do things like this, along with marketplace integrations to make Weave GitOps more widely available to drive adoption.

**Comment by markramm** [comment]
There is a place for this in the future, but we need to have the core GitOps story for application developers in place first.
