### ISSUE TITLE
Interactively turn on pendo at first run

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#2843]
* On OSS the first time they run a command we ask them if we can turn on "analytics" to improve our product with a link to our documentation outlining what we collect.
* When they say "yes" we save that response in a config file somewhere along with a unique ID.
* On Enterprise, this shouldn't ask - it should just turn it on if it's the first run.

If the config file doesn't exist, it's assumed that means it's the first run.

The link to our documentation page (provided by @josefaworks ):
https://docs.gitops.weave.works/docs/feedback-and-telemetry/

**Comment by katya-makarevich** [comment]
blocked by legal work
