### ISSUE TITLE
GitOps Run create a CLI log forwarding mechanism

### ISSUE THREAD

**Issue by chanwit** [weaveworks/weave-gitops#2848]
GitOps Run log receiver is an important server-side component to help store logs on the server side.

A GitOps Run instance would printouts logs to the os.Stdout, os.Stderr, while sending a copy of logs to the log receiver simultaneously.

The receiver receives the logs, and stores them in RAM.

Out of scope:
The GitOps Run UI retrieves logs stored by the log receiver, re-styling each line of the logs, then displaying them on the UI - in real time.

**Comment by chanwit** [comment]
cc @ozamosi for the refinement.

**Comment by JamWils** [comment]
I think we should break this into two separate stories.  1. Abstracting the logger in our codebase and 2. Figuring out the log receiver.  The latter feels like we should use fluentd or fluentbit installed onto the vcluster.
