### ISSUE TITLE
Helm reference documentation update for admin username

### ISSUE THREAD

**Issue by nealf** [weaveworks/weave-gitops#2856]
**Describe the bug**

The Helm Reference in the [documentation](https://github.com/weaveworks/weave-gitops/blob/6b2c60c49c047ca292e35617bbeba3be31fff3f6/website/docs/references/helm-reference.md?plain=1#L18) says for `adminUser.username`: 

> Set username for local admin user, these will be stored in a secret in k8s. Requires `adminUser.create` and `adminUser.createSecret`. 

but the "requires adminUser.createSecret" doesn't seem to be true. When I was referencing these docs and using an externally managed secret (so `adminUser.createSecret: false`), I assumed I only needed to set the username in the secret I created. But as I discovered, the username value is referenced directly  in the [ClusterRoleBinding template](https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/templates/admin-user.yaml#L21-L24) and needs to be set in the chart if using something other than the default username value even if not having the chart create the secret.

I think removing that it requires `adminUser.createSecret` in the Helm reference is probably sufficient to make that more clear, but I haven't checked all of the guided documentation to see if it needs to be cleared up elsewhere. If that's all it is, could probably be added into [this other PR](https://github.com/weaveworks/weave-gitops/pull/2836) with a minor document change.

**Environment**

- Weave-Gitops Version - 0.9.6
- Flux Version - 0.35.0

**To Reproduce**

Just documentation

Thanks for the project!

**Comment by sympatheticmoose** [comment]
Hi @nealf - sorry this slipped, many thanks for raising - taking a look now!
