### ISSUE TITLE
gitops run doesn't accept failure to reconcile

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#2882]
When I 
* Write a bad error in my kustomization - in my case, one of the yaml documents my kustomization included started with `--` instead of `---` 🙈
* See that my pod isn't starting
* Use kubectl to figure out that my kustomization is incorrect
* Fix it
* Hit save

Then I expect gitops run to pick it up and reconcile the fix.

What instead happens is that I have to wait 5 minutes for a timeout to occur.

While on some level it's working as intended (5 minute timeout innit), as a user I am happy to wait 5 minutes for a process to complete, but I get unhappy when the process has already completed and we're just waiting 5 minutes to accept the result.

Could we make the watch process have a shorter timeout, even if the flux resource timeouts are still longer?

**Comment by chanwit** [comment]
Client-side YAML validation would be useful in this and similar scenarios.

**Comment by ozamosi** [comment]
Another example than a pure syntax error seems to be if I reference a chart that doesn't exist.

So yaml validation would be awesome, but I don't think that fully solves this problem.
