### ISSUE TITLE
Gitops run client-side yaml validation

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#2887]
Client-side YAML validation would be useful to stop gitops run trying to reconcile invalid yaml.

How would it be implemented - would it be annoying if it's constantly complaining? 

Workflow:

* changes detected
* run client-side validation with [1] (policies would also be used here)
  * passed -> upload to the bucket
  * failed -> say error messages
[1] - https://github.com/yannh/kubeconform

Pulled out of #2882

**Comment by chanwit** [comment]
Here's the logic we need to use.

https://github.com/fluxcd/flux2-kustomize-helm-example/blob/f74b89c4e23672e6bfaa9c0f204e57179d335173/scripts/validate.sh#L33-L52
