### ISSUE TITLE
Sidebar space for GitOps run

### ISSUE THREAD

**Issue by josefaworks** [weaveworks/weave-gitops#2895]
As a platform operator, I would like to have an area specific to runs so that I can easily access just this information with no distractions or clutter. I would like to be able to quickly jump into this page via the sidebar. 

This should be enterprise only.

Figma: https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?node-id=11227%3A53921

![Screen Shot 2022-10-17 at 9.07.41 AM.png](https://images.zenhubusercontent.com/6138b1b3d7038f238a0ab7fb/2b8d00b4-ca28-4425-a7ff-2223888fc530)

**Comment by ozamosi** [comment]
Please add link to figma
