### ISSUE TITLE
Filter and sort gitops run table

### ISSUE THREAD

**Issue by josefaworks** [weaveworks/weave-gitops#2899]
- [ ]  I would like to be able to filter the list of clusters on all of the columns in the table, except `duration`, `port forward` and `commands used` , so that i can find the information i’m looking for easily
- [ ]  I would like to be able to sort the list on all of the categories above, except `port forward` and `commands used` , so that i can find the information i’m looking for easily. I **should** be able to sort on `duration`. 

Note: this should be enterprise only
Figma link: https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?node-id=11227%3A53921

**Comment by joshri** [comment]
Completed in [#1916](https://github.com/weaveworks/weave-gitops-enterprise/pull/1916)

**Comment by joshri** [comment]
[#3021] also relevant (https://github.com/weaveworks/weave-gitops/pull/3021)
