### ISSUE TITLE
gitops run: If dev-ks never becomes healthy, then eventually it goes missing

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#2902]
If I:
 * Try to run gitops run against something broken - for example, point it at a directory with invalid yaml
 * Don't fix the reason it's breaking
 * Wait 5 minutes or so

Then the dev-ks will be completely deleted, and the only way to recreate it is to turn gitops run off and on again.

I expect that I will be able to work to fix the reason it's failing for as long as I want, and whenever I fix it, everything will start to work.

**Comment by JamWils** [comment]
In good news, I have left a "healthy" gitops run running for days and it still works when I come back :)

**Comment by opudrovs** [comment]
@chanwit cool!

**Comment by chanwit** [comment]
Fixed by #2970
