### ISSUE TITLE
gitops run: ctrl+c doesn't work during dashboard installation

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#2913]
76d7151d7 tried to make it so that hitting ctrl+c while part of the way through the dashboard installation would still clean up. However, if the dashboard installation gets stuck - for example if the port forward fails - then we're stuck with a process that is ignoring ctrl+c.

**Comment by ozamosi** [comment]
ctrl+c should terminate the process - no cleanup is performed, as we haven't finished installing onto the cluster yet.

**Comment by makkes** [comment]
closed by #3113
