### ISSUE TITLE
WGE GitOps CLI download link is hardcoded to linux and doesn't automatically update version

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2916]
https://docs.gitops.weave.works/docs/installation/#install-cli

**Comment by sympatheticmoose** [comment]
Unsure state of WGE CLI, draft PR there using the example from WG OSS if is of use to folks

**Comment by winniegakuru** [comment]
Did it work?
the only WGE cli I was able to install was on my local machine using `brew install fluxcd/tap/flux`

<img width="1161" alt="Screenshot 2022-11-23 at 10 35 26" src="https://user-images.githubusercontent.com/17796294/203493287-e1b9160a-2798-42c4-80eb-40820f83568c.png">

**Comment by sympatheticmoose** [comment]
Resolved by https://github.com/weaveworks/weave-gitops/pull/3067
