### ISSUE TITLE
gitops run: Context flag doesn't work when using sessions

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#2944]
When using the --context flag, I can't run gitops run with sessions.

The context flag should be applied to the user's local kubeconfig. It looks like it's being applied to the vcluster generated kubeconfig as well.

**Comment by josefaworks** [comment]
@ozamosi should we update this ticket with the no session decision made last week?

**Comment by JamWils** [comment]
This one is blocked on the flattening of the CLI package.  We are also looking at eliminating having multiple CLIs in the first place.  Once that final decision is made, the likely outcome is a single CLI then we will know how to proceed with fixing this.
