### ISSUE TITLE
support default password or decode password

### ISSUE THREAD

**Issue by willzhang** [weaveworks/weave-gitops#2949]
**Describe the bug**

support default password or decode password, the passwordhash can not be decode when weave-gitops as a public application 

**Environment**

- Weave-Gitops Version  
0.10.1
- Flux Version
- Kubernetes version
1.24.3

**To Reproduce**
```
root@node1# kubectl -n flux-system get secrets cluster-user-auth  -o yaml
apiVersion: v1
data:
  password: JDJhJDEwJFdoS01YQzdmQkZzc25lN2U5WWh6Y2VHR0JPWHVSVmEub0lIaXkxQ2tCc2s2dkloMmlJUXlD
  username: Z2l0b3BzLXRlc3QtdXNlcg==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: wego
    meta.helm.sh/release-namespace: flux-system
  creationTimestamp: "2022-10-30T08:04:00Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cluster-user-auth
  namespace: flux-system
  resourceVersion: "805791"
  uid: 69b50c83-a6ff-471c-af90-3cae23877a6c
type: Opaque
```
i package weave-gitops as an application, and let user auto install for themself ,but i must set password and it can not be skiped, this makes no one know what password it is
```
echo JDJhJDEwJFdoS01YQzdmQkZzc25lN2U5WWh6Y2VHR0JPWHVSVmEub0lIaXkxQ2tCc2s2dkloMmlJUXlD |base64 -d
```

**Expected behavior**

**Actual Behavior**

**Additional Context (screenshots, logs, etc)**

**Comment by chanwit** [comment]
Hi @willzhang 

Thank you for reporting this.

For security reasons, we will not support the default password nor the way to reverse it.
There's many ways to workaround this for example you can let your user generating a new HelmRelease object that contains a new hash password.

We also ship a command to help user generate hashed passwords on their own.

**Comment by willzhang** [comment]
is it possible skip password set when i run helm install ?

i have try not helm --set password but i got pod crashloopback.

**Comment by chanwit** [comment]
Please follow this guide:

https://docs.gitops.weave.works/docs/getting-started/#install-weave-gitops

where you'll see the following snippet for generating a Flux Helm Release object for the GitOps dashboard.

```bash
PASSWORD="<your password>"
gitops create dashboard ww-gitops \
  --password=$PASSWORD \
  --export > ./clusters/my-cluster/weave-gitops-dashboard.yaml
```

**Comment by chanwit** [comment]
Hi @willzhang 

did you manage to fix it on your side with the docs provided?

**Comment by willzhang** [comment]
1、i hope weave-gitops have a official default password, if i set password no one know what it is, but he can find it from weave-gitops official  installtation docs.

2、I package Weave gitops as an independent application. I don't use FluxCD to deploy Weave gitops.

**Comment by chanwit** [comment]
Thank you @willzhang for the feedback.

ping @JamWils @josefaworks

**Comment by ozamosi** [comment]
We will not add a default password - it would make it too easy to accidentally leave the default account on a public facing system, and suddenly you have a big security problem.

We will also not make the password recoverable - it would make it too easy to accidentally give someone the ability to read a password they shouldn't have access to.
