### ISSUE TITLE
Remove Sync button from above table in Source details view

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2952]
On the details view for a given source, the user is presented with two `Sync` action buttons which can cause confusion.

To simplify matters for now, we should remove the highlighted `Sync` above the table 
<img width="685" alt="button" src="https://user-images.githubusercontent.com/19860021/199059997-80ea6005-4a41-40b2-9c20-86959bf88806.png">

Question remains on whether we should additionally remove suspend and resume and have consistency with other details tables

**Comment by JamWils** [comment]
I really don't think we should do that until we get customer feedback showing that it is confusing.  There is also indicators on the UI that will show "blue" when they take an action, this should inform the user of what they have done.
