### ISSUE TITLE
show revision info for kustomizations

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2958]
Its very strange having the empty column, given the preceding column states the applied revision...

Would truncate as per status on `flux get kustomizations` i.e. `main/d7c6f21`

<img width="894" alt="Screenshot 2022-11-01 at 21 17 00" src="https://user-images.githubusercontent.com/19860021/199343366-597c7599-c0ea-450f-b994-a028195dc19e.png">

**Comment by jpellizzari** [comment]
@sympatheticmoose Confirming you want this as a column on the Kustomizations table? Like, on the list view?

**Comment by sympatheticmoose** [comment]
Correct 👍 already there on the details as "Applied Revision"

**Comment by jpellizzari** [comment]
Could not reproduce this after clearing cache with the latest `main`:

![Screenshot from 2022-11-17 10-13-00.png](https://images.zenhubusercontent.com/5a39a1308a75884b908bb1ea/aca85f50-19f5-4e7a-817a-88af40569119)
