### ISSUE TITLE
Ensure default cluster user role includes permissions for all core kubernetes resources

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2966]
**Problem**

Users sometimes hit issues where the Weave GitOps UI is not showing all reconciled objects for a given kustomization or helmrelease due to missing permissions, such as #2897.

**Solution**

Updated: 
We should wildcard "get", "list", "watch" to all resource, adding "patch" to the flux resources.

This change should occur for both OSS and Enterprise admin users.

**Comment by rparmer** [comment]
The list of rules is getting pretty extensive and looking through the UI I'm honestly not sure if any permissions can be removed without breaking wego-admin access.  Since this is an admin role it might be worth wildcarding `"get", "list", "watch"` to all resources and adding `"patch"` to the flux resources that need to be able to suspend/resume from the UI.  Thoughts?

**Comment by JamWils** [comment]
Yes, we should have a "read-only cluster admin" user that can "patch" applicable flux and flagger resources (including tf-controller, pipelines, if applicable).  

Can we also make sure this user is consistent for both OSS and Enterprise.  It is weird to have to switch paradigms when jumping from one version to the next.  

My expectation is if I go and use a third-party set of CRDs such as Agones, Crossplane, Contour, or Tekton that I do not need to adjust this default user.  I should see those resources appear in our app.

**Comment by jpellizzari** [comment]
> My expectation is if I go and use a third-party set of CRDs such as Agones, Crossplane, Contour, or Tekton that I do not need to adjust this default user. I should see those resources appear in our app.

My understanding is that this is not possible without enumerating all those  API groups/objects in the role. We cannot support every object without doing a `*` for `apiGroups`. 

We can limit the `verbs` for `*` to `get` and `list`, and reserve `patch` for Flux objects (I think). @JamWils @sympatheticmoose WDYT?

**Comment by JamWils** [comment]
Yeah, I think that sounds right.  I would double check the permissions just to make sure there aren't any odd ones outside of the Flux primitives.  E.g. does some other resource have "patch".  If so, why and do we keep it that way.
