### ISSUE TITLE
Add wego app list via UI

### ISSUE THREAD

**Issue by pzfreo** [weaveworks/weave-gitops#297]
**Short description**
As a wego user I want to list deployed apps so that I can manage my gitops environment.

`wego app list` will list deployed apps in the cluster. 

Applications list. 

Define what we show for each app, start with the name so folks can use it -- start with just the name.  On the UI you can click through to get an app status page with more details.   On the CLI you can use app status.

**Comment by jpellizzari** [comment]
Completed in #337
