### ISSUE TITLE
`gitops beta run` does not appear to work on an arm64 cluster

### ISSUE THREAD

**Issue by jbalonso** [weaveworks/weave-gitops#2971]
**Describe the bug**

When running `gitops beta run --no-session` on a hybrid amd64/arm64 (rpi4) k3s cluster, the `dev-bucket` deployment fails to "become ready". The root cause appears to be that `ghcr.io/weaveworks/gitops-bucket-server:$TAG` is not a multiarch manifest.

**Environment**

- Weave-Gitops Version `0.10.1`
- Flux Version: `v0.36.0`
- Kubernetes version `v1.24.6`

**To Reproduce**

1. Set the active `kubectl` context to a hybrid amd64/arm64 cluster with `fluxcd` already installed.
2. Enter a local directory with only a yaml for defining a namespace.
3. Run `gitops beta run --no-session --allow-k8s-context=$CONTEXT .`

**Expected behavior**

An active "gitops run".

**Actual Behavior**

Output of `gitops beta run --no-session --allow-k8s-context=$CONTEXT .` gets stuck on:

```
► Waiting for deployment dev-bucket to be ready ...
```

**Additional Context (screenshots, logs, etc)**

Output of `gitops beta run --no-session --allow-k8s-context=$CONTEXT .`:
```
► Checking for a cluster in the kube config ...
► Explicitly allow GitOps Run on kairos context
► Checking if Flux is already installed ...
► Getting Flux version ...
✔ Flux version v0.36.0 is found
► Checking if GitOps Dashboard is already installed ...
✔ GitOps Dashboard is found
► Request reconciliation of dashboard (timeout 5m0s) ...
✔ Dashboard reconciliation is done.
► Checking namespace dev-bucket ...
✔ Created namespace dev-bucket
► Checking service dev-bucket/dev-bucket ...
✔ Created service dev-bucket/dev-bucket
► Checking deployment dev-bucket/dev-bucket ...
✔ Created deployment dev-bucket/dev-bucket
► Waiting for deployment dev-bucket to be ready ...
^C^C✗ Max retry exceeded waiting for deployment to be ready
```

Evidence that the `dev-bucket` image was build for the wrong architecture:
```
$ kubectl logs -n dev-bucket dev-bucket-579fb5c685-8m297 
exec /gitops-bucket-server: exec format error
```

The tail of `kubectl describe pods -n dev-bucket`:
```
  Normal   Pulled     9m1s (x4 over 10m)  kubelet            Container image "ghcr.io/weaveworks/gitops-bucket-server@sha256:8fbb7534e772e14ea598d287a4b54a3f556416cac6621095ce45f78346fda78a" already present on machine
  Warning  BackOff    25s (x50 over 10m)  kubelet            Back-off restarting failed container
```

Evidence that `ghcr.io/weaveworks/gitops-bucket-server:$TAG` is not a multiarch manifest (yeah, I cheated by guessing `:latest`, but I recognized that the absolute reference to the image hash wasn't going to return a multiarch manifest):
```
docker manifest inspect ghcr.io/weaveworks/gitops-bucket-server:latest
# output shows a list of layers rather than a list of manifests
```

**Comment by chanwit** [comment]
Thank you so much for reporting this @jbalonso

We will take a look into it shortly!

**Comment by katya-makarevich** [comment]
blocked on @JamWils

**Comment by JamWils** [comment]
Creating the OSS project `gitops-bucket` could resolve this issue.  We don't have an ARM64 binary for bucket which is preventing us from doing this.

**Comment by thebearingedge** [comment]
Is this something that the maintainers would like done? If there's any plan or work that's needed, I'd like to help work on it 🚀

**Comment by LappleApple** [comment]
Hi all: We're deprecating this feature to focus on other opportunities that will bring value to WeGO users. Thanks so much for your interest!
