### ISSUE TITLE
wego gitops uninstall

### ISSUE THREAD

**Issue by pzfreo** [weaveworks/weave-gitops#298]
**Short description**
As a wego user (Cluster SRE) I want to uninstall wego from a cluster so that I can clean up.

Process for deleting apps would be to delete each app, (pipe the list of apps to wego app delete) then uninstall. 

Basically just call flux uninstall and remove the app custom resources from the cluster.

**Acceptance criteria**
`wego gitops uninstall` should remove all parts of wego from the currently defined cluster, but should NOT delete all apps.

**Comment by palemtnrider** [comment]
Does this 
* Delete the applications from the cluster previously installed via `wego app add`?
* Remove the GitOps automation for all applications targeted to this cluster? i.e., Open PRs to where the application GitOps runtimes were installed - which could be multiple repositories

**Comment by markramm** [comment]
Wego uninstall should:  

Remove the gitops runtime from the cluster.   It should have a flag which removes the running apps as well. 

One use case is a step in the process of bringing up a new cluster and migrating workloads to that cluster.

**Comment by markramm** [comment]
Just call flux uninstall and remove the app custom resource definition from the cluster.
