### ISSUE TITLE
support for `-n` flag for `--namespace`

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2982]
**Problem**

Typing is hard. The `gitops` command doesn't have an abbreviated version the `--namespace` flag.

**Solution**

We should support `-n` (as I believe we used to), the lack of support feels jarring when also using flux/kubectl.

**Additional context**

**Comment by yitsushi** [comment]
Support `-n` flag where? Which repo and command?

**Comment by makkes** [comment]
Added some context from what I assumed is meant here. @sympatheticmoose please let me know if that's what you meant.

**Comment by sympatheticmoose** [comment]
yup - global flag on the gitops cli
