### ISSUE TITLE
Support for custom groups claim

### ISSUE THREAD

**Issue by eloo** [weaveworks/weave-gitops#2993]
**Problem**
Using OIDC with group impersonate is currently not working when custom group claims are used. 
Only the  default groups claim is hardcoded right now and thus providers like Auth0 are not working. 

**Solution**
Make the claim name which is used to obtain groups configurable

**Comment by chanwit** [comment]
Thank you @eloo for reporting this. We'll take a look at this issue shortly.

**Comment by antonyquant123** [comment]
@bigkevmcd @foot - thoughts?
