### ISSUE TITLE
ID Token not verified from cookie causes RateLimits

### ISSUE THREAD

**Issue by eloo** [weaveworks/weave-gitops#2994]
**Describe the bug**

Hi, i'm trying to get the OIDC setup running properly but it seems that there is an issue with the tokens in cookie storage.
Right now the order which cookie is verifies is hardcoded to `access_token`, `id_token`.
Using auth0 the access_token can not be used because it contains a different (non-valid) schema but the id_token could be used but only the first one is taken into account.

Nevertheless also when the correct token would be read from the cookies is could not get verified in the userinfo code because https://github.com/weaveworks/weave-gitops/blob/main/pkg/server/auth/server.go#L379 only the HMAC verifier is present.
This result in a call to the userinfo endpoint of the oidc provider everytime. 

In general this is going to work. But its creating a lot of unnecessary requests against the oidc-provider and in the case of Auth0 the rate limit is kicking in and make the UI unusable.

So i guess the best would be to add the correct verifiers to the userinfo code so the token from the cookies can be used. 

**Environment**

- Weave-Gitops Version: 0.10.1

**To Reproduce**

- Configure oidc with auth0
- Click around in the ui or call .../oauth2/userinfo multiple times
- You will se 429 in logs and you will be logged out of the ui

**Expected behavior**

IdToken from cookie is used

**Actual Behavior**

Everytime userinfo is called a request against the oidc-provider is made

**Additional Context (screenshots, logs, etc)**

**Comment by chanwit** [comment]
Thank you again @eloo for reporting this issue!
We'll take a look at it shortly.
