### ISSUE TITLE
SPIKE: Decide whether/how to flatten the CLI package

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#3003]
Follow up to #2946. That approach doesn't work for sharing with enterprise. What should we do instead?

We are increasing the scope of this spike.  From a product perspective, it was a mistake to have two different CLIs (one for OSS and one for Enterprise).  We want to understand the impact of eliminating the OSS-only CLI and what that means for the workflow.

The structure of the `cmd` packages.  We have a lot of duplicate code because of how the packages are structured.  We want to look at copying Flux's pattern.

Timebox: 2-3d

**Comment by yiannistri** [comment]
The decision of having 2 CLIs vs 1 is impacted by the ongoing discussion to merge the 2 repos. Therefore I would keep this issue focused to the structure of the CLI instead and how it can be improved.

**Comment by LappleApple** [comment]
Blocked by repo merge conversations
