### ISSUE TITLE
TF Plan - Add Plan tab contents

### ISSUE THREAD

**Issue by josefaworks** [weaveworks/weave-gitops#3013]
As a user, I would like to go to the `plan` tab to see my TF plans so that I can easily understand the changes that have been made. 
- [ ] The code in the `plan` tab should be color coded to designate what will be created, destroyed, and updated. Green text indicates new, yellow text indicates updates, and red text indicates deletion
- [ ] I still need to be able to access the  sync and suspend buttons when this tab is selected 

Mockups available here: https://github.com/weaveworks/weave-gitops-enterprise/issues/1829#issuecomment-1313604122

**Comment by ozamosi** [comment]
* Add endpoint for plan retrieval
* The endpoint should return a string.
* We don't have color information, so we have to figure out how to colorize the output. TODO: find out if we can use a terraform library that colorizes the output.

**Comment by opudrovs** [comment]
@josefaworks 
Moved creating the Plan button to a separate issue:
https://github.com/weaveworks/weave-gitops/issues/3238
