### ISSUE TITLE
Terraform docs should reference feature flag in WGE helm chart

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#3030]
The enterprise dashboard for Weave GitOps Enterprise needs to be explicitly enabled by users with the `enableTerraformUI` flag in the WGE Helm Chart. The documentation doesn't currently explain this step as far as I can see.

**Comment by JamWils** [comment]
It is turned on by default, we need to update the documentation for the enterprise helm chart in general.
