### ISSUE TITLE
docs/installation: explain username and passwordHash

### ISSUE THREAD

**Issue by dholbach** [weaveworks/weave-gitops#3036]
The docs under "Install the Helm Chart" currently say:

> Weave GitOps is provided through a Helm Chart and installed as a Flux resource through a `HelmRepository` and `HelmRelease`. To install on your cluster, adjust the following so that `username` is the username you want and `passwordHash` is a bcrypt hash of your password, and commit the file to the location bootstrapped with Flux so that it is synchronized to your Cluster.

This could be a bit more user-friendly - or provide an example. I'm not quite sure what needs to go in there. Which user, which password, how to bcrypt?

**Comment by Callisto13** [comment]
this is done and will also be tidied in https://github.com/weaveworks/weave-gitops/pull/3373
