### ISSUE TITLE
Avoid creating duplicate deploy keys

### ISSUE THREAD

**Issue by jrryjcksn** [weaveworks/weave-gitops#305]
**Short description**
As a wego user I would like to avoid a buildup of deploy keys within a repository if I perform multiple `app add`s in a single repository

**Acceptance criteria**

**Given** a cluster with wego installed
**When** I `wego app add` more than one application within a single repository
**Then** I would like to only have one wego deploy key associated with the repository

**Comment by markramm** [comment]
Name is unique already.
