### ISSUE TITLE
abandon the idea of versioning the docs

### ISSUE THREAD

**Issue by dholbach** [weaveworks/weave-gitops#3051]
> This is part of the reason why I recommend we abandon the idea of versioning the docs as it would free us a lot more.

_Originally posted by @sympatheticmoose in https://github.com/weaveworks/weave-gitops/issues/3039#issuecomment-1324884061_

**Comment by dholbach** [comment]
Maybe it'd help to just have `stable` and `next`, so there's no need to have a big archive of URLs you need to maintain forever.

**Comment by sympatheticmoose** [comment]
Also see - https://docusaurus.io/docs/versioning where docusaurus itself advises against versioning unless you really need it

**Comment by Callisto13** [comment]
at the very least we should draw a line on how many versions we keep live

**Comment by morancj** [comment]
I'm torn on this. Originally, I'd agree with removing or minimising versioning. However, having access to the docs as they were for a previous release is useful.

NB: the linked docusaurus page states
> Versioning is best suited for websites with high-traffic and **rapid changes to documentation** between versions

(emphasis mine)
Which I think is true for these docs.

**Comment by morancj** [comment]
https://docusaurus.io/docs/2.2.0/docs-multi-instance#versioned-and-unversioned-doc

> ## Versioned and unversioned doc
> Sometimes, you want some documents to be versioned, while other documents are more "global", and it feels useless to version them.
> 
> We use this pattern on the Docusaurus website itself:
> 
> The [/docs/*](https://docusaurus.io/docs) section is versioned
> The [/community/*](https://docusaurus.io/community/support) section is unversioned

**Comment by Callisto13** [comment]
Linking some slack conversations so all context is here:
- https://weaveworks.slack.com/archives/C04KNEME4AJ/p1676468028655599
- https://weaveworks.slack.com/archives/C04KNEME4AJ/p1676437989871869
- https://weaveworks.slack.com/archives/C04KNEME4AJ/p1674737333819449

**Comment by Callisto13** [comment]
I am closing this as we have decided that we need them for now.
In a year we should reassess, and a new ticket can be opened then.
