### ISSUE TITLE
docs: consider breaking out the CLI installations into a separate page

### ISSUE THREAD

**Issue by dholbach** [weaveworks/weave-gitops#3052]
Personally I would also break out the CLI installations into a separate page

_Originally posted by @sympatheticmoose in https://github.com/weaveworks/weave-gitops/issues/3039#issuecomment-1324887551_

**Comment by dholbach** [comment]
In #3039 I said:

>If anyone would like to take a crack at breaking out the CLI installations, sure that WFM. I just wasn't sure about it as it'd be a separate flow for WG vs WGE, right?

**Comment by Callisto13** [comment]
Closing this as nobody has context on what was actually wanted. If someone wants to reopen with crystal clear detail on outcomes, please go ahead
