### ISSUE TITLE
This is an issue on WG OSS created by a github account which is not part of the WW org

### ISSUE THREAD

**Issue by lizwarner** [weaveworks/weave-gitops#3065]
Hello Team

**Describe the bug**

**Environment**

- Weave-Gitops Version
- Flux Version
- Kubernetes version

**To Reproduce**

**Expected behavior**

**Actual Behavior**

**Additional Context (screenshots, logs, etc)**

**Comment by makkes** [comment]
I assume we don't need this, anymore. Please re-open if it's still the case.
