### ISSUE TITLE
WeGO --url flag cannot recognize git repository

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#308]
**Describe the bug**
The `wego app add --url` command cannot recognize a git repository and is failing to initialize user-specified repository.

**Environment**
 - wego: [v0.0.5]

**To Reproduce**
1. Download `wego` binary
2. Run `wego install`
3. Run `wego app add --url=<git-url>`

**Expected behavior**
Wego tries to use the specified url, but fails to recognize it as a git repo

**Screenshots**
![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/0b83e230-a121-42b9-8e06-c94d677b0fbb)

**Comment by palemtnrider** [comment]
Currently, we require a local clone to write the GOAT files into. We are defaulting the path to "./" which is why this passes our check.  We need to inform the user to pass the clone dir

**Comment by markramm** [comment]
If we have both, and the current directory is not a checkout from that URL, it should print a warning, or provide an error. 

What happens to the checkout if you are already in another git clone?
