### ISSUE TITLE
adminUser passwordSecret

### ISSUE THREAD

**Issue by cdenneen** [weaveworks/weave-gitops#3097]
The install documentation recommends using something like SOPS or similar rather than using the default PASSWORD hash.
The issue is the chart doesn't provide an option to pass along the secret name to use.

So for example create a admin-dashboard-secret this would need to be able to be passed to the HelmRelease in place of adminUser.passwordHash ... so something like adminUser.passwordSecretName ?

**Comment by sympatheticmoose** [comment]
Hi @cdenneen https://docs.gitops.weave.works/docs/configuration/securing-access-to-the-dashboard/#login-via-a-cluster-user-account this page should help, we look for a secret called `cluster-user-auth` in the namespace where Weave GitOps is installed - which should contain the username and password for logging into the dashboard. We could certainly improve the documentation for Install to reference this more clearly.
