### ISSUE TITLE
Buggy OIDC

### ISSUE THREAD

**Issue by hakuno** [weaveworks/weave-gitops#3099]
**Describe the bug**

I can login with admin user. But I cannot login through OIDC provider. In this case, Google OAuth2.

**Environment**

- Weave-Gitops Version 0.11.0
- Flux Version 0.33.0
- Kubernetes version 1.23

**To Reproduce**

If I create the `oidc-auth` secret as

```
kubectl create secret generic oidc-auth \
  --namespace flux-system \
  --from-literal=clientID="" \
  --from-literal=clientSecret=""
  --from-literal=redirectURL="https://site.com/oauth2/callback" \
```

The web returns

```
{"message":"oidc provider not configured","code":400}
```

with these logs

```
022-12-01T16:51:29.691Z	ERROR	gitops.auth-server	auth/server.go:373	Failed to get cookie from request	{"error": "http: named cookie not present"}
2022-12-01T16:51:29.691Z	INFO	gitops	middleware/middleware.go:61	request error	{"uri": "/oauth2/userinfo", "status": 400}
2022-12-01T16:51:36.282Z	ERROR	gitops.auth-server	auth/server.go:373	Failed to get cookie from request	{"error": "http: named cookie not present"}
2022-12-01T16:51:36.282Z	INFO	gitops	middleware/middleware.go:61	request error	{"uri": "/oauth2/userinfo", "status": 400}
2022-12-01T16:51:37.794Z	INFO	gitops	middleware/middleware.go:61	request error	{"uri": "/oauth2?return_url=https%3A%2F%2Fsite.com", "status": 400}
2022-12-01T16:51:37.998Z	INFO	gitops	middleware/middleware.go:61	request error	{"uri": "/favicon.ico", "status": 404}
2022-12-01T16:51:40.467Z	ERROR	gitops.auth-server	auth/server.go:373	Failed to get cookie from request	{"error": "http: named cookie not present"}
2022-12-01T16:51:40.467Z	INFO	gitops	middleware/middleware.go:61	request error	{"uri": "/oauth2/userinfo", "status": 400}

```

If I create the `oidc-auth` secret as

```
kubectl create secret generic oidc-auth \
  --namespace flux-system \
  --from-literal=clientID="" \
  --from-literal=clientSecret=""
  --from-literal=redirectURL="https://site.com/oauth2/callback" \
  --from-literal=issuerURL="https://site.com"
```

The deployment break down with

```
Error: could not initialise authentication server: could not create auth server: could not create provider: oidc: failed to decode provider discovery object: expected Content-Type = application/json, got "text/html; charset=utf-8": invalid character '<' looking for beginning of value
```

**Expected behavior**

No error log. Successful OIDC login.

**Actual Behavior**

The OIDC is failing.

**Additional Context (screenshots, logs, etc)**

**Comment by hakuno** [comment]
There's other OIDC open issues like https://github.com/weaveworks/weave-gitops/issues/2955

Please, any tip?

**Comment by bigkevmcd** [comment]
@hakuno In the first case, you're not providing an issuerURL, and in the second, it looks like you're not providing a valid issuer URL?

For Google OIDC, I think you want `https://accounts.google.com`

**Comment by bigkevmcd** [comment]
You will need to provide a client id/secret keypair too

**Comment by hakuno** [comment]
Thanks, @bigkevmcd 

It has both `clientID` and `clientSecret`. But I omitted for security.

I changed the `issuerURL` as you said.

Now I've got new problems.

```
Error 400: invalid_scope
Some requested scopes were invalid. {valid=[https://www.googleapis.com/auth/userinfo.profile, openid, https://www.googleapis.com/auth/userinfo.email], invalid=[groups]}
```

**Comment by hakuno** [comment]
How can I solve this?

It says the `groups` is invalid in scope. I tried to add some, but no success yet.

**Comment by bigkevmcd** [comment]
@hakuno I think Google's OIDC API doesn't provide the "groups" scope, I can recommend Dex, which will get the groups via an API call https://dexidp.io/docs/connectors/google/

We will also change it to allow you to not request the "groups" scope.

**Comment by hakuno** [comment]
hmm I can't count on this feature by now.

Even if I deploy Dex, so I'd need a special service account with `Domain-Wide Delegation` as told.

I hope to see this improvement sooner. Thanks!
