### ISSUE TITLE
Programmatically create WeGO Git Repository

### ISSUE THREAD

**Issue by jrryjcksn** [weaveworks/weave-gitops#31]
Configuring an application in wego can require creating a repository (if an existing repository is not specified). The new repository should have the structure currently being defined for wego applications (TBD).

We should be able to create repositories via `clone` or `fork`.

**Comment by josecordaz** [comment]
I'll be using go-git-providers for to interact with repositories api's. I added the corresponding issue https://github.com/fluxcd/go-git-providers/issues/72.

**Comment by josecordaz** [comment]
It seems there is some work still in progress to support bitbucket in go-git-providers:

- https://github.com/fluxcd/go-git-providers/issues/29 
- https://github.com/weaveworks/product-management/issues/41 
- https://github.com/fluxcd/go-git-providers/pull/70.

I'll add only `github` and `gitlab` support for now.

**Comment by josecordaz** [comment]
PR ready https://github.com/fluxcd/go-git-providers/pull/74
