### ISSUE TITLE
Clicking on an object in a details table results in error

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#3103]
**Describe the bug**

When I click for details on an Alert, the object type is `undefined` and therefore breaks the UI

<img width="1458" alt="Screenshot 2022-12-02 at 09 46 57" src="https://user-images.githubusercontent.com/19860021/205264619-e80ae075-c354-4d77-b39b-8792d8fbe551.png">

The URL shows as: `https://dashboard/kustomization/undefined?clusterName=Default&name=on-call-webapp&namespace=flux-system`

<img width="1476" alt="Screenshot 2022-12-02 at 09 47 03" src="https://user-images.githubusercontent.com/19860021/205264629-b9afea58-e9e2-4bed-a255-14a3a431431a.png">

**Environment**

- Weave-Gitops Version 0.11.0
- Flux Version 0.36.0
- Kubernetes version

**To Reproduce**

**Expected behavior**

I don't believe we have details pages for alerts, so should just be the yaml output as you can get from the notifications view
<img width="1146" alt="Screenshot 2022-12-02 at 09 53 02" src="https://user-images.githubusercontent.com/19860021/205265681-1e76c302-4e43-4652-8cc8-1efb4fd6f892.png">

**Actual Behavior**

broken

**Additional Context (screenshots, logs, etc)**

**Comment by JamWils** [comment]
This happens for almost all objects on that page, I have now seen it with `Terraform`, `Alert`, and `GitOps Templates`.  If there is an actual detail page in Weave GitOps then the user should be taken to that detail page when they click on a link.

**Comment by TheGostKasper** [comment]
[Obj value](https://github.com/weaveworks/weave-gitops-enterprise/blob/main/ui-cra/src/components/Applications/Kustomization.tsx#L99) Resolver of the LinkResolverProvider  is set by default to the `kind` so this will always having a `kind` if we didn't set a value instead like her in [Link](https://github.com/weaveworks/weave-gitops/blob/main/ui/components/ReconciledObjectsTable.tsx#L74)

#### ReconciledObjectsTable.tsx
```
   const resolved = resolver && resolver(u.type, params);
        return kind || resolved ? (
                <Link  to={resolved || formatURL(objectTypeToRoute(kind), params)} >
                  {u.name}
                 </Link>
```

### In WGE WGApplicationsKustomization
```
 <LinkResolverProvider
          resolver={(obj, params) => {
            const resolved = resolveLink(obj, {
              clusterName: params.clusterName,
              namespace: params.namespace,
              name: params.name,
            });
            return resolved || '';
          }}
        >
```

@jpellizzari this what i mentioned in the standup

**Comment by jpellizzari** [comment]
Could be this?: https://github.com/weaveworks/weave-gitops/pull/3112
