### ISSUE TITLE
Simplify resource creation/modification with GitOps Run

### ISSUE THREAD

**Issue by makkes** [weaveworks/weave-gitops#3104]
We should have a look at leveraging the [Flux SSA](https://pkg.go.dev/github.com/fluxcd/pkg/ssa) package for creating the Kubernetes resources. This should lead to less code and more opportunities, e.g. to update already existing resources.

**Comment by chanwit** [comment]
We tried at least a couple of time to adopt SSA for applying resources, but with not very good results with the Flux internal package.

It's really great to see that you bring this up again. We will definitely be able to move things forward.

**Comment by makkes** [comment]
I played with it again today and it looked pretty promising.

**Comment by chanwit** [comment]
Ping @josefaworks for further refinement.

**Comment by JamWils** [comment]
@makkes can you provide some additional info in the description so I can fully understand the scope of server-side apply.  Or is this intended to be a spike?
