### ISSUE TITLE
Wego version should report version from the flux binary

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#311]
**Short description**
As an app developer I want to verify the version of flux installed in my wego environment so that I know which version is actually installed.

**Acceptance criteria**
**given** wego is installed
**when** issuing `wego version`
**then** the version from `flux -v` is displayed along with the wego software version info

**when** issuing `wego version` and I've replaced the flux binary under $HOME/.wego/bin
**then** the version from `flux -v` is displayed along with the wego software version info

**when** issuing `wego version` and I've removed the flux binary under $HOME/.wego/bin
**then** an error is displayed regarding the missing binary

**when** issuing `wego version` and I've replaced the flux binary under $HOME/.wego/bin with one that isn't for my OS/arch
**then** an error is displayed regarding the invalid binary

**Comment by markramm** [comment]
Flux version in code shown now, binary itself is not listed.
