### ISSUE TITLE
Suggestion: update issue templates to reduce comment confusion

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#3122]
Our issue templates contain a lot of comment block sections to try and guide users into giving sufficient context to help us fix a bug or understand the feature request. 

The templates are arguably overloaded and complex so often sections are omitted anyway, or worse folks can get confused and add content into the comment blocks so the issue appears empty. 

We could adopt an approach similar to [podman desktop](https://github.com/containers/podman-desktop/issues/new?assignees=&labels=kind%2Ffeature&template=feature_request.yml)

I think we would just have to be lenient in which sections are required vs optional so that it isnt _too_ restrictive for users.

If supportive of this change please 👍 if concerned 👎 and comment. 

Will leave this for a week or so before making changes as it's not urgent.

**Comment by LappleApple** [comment]
Closing due to age and lack of activity/response.
