### ISSUE TITLE
Add automation and documentation for building gitops-bucket-server image

### ISSUE THREAD

**Issue by makkes** [weaveworks/weave-gitops#3123]
The gitops-bucket-server used by GitOps Run is currently built and pushed manually by an engineer. There is a [Make target](https://github.com/weaveworks/weave-gitops/blob/4c6fc605c2e4556aae143a7855862dfd79ba7673/Makefile#L155) in place for doing this but we need to automate and document that process.

TBD:

- what should the trigger be for building/pushing the image?

**Comment by LappleApple** [comment]
@makkes Is this still relevant? Is it something to include in the user guide?

**Comment by makkes** [comment]
> @makkes Is this still relevant? Is it something to include in the user guide?

As far as I know this hasn't been fixed, yet. Pulling in @chanwit here as I'm no longer working on this code.

**Comment by LappleApple** [comment]
Closing due to change of plans for this feature.
