### ISSUE TITLE
[Spike] Investigate potential release process improvements

### ISSUE THREAD

**Issue by katya-makarevich** [weaveworks/weave-gitops#3157]
# Goal

Make releasing a new version of Weave GitOps more resilient and as easy as pushing a new tag.

# Motivation

* Currently, the release process involves several manual steps which is inconvenient in particular as we want to up our release cadence.
* While the release PR's CI checks are running, no other PR can be merged to not interfere with the releasing. This is error-prone.
* #3229

# Potential Ideas

* simplify watching over the release process (hopefully fixing the tests and merging PRs during the release process will help with that).
* aadd either automatic guards agains merging PRs during the release process or, if possible, take a "snapshot" of the repo to release it and allow merging PRs after that.

# Timebox

2-3 days

**Comment by makkes** [comment]
Notes from the investigation (these will be updated as I move forward):

# Goals

1. Eliminate need for a long-running release PR

|Suggestion|Goal|Explanation|
|----------|----|-----------|
|The released chart manifests don't need to be stored in `main`. They can be built on the fly from a tag.|1|This removes one item to be modified from the PR that's created for a release.|
