### ISSUE TITLE
Tie default graph zoom level to window size

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#3167]
**Problem**

When viewing the Graph tab on a kustomization or helmrelease details page on a large window, the default zoom level of 85% renders objects in a jarringly large as shown below
<img width="3189" alt="Screenshot 2022-12-16 at 18 11 46" src="https://user-images.githubusercontent.com/19860021/208162383-0416afce-25de-4ba9-b9f6-3087fdd27f5e.png">

However on small windows it is perfectly reasonable
<img width="1253" alt="Screenshot 2022-12-16 at 18 13 49" src="https://user-images.githubusercontent.com/19860021/208162489-c32a1fd4-63c4-42b9-8126-ca55bf938990.png">

**Solution**

Take into account the window size when setting the default zoom level when a user navigates to that page.

**Additional context**

There could be a number of other solutions to this problem. The proposed solution is purely based on observed current behaviour.

**Comment by TheGostKasper** [comment]
We may set the default zoom level based on the (aspect ratio or width) of the screen  as if width > 1300 then default zoom set to 50% .
Or maybe we set max-width for the content page itself to 1300 (for example) and center the content :thinking:

**Comment by joshri** [comment]
Maybe we have a happy medium if we just set default zoom to 70? If we can avoid additional calculations we definitely should - regardless, whatever we change we have to make sure it makes it into `DirectedGraph` as well as `DagGraph` and make sure the issue is the same on each

**Comment by yiannistri** [comment]
@joshri how much effort do you estimate this fix will take?
