### ISSUE TITLE
gitops run - gather all logs from vcluster

### ISSUE THREAD

**Issue by katya-makarevich** [weaveworks/weave-gitops#3176]
Here are possible tasks:

- Install and configure Fluent-Bit to collect logs from all pods in the VCluster, and configure dev-bucket credentials for Fluent-Bit to allow it to access the the dev-bucket.
- Set up a new bucket to store the collected logs (in addition to the current two buckets)
- Write an API that allows users to retrieve logs by pod name and namespace.
- Document the system and API for other users and maintainers.

#### Optional
- Consider the storage type (disk or memory) and log retention policy for the S3 bucket. (Optional: we can use in-memory setting as is)

# Sub-tickets
- [ ] #3267 
- [ ] #3268 
- [ ] #3269 
- [ ] #3270

**Comment by chanwit** [comment]
Tech notes from the Spike: https://github.com/weaveworks/weave-gitops-enterprise/issues/2034

**Comment by makkes** [comment]
blocked by #3195

**Comment by chanwit** [comment]
@katya-makarevich we don't need this to be an EPIC anymore as @josefaworks added all sub-tickets of it to the GitOps Run UI EPIC.
