### ISSUE TITLE
Flaky test when running curl to a Flux URL

### ISSUE THREAD

**Issue by opudrovs** [weaveworks/weave-gitops#3197]
I ran into the following flaky test several times yesterday (network issues?).

Sample run:
https://github.com/weaveworks/weave-gitops/actions/runs/3762703203/jobs/6395638535

```
Run curl -s https://fluxcd.io/install.sh | sudo bash
  curl -s https://fluxcd.io/install.sh | sudo bash
  shell: /usr/bin/bash -e {0}
  env:
    CI_CONTAINER_REGISTRY: europe-west1-docker.pkg.dev
    CI_CONTAINER_REPOSITORY: europe-west1-docker.pkg.dev/weave-gitops-clusters/weave-gitops
    GOROOT: /opt/hostedtoolcache/go/1.19.4/x64
[INFO]  Downloading metadata https://api.github.com/repos/fluxcd/flux[2](https://github.com/weaveworks/weave-gitops/actions/runs/3762703203/jobs/6395638535#step:5:2)/releases/latest
Error: Process completed with exit code 22.
```

<img width="1491" alt="Screenshot 2022-12-23 at 22 12 38" src="https://user-images.githubusercontent.com/8824708/209405985-a6cb168b-7212-4997-b9f6-eb0f4aab6902.png">

After restarting the test, it succeeds.

**Comment by makkes** [comment]
Some more detail on return code 22 from curl's manpage:

>        22     HTTP page not retrieved. The requested URL was not found or returned another error with the HTTP error code being 400 or above. This return code only appears if -f, --fail is used.

Maybe the request is subject to rate limiting on GitHub's side.

**Comment by chanwit** [comment]
Would it be ok to sleep and retries?

**Comment by opudrovs** [comment]
@kingdonb I have not seen the current issue for a while.

Is it possible that it has been fixed after the following or a similar issue was fixed?
https://github.com/fluxcd/flux2/issues/3509

**Comment by kingdonb** [comment]
You do, if you want it to return OK and not get rate limited – all anonymous clients [will eventually get rate limited](https://github.com/fluxcd/flux2/issues/3509#issuecomment-1400820992) by GitHub's API, and your usage is considered in a block with every other runner from your same IP address, (so if you are on a hosted runner it's much worse than flaky.)

**Comment by opudrovs** [comment]
@kingdonb great, thank you for the info and the links! ✨
