### ISSUE TITLE
"gitops beta run" reports error

### ISSUE THREAD

**Issue by pfcurtis** [weaveworks/weave-gitops#3201]
**Describe the bug**
The "gitops beta run ./podinfo --no-session --port-forward namespace=dev,resource=svc/dev-podinfo,port=9898:9898" reports the following error:
✔ Setup Bucket Source and Kustomization successfully
Error: error walking path: open /Users/pcurtis/.Trash: operation not permitted

**Environment**

- Weave-Gitops 0.13.0
- Flux Version 0.37.0
- Kubernetes version 1.25.3

**To Reproduce**
https://docs.gitops.weave.works/docs/gitops-run/get-started/#set-up-gitops-run

**Expected behavior**

No errors when following the documentation exactly.

**Actual Behavior**

Error message reported ... not able to determine state or ways to fix.

**Additional Context (screenshots, logs, etc)**

**Comment by pfcurtis** [comment]
Additional Context: the example podinfo never syncs.

<img width="981" alt="Screen Shot 2022-12-27 at 11 34 20" src="https://user-images.githubusercontent.com/2014686/209695104-70d0098a-f9cd-4f75-b462-f3f4593bd3c5.png">

**Comment by chanwit** [comment]
Hi @pfcurtis 

In which dir you're running the command?

**Comment by pfcurtis** [comment]
I ran the command both from my home directory and a sub-directory. I'm following the documentation listed above.

**Comment by pfcurtis** [comment]
```
Paul--WeaveWorks:gitops-test pcurtis$ kubectl get pods -A
NAMESPACE            NAME                                         READY   STATUS    RESTARTS      AGE
flux-system          helm-controller-7b85c84687-vxrtx             1/1     Running   1 (65s ago)   36m
flux-system          kustomize-controller-d88d76876-pcl68         1/1     Running   1 (65s ago)   36m
flux-system          notification-controller-55df97fbb9-fzk8g     1/1     Running   1 (65s ago)   36m
flux-system          source-controller-5bb5c7b9bd-zxtl6           1/1     Running   0             11s
flux-system          ww-gitops-weave-gitops-7d5cf4ddbf-c2drb      1/1     Running   1 (65s ago)   31m
gitops-run           run-dev-bucket-795bfcfdb6-vb9fh              1/1     Running   1 (65s ago)   35m
kube-system          coredns-565d847f94-bmgvc                     1/1     Running   1 (65s ago)   37m
kube-system          coredns-565d847f94-w25mt                     1/1     Running   1 (65s ago)   37m
kube-system          etcd-kind-control-plane                      1/1     Running   1 (65s ago)   38m
kube-system          kindnet-8kt88                                1/1     Running   1 (65s ago)   37m
kube-system          kube-apiserver-kind-control-plane            1/1     Running   1 (65s ago)   38m
kube-system          kube-controller-manager-kind-control-plane   1/1     Running   1 (65s ago)   38m
kube-system          kube-proxy-8jgcp                             1/1     Running   1 (65s ago)   37m
kube-system          kube-scheduler-kind-control-plane            1/1     Running   1 (65s ago)   38m
local-path-storage   local-path-provisioner-684f458cdd-wf46t      1/1     Running   1 (65s ago)   37m
Paul--WeaveWorks:gitops-test pcurtis$ 

```

**Comment by chanwit** [comment]
The document said you needed a Git repository also needed to clone it locally before running the command.

https://docs.gitops.weave.works/docs/gitops-run/get-started/#git-repository

The doc seems to be not very clear for users to get started with the podinfo demo mentioned there.
It would have said that you needed to clone the podinfo repo before running the command.

**Comment by pfcurtis** [comment]
Thanks, @chanwit. The published docs could perhaps be better organized to be more linear.

**Comment by chanwit** [comment]
I'll have a PR to address them. Thank you @pfcurtis

**Comment by pfcurtis** [comment]
I have used your instructions, and they run through the complete "gitops run" process. The last items being the port-forwards.
