### ISSUE TITLE
Pause GitOps automation for an application

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#322]
**Short description**
As an Application operator, I want to pause the gitops automation for application foo so that I can manipulate the application manifests without impacting my running application.

**Acceptance criteria**
**given** cluster with wego installed and application foo added via `wego app add foo`
**when** issuing `wego app pause foo`
**then** gitops runtime doesn't pull updates from my repo when I commit and push to the branch and/or path I used in `wego app add`
**when** issuing `wego app pause foo` a second time
**then** an error isn't displayed

**given** cluster with wego installed and application foo paused via `wego app pause foo`
**when** issuing `wego app unpause foo`
**then** gitops runtime resumes  pull updates from my repo when I commit and push to the branch and/or path I used in `wego app add`
**when** issuing `wego app unpause foo` a second time
**then** an error is not displayed (but an info message saying already reconciling is displayed)

Must work on app added with and without branch and path values

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by J-Thompson12** [comment]
I need to clarify some things on this task. Basically what the assumption is about where this command will be run.

1. The command is always run from inside the repository so the code has access to the target yaml and can add suspend to it.

2. The command can be run from anywhere and the use the app name to get the url from the app describe and clone the repo to a tmp dir then add suspend to it and push. 

3. A possible third option that is the correct one that I havent thought of.

**Comment by jpellizzari** [comment]
Re-opening to assign to QA since this is user facing

**Comment by jpellizzari** [comment]
Closing in favor of #528
