### ISSUE TITLE
Resume GitOps for paused application 

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#323]
**Short description**
As an Application operator, I want to resume the gitops automation for application foo so that I can manipulate the application manifests and my running application sees the changes.

**Acceptance criteria**
**given** cluster with wego installed and application foo added via `wego app add` and `wego app pause foo` is run
**when** issuing `wego app resume foo`
**then** gitops runtime pulls updates from my repo when I commit and push to the branch and/or path I used in `wego app add`

**when** issuing `wego app resume foo` a second time
**then** an error isn't displayed

Must work on app added with and without branch and path values

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by markramm** [comment]
Closed as dupe
