### ISSUE TITLE
gitops-run accepts empty password for dashboard while webui requires non-empty password

### ISSUE THREAD

**Issue by gberche-orange** [weaveworks/weave-gitops#3237]
**Describe the bug**

gitops run accept empty password for dashboard while webui requires non-empty password

**Environment**

- Weave-Gitops Version
- Flux Version
- Kubernetes version

**To Reproduce**

with kind

```
$ gitops beta run ./podinfo --no-session --port-forward namespace=dev,resource=svc/dev-podinfo,port=9898:9898

[...]
Would you like to install the GitOps Dashboard: y
Please enter a password for logging into the dashboard: 
► Creating GitOps Dashboard objects ...
✚ Generating GitOps Dashboard manifests ...
```

**Expected behavior**

either
* cli rejects empty password
* web ui accepts empty password

**Actual Behavior**

* cli accepts empty password
* web ui rejects empty password

No easy way to change password see, https://github.com/weaveworks/weave-gitops/issues/2064

**Additional Context (screenshots, logs, etc)**

![image](https://user-images.githubusercontent.com/4748380/211055564-56a9c2bb-a423-4296-a724-75bf3382735b.png)

**workaround**

```
kind delete cluster
[...]
kind create cluster
```

**Comment by opudrovs** [comment]
@gberche-orange thank you for reporting it! ✨  We will look into it on Monday.

**Comment by opudrovs** [comment]
@gberche-orange thank you for reporting it, good catch! We have reviewed this issue and will fix it as soon as we have bandwidth to fix it or review an incoming PR for it.
