### ISSUE TITLE
Inform user their application has GitOps paused

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#324]
**Short description**
As an application operator I want to be able to tell if I have an application paused so that I can resume GitOps operations when I'm done manipulating the application manifests].

**Acceptance criteria**
**given** cluster with wego installed and application foo added via `wego app add` and `wego app pause foo` run
**when** issuing `wego app status foo`
**then** the command informs me that application foo has GitOps paused

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by markramm** [comment]
API server should pause and unpause application.   

CLI talks to API server.

**Comment by J-Thompson12** [comment]
@palemtnrider I am not sure if you were looking for more info on the paused status but when the status call is made to flux we already do get if its paused or not. It just says suspended 

```
NAME                    READY   MESSAGE                                                         REVISION                                        SUSPENDED 
gitrepository/nginx     True    Fetched revision: main/b8872cb44b9b30d67505ea01a585bd1d23412610 main/b8872cb44b9b30d67505ea01a585bd1d23412610   False    

NAME                    READY   MESSAGE                                                         REVISION                                        SUSPENDED 
kustomization/nginx     True    Applied revision: main/b8872cb44b9b30d67505ea01a585bd1d23412610 main/b8872cb44b9b30d67505ea01a585bd1d23412610   False 
```
I could just change the word suspended to paused if that works?

**Comment by palemtnrider** [comment]
>I could just change the word suspended to paused if that works?

I think showing suspended true/false is fine.
