### ISSUE TITLE
What you're seeing is certainly a networking issue between your cluster and GitHub's container registry, nothing we can do here, sorry.

### ISSUE THREAD

**Issue by AntonChernyaevArammeem** [weaveworks/weave-gitops#3256]
What you're seeing is certainly a networking issue between your cluster and GitHub's container registry, nothing we can do here, sorry.

_Originally posted by @makkes in https://github.com/weaveworks/weave-gitops/issues/3255#issuecomment-1377467516_

i also can't get chart in my local pc

**Comment by makkes** [comment]
```
$ helm pull oci://ghcr.io/weaveworks/charts/weave-gitops --version  4.0.11
Pulled: ghcr.io/weaveworks/charts/weave-gitops:4.0.11
Digest: sha256:658c2b880734898358c61b2c1dee9b5d51701c5224bfc2feb167813786d0ecde
```
Sorry, can't reproduce this.
