### ISSUE TITLE
Set up a new bucket for gitops run logs

### ISSUE THREAD

**Issue by josefaworks** [weaveworks/weave-gitops#3268]
Set up a new bucket to store the collected logs (in addition to the current two buckets)

# Implementation Details

In order to set up a new bucket to store the collected logs in addition to the current two buckets, the following steps can be taken:

1. Create A new S3-compatible bucket named `pod-logs` in the dev-bucket server.

# Acceptance Criteria

- A bucket named `pod-logs` is created in the dev-bucket server.

**Comment by opudrovs** [comment]
As discussed with @chanwit I am removing the second task and acceptance criterion because we are hardcoding the bucket name as `pod-logs` and there is nothing to configure with Fluent-Bit.

Removed:
```
2. Configure Fluent-Bit to send the logs it collects from the vcluster to the `pod-logs` bucket.
- The logs collected by Fluent-Bit are successfully forwarded to the `pod-logs` bucket.
```

Besides, Fluent-Bit is not added yet. So, the bucket will be added first in this issue probably.
