### ISSUE TITLE
Add endpoint to fetch GitOps Run sources of logs

### ISSUE THREAD

**Issue by makkes** [weaveworks/weave-gitops#3279]
The task is to create an endpoint function that will populate a list of sources of logs to be used in the UI. The function will take in a token as an argument and will read a page of logs, extract the values from the log name, remove any duplicates, and cache the results. The cached results will be returned in a list, with "gitops-run-client" always prepended as the first element. Additionally, the function will also return the next token for pagination if one is present.

# Implementation Details

- The function will take in a token as an argument. If the token is empty, it will be assumed that it is the first page of logs.
- The function will then read a page of logs using the token.
- The function will extract the values from the log name and remove any duplicates.
- The function will cache the results.
- The function will prepend "gitops-run-client" as the first element in the list of cached results.
- The function will return the list of cached values, along with the next token for pagination if one is present.

# Acceptance Criteria

- The function must be named "PopulateLogSources."
- The function must take in a token as an argument and return a list of sources of logs.
- The function must extract the values from the log name and remove any duplicates.
- The function must cache the results.
- The function must always prepend "gitops-run-client" as the first element in the list of cached results.
- The function must return the next token for pagination if one is present.

**Comment by chanwit** [comment]
will be addressed by #3269
