### ISSUE TITLE
Return timestamp, source, level and message in GitOps Run log endpoint

### ISSUE THREAD

**Issue by makkes** [weaveworks/weave-gitops#3280]
Currently, the get-session-logs endpoint returns logs as an array of strings, which is not enough to be used by the front end.

We should return logs as an array of tuples, each of which contains
- timestamp (standard logging format)
- source (the source of the log - it would be "gitops-run-client" to indicate that the log is from the GitOps Run console, or "$namespace/$resource" to indicate that it's from pods of the resource (e.g. deployment, statefuleset, daemonset, etc)
- level (the logs level) they are 3 levels, "info", "warning" and "error".
- message (the log itself)

**Comment by opudrovs** [comment]
Blocked by https://github.com/weaveworks/weave-gitops/issues/3313
