### ISSUE TITLE
Microsoft.Flux on AKS use with gitops run is not straightforward and well-documented

### ISSUE THREAD

**Issue by chanwit** [weaveworks/weave-gitops#3281]
When using Microsoft.Flux on an AKS cluster with gitops run, there are missing permissions for the flux-system:flux-applier role that need to be provided on a per-tenant basis through FluxConfig. This is not clearly documented and can lead to issues with the deployment.

```
flux-system   run-dev-ks   66s   False   Service/frontend dry-run failed, reason: Forbidden, error: services "frontend" is forbidden: User "system:serviceaccount:flux-system:flux-applier" cannot patch resource "services" in API group "" at the cluster scope...
```

The issue can be resolved by providing the necessary permissions, but the lack of clear documentation may cause confusion and delay in deployment.

cc @kingdonb

**Comment by kingdonb** [comment]
Do we collect any metric or phone home when weave `gitops beta run` is run? I wonder if there's any way we can know if any people installed or tried to use `gitops beta run` with AKS Flux before; those people might have extra clusterroles on the cluster now, that were installed inadvertently on the cluster if they used `gitops run` before #3049 has been released.

It's probably not likely this affected anyone, most production clusters are locked down and hopefully there is nobody who is likely to run anything marked `beta` on them.

Is there any entrypoint in the weave gitops docs that explains how to create a tenant?

It might be the [Multi Tenancy](https://docs.gitops.weave.works/docs/enterprise/multi-tenancy/) doc. Perhaps there is already enough documentation of the specific feature, but we need some glue to make it clearer for AKS users how they should configure `gitops run` for their tenants. It isn't clear to me what permissions gitops run should get, unless it's just the tenant.

Even so, then it's not yet clear to me how to pass that tenant name / service account in to gitops run. Maybe this isn't only documentation issue but also a feature request – can users already configure the name of service account to use with the gitops run kustomization?

**Comment by Callisto13** [comment]
🤔 I also can't see anything obvious about how one would pass a name/sa:

```
Flags:
      --allow-k8s-context strings          The name of the KubeConfig context to explicitly allow.
      --components strings                 The Flux components to install. (default [source-controller,kustomize-controller,helm-controller,notification-controller])
      --components-extra strings           Additional Flux components to install, allowed values are image-reflector-controller,image-automation-controller.
      --context string                     The name of the kubeconfig context to use
      --dashboard-hashed-password string   GitOps Dashboard password in BCrypt hash format
      --dashboard-port string              GitOps Dashboard port (default "9001")
      --decryption-key-file string         Path to an age key file used for decrypting Secrets using SOPS.
      --flux-version string                The version of Flux to install. (default "0.37.0")
  -h, --help                               help for run
      --no-bootstrap                       Disable bootstrapping at shutdown.
      --no-session                         Disable session management. If not specified, the session will be enabled by default.
      --port-forward string                Forward the port from a cluster's resource to your local machine i.e. 'port=8080:8080,resource=svc/app'.
      --root-dir string                    Specify the root directory to watch for changes. If not specified, the root of Git repository will be used.
      --session-name string                Specify the name of the session. If not specified, the name of the current branch and the last commit id will be used. (default "run-master-eac008b3-dirty")
      --session-namespace string           Specify the namespace of the session. (default "default")
      --skip-dashboard-install             Skip installation of the Dashboard. This also disables the prompt asking whether the Dashboard should be installed.
      --skip-resource-cleanup              Skip resource cleanup. If not specified, the GitOps Run resources will be deleted by default.
      --timeout duration                   The timeout for operations during GitOps Run. (default 5m0s)
```

Agree this is probably also a feature request cc @JamWils

**Comment by LappleApple** [comment]
How should we prioritize by severity level?

**Comment by LappleApple** [comment]
Closing due to change of plans for this feature.
