### ISSUE TITLE
Enable additional linters

### ISSUE THREAD

**Issue by makkes** [weaveworks/weave-gitops#3282]
Linter descriptions:

> whitespace
> 
> Enforces newlines (or comments) after every multi-line if statement.
> Enforces newlines (or comments) after every multi-line function signature.
> 
> unconvert
> 
> Removes unnecessary type conversions
> 
> gocritic
> 
> Provides diagnostics that check for bugs, performance and style issues.
> Extensible without recompilation through dynamic rules.
> Dynamic rules are written declaratively with AST patterns, filters, report message and optional suggestion.

Acceptance Criteria

- In the golangci-lint linter config
  - the `whitespace` linter is enabled
  - the `unconvert ` linter is enabled
  - the `gocritic ` linter is enabled
 
 - The code is updated according to the linter rules.

**Comment by opudrovs** [comment]
A follow-up issue raised:
https://github.com/weaveworks/weave-gitops/issues/3528
