### ISSUE TITLE
Access logs for GitOps run via UI using real data

### ISSUE THREAD

**Issue by katya-makarevich** [weaveworks/weave-gitops#3290]
# Acceptance Criteria

- the logs are only sortable by timestamp (asc and desc)
- filtering is not part of this issue (no select element will be displayed)
- errors from requests to the server are displayed the same way as they are shown on other pages.
- timestamps are formatted as displayed in [the designs](https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?node-id=11227%3A51192&t=rw0LwXEx7dC4GwBW-0).

# TBD/unknowns

- how is filtering supposed to work in conjunction with the backend? What does the backend provide for filtering?
- do we need/want paging here? How? see #3344
- how do we go about auto-reloading? Should new logs automatically appear or should the user have to hit "refresh" or enable a check mark like "auto reload"?

**Comment by makkes** [comment]
We need to figure out the details/acceptance criteria here.
