### ISSUE TITLE
Errors on GitOps Run object details pages before GitOps Run objects are ready

### ISSUE THREAD

**Issue by opudrovs** [weaveworks/weave-gitops#3297]
When starting a GitOps Run session and looking at it in the GitOps Run UI, there is a moment when a session is already displayed in the sessions table, with links to GitOps Run objects

<img width="1500" alt="Screenshot 2023-01-23 at 13 16 29" src="https://user-images.githubusercontent.com/8824708/214075743-5046b1dc-4bac-4a8c-b917-6156b2af8aa7.png">

but clicking the links displays the following errors:

<img width="1521" alt="Screenshot 2023-02-13 at 17 54 44" src="https://user-images.githubusercontent.com/8824708/218526369-ba1bd3e8-9f5e-4a0a-adee-dfc69f175f6e.png">

<img width="1528" alt="Screenshot 2023-02-13 at 18 08 25" src="https://user-images.githubusercontent.com/8824708/218526412-6d243287-27cc-4f38-996e-7577b53372f7.png">

<img width="1536" alt="Screenshot 2023-02-13 at 18 08 48" src="https://user-images.githubusercontent.com/8824708/218526598-79bbef96-5ba8-431b-b461-30a656df05ec.png">

I guess it happens because GitOps Run objects are not reconciled/ready yet.
After a while, object detail pages are displayed as expected when clicking the links.

**Comment by joshri** [comment]
We're constructing these links from pieces of data in the annotations, and we're definitely making an assumption that the automation and source will be ready. I'm not sure that there's a way to easily avoid this in the data as-is, but at the very least this error should be handled in a way that makes it look like we know it's there

**Comment by opudrovs** [comment]
I thought about returning a flag alongside with data returned from the backend, smth. like "objects are ready". Like first we return the data for a gitops run session (or whatever it is, have not looked at specific data yet) without this flag and display the session but do dnot display working links to object detail pages of now. But after re-polling if the flag is present we can display the links.

Otherwise if we just wait until returning the whole data we will not be able to display the session until the objects are ready, so there would be a considerable delay between starting a gitops run session and showing it in the sessions table.

**Comment by opudrovs** [comment]
Updated screenshots in the issue description. Full error logs from the browser console:

```
http://localhost:8000/v1/object/run-dev-ks?namespace=flux-system&kind=Kustomization&clusterName=default%2Frun-master-fdd0a0b7 500 (Internal Server Error)

query.js:356 {code: 2, message: 'kustomizations.kustomize.toolkit.fluxcd.io "run-dev-ks" not found', details: Array(0)}

index.js:9317          POST http://localhost:8000/v1/reconciled_objects 500 (Internal Server Error)

query.js:356 {code: 2, message: 'unsupported application kind: ', details: Array(0)}
```

**Comment by opudrovs** [comment]
A followup issue has been added to create a new endpoint and add more test coverage #3417
