### ISSUE TITLE
How do we install the wego UI in a running weave gitops managed cluster

### ISSUE THREAD

**Issue by markramm** [weaveworks/weave-gitops#330]
As a Platform Operator I would like to use the wego ui install command to setup the wego UI at a known URL inside the cluster.   

Ingress is a separate issue.   In amazon this should be as simple as adding a load balancer config.

Output of the spike is a definition of how the cluster installs into the system. 

(At the end of the day you need API server in the right place, and somewhere you can get the HTML)

**Comment by markramm** [comment]
We can install the UI at wego install time, but when we get to multi-cluster support we may want to install in just one of the clusters.   

Also if teams move to the enterprise product they may want to move where the UI is installed. 

But to be clear, we can install via the install command now.

**Comment by jpellizzari** [comment]
Closed by https://github.com/weaveworks/weave-gitops/issues/655
