### ISSUE TITLE
Understand the effort needed to add support for BitBucket Server

### ISSUE THREAD

**Issue by yiannistri** [weaveworks/weave-gitops#3306]
**Question**

What is the effort for adding support for BitBucket Server?

**Short description**

We currently have code in Weave GitOps that interacts with GitHub and GitLab. We want to understand the work needed to add support for BitBucket Server.

**Goal**

To come up with a set of stories for adding support for BitBucket Server

**Timebox**

2 days
---

**Outcome**

**Comment by jpellizzari** [comment]
Some note:

`gitauth` has been moved to EE, which should save us some time.

Also, bitbucket server supports PKCE, which is what we use for Gitlab, so we can probably re-use or at worst copy paste some code to make it work.

https://confluence.atlassian.com/bitbucketserver0720/bitbucket-oauth-2-0-provider-api-1116282017.html
