### ISSUE TITLE
Get Session Logs endpoint returns an error instead of log data

### ISSUE THREAD

**Issue by opudrovs** [weaveworks/weave-gitops#3313]
The following error is returned by the Get Session Logs OSS endpoint when testing it from both enterprise (recommended) and directly in OSS, even thought a GitOps Run session is running:

<img width="1527" alt="Screenshot 2023-01-27 at 12 56 32" src="https://user-images.githubusercontent.com/8824708/215085761-85c08143-ec84-4fc1-99db-1df37f0667af.png">

Testing:

The enterprise PR to test the issue:
https://github.com/weaveworks/weave-gitops-enterprise/pull/2283

- To run the session, I use the following command in the podinfo directory:
```
gitops beta run ./deploy/overlays/dev --timeout=3m --port-forward namespace=dev,resource=svc/backend,port=9898:9898
```

The session is displayed in the list of GitOps Run sessions but a vcluster is not displayed in the list of vclusters.

- Please replace the following hardcoded values in the `GitOpsRunDetail` component with appropriate values:

```
const { isLoading, data, error } = useGetLogs({
    namespace,
    sessionId: 'run-master-fdd0a0b7',
    clusterName: 'default/run-master-fdd0a0b7',
  });

  console.log('logs:');
  console.log(data);
```

- To show the `GitOpsRunDetail` component, please run a GitOpsRun session and click on the session's name in the list of sessions.

**Comment by opudrovs** [comment]
I mean except for getting their logs. Links to object detail pages work for the sessions.

**Comment by opudrovs** [comment]
Also added commented out previous args next to current hardcoded args passed to the GetSessionLogsRequest.

**Comment by chanwit** [comment]
do we still need this ticket?
It's not blocking us any more.

**Comment by chanwit** [comment]
^- cc @opudrovs

**Comment by opudrovs** [comment]
But the GetSessionLogs endpoint is not working on the frontend. We are not able to use it.

**Comment by chanwit** [comment]
ok let's keep it.

**Comment by chanwit** [comment]
To set up the dev env for testing the session endpoint:

```
make gitops
make install
gitops beta run --no-session ./deploy/overlays/dev/

# create kind with local registry
make local-kind-cluster-with-registry

# tilt up
tilt up
```

Then go to https://localhost:9001

To test the session_logs endpoint, use:

```
curl ... -d '{"namespace":"flux-system","clusterName":"Default"}'
```
