### ISSUE TITLE
dashboard UX: refine permalink support (list: search, sort)

### ISSUE THREAD

**Issue by gberche-orange** [weaveworks/weave-gitops#3359]
**Problem**

As a flux user
in order to share permalinks to dashboard pages with others
I need the permalinks to include navigation actions such as:
* in list (applications, sources, ...):
   * search criteria
   * sorting criteria

Currently, the browser address bar is not reflecting the search or sorting actions previous performed:
![image](https://user-images.githubusercontent.com/4748380/216599953-41f8c7f4-7967-4db0-8afb-28a30cab1032.png)

**Solution**

Improve the permalink support in the dashboard to capture the navigation actions

**Additional context**

## Acceptance Criteria:

1. The permalinks in the dashboard capture the navigation actions performed by the user.
1. The permalinks include the search criteria used in the list views of applications, sources, etc.
1. The permalinks include the sorting criteria used in the list views of applications, sources, etc.
1. The browser address bar accurately reflects the search and sorting actions performed by the user.
1. The permalinks are easily shareable with others and accurately reflect the user's navigation actions.

**Comment by chanwit** [comment]
Thank you @gberche-orange
We'll take a look at your dashboard UX issues shortly. Thank you so much for actively reporting issues for us :1st_place_medal:

**Comment by chanwit** [comment]
Acceptance criteria added to help verify regression behavior.

**Comment by gberche-orange** [comment]
great, thanks @joshri for the prompt fix !
