### ISSUE TITLE
dashboard UX: preserve kustomization graph navigation

### ISSUE THREAD

**Issue by gberche-orange** [weaveworks/weave-gitops#3360]
**Problem**

As a flux user
in order to browse a deep hierarchy of kustomizations in the graph view
I need to go navigate across kustomization by remaining in the graph view

in the following screen, when clicking on a bottom kustomization
![image](https://user-images.githubusercontent.com/4748380/216601763-e601442e-f718-447b-81bf-b0cafc8d5f72.png)
I'm landing on the default tab and have to click on the graph tab 
![image](https://user-images.githubusercontent.com/4748380/216601820-f4e21efd-c643-41fa-bc45-ddefdc0cd460.png)
to reach the inventory resources
![image](https://user-images.githubusercontent.com/4748380/216601770-7059d389-7d73-40ec-89a4-cfce1ebee9f9.png)

**Solution**

Modify the navigation in the graph view to have nested kustomization urls as `/kustomization/graph`instead of `kustomization/details`
 
**Additional context**

## Acceptance Criteria:

1. The navigation in the graph view allows for browsing a deep hierarchy of kustomizations.
1. The navigation links for kustomizations in the graph view use the format "/kustomization/graph" instead of "/kustomization/details".
1. When clicking on a bottom kustomization, the user remains in the graph view and is not redirected to the default tab.
1. The graph view displays the inventory resources for the selected kustomization.

**Comment by JamWils** [comment]
cc: @josefaworks

**Comment by chanwit** [comment]
Acceptance criteria added

**Comment by jpellizzari** [comment]
I'm not sure why the graph would be the default landing page. 

Does clicking on a kustomization in the graph mean I want to see it's inventory? Or did I click it because I want to navigate to it.

A dynamic graph view would probably be a better UX. I would imagine an accordion-like expansion where clicking on a button on the Kustomiation tile shows it's inventory on the same graph (without navigating).

**Comment by jpellizzari** [comment]
Closing as not doing, per our FE team meeting.
