### ISSUE TITLE
Missing images in the README created by `create dashboard` command 

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#3364]
**Describe the bug**

The `gitops create dashboard ww-gitops` command adds a README to the repo. This README looks like it should have images in it, but they are not added.

![Screenshot 2023-02-03 at 16 31 19](https://user-images.githubusercontent.com/8898786/216656224-de2dd7cf-1b26-4d0f-9d23-fa63b31dc43b.png)

**Environment**

- Weave-Gitops Version 0.16.0
- Flux Version
- Kubernetes version

**To Reproduce**

Run the `gitops create dashboard ww-gitops` command.

**Expected behaviour**

If the README is meant to have images, they should be there.

**Comment by makkes** [comment]
The `gitops create dashboard` command merely creates a HelmRepository and a HelmRelease. I'm not sure what you mean by "adds a README to the repo". Which repo has it been adding the file to for you?

**Comment by Callisto13** [comment]
Huh interesting. _Something_ put a License and Readme in my `fleet-infra` repo, I thought it was weird that the command did that 🤔 I will retrace my steps.
![Screenshot 2023-02-03 at 17 06 02](https://user-images.githubusercontent.com/8898786/216663775-3c3cfa6e-abcb-4cfe-a7e9-60b28495d57d.png)
