### ISSUE TITLE
`gitops beta run` is removing fluent-bit pod, but not removing helmrelease

### ISSUE THREAD

**Issue by steve-fraser** [weaveworks/weave-gitops#3375]
**Describe the bug**
gitops run is removing fluent-bit pod, but not the helmrelease cause rerunning the command to fail.

**Environment**

🕙08:29:05 PM ❯ gitops version                                                              
Current Version: v0.16.0-rc.1-30-g02ed0da-Enterprise-Edition-v0.16.0
GitCommit: 02ed0da9
BuildTime: 2023-02-02_13:34:07
Branch: HEAD

**To Reproduce**
1. Follow 

1. gitops beta run . --allow-k8s-context=test-cluster --no-session --timeout 3m
2. cancel out
3. gitops beta run . --allow-k8s-context=test-cluster --no-session --timeout 3m 
**Expected behavior**
HelmRelease to removed (can this also be moved the gitops run namespace?)

**Actual Behavior**
getting stuck

**Additional Context (screenshots, logs, etc)**

## User story: 

As a GitOps user, I want the gitops beta run command to remove both the fluent-bit pod and the HelmRelease, so that I can rerun the command without getting stuck.

## Acceptance Criteria:

1. The gitops beta run command should remove both the fluent-bit pod and the HelmRelease in the test-cluster context.
1. The rerun of the gitops beta run command should not get stuck.
1. The HelmRelease should be removed in the gitops run namespace.

**Comment by chanwit** [comment]
@josefaworks I added user story and acceptance criteria to the ticket.
Could you please review it?

**Comment by josefaworks** [comment]
lgtm :)
