### ISSUE TITLE
Sanitize Cluster Name

### ISSUE THREAD

**Issue by luizbafilho** [weaveworks/weave-gitops#338]
**Short description**
As an user, I want to have my cluster name sanitized so that it doesn't failed when used.

**Acceptance criteria**
- [ ] the cluster name we pick from current kubectl context should be sanitized and have all invalid chars removed

Sample of invalid names:
- `arn:aws:eks:us-east-1:892476923372:cluster/sandbox`
- `cornelia@weave.works@cornelia-prod.us-east-2.eksctl.io`

**Design materials**
- Screenshots
- Design diagrams
- WEP 
- PR/FAQ

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by ambled** [comment]
Adding to this issue is the default kubernetes context is "kubernetes-admin@kubernetes" and currently requires a rename-context to use wego.
