### ISSUE TITLE
wego app add should default to the current HEAD branch ref when called from within a Git repo

### ISSUE THREAD

**Issue by sbernheim** [weaveworks/weave-gitops#341]
**Describe the bug**
`wego app app .` defauts to the `main` branch when the `--branch` option is not explicitly set.

```
$ wego app add .
Updating parameters from environment... using URL: 'ssh://git@github.com/sbernheim/podinfo.git' of origin from git config...

done

Checking cluster status... FluxInstalled

Uploading deploy key
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: podinfo
  url: ssh://git@github.com/sbernheim/podinfo.git

---
```

If the instant repo does not have a `main` branch, this will result in an error on the resulting GitRepository resource in the target cluster.

```
$ kg gitrepo -A
NAMESPACE     NAME      URL                                          READY   STATUS                                                                                                            AGE
wego-system   podinfo   ssh://git@github.com/sbernheim/podinfo.git   False   unable to clone 'ssh://git@github.com/sbernheim/podinfo.git', error: couldn't find remote ref "refs/heads/main"   33s
```

Pushing a `main` branch can easily resolve this error.

```
$ git checkout -b main 
Switched to a new branch 'main'
$ git push -u origin main
Total 0 (delta 0), reused 0 (delta 0)
remote: 
remote: Create a pull request for 'main' on GitHub by visiting:
remote:      https://github.com/sbernheim/podinfo/pull/new/main
remote: 
To github.com:sbernheim/podinfo.git
 * [new branch]      main -> main
Branch 'main' set up to track remote branch 'main' from 'origin'.

<... after some time ...>

$ kg gitrepo -A
NAMESPACE     NAME      URL                                          READY   STATUS                                                            AGE
wego-system   podinfo   ssh://git@github.com/sbernheim/podinfo.git   True    Fetched revision: main/5ac18a31750cd88b07504f74f770fde2bbfd3fcd   6m11s
```

There is nothing magic about either the `master` or `main` branches, and user application repos may not have either branch.  It would be safer to read the current HEAD ref from the local Git repository and use that as the default branch when calling `wego app add` from within a local repo.

```
$ git branch --show-current
current-branch-name
```

This would disintermediate between `main` and `master` default branches and offer more confidence that the expected branch actually exists in the GitHub remote repo.

**Environment**
 - wego: v0.0.5
 - kubernetes:
    - [ x] KinD - v0.8.1 go1.14.4 darwin/amd64
 ```
$ kubectl cluster-info
Kubernetes master is running at https://127.0.0.1:52803
KubeDNS is running at https://127.0.0.1:52803/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```
 - Browser + version: N/A
 - 
**Affects versions**

**To Reproduce**
Steps provided in the description above.

**Expected behavior**
The default GitRepository manifest generated by `wego app add` should reference the current HEAD ref of the local repository when run from within a Git repo.

**Additional context**
Encountered while running through the Getting Started Docs for v0.0.5 during today's GitOps WOUG.

**Comment by pzfreo** [comment]
I agree with this. I think this would be a good improvement.
