### ISSUE TITLE
Getting Started Guide docs `wego app add .` should set the `--branch` option

### ISSUE THREAD

**Issue by sbernheim** [weaveworks/weave-gitops#342]
**Describe the bug**
The [Weave GitOps Getting Started Guide](https://docs.gitops.weave.works/docs/getting-started) instructs the user to clone Stefan's Podinfo GutHub repository and add the `podinfo` application using the `wego app add .` command.

See [Configure Weave GitOps to reconcile the workload automatically](https://docs.gitops.weave.works/docs/getting-started/#configure-weave-gitops-to-reconcile-the-workload-automatically) item 6.

By default, `wego app add` generates a GitRepository manifest which refers to the expected `main` default branch as per current standard.
```
$ wego app add .
Updating parameters from environment... using URL: 'ssh://git@github.com/sbernheim/podinfo.git' of origin from git config...

done

Checking cluster status... FluxInstalled

Uploading deploy key
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: podinfo
  url: ssh://git@github.com/sbernheim/podinfo.git

---
```

However, Stefan's Podinfo repository does not define a `main` branch ref.  It is still using `master` as its default branch. 
 Forked user repos will follow the parent's pattern (unless otherwise configured) when the fork is created.

The [Getting Started Guide](https://docs.gitops.weave.works/docs/getting-started/#configure-weave-gitops-to-reconcile-the-workload-automatically) should set the `--branch` option explicitly to `master` and possibly include a short note to suggest a solution should the application repo not define a `main` branch reference.

IMHO, the Guide should address this issue explicitly regardless of the fix for #341 

**Environment**
 - wego: v0.0.5
 - docs at https://docs.gitops.weave.works/docs/getting-started/#getting-started-with-a-kind-cluster-and-podinfo-workload

**Additional context**
Encountered during today's Weave GitOps WOUG meeting `wego` demo.

**Comment by pzfreo** [comment]
As you spotted, this is because you used Stefan's repo instead of the https://github.com/wego-example/podinfo-deploy repo.

I think the way of addressing this is to have say three levels of GS. 5 mins (just see stuff running, no exploration). If we get you interested, then next 5 mins is digging into what is happening. If you are still engaged, then another 10 minutes where we explore branches, paths, helm, etc.

**Comment by markramm** [comment]
Paul added a line to the docs making it more explicit that we choose the proper podinfo directory
