### ISSUE TITLE
Mis-numbered Items in Getting Started Guide docs

### ISSUE THREAD

**Issue by sbernheim** [weaveworks/weave-gitops#343]
**Describe the bug**
There are two instances of Item 5 and Item 8 in the Getting Started Guide:
<img width="1824" alt="Screen Shot 2021-06-15 at 4 04 30 PM" src="https://user-images.githubusercontent.com/1707604/122117337-bf4ad980-cdf4-11eb-9bac-62c43e588de8.png">
<img width="1824" alt="Screen Shot 2021-06-15 at 4 10 15 PM" src="https://user-images.githubusercontent.com/1707604/122117358-c4a82400-cdf4-11eb-85d8-206a2ab7c9f2.png">

**Environment**
 - wego: 0.0.5
 
Repeat of #271

**Comment by jpellizzari** [comment]
This looks fixed to me https://docs.gitops.weave.works/docs/getting-started/

Closing.
