### ISSUE TITLE
GitOps Run takes too long to validate manifests

### ISSUE THREAD

**Issue by makkes** [weaveworks/weave-gitops#3457]
**Describe the bug**

@kingdonb says: "The point of Gitops Run is to help people find errors in their manifests, but since some errors don't surface at validation time, they have to wait for timeout... the Kustomization that gitops run creates seems to have all the default settings, including timeout: 5m – this is not conducive to getting the errors in a fast-feedback way"

**To Reproduce**

TBD

**Expected behavior**

TBD

**Comment by makkes** [comment]
#3461 might mitigate this as you'd see the logs e.g. from failing pods early (before the Kustomization would be marked as failed).

**Comment by kingdonb** [comment]
The 5m timeout is a blocker from my perspective, because of the DORA stuff that says you should aim for the low end of 30s-5m when you're building iterative processes (but no higher than 5m)

We are on the wrong side of the chart

**Comment by opudrovs** [comment]
@chanwit @kingdonb 

Places in which GitOps Run uses the `timeout` flag (which is set to 5m by default):

- For installing Flux:
https://github.com/weaveworks/weave-gitops/blob/main/cmd/gitops/beta/run/cmd.go#L319

- For reconciling the OSS dashboard if we installed it:
https://github.com/weaveworks/weave-gitops/blob/main/cmd/gitops/beta/run/cmd.go#L445

- For setting timeout in dev Kustomization or HelmRelease:
https://github.com/weaveworks/weave-gitops/blob/main/cmd/gitops/beta/run/cmd.go#L795

- When requesting reconciliation of GitOps Run resources:
https://github.com/weaveworks/weave-gitops/blob/main/cmd/gitops/beta/run/cmd.go#L976

- When setting uo pord-forwarding (if I got it right):
https://github.com/weaveworks/weave-gitops/blob/main/cmd/gitops/beta/run/cmd.go#L1045

**Questions:**
- In which of these places would you like to use smaller/custom timeouts?

- Should the timeouts be hardcoded or should I add additional timeout flags for some of them?

- What default values should the new custom timeouts have?

**Comment by opudrovs** [comment]
As discussed, @chanwit will first complete the spike:
https://github.com/weaveworks/weave-gitops/issues/3645

It is possible that just adding proper feedback via logs will resolve the current issue because the users willl be made aware of what is going on.

**Comment by opudrovs** [comment]
@kingdonb thank you for your considerations! ✨

**Comment by opudrovs** [comment]
@chanwit @kingdonb let's re-investigate the current issue after the logs spike is completed.

**Comment by LappleApple** [comment]
Feedback from @fsequeira1: would give this another look soon -- useful to improve perf

**Comment by LappleApple** [comment]
Closing due to change of plans regarding this feature.
