### ISSUE TITLE
GitOps Run: Show workload logs in terminal

### ISSUE THREAD

**Issue by makkes** [weaveworks/weave-gitops#3458]
**Problem**

@chanwit: "regarding GitOps Run, would it be OK to see workloads logs being printed out thru the console (like Docker Compose etc) (edited)"
@kingdonb: "Yes, I think that's optimal. I'm working with spin for some wasm tests, and they used to have an option --follow-all so that the spin "orchestrator" (like weave gitops run) prints out the logs from every wasm container on the console. They deprecated this option and made it the default, I think that's a good idea. Instead now they have --follow only, which lets you select the container whose logs you want to follow (ignoring all the others)."

**Solution**

TBD

**Additional context**

TBD

**Comment by LappleApple** [comment]
From @chanwit: This is a bit big. Technically we'd need to do a lot of talking to the server, reading logs or probably someone might be finding some tricks to implement it better. Need a spike first for how to do it.
