### ISSUE TITLE
SPIKE: GitOps Run Logs

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#3461]
**Question**

We built an integrated logging experience for gitops run in Weave GitOps Enterprise.  It would be really useful to extend this as a tab on the `Kustomization` or `HelmRelease` detail page for GitOps Sets Pull Request previews or for GitOps Run sessions in OSS.  What would it take to have the same logging functionality in other areas of the product?  

**Short description**

When engineers are debugging issues it would be nice to have more verbose logs that they can reference for their application.  These logs should be encapsulated as a whole under the deployed kustomization.

**Goal**
1. A t-shirt size for a "Logs" tab on an OSS GitOps Run instance.  I.e. non-session mode.
2. A t-shirt size on effort for a "Logs" tab on a kustomization or helm release page?

**Known Unknowns**

- How do we know the pods that a HelmRelease creates?

**Timebox**

2-3d

---

**Outcome**

Review with PM and Tech Lead before closing.  If LOE is low enough then the outcome might be a set of stories to move the feature forward more quickly.

**Comment by chanwit** [comment]
> How do we know the pods that a HelmRelease creates?

We already have inventory implemented in Helm controller.
