### ISSUE TITLE
Make GitOps Run work in air-gapped environments

### ISSUE THREAD

**Issue by makkes** [weaveworks/weave-gitops#3470]
**Short description**

As a Weave GitOps user I want to use GitOps Run in an air-gapped environment where images cannot be pulled from the internet.

**Acceptance criteria**

- [ ] Provide a list of all images used with GitOps Run upon each Weave GitOps release. This list can be used to pull these images from the internet and push them to a local registry.
- [ ] Provide a way for users to let GitOps Run know it should create all resources so that images are pulled from the internal registry.

**TBD**

How do we make the image list available? Options:

- A simple text/JSON/YAML file with a list of image references created upon each Weave GitOps release and made available as a downloadable artifact attached to the GitHub release.
- A command like `gitops run image-list` that prints this list out.

**Comment by chanwit** [comment]
Image List

Standard Flux images, for example:
```
ghcr.io/fluxcd/helm-controller:v0.27.0                                                                    
ghcr.io/fluxcd/kustomize-controller:v0.31.0                                                               
ghcr.io/fluxcd/notification-controller:v0.29.0                                                            
ghcr.io/fluxcd/source-controller:v0.32.1                                                                                                                                                                             
ghcr.io/weaveworks/wego-app:v0.18.0  
```

GitOps Run related images:
```
cr.fluentbit.io/fluent/fluent-bit:2.0.9
docker.io/loftsh/vcluster:0.14.2
docker.io/rancher/k3s:v1.26.0-k3s1
ghcr.io/weaveworks/gitops-bucket-server@sha256:9fa2a68032b9d67197a3d41a46b5029ffdf9a7bc415e4e7e9794faec8bc3b8e4                                                                                                    
ghcr.io/weaveworks/wego-app:v0.18.0
loftsh/vcluster:0.14.2
rancher/k3s:v1.26.0-k3s1
```

**Comment by chanwit** [comment]
Next step would be grouping and map them to KIND + localhost.

**Comment by chanwit** [comment]
Also, GitOps Run requires to download many things.
- Flux CLI
- Flux & K8s schemas for validation

**Comment by LappleApple** [comment]
Airgapped doesn't apply to just GitOps Run but to everything -- containers, Helm charts, etc.  

We have instructions for customers to replicate steps in their environment. Might need to provide tooling to provide them. Will create a research spike into current setup.

**Comment by makkes** [comment]
Yes, I believe we need to support air-gap environments as first-class citizens and include tooling around it, e.g. to easily fetch all necessary images and load them onto the cluster. A tool that we built at D2iQ to do that is https://github.com/mesosphere/mindthegap that we could leverage here as well.

**Comment by LappleApple** [comment]
Marking as low priority for now as it seems the bulk of airgapped support work would be done by a different team and GOR would come afterward.
