### ISSUE TITLE
Support non-passwordless SSH keys 

### ISSUE THREAD

**Issue by pzfreo** [weaveworks/weave-gitops#348]
**Short description**
As an SRE I want to use my existing or specific SSH key with a password so that I can use keys without passwords

**Comment by bigkevmcd** [comment]
Not quite sure what this means?

"non-passwordless" i.e. encrypted keys?

**Comment by bigkevmcd** [comment]
Would you propose to strip the password from the key before uploading?

**Comment by pzfreo** [comment]
Maybe this isn't possible?!

**Comment by bigkevmcd** [comment]
It's not particularly easy, if you upload an encrypted key, then you need to store the decryption string for it (the password) pretty close by, so you've effectively stripped the key of its encryption.

**Comment by pzfreo** [comment]
This was in response to a bunch of comments about some teams that won't allow SSH keys without passwords. However, I agree this doesn't really help. Closing!
