### ISSUE TITLE
Export new Nav to Enterprise

### ISSUE THREAD

**Issue by makkes** [weaveworks/weave-gitops#3480]
This one is a beast. 

- Delete all enterprise nav code and import OSS nav
- Rewrite the way we detect the current url in enterprise to send to the oss nav
- Rewrite and begin organization of enterprise UI structure to support display of oss nav
- Try not to break everything

**Comment by katya-makarevich** [comment]
blocked by https://github.com/weaveworks/weave-gitops-enterprise/issues/2524
