### ISSUE TITLE
GitOps Run failing validation on non-Kubernetes yaml files

### ISSUE THREAD

**Issue by SamStenton** [weaveworks/weave-gitops#3491]
**Describe the bug**

When running `gitops beta run ./` the command fails validation as it runs into other non-flux related yaml files. 

**Environment**

- Weave-Gitops Version: 0.18
- Flux Version v0.39.0
- Kubernetes version v1.23.7+k3s1

Running in `--no-session` mode. 

**To Reproduce**

1. Create `kustomization.yaml` in project root with references
2. Create `gitlab-ci.yml` or `sops.yaml` files 
3. Run `gitops beta run ./`

**Expected behavior**

I would expect there to be an understanding of flux vs non-flux files or the ability to ignore via cli or using [.sourceignore](https://fluxcd.io/flux/components/source/gitrepositories/#excluding-files) file.

**Actual Behavior**
```
► 1 change events detected
► Validating files under ./ ...
/[...]/clusters/cluster1/.gitlab-ci.yml - failed validation: error while parsing: missing 'kind' key
✗ Validation failed: please review the errors and try again: validation failed
```

**Comment by bigkevmcd** [comment]
Hey @SamStenton thanks for the report, yes, it feels like we should do something like `.sourceignore` which would be in keeping with. the Flux source-controller.

**Comment by chanwit** [comment]
+1 @bigkevmcd 

We would probably name it `.gitopsrunignore`.

**Comment by chanwit** [comment]
After discussion, we would go with `.sourceignore` similar to what is used by Flux.
ref: https://github.com/fluxcd/pkg/blob/main/sourceignore/sourceignore.go

**Comment by JamWils** [comment]
We are moving this over to the "ready" column for the team to pick up.
