### ISSUE TITLE
Epic: docs guides

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#3502]
I have created a bunch of tickets for writing guides using information shared by
users of what they are trying/struggling to do and what is lacking. I have guessed at
some things, and, as someone who does not use WG like that, I may have asked for the
wrong thing. If that is the case, please don't @ me about it (I won't be here anyway), just
update the issue with the correct instructions and get on with the job.

----------------------

Useful guides take users through several easy-to-follow and adaptable steps
towards a clear outcome. They will cover at least one product feature, or
combine many, and could include integration with some external component.
Guides are often known as 'advanced' because they are taking users through a
near real life use-case, far beyond 'simply set up this one thing'.

We have some guides right now, some are [thorough and have clear goals](https://docs.gitops.weave.works/docs/next/guides/delivery/), some
seem to suddenly [stop half way through](https://docs.gitops.weave.works/docs/next/guides/deploying-capa/)
with barely a mention of WGEE, some assume quite a bit of knowledge from the
user with no links for them to go get that knowledge, and some advise on
[standard kubernetes things which are not (explicitly) related to WGEE](https://docs.gitops.weave.works/docs/next/guides/cert-manager/).
All of them are somewhat lightweight, and don't provide users with much
opportunity to really sink their teeth into the product, which **really is what
they should be doing**. Many of these guides could easily be moved into general
setup or configuration sections.

The purpose of these guides should be to explain things that users would not be
able to find anywhere else: in other words specific use-cases for our product.

Examples of guides that we could do with that we are now missing:
- How to build a recommended directory structure for:
  - single cluster with some apps
  - management+leaf cluster with some apps
  - management+leaf cluster with semi-complex tenancy
  - (This should actually be a whole subsection under the guides)
- How to configure RBAC, OIDC and tenancy for a management+leaf cluster.
- How to go from having zero policies in place to several policies across more
  than one cluster and tenancy.
- How to use GitOpsSets and Pipelines to manage promotion of multiple apps
  across multiple environments.

**All of the above**, and ideally all guides in general, should have a repo or template
which can be forked/cloned and 'launched' locally within an hour. We should also
take care to title based on outcome, not implementation or technology, eg: 'How
to set up SSO' over 'Configure OIDC'.

Examples:
- https://github.com/fluxcd/flux2-kustomize-helm-example
- https://github.com/fluxcd/flux2-multi-tenancy
- https://fluxcd.io/flux/guides/repository-structure/

A further step would then be to combine several of these tips into larger "best
practices" guides, eg around GitOps at scale.

In the future it would be good to get feedback from Users (internal and external)
to find out what they are trying to do that the docs are NOT currently helping
them with, and working with them to produce that advanced content.

**Comment by LappleApple** [comment]
Closing this issue to restructure the docs improvements info differently. This is all A+ content and it will live on in upcoming work -- thank you for writing it!
