### ISSUE TITLE
Write guide for simple repo/directory structure

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#3503]
**As a WG User** who has a management cluster, 2+ leaf clusters, and a handful (~20-50) of objects (apps/kustomizations/etc), **I would like to** know about how to create a simple repo/directory structure and why I'd do that.

**Acceptance criteria:**
- [ ]  The guide explains what problem the user can solve, why the user wants to solve that problem, and a summary of the outcome
- [ ]  Provides a complete list of prerequisites:
   - [ ]  what state does the cluster need to be in?
    - [ ]  do I need to have set anything up outside the cluster?
    - [ ]  is this guide for a development environment? or do i need a "real" env with network/dns/routing etc?
- [ ] An intuitive journey through the steps
- [ ] Yaml/command output is collapsed to avoid saturating the page
- [ ] Screenshots with readable text, if applicable
- [ ] Every copy-pastable command is tested
- [ ] An example repository that shows the completed solution, which users can easily clone and apply to their cluster if they want

**Comment by LappleApple** [comment]
Moved user story to #3504
