### ISSUE TITLE
Write guide for how to go from zero policy to all the policies

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#3507]
**As a WG User** who has *one management* cluster, *one+ leaf* cluster, and a handful (~10) of objects (apps/kustomizations/etc) and namespaces (~5-10), **I would like to** know how to write policies and properly store them in my GitOps repo, **so that I can** enforce them on my cluster(s). 

**Acceptance criteria:**
- [ ]  The guide explains what problem the user can solve, why the user wants to solve that problem, and a summary of the outcome
- [ ]  Provides a complete list of prerequisites:
   - [ ]  what state does the cluster need to be in?
    - [ ]  do I need to have set anything up outside the cluster?
    - [ ]  is this guide for a development environment? or do i need a "real" env with network/dns/routing etc?
- [ ] An intuitive journey through the steps
- [ ] Yaml/command output is collapsed to avoid saturating the page
- [ ] Screenshots with readable text, if applicable
- [ ] Every copy-pastable command is tested
- [ ] An example repository that shows the completed solution, which users can easily clone and apply to their cluster if they want

**Comment by LappleApple** [comment]
@MostafaMegahid Do we still need to do this ("need" being up to you and team)?
