### ISSUE TITLE
gitops run: replace the `promptui` library for Weave GitOps 

### ISSUE THREAD

**Issue by chanwit** [weaveworks/weave-gitops#3547]
### User Story: 

As a Weave GitOps developer, 
I want to replace the `promptui` library with a more reliable and actively maintained alternative so that I can avoid race conditions and ensure the stability and maintainability of the WG OSS project.

### Acceptance Criteria
- Identify a suitable alternative library that is actively maintained and does not have known race condition issues.
- The new library should provide similar functionality to the `promptui` library, especially the user prompts functionalities.
- Replace all instances of the `promptui` library in the Weave GitOps project with the new library. Also in the `go.mod`.
- Confirm that Weave GitOps continues to function as expected, with no loss of functionality, and without race conditions.

**Comment by opudrovs** [comment]
Investigated the issue. The best option looks like replacing `promptui` with the `survey` library (which is used in GitHub CLI). But more testing concerning binary size and investigation on how how to replace some hardcoded colors in survey with system colors is needed.

Closes as a low-priority issue which would require too much effort right now.
