### ISSUE TITLE
Discussion on `WeGO app status` output format for better CLI experience

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#355]
**Short description**
As a User
When I use `wego app status` command
Then I should see the CLI output with better formatting
And I don't have to rely on UI for proper status output

**Acceptance criteria**
- Formatting `wego app status` output does not introduce more flakiness

**Screenshots** 

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/6e200602-8d3c-40f9-968e-cf26e80dce72)

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/6d26f6f6-f429-4a40-9dfe-e414ff48003f)

**Additional Context**
- [ ] As a user, even if I have access to UI, I want a better CLI experience. I want properly formatted output messages to show up on my console. 
- [ ] As a user, installing WeGO UI components is totally optional. Ergo, I do not want to rely on the UI for a more readable `app status` output
- [ ] As a user, if I decide to forgo installing UI components, I should still have better CLI readability to make use of `wego app status`.

**Comment by rokshana-b** [comment]
CC'ing all folks here to start a discussion on this topic. 
@jrryjcksn @markramm @palemtnrider @pzfreo @iahmad9

**Comment by jpellizzari** [comment]
Sorry mean to hit cancel and accidentally closed the issue. Re-openend.

**Comment by jpellizzari** [comment]
Similar to #535, I have copied the description into the comments. Closing.
