### ISSUE TITLE
Add OIDC Prefix support for impersonation

### ISSUE THREAD

**Issue by adberger** [weaveworks/weave-gitops#3585]
**Problem**

We currently use GitLab as an OIDC provider for logging in to our Kubenetes clusters.
Our kube-apiserver is configured with `--oidc-username-prefix` & `--oidc-groups-prefix` (https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server)

Now we set up the Weave Gitops UI to also use GitLab OIDC.
The problem now is, that Weave GitOps tries to impersonate without the prefix on the cluster and therefore fails.

Example:
GitLab group name: `sre-admins`
Kubernetes group claim: `idp_sre-admins`

We now see the `sre-admins` group in the Weave Gitops UI when we are logged in, and the impersonation tries to access resources as `sre-admins` instead of `idp_sre-admins`.

Does this description makes sense?

**Solution**

Possibly add another flag to set prefix for the OIDC?
Other solutions welcome

**Comment by foot** [comment]
Hi @adberger, thanks for the issue!

Yes, this definitely makes sense and is something we want to add.

Probably into [OIDCConfig](https://github.com/weaveworks/weave-gitops/blob/15becb29f48663bf3e1ad70831d5d7b986b65910/pkg/server/auth/server.go#L109) secret alongside the other configuration.

**Comment by foot** [comment]
- Read prefix values out of OIDCConfig secret
- When impersonating add the appropriate prefixes
