### ISSUE TITLE
Empty groups list with Authentik

### ISSUE THREAD

**Issue by Neferites** [weaveworks/weave-gitops#3588]
**Describe the bug**
Using a secret to configure the groups claim is not working as expected. Despite configuring secret, no groups are found.

**Environment**

- Weave-Gitops Version : v0.20.0
- Flux Version : v0.41.2
- Kubernetes version : 1.25.6

**To Reproduce**

1. create secret 
```
  kubectl create secret generic oidc-auth \
  --namespace flux-system \
  --from-literal=issuerURL=https://my.authentik.url/application/o/Weave/ \
  --from-literal=clientID=Weave \
  --from-literal=clientSecret=mylientsecret \
  --from-literal=redirectURL=https://my.weave/oauth2/callback \
  --from-literal=claimUsername=email \
  --from-literal=claimGroups=groups \
  --from-literal=customScopes=groups,email,openid,offline_access
```
2. Click on OIDC button
3. Chek logs from server and see errors 
```
DEBUG    gitops.auth-server    auth/jwt.go:54    parsing cookie JWT token    {"claimsConfig": {"Username":"email","Groups":"groups"}} 
DEBUG    gitops.auth-server    auth/jwt.go:161    Found principal    {"user": "my_user", "groups": [], "tokenLength": 0, "method": "*auth.JWTCookiePrincipalGetter"}                                                                                        
ERROR    gitops    clustersmngr/factory.go:566    failed filtering namespaces    {"cluster": "Default", "user": "my_user", "error": "user namespace access: users \"my_use\" is forbidden: User \"system:serviceaccount:flux-system:weave\" cannot impersonate resource \"users\" in API group \"\" at the cluster scope"}        
```
-->

**Expected behavior**
Groups should appears as follow : 
 {"user": "my_user", "groups": **["groups1", "groups2"]**, "tokenLength": 0, "method": "*auth.JWTCookiePrincipalGetter"} 

**Additional Context (screenshots, logs, etc)**
Authentik can simulate a JWT payload, and groups are in it : 
```
Example JWT payload (for currently authenticated user)
{
    "iss": "https://authentik.dev.external.bealv.lan/application/o/Weave/",
    "sub": "17696557148a18458bab4b96af130ff73aca751866e",
    "aud": "Weave",
    "exp": 1680465618,
    "iat": 1680463818,
    "auth_time": 1680463818,
    "acr": "goauthentik.io/providers/oauth2/default",
    "email": "***@gmail.com",
    "email_verified": true,
    "name": "Me",
    "given_name": "Me",
    "preferred_username": "Neferites",
    "nickname": "Neferites",
    "groups": [
        "authentik Admins",
        "Admins",
        "Administrators"
    ],
    "username": "Neferites"
}
```

Regards :)

**Comment by chanwit** [comment]
Thank you for reporting @Neferites 

We'll take a look at it shortly.

**Comment by Neferites** [comment]
Hello @bigkevmcd i tried to mix a lot of configuration, but groups are still missing.
Regards

**Comment by bigkevmcd** [comment]
@Neferites It's working with other OIDC providers.

I'm not quite sure what Authentik could be doing that could be breaking this as we are parsing the claims in the same way irrespective of the provider, do you have any additional information to add?

**Comment by Neferites** [comment]
Authentik works fine with weave, i made a misconfiguration.
Groups belongs to the profile scope, witch i did not include in my customScope.
Thx @chanwit  and @bigkevmcd for your time.
Regards
