### ISSUE TITLE
Certain point pressing ^C does not exit cleanly

### ISSUE THREAD

**Issue by kingdonb** [weaveworks/weave-gitops#3591]
**Describe the bug**

When I was testing `gitops beta run` I found some unexpected behavior pressing `^C`

<img width="992" alt="Screenshot 2023-04-03 at 2 45 17 PM" src="https://user-images.githubusercontent.com/3286998/229599304-3b162d7b-5320-47be-9d19-672c4cad2e02.png">

At the "want to install Dashboard?" prompt, I realized that I had intended to call `--no-session`.
I pressed ^C and instead of quitting, I entered "waiting for session to be ready" mode.

I pressed ^C again and it quit normally, I just thought this should be filed as a report for follow-up.

**Environment**

Weave GitOps -ee CLI:
```
Current Version: v0.19.0-276-g005ef26-Enterprise-Edition-v0.20.0
```

**Actual Behavior**

It didn't break anything else, the only problem

**Additional Context (screenshots, logs, etc)**
Attached screenshot above

**Comment by kingdonb** [comment]
Having switched to the fully OSS `gitops` CLI, release version: v0.20.0, I repeated the test on a cluster that has had `gitops run` session cleaned up by deleting the helmrelease off the cluster. This cluster has a prior `gitops` dashboard installed that is detected, and the `gitops run` session is erroring out.

That's because there is no volume provisioning possible, and the stateful set can't exit from Pending into Running.

I press `^C` at the same point in the workflow, (only this time I'm not in the middle of answering a question about the dashboard)

```
$ gitops beta run podinfo-simple
► Checking for a cluster in the kube config ...
► Preparing the cluster for GitOps Run session ...

You can run `gitops beta run --no-session` to disable session management.

If you are running GitOps Run for the first time, it may take a few minutes to download the required images.
GitOps Run session is also required to install Flux components, if it is not installed yet.
You may see Flux installation logs in the next step.

► Creating GitOps Run session run-main-affead38-dirty in namespace default ...

You may see Flux installation logs again, as it is being installed inside the session.

► Waiting for GitOps Run session run-main-affead38-dirty to be ready ...
^C
```

These resources are not cleaned up. I think this is the follow-up issue from #3456, that was intended to be reported there, (but some notes got lost from that initial report as we were in the middle of preparing urgently for a demo, and couldn't stop the works to make a full report at the time... sorry!)

**Comment by chanwit** [comment]
Hi @kingdonb 

Yes, we're working on the proper clean-up process. We will also add a command to do cleanup in case of ^C does not work too.

**Comment by LappleApple** [comment]
@fsequeira1 also had this issue -- frustrating because then you have to take manual steps

**Comment by chanwit** [comment]
@fsequeira1 we already implemented `gitops remove run` to help clean up dangling sessions. Let me know if you still need improvement in some specific area of the cleaning-up process.
