### ISSUE TITLE
Install weave gitops in a second cluster to allow applications to be targeted to it. 

### ISSUE THREAD

**Issue by markramm** [weaveworks/weave-gitops#362]
**Short description**
As a [User Role] I want to [feature/functionality] so that [business outcome/value].

**Acceptance criteria**
- [ ] _does X_
- [ ] _displays Y_
- [ ] _..._

**Design materials**
- Screenshots
- Design diagrams
- WEP 
- PR/FAQ

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by jpellizzari** [comment]
Closing in favor of #71
