### ISSUE TITLE
The YAML tab displays a wrong version of CRD

### ISSUE THREAD

**Issue by chanwit** [weaveworks/weave-gitops#3626]
### Problem

According to this: https://github.com/weaveworks/weave-gitops/blob/5cd78d74f975b68a28572032d143a622058a0117/core/server/primarykinds.go#L21-L34

The DefaultPrimaryKinds() function in the provided code snippet is designed to loop over all known types in the Kubernetes scheme and create a map of GroupVersionKinds (GVKs). However, there is a hidden bug in this function, which makes it unable to obtain the storage version from the scheme.

The issue arises because the function relies on the scheme.AllKnownTypes() map, which contains types registered in the program during compile time. If the program uses a different version of an object (e.g., v1beta2 version of GitRepository) than the environment it's running in (e.g., an environment with the v1 version of GitRepository), the program does not have the knowledge of the environment's version (in this example, GitRepository/v1). This is because the environment's version only exists in the actual cluster, not in the program's registered types.

As a result of this bug, the YAML tab might display incorrect versions of objects, leading to potential issues and inconsistencies when working with Kubernetes objects.

### Proposed solution

To address the bug, the first approach would be to update the program to have matching versions of objects registered, ensuring consistency between the program and the environment it's running in. By doing this, the program will have knowledge of the correct versions and can display accurate information in the YAML tab.

If upgrading the program to have matched versions registered does not resolve the issue effectively, a follow-up ticket will be created to further investigate the problem and find an alternative solution. This ensures that the bug is addressed and the correct versions of objects are displayed, improving the overall user experience and preventing potential issues when working with Kubernetes objects.

**Comment by joshri** [comment]
SO -

My podinfo GitRepo source has matching apiVersion and annotation:
![image.png](https://images.zenhubusercontent.com/617c4a20ede496b2fae35baf/1a503979-b243-413d-be74-30a89c9e6f62)

But my `helloworld` GitRepo source (which is from the tf-controller getting started guide) does not:
![image.png](https://images.zenhubusercontent.com/617c4a20ede496b2fae35baf/5cc5e450-89ec-48e9-91bb-059991c869cf)

When I get the yaml in a terminal, it also doesn't match:
![image.png](https://images.zenhubusercontent.com/617c4a20ede496b2fae35baf/13d0d51d-6d57-4eb4-9039-c0e85fadd0b8)

Which makes me think this isn't something that's happening on the frontend. 

Everything else on my cluster (Helm charts, repos, kustomizations, buckets, and non-flux-primitives) match. Couldn't find another example of this.

**Comment by chanwit** [comment]
I'm talking to Kevin and probably Simon to investigate this.

**Comment by chanwit** [comment]
Found a feasible solution. I'll go fix it this way first.

**Comment by squaremo** [comment]
`kubectl` gives you the preferred version (usually the stored version); so if I create a GitRepository marked as `apiVersion: source.toolkit.fluxcd.io/v1beta2`, it accepts it, and when I `kubectl edit` it, I get a v1 file to edit. I think the same approach would work here: ask the Kubernetes API server what the preferred version is, and use that.

**Comment by foot** [comment]
@bigkevmcd noted we could check out kubectl does it
- https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/get/get.go#L252
- https://github.com/kubernetes/cli-runtime/blob/v0.27.3/pkg/printers/typesetter.go#L41

**Comment by enekofb** [comment]
@chanwit is there anything that we think we would do around this ticket?

**Comment by chanwit** [comment]
I think we could close this issue for now, as the issue would be fixed already by our Flux v2 upgrade.

If the problem still persists, we can reopen this issue.

**Comment by enekofb** [comment]
Based on our finidings yesterday, it seems that we should revisit this logic for the `GitRepository` case where we are not seeing predicable resolution to v1 apiGroup 

https://github.com/weaveworks/weave-gitops/blob/main/core/server/primarykinds.go#L126

Scenario #1  - both gvk exists

```
2023-08-08T07:27:06.856Z	INFO	gitops	server/primarykinds.go:132	AllKnownTypes getPrimaryKinds	{"gvk": "source.toolkit.fluxcd.io/v1beta2, Kind=GitRepository"}
...
2023-08-08T07:27:06.857Z	INFO	gitops	server/primarykinds.go:132	AllKnownTypes getPrimaryKinds	{"gvk": "source.toolkit.fluxcd.io/v1, Kind=GitRepository"}
```

Scenario #2 - only v1 exists 

```
2023-08-08T07:31:09.845Z	INFO	gitops	server/primarykinds.go:132	AllKnownTypes getPrimaryKinds	{"gvk": "source.toolkit.fluxcd.io/v1, Kind=GitRepositoryList"}
2023-08-08T07:31:09.845Z	INFO	gitops	server/primarykinds.go:132	AllKnownTypes getPrimaryKinds	{"gvk": "/v1, Kind=Secret"}
2023-08-08T07:31:09.845Z	INFO	gitops	server/primarykinds.go:132	AllKnownTypes getPrimaryKinds	{"gvk": "notification.toolkit.fluxcd.io/v1beta2, Kind=PatchOptions"}
2023-08-08T07:31:09.845Z	INFO	gitops	server/primarykinds.go:132	AllKnownTypes getPrimaryKinds	{"gvk": "source.toolkit.fluxcd.io/v1, Kind=GitRepository"}
2023-08-08T07:31:09.845Z	INFO	gitops	server/primarykinds.go:132	AllKnownTypes getPrimaryKinds	{"gvk": "kustomize.toolkit.fluxcd.io/v1, Kind=CreateOptions"}
```

We have also seen Scenario #3 - only beta exits

**Comment by enekofb** [comment]
bumping the severity as from v0.29 we want to manage v1 resources over beta

**Comment by enekofb** [comment]
Yes @LappleApple i take over

**Comment by enekofb** [comment]
rolled out to staging looking fine 

<img width="849" alt="Screenshot 2023-09-05 at 12 01 19" src="https://github.com/weaveworks/weave-gitops/assets/12957664/f9c20f94-0140-4632-ac37-5868a96edcb4">


https://gitops.euw1.wego-gke.weave.works/git_repo/yaml?clusterName=Default&name=weave-gitops-enterprise&namespace=flux-system
