### ISSUE TITLE
Argo Application Support in Weave GitOps

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#3630]
As a user, I want to:

1. Click on an Argo Application to view its details, so I can understand the current status and configuration of the application.

    Acceptance Criteria:
    - Display Argo Application's name, namespace, source repository, path, and target cluster
    - Display the Argo Application's sync status, health status, and latest revision information
    - Show the time since the last sync and the last successful sync

2. Resume or suspend an Argo Application, so I can control the synchronization process of my applications.

    Acceptance Criteria:
    - Display buttons to resume or suspend the Argo Application
    - Update the application's status accordingly after resuming or suspending

3. Force a synchronization of an Argo Application, so I can ensure my application is up-to-date with its desired state.

    Acceptance Criteria:
    - Display a "Force Sync" button on the Argo Application details page
    - Trigger a synchronization when the button is clicked

4. View recent events related to an Argo Application, so I can quickly identify issues or changes made to the application.

    Acceptance Criteria:
    - Display an "Events" tab on the Argo Application details page
    - Show a list of recent events with timestamps, types, reasons, and messages

5. View the YAML definition of an Argo Application, so I can see the full details and configuration of the application.

    Acceptance Criteria:
    - Display a "YAML" tab on the Argo Application details page
    - Show the YAML content of the Argo Application in a read-only format

6. Visualize the workloads deployed by an Argo Application, so I can understand the relationship between the application and its deployed resources.

    Acceptance Criteria:
    - Display a "Graph" tab on the Argo Application details page
    - Show a visual representation of the workloads and their relationships within the application

7. Maintain a consistent user experience across Kustomizations, Helm Releases, and Argo Applications, so I can easily navigate and use the Weave GitOps platform.

    Acceptance Criteria:
    - Ensure the same look and feel for Argo Application details pages as Kustomizations and Helm Releases
    - Use the same patterns for actions, tabs, and information display

**Comment by joshri** [comment]
Having trouble getting the argo app through our backend - I have it showing in the argo UI though which is a good start. 
Two questions about what might be going on:
1. Argo getting started guide has me switching kubectl contexts - would that mess with what our backend is looking at in any way?
2. The backend will crash if you ask for anything outside of `scheme.AllKnownTypes` - [link](https://pkg.go.dev/k8s.io/apimachinery@v0.26.1/pkg/runtime#Scheme.AllKnownTypes)
There's an Add function that I can use to slot argo stuff into our default kinds, but I'm REALLY struggling to find what the `GroupVersionKind` would be for these resources.

**Comment by chanwit** [comment]
> The backend will crash if you ask for anything outside of scheme.AllKnownTypes - link

This is very good point as we would also fix this `scheme.AllKnownTypes` things too so that WG OSS would be able support any kind of CRD without importing its dependency into the binary.

**Comment by LappleApple** [comment]
Closing in light of other priorities.
