### ISSUE TITLE
`gitops generate gitopssets list-generator.yaml` for the list-generator

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops#3632]
Alternatives
- refactor the gitopssets packages to expose a way to provide a gitopsset explicitly rather than use the k8s client. Call the functions directly from the `gitops` cli.
- Add a "/evaluate" api endpoint + http server etc to the gitopssets-controller that the `gitops` cli could http POST to.

e.g. reconcileResource:150

**Comment by bigkevmcd** [comment]
@foot I'm going to close this one out
