### ISSUE TITLE
Add Argo Application to known types

### ISSUE THREAD

**Issue by joshri** [weaveworks/weave-gitops#3646]
Part of [3630](https://github.com/weaveworks/weave-gitops/issues/3630)

In order to run our sync, suspend, and events requests on Argo Applications, the `Kind` of `Application` needs to be added to the list of known types. This is before knowing if any other measures need to be taken for Argo apps. Additionally, at least for sync, each kind has an adapter (in fluxsync/adapters.go) so Applications will likely need one as well. 

- [ ] Add `Application` to known types
- [ ] Either break down into smaller issues or confirm that the backend can run sync, suspend, and events reqs for Argo applications.

**Comment by LappleApple** [comment]
Closing in light of other priorities.
