### ISSUE TITLE
Weave Flux CD UI Dashboard for Windows Support

### ISSUE THREAD

**Issue by venkatesh3889** [weaveworks/weave-gitops#3649]
Hello,

It's nice that we now have Gitops Flux UI.
but we could see that we can only use this with Mac and Linux. 

Is there any way that we can can configure this dashboard with windows?

**Comment by opudrovs** [comment]
@venkatesh3889 thank you for your suggestion!

We do not plan to add support for Weave GitOps dashboard UI on Windows.

But you can try running the dashboard on the Windows Subsystem for Linux (WSL 2).
