### ISSUE TITLE
Question: how does the namespace filtering feature work?

### ISSUE THREAD

**Issue by ljakimczuk** [weaveworks/weave-gitops#3652]
Hey, I have some questions about the correct behavior of the namespaces filtering feature.

I have a use case where the Weave GitOps UI v0.18.0 reports lots of errors for some of its users, coming from [this package](https://github.com/weaveworks/weave-gitops/blob/b05ebd8c090f923b4e99f3d1e43f55a47ec857b6/core/server/objects.go#L122), due to insufficient permissions to the Kubernetes Secrets the Helm releases are kept in. The error is correct because the group these users belong to lacks permissions to the secrets in some of the namespaces, they can though still see Flux CRs and related resources. This makes me confused however for I would expect server to filter out such namespaces, if access to the secrets counts as crucial for the namespace to be considered accessible. And if not, then I would expect the UI to not display any errors for the users and instead only display `HelmRelease` CRs without an inventory. 

To be more precise my questions are:
* how is the accessibility / inaccessibility determined, if determined at all?
* does partially accessible, when lacking certain permissions, equals to accessible, and in such case, is there a way to hide permission errors in the UI?
* is there a way to tweak how is the accessibility determined, in case it is not strictly tied to some set of permissions? That is, can I tell the server to skip certain namespaces for certain groups?

I also tried to answer these questions on my own, but got confused by what I have found. I eventually landed in here, in the [nsaccess package](https://github.com/weaveworks/weave-gitops/blob/v0.18.0/core/nsaccess/nsaccess.go#L67), for this seems involved in getting accessible namespaces upon impersonation. If that is the case, and if I get it right, it eventually translates what is returned on the [the SelfSubjectRulesReview request](https://github.com/weaveworks/weave-gitops/blob/4c048c23697ee4f3a463d61bebd15d7447fab8f6/core/nsaccess/nsaccess.go#L91) into [the derivedAccess map](https://github.com/weaveworks/weave-gitops/blob/4c048c23697ee4f3a463d61bebd15d7447fab8f6/core/nsaccess/nsaccess.go#L162). And then policy rules, which are being [these by default](https://github.com/weaveworks/weave-gitops/blob/4c048c23697ee4f3a463d61bebd15d7447fab8f6/core/nsaccess/nsaccess.go#L18), are being [checked against this map](https://github.com/weaveworks/weave-gitops/blob/4c048c23697ee4f3a463d61bebd15d7447fab8f6/core/nsaccess/nsaccess.go#L202) to determine value of [hasAccess boolean](https://github.com/weaveworks/weave-gitops/blob/4c048c23697ee4f3a463d61bebd15d7447fab8f6/core/nsaccess/nsaccess.go#L200), which is initially true. And this is the part that confuses me. 

The [DefautltWegoAppRules](https://github.com/weaveworks/weave-gitops/blob/v0.18.0/core/nsaccess/nsaccess.go#L18) starts with the `{"","secrets,pods,events","get,list"}`. In my case users have access to `pods` and `events`, so the `""` API group is available in the `derivedAccess` map, hence filtering passes the API group check. But then it does not find `secrets`, hence switches `hasAccess` to false, and continues to the [next rules](https://github.com/weaveworks/weave-gitops/blob/4c048c23697ee4f3a463d61bebd15d7447fab8f6/core/nsaccess/nsaccess.go#L217). Shouldn't it break here instead, for it knows the minimum permissions user needs are already incomplete? 

On continuing, it processes the next rules and it eventually gets to the [last item](https://github.com/weaveworks/weave-gitops/blob/4c048c23697ee4f3a463d61bebd15d7447fab8f6/core/nsaccess/nsaccess.go#L44) on the policy rules list, which is being the `{"","events","get,list,watch"}`, and in my case all users are granted this set of permissions, even those who don't have access to the secrets. In result this item passes the API group check, then the resource check, and it gets to the verbs check [here](https://github.com/weaveworks/weave-gitops/blob/4c048c23697ee4f3a463d61bebd15d7447fab8f6/core/nsaccess/nsaccess.go#L221). All the verbs are in the derived map, so the `hasAccess` boolean [is restored](https://github.com/weaveworks/weave-gitops/blob/v0.18.0/core/nsaccess/nsaccess.go#L230) to true, and since it was the last item on the list, the namespace is recognized as accessible as far as I understand it. It looks like user could lack permissions to the Secrets, Pods, and Flux CRs altogether, but having read-only access to `events` would still grant him permissions to the namespace, but maybe I've confused something.

Even for the future sake, is this the part of code that is actually responsible for determining the access? And if so, is my understanding of it correct?

**Comment by ljakimczuk** [comment]
I also played with your unit tests today wondering of why they pass, and I think it is because the required rules is a list with a single item on it, like in [this](https://github.com/weaveworks/weave-gitops/blob/dd28efab3079b643cebe52a1c43efcc9674663b7/core/nsaccess/nsaccess_test.go#L139) test for example, see:

```golang
requiredRules := []rbacv1.PolicyRule{
	{
		APIGroups: []string{""},
		Resources: []string{"secrets", "events", "pods", "namespaces"},
		Verbs:     []string{"get", "list"},
	},
}
```

When the `pods` resource is not found, the `hasAllRules` function continues to the next rule on the list, where there are none left, so it returns false. But, when if I change the required rules list so it resembles more [DefaultWegoAppRules](https://github.com/weaveworks/weave-gitops/blob/dd28efab3079b643cebe52a1c43efcc9674663b7/core/nsaccess/nsaccess.go#L18), like below, then the test fails, for the `hasAllRules` returns true. Processing the first item sets the `hasAccess` to false, but processing the second item resets it to true.

```golang
requiredRules := []rbacv1.PolicyRule{
        {
		APIGroups: []string{""},
		Resources: []string{"pods"},
		Verbs:     []string{"get", "list"},
	},
	{
		APIGroups: []string{""},
		Resources: []string{"secrets", "events", "namespaces"},
		Verbs:     []string{"get", "list"},
	},
}
```

**Comment by foot** [comment]
Hiya, thanks for the issue!


> how is the accessibility / inaccessibility determined, if determined at all?

I think you've got it, the idea is to only show things in the UI a user has access to. Right now this a bit of simple check, if the user has access to all the things mentioned in `DefautltWegoAppRules` in namespaces `foo` and `bar` then we will try and query `foo` and `bar` for the particular resources to show in the UI, e.g. gitrepo/helmrepo on the sources page. The type of the resource at query time is not taken into account, which would be a nice improvement, e.g. so different resources queries would potentially query different namespaces, however this not how it works today.

> does partially accessible, when lacking certain permissions, equals to accessible, and in such case, is there a way to hide permission errors in the UI?

No, its on/off right now.

> is there a way to tweak how is the accessibility determined, in case it is not strictly tied to some set of permissions? That is, can I tell the server to skip certain namespaces for certain groups?

Not right now, this is an interesting use case though.

But!

- What is the error message you are seeing? If you are able to share a screenshot etc that would be great.
- What version of flux are you running?
- Are you able to upgrade to a more recent release? (Not sure if it will fix, but slightly easier to try and repro on this side)

As you say it sounds like we are querying outside of the user's permissions which sounds like a bug. There has been some finicky issues w/ helm-release secrets in the past..

**Comment by foot** [comment]
I see! Great catch and thanks for the solid writeup.

Indeed that is a good bug there, can repro the unit-test failure. I wonder why it's been overlooked, I guess it doesn't appear until you tighten up RBAC around the place.

You've done most of the legwork! Do you wanna put together a PR w/ a test and fix? Otherwise I'm very happy to fix it up this week and make sure we get it into the release next week.

**Comment by ljakimczuk** [comment]
Sorry @foot, I went of straight for short holidays after my last comment and had no Internet to reply you 😅 If you haven't done or started yet, I could gladly take this one

**Comment by foot** [comment]
Yes!

First up thanks for the PR! Great stuff.

Investigating that CI failure at the moment, I think its a fork constraint somewhere.. 👀

**Comment by ljakimczuk** [comment]
Nice! Thank you, I've seen you managed to do it, for the tests are now green <3
