### ISSUE TITLE
Dynamic Menu

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#3663]
**Note: this work is only for the Enterprise Dashboard**

As a user, I want to see only the menu items that I have access to when I log into the WGE UI, so that I can have a more personalized and clutter-free experience.

As a user, I want to receive an appropriate message or notification when I try to access a restricted resource, so that I am aware of my limitations within the WGE UI.

As a user, I want the menu items to be hidden by default if I do not have access to the corresponding resources, to maintain a clean and easy-to-navigate user interface.

As a customer, I want to be able to see the features built by WGE, but have them disabled if they are not listed in my entitlement, so that I can explore the available features without accidentally accessing something I shouldn't.

As a user, I want the WGE UI to disable features based on my entitlement properties, so that I am aware of the additional functionalities I might not have access to but could consider for future use.

As a user, if a particular pages requires multiple objects to have (GET and LIST) I would expect the user to have access to the menu item if they have access to just one of those objects.  The user shouldn't see any errors when they go to that page, they should just see the list of resources they have access to.

As a user, if I go to any of these pages by typing in the URL.  E.g. I do not have access to clusters, but I type in (localhost:8080/clusters) then I receive a 401 (unauthorized) because I don't have the correct permissions.

As a product manager, I want to provide the list of entitlement properties to the development team, so that they can implement the feature disabling functionality accurately in the WGE UI.

As a user, I want the default behavior of the WGE UI to hide menu items for resources I do not have access to, rather than disabling them, to maintain a streamlined and user-friendly interface.

As a user, I want to see in the settings page a list of my user permissions so I know what I have access to.  For enterprise, this should show my permissions across the various clusters that I have privilege access to.

---

### Entitlement 

In the context of a product, "entitlements" refer to the specific features, services, or levels of access that a customer is granted upon purchasing or subscribing to that product. These entitlements are typically linked to the type or level of the product package that the customer has purchased.

For example, in a software product, entitlements might include access to certain functionalities, the amount of storage or resources a user can utilize, the level of customer support they receive, or the number of user accounts they can create. In essence, entitlements define what a customer is "entitled" to use or access within a product based on the terms of their purchase or subscription agreement.

### RBAC (Role Based Access Control)

RBAC is a method of regulating access to computer or network resources based on the roles of individual users within an organization. In Kubernetes (k8s), RBAC is used to control who can access the Kubernetes API and what permissions they have.

Kubernetes RBAC is built around three fundamental components:

Users: These are the entities that interact with the Kubernetes API. They could be actual people, like system administrators, or even services that need to interact with the API.

Roles (or ClusterRoles): A Role or ClusterRole is a set of permissions that represent a specific set of operations (like read, write, etc.) that can be performed on a certain set of resources (like pods, services, etc.). The difference between a Role and a ClusterRole is the scope: Roles apply to a specific namespace, while ClusterRoles apply across all namespaces.

RoleBindings (or ClusterRoleBindings): These are the links that connect Users to Roles or ClusterRoles. A RoleBinding grants the permissions defined in a Role to a User within a specific namespace. Similarly, a ClusterRoleBinding grants the permissions defined in a ClusterRole to a User across all namespaces in the cluster.

With RBAC, administrators can define what actions a user can perform (like creating a pod or viewing a service) and where they can perform them (in which namespaces). This approach allows granular control over access and privileges, enhancing the security of the Kubernetes environment. It ensures that users only have the access they need to perform their tasks, adhering to the principle of least privilege.

### Security Notes

1.  This is purely for the visual layer.  This data should **NOT** be used to allow access to the API.  Let's say a threat actor got access to this data, and updated it to enhance the "scopes" of a user's access.  In this scenario, the threat actor gives the user additional permissions to create, get, and list Canaries.  The only outcome of this is that the "Progressive Delivery" menu item would appear, this would not give them access to the objects via our API.
2.  Do these need to be stored in-memory?  It's not a lot of data, they can probably be stored in-memory?
3. If the user is authorized on the UI, and they switch to the different tab then how should this data persist?  If this data is cached on the backend, then when they open a new tab the front-end should go and fetch that data so the menu can be displayed consistently across the different tabs.
4. What happens when we cannot reach all clusters?
5. What happens when the user is part of multiple groups with different sets of permissions?  This data should be a "union" of those groups.

### Spikes

* What are the endpoints to aggregate this information?
* What additional permissions does Weave GitOps server need to be able to fetch this information?
* Do we have information about user group?  The info should be accessible via Dex.
* This info may already be available in the new explorer BE: https://demo3.weavegitops.com/explorer/access

### Menu Item RBAC Permissions
| No. | Menu Item             | Objects                                            | Operations       |
|-----|----------------------|----------------------------------------------------|------------------|
| 1   | Clusters             | `GitOpsCluster`                                    | GET, LIST        |
| 2   | Templates            | `GitOpsTemplate`                                   | GET, LIST        |
| 3   | GitOpsSet            | `GitOpsSet`                                        | GET, LIST        |
| 4   | Terraform            | `Terraform`         | GET, LIST        |
| 5   | Secrets Management   | `SecretStore`, `ExternalSecret`, `ClusterSecretStore` | GET, LIST  |
| 6   | Applications         | `Kustomization` or `HelmRelease`  | GET, LIST |
| 7   | Sources              | `GitRepository`, `HelmRepository`, `HelmChart`, `OCIRepository`, `Bucket`  | GET, LIST |
| 8   | ImageAutomation      | `ImageRepository`, `ImagePolicies`, `ImageUpdateAutomation` | GET, LIST |
| 9   | Pipelines            | `Pipeline`                                         | GET, LIST        |
| 10  | Progressive Delivery | `Canary` & `Deployment`    | GET, LIST        |
| 11  | Flux Runtime         | N/A                     |                  |
| 12  | Workspaces           | `ServiceAccount`, `Roles`, `RoleBindings`, `Policies` | GET, LIST   |
| 13  | Policies             | `Policy`                                           | GET, LIST        |
| 14  | PolicyConfig         | `PolicyConfig`                                     | GET, LIST        |
| 15  | GitOps Run           | N/A |                  |
| 16  | Notifications        | `Providers`                                        | GET, LIST        |
* The user just needs access to one namespace for any namespaced objects listed above.

Flux runtime is a challenge because while most users might install flux into the namespace `flux-system` that isn't guaranteed.
For Gitops Run, the list page is mainly driven by stateful sets, but these are create dynamically and aren't tied to the user in any meaningful way via RBAC

### Additional Resources
1. https://kubernetes.io/docs/reference/access-authn-authz/rbac/
2. https://demo3.weavegitops.com/workspaces/details/roles?clusterName=management&workspaceName=team-podinfo

**Comment by JamWils** [comment]
cc: @enekofb, @bigkevmcd, @squaremo for feedback.  The team is doing preliminary work.  @enekofb, I already told the team that if this is restricted to customers using the new explorer BE then that works for me.  This was a request from Pepsi.  We are not planning on doing anything for the OSS dashboard.

**Comment by bigkevmcd** [comment]
@JamWils 
> Do we have information about user group? The info should be accessible via Dex.
What does "user group" mean in this case?

Are these the nominal groups that we receive in the OIDC ID Token?

**Comment by LappleApple** [comment]
Are the provided user stories listed by priority?

**Comment by LappleApple** [comment]
Closing for now as this was deprioritized. We can reopen if things change.
