### ISSUE TITLE
Flux version not shown

### ISSUE THREAD

**Issue by makkes** [weaveworks/weave-gitops#3665]
**Describe the bug**

Whenever I access the Dashboard with a user that only has access to a single Namespace, this is what the footer shows:

![2023-05-03_18-16](https://user-images.githubusercontent.com/387444/235977106-e3800ccf-ba16-4d0f-b436-78bb0c0b73b8.png)

The Flux version isn't shown, instead it reads `-`.

**Environment**

- Weave-Gitops Version: 0.22.0
- Flux Version: reproducible with 0.41.2 and 2.0.0-rc.1
- Kubernetes version: 1.27.1

**To Reproduce**

Access the Dashboard with a user that only has access to a single Namespace.

**Expected behavior**

The Flux version is shown. Alternatively show a message that tells me why I can't see the Flux version.

**Actual Behavior**

It just shows `-`.

**Additional Information**

This is logged by the weave gitops container when accessing the version endpoint:

```
2023-05-04T10:01:56.465Z        ERROR   gitops.core-server      server/version.go:104   error getting flux version      {"error": "error getting list of objects"}
```

**Comment by chanwit** [comment]
We don't support v2.0.0-rc.1 of Flux yet so that's the reason it's falling back to -.

Maybe we should have used "Unsupported version" or whatever instead.

**Comment by makkes** [comment]
Updated the description accordingly.

**Comment by makkes** [comment]
Another data point to note is that the Flux Runtime page is very able to show the Flux version (when the user has the necessary permission) whereas the footer is not so it looks like it is generally possible:

![2023-05-05_16-25](https://user-images.githubusercontent.com/387444/236485793-087b3884-e264-408f-a7a1-f466d50d07bb.png)

**Comment by mmorejon** [comment]
I have the same problem. This is my setup.

```
$ flux version
flux: v2.0.1
helm-controller: v0.35.0
image-automation-controller: v0.35.0
image-reflector-controller: v0.29.1
kustomize-controller: v1.0.1
notification-controller: v1.0.0
source-controller: v1.0.1

$ gitops version
Current Version: 0.28.0
GitCommit: 3ad24e719c66f01efa755072476e3aa5efb3e1c9
BuildTime: 2023-07-19T18:04:30Z
Branch: releases/v0.28.0
```
