### ISSUE TITLE
Background image is too small

### ISSUE THREAD

**Issue by joshri** [weaveworks/weave-gitops#3681]
This is specifically for the dark mode background, but check the light mode background as well

<img width="764" alt="image" src="https://github.com/weaveworks/weave-gitops/assets/65822698/3f1482c9-ff3c-4170-a7a4-2ade175edf85">

**Comment by jpellizzari** [comment]
@mmoulian Do you have a bigger image that we can use as the background?

**Comment by mmoulian** [comment]
@jpellizzari I created the background in Illustrator and it works with vectors. This means that I can make the image as we need it.

**Comment by jpellizzari** [comment]
@mmoulian Can you link that image here?

**Comment by jpellizzari** [comment]
@joshri I think I am missing something. Are both images the exact same size? If so, we can just swap one out with the exact same styling logic applied to it, right?

**Comment by joshri** [comment]
@jpellizzari if I just use the images everything scales based on screen width (as it should - demonstrated above) and the wheel is all sorts of different sizes - I'm trying to explain in my novel that as far as I can tell there's no way I can think of to guarantee the position of the 'wheel' part of the image unless we separate it out and absolutely position it. Even then, we'd still need to scale the wheel based on screen size, which means that it's not always going to end up in exactly the same place in relation to the content - but it'd probably be closer.

In order to do that, I'd like the exact gradient of the dark mode background because I'd rather not figure it out with educated guesses like I did with light mode

**Comment by jpellizzari** [comment]
@joshri Alright well lets not have the image get squished like it is in your screenshot. Tough for me to comment without seeing code/PR.

**Comment by joshri** [comment]
Sure - Manuela left a comment in the team channel today saying that she's good on the background, and also reporting something new with the sign in page - so I will make an issue for that and close this issue
