### ISSUE TITLE
Ability to use GitLab groups claim instead of groups_direct claim

### ISSUE THREAD

**Issue by adberger** [weaveworks/weave-gitops#3687]
**Problem**
With [v0.22.0](https://github.com/weaveworks/weave-gitops/releases/tag/v0.22.0) release, we are finally able to implement OIDC with GitLab thanks to #3611.

Now there is a problem with fetching the `groups` claim.
GitLab only includes the `groups_direct` claim in the id token.
The `groups` claim is available on the _/oauth/userinfo_ endpoint:
https://docs.gitlab.com/ee/integration/openid_connect_provider.html#shared-information

Is there a way to solve this?
ArgoCD seemed/seems to have the same problem: https://github.com/argoproj/argo-cd/issues/5944

Additionally setting the `oidc-token-duration` doesn't seem to work with GitLab and we get logged out after a short time with the following Log entries:
```
2023-05-10T08:39:56.756Z	INFO	gitops.auth-server	auth/auth.go:245	refreshing token failed	{"err": "failed to refresh token: oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\"}", "principal": "<nil>"}
2023-05-10T08:39:56.756Z	INFO	gitops.auth-server	auth/auth.go:246	Authentication failed	{"err": "failed to verify JWT token: oidc: token is expired (Token Expiry: 2023-05-10 08:36:33 +0000 UTC)", "principal": "<nil>"}
```

**Solution**

- Would be great if we could set the claim to `groups` instead of `groups_direct`.
- Would be great if the _token duration_ would work correctly.

**Additional context**
Our current configuration looks as follows:
```
additionalArgs:
  - --oidc-client-id=xxx
  - --oidc-client-secret=xxx
  - --oidc-issuer-url=https://git.selfhosted-domain.com
  - --oidc-redirect-url=https://wego.ingress-url.com/oauth2/callback
  - --oidc-token-duration=24h
  - --oidc-username-claim=email
  - --oidc-groups-claim=groups
  - --custom-oidc-scopes=openid,profile,email
  - --oidc-username-prefix=idp_
  - --oidc-group-prefix=idp_
```

- Setting _oidc-groups-claim_ to `groups_direct` we can see the group from GitLab, but only the direct ones (obviously).
- Setting _oidc-groups-claim_ to `groups` returns none.

**Comment by bigkevmcd** [comment]
@adberger Have you tried setting the `--oidc-groups-claim` to `groups_direct` is that failing?

**Comment by adberger** [comment]
> * Setting _oidc-groups-claim_ to `groups_direct` we can see the group from GitLab, but only the direct ones (obviously).
> * Setting _oidc-groups-claim_ to `groups` returns none.

See at the bottom of the issue:
```
Setting oidc-groups-claim to groups_direct we can see the group from GitLab, but only the direct ones (obviously).
Setting oidc-groups-claim to groups returns none.
```

So it's not failing, but because we have indirect groups for the access to kubernetes, we can't list all Flux resources.

**Comment by bigkevmcd** [comment]
@adberger ahh...right, how do you configure your Kubernetes login?

**Comment by adberger** [comment]
We use h[ttps://openunison.github.io/](OPenUnison) with GitLab behind.

api-server looks something like this:
```
    - --oidc-issuer-url=https://openunison.k8s.somedomain.com/auth/idp/k8sIdp
    - --oidc-client-id=kubernetes
    - --oidc-username-claim=email
    - --oidc-groups-claim=groups
    - --oidc-username-prefix=idp_
    - --oidc-groups-prefix=idp_
```

Like I said, setting _oidc-groups-claim_ to `groups_direct`, the impersonation works for the k8s resources which are permitted via a direct group. But we would like to also have the resources from the indirect groups (inherited etc.) aswell.
 
![Screenshot from 2023-05-10 11-17-36](https://github.com/weaveworks/weave-gitops/assets/43774417/c5c94762-3670-4532-9c03-8fde6070045e)
![Screenshot from 2023-05-10 11-18-01](https://github.com/weaveworks/weave-gitops/assets/43774417/7482950a-0416-4821-918a-333c390b5491)

**Comment by bigkevmcd** [comment]
Hello @adberger I'm not sure this is something we want to take on, [Dex](https://dexidp.io/) deals with this (this is linked to from the ArgoCD issue you provided), and to implement it for each provider we would need to replicate Dex's behaviour, which is just not something we want to do.

This might be considered to be a bug in GitLab, but if you look at how Dex deals with it, it does the authentication, and then makes a supplementary call to get the users and add them to the ID token.

As you can imagine, we would need to implement this sort of behaviour for all the cases that Dex handles in our code, and instead I would recommend authenticating via Dex.
