### ISSUE TITLE
Monitor change from Flux upstream and update PRs accordingly

### ISSUE THREAD

**Issue by katya-makarevich** [weaveworks/weave-gitops#3698]
Follow-up ticket for this PR: https://github.com/weaveworks/weave-gitops/pull/3653

**Comment by yiannistri** [comment]
@katya-makarevich can we add more details to this issue? What is the problem we're trying to solve and what is the suggested solution?

**Comment by LappleApple** [comment]
Closing -- we can reopen if we remember what this was
