### ISSUE TITLE
Initial investigation for WGE dark mode

### ISSUE THREAD

**Issue by katya-makarevich** [weaveworks/weave-gitops#3707]
Scope:
- document the current state of WGE UI
- any blockers?
- suggest a plan/options to implement the dark mode in WGE with pros & cons

**Comment by jpellizzari** [comment]
I wouldn’t begin thinking about adding Dark Mode to Enterprise in the near term, for all the reasons Josh listed. There is way too much inconsistency in the code base.

We need to decide what our UI code should look like across both projects, and then work towards that, in my opinion.

**Comment by JamWils** [comment]
@jpellizzari I have to disagree.  These need to be solved, there will never be a good time to do it and it will only be harder in the future.  @LappleApple and @katya-makarevich let me know what help you need to get the FEs to coordinate and establish the right patterns.

**Comment by jpellizzari** [comment]
@JamWils 

> These need to be solved

That is what I am advocating for. Without documenting best practices and holding people to them, how would these be solved?

**Comment by LappleApple** [comment]
Hi @JamWils, Jordan is working on a guide and I'm hearing that it should land quite soon. He's in touch with @yiannistri and @joshri.

**Comment by JamWils** [comment]
Thanks @LappleApple.  Also, my last comment did undermine @jpellizzari and I apologize for my tone.  I meant to say can you and Katya coordinate with him so we can have the dark mode enterprise work unblocked.  As one of the lead FEs in the organization he should approve these patterns for the other engineers to follow moving forward.  Thanks for the extra clarification @jpellizzari!

**Comment by jpellizzari** [comment]
No hard feelings. I realize I didn't offer any solutions in my comment.
