### ISSUE TITLE
Add Violations tab to Policy Details Page

### ISSUE THREAD

**Issue by serboctor** [weaveworks/weave-gitops#3713]
**Story Description**
As a user, I need to know the violations generated per each policy.

**Acceptance Criteria**
-  We need to have 2 tabs in the policy view (Details, Violations)
- Details tab should include all that we already have on the page now.
-  Violations should have the violations for this policy, with filtering options (severity, category) + name search.

**Comment by waleedhammam** [comment]
Backend is done at https://app.zenhub.com/workspaces/team-timberwolf-62d58e5eb866100020d3aeb1/issues/gh/weaveworks/weave-gitops/3720 and merged to application violations
