### ISSUE TITLE
wego app add fails when using with --app-config-url param

### ISSUE THREAD

**Issue by iahmad9** [weaveworks/weave-gitops#372]
**Describe the bug**
`wego app add . --app-config-url`  and `wego app add --url --app-config-url` fails to deploy the app to the cluster

**Environment**
 - wego v0.0.5
 - kubernetes:  v1.20.2

**Affects versions**
30th June Release

**To Reproduce**

1. Get the latest wego binary from nightly build => s3://weave-gitops/nightly/2021-06-22/wego-macOS-latest
2. Create a repo on github to hold the wego config files
3. Create a repo to hold the app/workload manifest files
4. Now run the command from the app repo directory => `wego app add . --app-config-url=<ssh url of config repo inclusive of .git>`
5. Observe that wego app add completes successfully without any error or warning but application is not deployed to the cluster
6. Repeat the steps from 1 to 4 with both `--url` and `--app-config-url` params and observe that behaviour is same

**Expected behavior**
App workload should deploy successfully and when you run `kubectl get pods -A`, it should be in the list.

**Config and Logs**
Complete logs => https://github.com/weaveworks/weave-gitops/runs/2875703487?check_suite_focus=true#step:12:1020

**Screenshots**
![Screenshot 2021-06-22 at 09 47 12](https://user-images.githubusercontent.com/7713444/122894291-f9f5ca00-d33e-11eb-8ac4-a0335b74d0c1.png)

**Comment by luizbafilho** [comment]
Not valid anymore.
