### ISSUE TITLE
Remove "ghost pages" from user guide documentation

### ISSUE THREAD

**Issue by LappleApple** [weaveworks/weave-gitops#3750]
**Describe the bug**

We have several user guide pages showing up on the website that are not listed in the repository. @luizbafilho and I checked yesterday and were stumped. Maybe they live in the cloud. Let's make sure these do not appear in the left-side menu--they're confusing, bring up an inaccurate left-side page menu, and won't look great in Google searches.

- [ ]  Remove this [Introduction](https://docs.gitops.weave.works/docs/next/enterprise/intro/index.html) page. 
- [ ]  Remove the “Enterprise” section it fits under. 
- [ ]  Remove this [Architecture](https://docs.gitops.weave.works/docs/next/architecture) page.
- [ ]  Remove this [Upgrading](https://docs.gitops.weave.works/docs/next/enterprise/upgrading) page.
- [ ]  Remove this [Troubleshooting](https://docs.gitops.weave.works/docs/next/troubleshooting/index.html) page. 
- [ ]  Remove this [Examples](https://docs.gitops.weave.works/docs/next/examples/sock-shop/index.html) page.
- [ ]  Resolve https://github.com/weaveworks/weave-gitops/issues/3556

**Comment by Sajiyah-Salat** [comment]
Hello, I am a beginner and want to work on this issue. Can you please assign me this.

**Comment by LappleApple** [comment]
Hi @Sajiyah-Salat, thank you for your interest in helping out. Unfortunately this issue likely involves internal systems and we'll need to investigate ourselves. What would be greatly helpful is if you could check out our recently updated [WeGO OSS install guide](https://docs.gitops.weave.works/docs/open-source/getting-started/install-OSS/) (three pages) and share your feedback with us about how to improve. And if you spot any errors in the instructions, pointing them out and/or proposing changes would be great so that we can continue improving the UX. How does that sound?

**Comment by LappleApple** [comment]
Closing as duplicate of #3556

**Comment by Sajiyah-Salat** [comment]
Yeah, I will try to do that.
