### ISSUE TITLE
Add automation around keeping in sync with Flux releases

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#377]
As part of our discussion on vulnerability tracking, we decided it would be valuable to stay in sync with Flux binary and controller releases.

Automation can take several forms. Some ideas:
* A new GH issue gets made in the weave-gitops repo when a flux version is released, prompting someone to upgrade wego
* A PR is opened with the new flux version "embedded" for review

Some prior research from [this issue](https://github.com/fluxcd/webui/issues/42):

>@jpellizzari yes we need to keep the UI in-sync with flux2 release, in the same way we do for terraform provider. Some >examples:
>- https://github.com/fluxcd/flux2/blob/main/.github/workflows/update.yaml
>- https://github.com/fluxcd/terraform-provider-flux/blob/main/.github/workflows/update.yaml

>_Originally posted by @stefanprodan in https://github.com/fluxcd/webui/issues/41#issuecomment-840634274_

**Comment by josecordaz** [comment]
I need a token with right access so this works well. I created this ticket https://github.com/weaveworks/corp/issues/1976.
