### ISSUE TITLE
Remove duplicate Policies Icons

### ISSUE THREAD

**Issue by joshri** [weaveworks/weave-gitops#3782]
From https://github.com/weaveworks/weave-gitops/pull/3781

<img width="808" alt="image" src="https://github.com/weaveworks/weave-gitops/assets/65822698/77dca3d0-06d5-45bd-b3ba-159c0faaad83">

This is what I found in Figma if it matters:
<img width="212" alt="image" src="https://github.com/weaveworks/weave-gitops/assets/65822698/1c51d81c-f6b2-4d46-92c1-2850569300f0">

Policies icons need to be more flexible to support both a hollow (for nav) and filled in (for policies pages) style

@TheGostKasper @AsmaaNabilBakr

**Comment by AsmaaNabilBakr** [comment]
@TheGostKasper @joshri It’s not possible to use the same icon for outlined and filled icons. I think it would be better to keep them as they are.

**Comment by joshri** [comment]
> @TheGostKasper @joshri It’s not possible to use the same icon for outlined and filled icons. I think it would be better to keep them as they are.

Have you tried a `className` for the `fill` on the main section (a `path`) on the magnifying glass/checkmark (I believe they are `line` tags in the svg)?

**Comment by AsmaaNabilBakr** [comment]
@joshri  still believe it'll be better to let then as they are, kindly take a look to close this ticket.

**Comment by alfaris** [comment]
We already have icons with both styles
<img width="439" alt="image" src="https://github.com/weaveworks/weave-gitops/assets/1141977/673b38aa-3151-4800-8c0f-3290ecf3284c">

I've putted them on the following link
https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?type=design&node-id=19443-1761&mode=design&t=dJUDNTA4Jat10Kan-4

**Comment by yiannistri** [comment]
@alfaris we don't want to have 2 icons but only 1 icon that can be styled differently. Can you create this for us?

**Comment by alfaris** [comment]
Yes, I've replied with a video explanation on Slack
https://weaveworks.slack.com/archives/CM38KQTEF/p1694083485624679?thread_ts=1694006483.492029&cid=CM38KQTEF
