### ISSUE TITLE
The user should be able to specify the external config repo branch

### ISSUE THREAD

**Issue by luizbafilho** [weaveworks/weave-gitops#380]
**Short description**
As a User I want to be able to specify the external repo branch.

If the app repo and the config repo have different default branches currently wego breaks because it will use whatever was specified for the app repo. ie: you app repo uses `main` your config repo uses `master`.

We currently already check the default branch of the external config repo.

Users will want to open a PR to a specific topic or environment branch.

**Acceptance criteria**
- [ ] the user can have the app repo and the config repo with different branch
- [ ] the `add` command accepts the `--app-config-branch`

**Design materials**
- Screenshots
- Design diagrams
- WEP 
- PR/FAQ

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by jpellizzari** [comment]
@luizbafilho Please fill out why a user would want to do this and what benefit they would get from this feature.

**Comment by luizbafilho** [comment]
if the app repo and the config repo have different default branches currently wego breaks because it will use whatever was specified for the app repo. ie: you app repo uses `main` your config repo uses `master`

**Comment by jpellizzari** [comment]
New directory structure work might negate this as a valid feature.
