### ISSUE TITLE
The user should be able to specify the external repo path

### ISSUE THREAD

**Issue by luizbafilho** [weaveworks/weave-gitops#381]
**Short description**
As a User I want to be able to specify the external repo path where the config files will be saved

As a user picking up an external repo to hold the config, it's natural to expect that companies have a global repo that holds of sort of files, ie: terraforms, ansible, helm charts, plain yaml and such. By not allowing to specify that path, we create a random folders at the root of that repo, I think that's no ideal.

**Acceptance criteria**
- [ ] the `add` command accepts the `--app-config-path` containing the path where flux manifests should be saved instead of hard coded to the root directory
- [ ] The path needs to exist already. We should error if the path does not exist.

**Comment by jpellizzari** [comment]
@luizbafilho Please add more context around the use case and *why* a user would want to do this.

**Comment by luizbafilho** [comment]
As a user picking up an external repo to hold the config, it's natural to expect that companies have a global repo that holds of sort of files, ie: terraforms, ansible, helm charts, plain yaml and such. By not allowing to specify that path, we create a random folders at the root of that repo, I think that's no ideal.

**Comment by jpellizzari** [comment]
From refinement: If specified folder is not hidden (not `.wego`). This allows for multiple paths to be included in the same repo, meaning things are more flexible for the user.

This field needs to be added to the `ApplicationSpec`. 

Dropping two folders called `apps` and `targets` into the root of an repo seems kinda weird. What if you have terraform and ansible files already in there?
