### ISSUE TITLE
Evaluate if the existing API endpoints (`v1/suspend` and `v1/sync`) need to be updated in order to work with Image Repository resources

### ISSUE THREAD

**Issue by yiannistri** [weaveworks/weave-gitops#3821]
We already have existing endpoints that are used to sync/suspend/resume other types of resources. We need to evaluate whether these same endpoints can **also** be used for Image Repository resources.

Context:
https://fluxcd.io/flux/components/image/imagerepositories/#suspend
https://fluxcd.io/flux/components/image/imagerepositories/#triggering-a-reconcile

**Comment by LappleApple** [comment]
Olga researching the issue.
