### ISSUE TITLE
gitops-server helm chart: Missing fields for oidc auth secret

### ISSUE THREAD

**Issue by tommyreilly** [weaveworks/weave-gitops#3833]
**Describe the bug**

The documentation for oidc describes the ability to define the following fields for the secret:

https://docs.gitops.weave.works/docs/configuration/oidc-access/#scopes

```
  --from-literal=tokenDuration=<token-duration> \
  --from-literal=customScopes=custom,scopes
```

https://docs.gitops.weave.works/docs/configuration/oidc-access/#claims

```
  --from-literal=claimUsername=sub \
  --from-literal=claimGroups=groups
```

The gitops-server helm chart secret does not provide the ability to set these fields in the oidc-auth-secret.yaml and they are not referenced in the values.yaml

https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/templates/oidc-auth-secret.yaml

```
# https://docs.gitops.weave.works/docs/configuration/securing-access-to-the-dashboard/#login-via-an-oidc-provider
oidcSecret:
  create: false
  # clientID:
  # clientSecret:
  # issuerURL:
  # redirectURL:
```
  
**Environment**

- Weave-Gitops Version: v0.27.0
- Flux Version: 2.0.0
- Kubernetes version: 1.26

**Expected behavior**

This is a request to enhance the chart to include these fields

**Comment by bigkevmcd** [comment]
@tommyreilly thanks for reporting this, we'll get it addressed as a bug.

**Comment by tommyreilly** [comment]
Thanks @bigkevmcd, appreciate it.

Tommy

**Comment by AhmedQaziMuhammadJamil** [comment]
Hi @bigkevmcd I am also facing the same issue. I tried to add customscopes  and Claimgroups through the values.yaml  but the outcome is the same.The secret is never created with customscopes and Claimgroups.

**Comment by dmcanally-leolabs** [comment]
I see the PR got closed. I'm having this same issue as well.

**Comment by bcorijn** [comment]
I opened up a new PR, I missed the previous one got closed until I already had my fork ready, but I feel there's still a need/use case for this anyway.
