### ISSUE TITLE
Upgrade Flux v2 dependencies - Take 3

### ISSUE THREAD

**Issue by chanwit** [weaveworks/weave-gitops#3878]
In order to fully support flux GA we need to upgrade weave gitops flux apis to use v2.0.0 apis

AC

- weave gitops using [flux v2.0.0 apis](https://github.com/fluxcd/flux2/releases/tag/v2.0.0)
- weave gitops should manage GitRepository, Kustomization and Receiver as v1 
- reduced scope of the impact for weave gitops ee by not upgrading controller runtime nor kube apis

**Comment by enekofb** [comment]
@chanwit added description to the ticket, feel free to modify it
