### ISSUE TITLE
Letter spacing in Tabs text

### ISSUE THREAD

**Issue by mmoulian** [weaveworks/weave-gitops#3884]
Text inside the tabs have to follow the same "Letter Spacing Style" as the others components

Tabs have 1 pixel of letter spacing each (12/ semibold/ 1px)

**Image of the Demo:**
![Captura de Pantalla 2023-07-25 a las 17.52.19.png](https://images.zenhubusercontent.com/64ad7261e8ff8333028723ac/7d5f1a83-d622-4e0e-9798-1398ce9efdc1)

**Image of the Figma files:** 
![Captura de Pantalla 2023-07-25 a las 17.57.34.png](https://images.zenhubusercontent.com/64ad7261e8ff8333028723ac/61a4d851-2fa4-427f-b169-6d4d5c5f6bd6)

See Design System:
https://www.figma.com/file/gnodK9xtoOahXBqa6ONsA5/WW-Design-System?type=design&node-id=2907%3A8713&mode=design&t=gJz0fdnU97xYQisY-1

**Comment by jpellizzari** [comment]
@mmoulian What is the deliverable here? Are the tab components "out of compliance" with the Figma files, and if so, how can we fix it.

**Comment by mmoulian** [comment]
@jpellizzari 
This is a small detail. I will try to explain myself better. All components (buttons and sidebar) have 1px letter spacing in the text, but tabs don't (at least I can't see it visually or in code)

<img width="1050" alt="Captura de Pantalla 2023-08-16 a las 14 47 26" src="https://github.com/weaveworks/weave-gitops/assets/95616291/8eea933e-0091-4abe-b3fc-3ff7f847991d">

<img width="623" alt="Captura de Pantalla 2023-08-16 a las 14 53 31" src="https://github.com/weaveworks/weave-gitops/assets/95616291/4323b935-17a1-49a8-90fe-09220a9bd813">

**Comment by opudrovs** [comment]
@jpellizzari @mmoulian if this issue is OK to pick up, I can add the required letter spacing. I need a couple of small issues to work on until Monday or Tuesday.

**Comment by jpellizzari** [comment]
@opudrovs Yes go ahead :)

**Comment by opudrovs** [comment]
@mmoulian I've checked for this issue in OSS and see that both locally built OSS and the staging demo os OSS has proper letter spacing of 1px in the tabs text. So, it must be an enterprise issue only. Will try it locally with the main branch of enterprise now.

<img width="1515" alt="Screenshot 2023-09-05 at 15 29 47" src="https://github.com/weaveworks/weave-gitops/assets/8824708/949efb84-4c3b-412b-bd80-b7509b269d1f">

<img width="1535" alt="Screenshot 2023-09-05 at 15 32 14" src="https://github.com/weaveworks/weave-gitops/assets/8824708/8e9155a3-caaa-43d5-a6b6-5deab4d2d712">

**Comment by opudrovs** [comment]
As discussed with @joshri , the current issue might be fixed by the following PR:
https://github.com/weaveworks/weave-gitops/pull/3989
which closes issue #3918 

This PR moves styles for the `SubRouterTabs` component used by WGE from the `ui/lib/theme.ts` file in OSS to `SubRouterTabs`. So, this should add the required `letter-spacing: `1px` to tabs in WGE.

But to test it I need that PR merged first, because trying to update WGE from this PR branch throws and error for me (and from the local files too), maybe because of the step "publish js library" skipped in the PR.

**Comment by mmoulian** [comment]
Hi @opudrovs! I'm looking at the EE demo and it's fixed. Thank you!

**Comment by opudrovs** [comment]
@mmoulian great, thanks for verifying it!

(Actually, it was not much to do here, I just waited until the OSS PR which moved the tab styles to the component instead of global styles is merged and updated enterprise with the latest OSS + fixed a broken snapshot test.)
