### ISSUE TITLE
GitHub release and Helm chart are published before images are ready

### ISSUE THREAD

**Issue by makkes** [weaveworks/weave-gitops#3907]
**Describe the bug**

With each Weave GitOps release the chart is updated prematurely so that upgrades fail as long as the images haven't been built, yet.

**Environment**

- Weave-Gitops Version: all
- Flux Version: n/a
- Kubernetes version: n/a

**To Reproduce**

Immediately after a Weave GitOps release is published, try to install that release.

**Expected behavior**

The release installs successfully.

**Actual Behavior**

Installation fails:

```
weave-gitops-648b7f9655-ll4zn   0/1     ImagePullBackOff   0          11m
weave-gitops-648b7f9655-ll4zn   0/1     ErrImagePull       0          11m
```

**Comment by tsunamaru** [comment]
Just faced the same issue when flux applied weave-gitops helm chart.  
Looks like image build job is stuck: https://github.com/weaveworks/weave-gitops/actions/runs/5738127454/job/15551440034

**Comment by makkes** [comment]
@tsunamaru thanks for verifying. The build job usually takes ~1.5h so that's expected.

**Comment by adelmoradian** [comment]
seems to be working now again!

**Comment by enekofb** [comment]
Thanks all for reporting and following up!  We will look into it to avoid it happening in the future.

**Comment by stefanprodan** [comment]
I would change the title to 

> GitHub release and Helm chart is published before images are ready

The release workflow should be:
- build and push container image
- build and push Hem chart
- run goreleaser

**Comment by enekofb** [comment]
Previous spike effort https://github.com/weaveworks/weave-gitops/issues/3157

**Comment by enekofb** [comment]
Release PR examples 

- [v0.28](https://github.com/weaveworks/weave-gitops/pull/3856)
- [v0.29](https://github.com/weaveworks/weave-gitops/pull/3906)

**Comment by enekofb** [comment]
**Done so far:** 

- We have implemented guardrails to avoid this issue from happening (as in v0.29 release with chart published before image with users impact). Attached PRs for full context on the solution. 
- Today's release v0.30 should help us to validate it. 

**Validation of the solution after merging:**

- [x] works as expected for push on [main](https://github.com/weaveworks/weave-gitops/commit/91e7f412c1d4dc7f694164973a96c4b7fa50e618)
- [x] works as expected for [non-release pr](https://github.com/weaveworks/weave-gitops/pull/3944)
- [ ] works as expected for release pr 

Suggestions for publishing release and

**Comment by makkes** [comment]
Strictly speaking this hasn't been completely resolved as the GitHub release is still created and announced (e.g. on Slack) prematurely, i.e. before the new chart version is actually available.

**Comment by enekofb** [comment]
> Strictly speaking this hasn't been completely resolved as the GitHub release is still created and announced (e.g. on Slack) prematurely, i.e. before the new chart version is actually available.

You are right, i have removed that expectation from the issue title and reflected in the follow up ticket https://github.com/weaveworks/weave-gitops/issues/3945
