### ISSUE TITLE
Tab View Enhancement

### ISSUE THREAD

**Issue by alfaris** [weaveworks/weave-gitops#3918]
### The Problem
Tabs are not visually related to the content beneath them, as shown in the screenshot below:
<img width="1051" alt="image" src="https://github.com/weaveworks/weave-gitops/assets/1141977/1cd59fe8-abe8-4513-bb03-4bd0e39d89e9">

This inconsistency is observed across the system and on various pages.

### Proposed Solution
A small enhancement that adds an underline will effortlessly address this issue and create a better visual connection between the tabs and their corresponding content.
as shown in the screenshot below:
<img width="1184" alt="image" src="https://github.com/weaveworks/weave-gitops/assets/1141977/ba74a51d-0a7e-46ee-9529-87b545e505a5">

 Please feel free to share your thoughts so we can further improve the user experience. Thank you!

**Comment by alfaris** [comment]
@mmoulian 
I looked for using underline with an active bigger underline, and it's okay to use them together
as shown in the screenshot below:
<img width="584" alt="image" src="https://github.com/weaveworks/weave-gitops/assets/1141977/5aedd399-d2a4-4039-9ae2-64e95b152445">

According to Carbon Design System that we rely on as a guideline for dashboards, more details on the following link
https://carbondesignsystem.com/components/tabs/usage/

**Comment by mmoulian** [comment]
Thanks @alfaris; I like the idea of increasing the visual connection to the tab with its corresponding content. I think the line is a good idea, but maybe we need something else. I did this couple of options. What do you think?:
![Tab-2](https://github.com/weaveworks/weave-gitops/assets/95616291/a0c05d59-9f4c-4293-bf3c-c8ffd8a87844)


![Tab-3](https://github.com/weaveworks/weave-gitops/assets/95616291/997ee13e-4eaf-43fa-a0f8-999968679879)

**Comment by katya-makarevich** [comment]
@jpellizzari please kindly review and advise on the priority: do we have time and resources to implement this?

**Comment by jpellizzari** [comment]
> @jpellizzari please kindly review and advise on the priority: do we have time and resources to implement this?

I cannot advise on priority, as this is a subjective aesthetic change that the design team is asking for, and they would have to determine the priority.

I can say that I think this is a pretty simple change from a feasibility perspective.

@mmoulian @alfaris Have you come to a consensus on which concept you would like to go with?

Putting on my designer hat, this one makes the most sense to me:

https://user-images.githubusercontent.com/95616291/258847077-a0c05d59-9f4c-4293-bf3c-c8ffd8a87844.png

**Comment by mmoulian** [comment]
@jpellizzari  Thanks for your answer. We don't have a consensus. I also like the option you point out. How do you usually make a decision? A poll in Slack?

**Comment by jpellizzari** [comment]
> @jpellizzari Thanks for your answer. We don't have a consensus. I also like the option you point out. How do you usually make a decision? A poll in Slack?

Up to you how you want to arrive at a consensus :). Just comment here when we have the desired design selected.

**Comment by jpellizzari** [comment]
@alfaris or @mmoulian Can you provide a link to the Figma for that view?

**Comment by alfaris** [comment]
@jpellizzari 
https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?type=design&node-id=19136-224722&mode=design&t=ZFNUhZUnh8t6oywH-4

**Comment by AsmaaNabilBakr** [comment]
@jpellizzari I'll not be able to attend the meeting tomorrow because I will be OOO, so I'll work on this ticket.

**Comment by yiannistri** [comment]
For what it's worth, I agree with the option that @jpellizzari proposes and @mmoulian agreed to. In my opinion, It looks nicer and more polished than what's currently in Figma and what's been done in #3989 .

**Comment by LappleApple** [comment]
+1 to @yiannistri's comment.

**Comment by TheGostKasper** [comment]
@mmoulian any updates, should we merge https://github.com/weaveworks/weave-gitops/pull/3989 or there's a change need to be done ?

**Comment by alfaris** [comment]
I've made a dark mode version on the same link
<img width="831" alt="image" src="https://github.com/weaveworks/weave-gitops/assets/1141977/2ac3e543-6893-454c-9dea-abb0901becdc">

I hope we can apply it across the system to be coherent experience, and let me know if you needed any help
