### ISSUE TITLE
GitOps Run fails on macOS using local k3d cluster: can't mount /etc/machine-id

### ISSUE THREAD

**Issue by MisterWS** [weaveworks/weave-gitops#3956]
**Describe the bug**

When running `gitops beta run` on macOS using a k3d local cluster, setup fails at this step:

```
► creating HelmRelease flux-system/fluent-bit
► waiting for HelmRelease flux-system/fluent-bit to be ready
✗ HelmRelease flux-system/fluent-bit failed to become ready
✗ Fluent Bit installation failed: timed out waiting for the condition
Error: timed out waiting for the condition
```

On further investigation, this appears to be because the fluent-bit pod is trying to mount the HostPath `/etc/machine-id` - which does not exist inside the k3d server container image (`docker.io/rancher/k3s:v1.27.4-k3s1`, in my particular case).

**Environment**

- GitOps version: 0.30.0
- Flux version: v2.0.1
- Kubernetes version: k3s:v1.27.4-k3s1
- macOS version: Ventura 13.5
- [colima](https://github.com/abiosoft/colima) version (used as Docker dev environment): 0.5.5

**To Reproduce**

1. Create a k3d cluster: `k3d cluster create flux-test`
2. Run GitOps Run against chosen directory: `gitops beta run . --context k3d-flux-test --no-session --no-bootstrap`

**Expected behavior**

GitOps Run should create resources needed.

**Actual Behavior**

Error above is shown.

**Additional Context (screenshots, logs, etc)**

**Comment by MisterWS** [comment]
To workaround this, I have included the following section in my k3d config file:

```yaml
volumes:
  - volume: /etc/machine-id:/etc/machine-id
    nodeFilters:
      - server:*
      - agent:*
```

**Comment by LappleApple** [comment]
Hello @MisterWS, thanks for sharing your workaround. We've included it in our user docs [here](uhttps://docs.gitops.weave.works/docs/next/gitops-run/gitops-run-get-started/#troubleshooting-tips) with a link back to this issue so you get credit. Let us know if you have any other issues or if you'd like to contribute to the project.
