### ISSUE TITLE
GitOps create dashboard export error

### ISSUE THREAD

**Issue by yodamad** [weaveworks/weave-gitops#3957]
**Describe the bug**

Running the [official doc](https://docs.gitops.weave.works/docs/open-source/getting-started/install-OSS/) to setup dashboard, the yaml generated is incorrect with the latest version of Flux.

Generated value for `HelmRepository` in `weave-gitops-dashboard.yaml` is 
```yaml
apiVersion: source.toolkit.fluxcd.io/v1
```
and it should be
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
```

**Environment**

- Weave-Gitops Version

```bash
❯ gitops version
Current Version: 0.30.0
GitCommit: 8d13b121c8fdce8904093c2d74c0a9b440a275d2
BuildTime: 2023-08-16T15:40:19Z
Branch: releases/v0.30.0
```

- Flux Version
```bash
❯ flux version
flux: v2.0.1
helm-controller: v0.35.0
kustomize-controller: v1.0.1
notification-controller: v1.0.0
source-controller: v1.0.1
```

- Kubernetes version : `1.26.0`

**To Reproduce**

follow the [official doc](https://docs.gitops.weave.works/docs/open-source/getting-started/install-OSS/)

**Expected behavior**

weave components are installed

**Actual Behavior**

nothing is installed (helm-controller doesn't detect the configuration)

**Additional Context (screenshots, logs, etc)**

**Comment by yiannistri** [comment]
@chanwit @enekofb this seems related to the Flux v2 support you've been looking at, if so can you investigate?

**Comment by enekofb** [comment]
That sounds definitely around the upgrade. I will try to look today.

**Comment by enekofb** [comment]
I think it comes from here:

https://github.com/weaveworks/weave-gitops/blob/e3b0570bb0d33c8433cc804252f23a2f33769ccd/pkg/run/install/install_dashboard.go#L304 

testing and raising PR if so

**Comment by enekofb** [comment]
with the change

```bash
go run cmd/gitops/main.go create dashboard ww-gitops \                                                                                                     --password=$PASSWORD \
  --export

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  annotations:
    metadata.weave.works/description: This is the source location for the Weave GitOps
      Dashboard's helm chart.
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/created-by: weave-gitops-cli
    app.kubernetes.io/name: weave-gitops-dashboard
    app.kubernetes.io/part-of: weave-gitops
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 1h0m0s
  type: oci
  url: oci://ghcr.io/weaveworks/charts
```

**Comment by enekofb** [comment]
PR raised, please @yiannistri @chanwit review it whenever you can.

**Comment by yodamad** [comment]
Let me know if you want me to test it when fixed & released

**Comment by enekofb** [comment]
Thanks you @yodamad. 

It will be part of next release (v0.31) which is expected to be released next Wednesday.

**Comment by enekofb** [comment]
Hi @yodamad  latest release is out in case you were waiting for it! 

Please let us know in case you find any further issue. 

Thanks!
