### ISSUE TITLE
Gitlab as an OIDC provider fails due to differing /oauth/ endpoints

### ISSUE THREAD

**Issue by pspurlock07** [weaveworks/weave-gitops#3997]
**Describe the bug**

Using Gitlab as an OIDC provider only works in a very limited fashion because the OIDC endpoints are different than what flux assumes.

Currently, Gitlab's OIDC endpoints all start with `/oauth/` such as `https://gitlab.com/oauth/authorize` but flux assumes these endpoints would fall under `/oauth2/` and so it fails.

I did not see a way to change the endpoints for weave-gitops to match gitlab either.

**Environment**

- Weave-Gitops - v0.31.2
- Flux Version - v2.1.0
- Kubernetes - v1.27.4

**To Reproduce**

Create a Gitlab App inside gitlab with OIDC access and use the credentials in your `oidc-auth` secret. Try to login with gitlab as an oidc in weave-gitops

**Expected behavior**

OIDC authorizes and pulls user info

**Actual Behavior**

errors like this:

```
2023-09-08T18:18:12.130Z	INFO	gitops.auth-server	auth/server.go:462	failed to get ID Token from request
2023-09-08T18:18:12.130Z	INFO	gitops	middleware/middleware.go:61	request error	{"uri": "/oauth2/userinfo", "status": 400}
2023-09-08T18:18:12.239Z	INFO	gitops.auth-server	auth/server.go:462	failed to get ID Token from request
2023-09-08T18:18:12.239Z	INFO	gitops	middleware/middleware.go:61	request error	{"uri": "/oauth2/userinfo", "status": 400}
```

**Comment by bigkevmcd** [comment]
Hello @pspurlock07 can you confirm what you are setting your Issuer URL to?

**Comment by bigkevmcd** [comment]
@pspurlock07 Can you confirm that going to https://<whatever you put in as your issuer URL/.well-known/openid-configuration gets a JSON response?

**Comment by pspurlock07** [comment]
It does, and it matches what is at https://gitlab.com/.well-known/openid-configuration (sans the differing hostname)

**Comment by bigkevmcd** [comment]
@pspurlock07 this...

errors like this:
```
2023-09-08T18:18:12.130Z	INFO	gitops.auth-server	auth/server.go:462	failed to get ID Token from request
2023-09-08T18:18:12.130Z	INFO	gitops	middleware/middleware.go:61	request error	{"uri": "/oauth2/userinfo", "status": 400}
2023-09-08T18:18:12.239Z	INFO	gitops.auth-server	auth/server.go:462	failed to get ID Token from request
2023-09-08T18:18:12.239Z	INFO	gitops	middleware/middleware.go:61	request error	{"uri": "/oauth2/userinfo", "status": 400}
```
Just means that you aren't logged in, the page is attempting to poll data.

I've just tested this against a GitLab installation, and it seems to work fine.

Some things to check...
1. Your "GitLab application" has the _openid_ scope.
2. Your OIDC secret is in the right place, it will log out that it has parsed the OIDC secret when debug logging is turned on.

```
2023-09-13T15:42:00.844Z	DEBUG	gitops	auth/init.go:77	OIDC config	{"IssuerURL": "https://gitlab.example.com", "ClientID": "<redacted>", "ClientSecretLength": 64, "RedirectURL": "http://localhost:9001/oauth2/callback", "TokenDuration": "1h0m0s"}
```
I'm not quite sure what part of Flux you're running into here when you say:

> Currently, Gitlab's OIDC endpoints all start with /oauth/ such as https://gitlab.com/oauth/authorize but flux assumes these endpoints would fall under /oauth2/ and so it fails.

But the URLs will likely have `oauth2`, and this doesn't mean that we can't access them, we use the "discovery" mechanism which will ask for that `/.well-known/openid-configuration` URL and then talk to the URLs that it provides, they are served by the GitLab instance, so they are almost always going to be correct (even if they include `oauth2`).

**Comment by pspurlock07** [comment]
okay, I think I see now. Here's how I went down the apparently wrong rabbit hole.

When I login with gitlab, I am not redirected to the weave-gitops ui, I am directed to a page on gitlab with an error `The requested scope is invalid, unknown, or malformed.`

In order to fix this, I added the option `--from-literal=customScopes=email` to `oidc-auth` after I saw that gitlab says it only presents group info in the `/userinfo/` endpoint, and correlating that with the error I was seeing above `{"uri": "/oauth2/userinfo", "status": 400}`

At that point, I thought that was erroring because gitlab's endpoints are `/oauth/` and that error says `/oauth2/`

However, I only realized after your last comment that my error above is presented at the start before I even attempt a login so it wasn't correlated.

Thanks for your quick response on this by the way.

**Comment by bigkevmcd** [comment]
Ahh..thanks for updating, I would recommend Dex for solving the "groups" problem (either that or use `direct_groups` as a scope and groups claim)

https://dexidp.io/docs/connectors/gitlab/

Dex does a supplemental query to inject the groups into the ID Token that they serve to the downstream OIDC Client (i.e. weave-gitops).

**Comment by pspurlock07** [comment]
Perfect, I will look into that.  Thanks again @bigkevmcd I will go ahead and close this.
