### ISSUE TITLE
Sub-Paths not working with OAuth2

### ISSUE THREAD

**Issue by steigr** [weaveworks/weave-gitops#4016]
**Describe the bug**

In #3992 sub-path support for the UI has been introduced.

If I configure wego with oauth2 authentication I get redirected (e.g. from /wego sub-path) to /oauth2 and not $subpath/oauth2.

**Environment**

- Weave-Gitops Version : v0.32.0
- Flux Version: /n/a
- Kubernetes version: n/a

**To Reproduce**

1. Set up wego with OAuth2.
2. Configure OAuth2 / OIDC provider. ( via oidc-auth secret from helm chart).
3. Set clientID/clientSecret/issuerURL.
4. Set callbackURL to $wegoBaseUrl  + "/oauth2/callback" ( e.g. https://example.com/wego/oauth2/callback )
5. Open the UI.
6. Click on "Login with OIDC Provider".

**Expected behavior**

After clicking the "Login with OIDC Provider" button there should be a redirect to the provider and after successful authentication the callback should provide wego the required information (thus forwarding after login to the "real" UI).

**Actual Behavior**

1. Nothing (HTTP/404).
2. After adding the path /oauth2 to the ingress I just get redirected back to the login screen.

**Additional Context (screenshots, logs, etc)**

I think, as #3992 covered the path-prefix for the UI only, OAuth2 should made aware of the prefix as well.

**Comment by bigkevmcd** [comment]
@steigr thanks again, this should be in the next release.
