### ISSUE TITLE
Document the OIDC Secret Configuration

### ISSUE THREAD

**Issue by Cajga** [weaveworks/weave-gitops#4024]
**Problem**

We are using AzureAD for kubernetes authentication. Every user is assigned to project specific groups in AzureAD and AzureAD groups then bind to kubernetes roles based on their IDs.

For the kube-apiserver we are also using `--oidc-username-prefix=aad:` and `--oidc-groups-prefix=aad:` to be able to immediately understand if a user/group is coming from AzureAD.
This basically results in groups like `aad:288a98e3-2940-4d91-f34d-dd388878964b` that we then use to configure in rolebindings.

Unfortunately, weave-gitops will try to impersonate to the group that is coming in the access_token (the id without the aad: prefix) and will have no roles assigned.

**Solution**

Please allow to define oidc-username-prefix and oidc-groups-prefix in the oidc-auth secret so the config of weave gitops is in pair with the kube-apiserver config.

**Additional context**

* [kubernetes docs about the kube-apiserver parameters](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server)

**Comment by bigkevmcd** [comment]
We do support these, we can improve the documentation for this.

But, you have the same command-line options for doing this, you'll need to pass them as `additionalArgs` in the Helm chart values.

`--oidc-username-prefix` and `--oidc-group-prefix` both work as you'd expect.

**Comment by Cajga** [comment]
Thanks a lot for the prompt information.
