### ISSUE TITLE
Helm upgrade failed: "dex" has no deployed releases

### ISSUE THREAD

**Issue by UGS-DanielSoriano** [weaveworks/weave-gitops#4040]
**Describe the bug**

I am trying to use Dex as OIDC Provider for Weave GitOps Dashboard by following your [guide](https://docs.gitops.weave.works/docs/guides/setting-up-dex/), but I am getting `Helm upgrade failed: "dex" has no deployed releases`.

**Environment**

- Weave-Gitops Version: 0.24.0
- Flux Version: 2.1.0
- Kubernetes version: 1.27

**To Reproduce**

1. Create a HelmRepository and HelmRelease object from you [guide](https://docs.gitops.weave.works/docs/guides/setting-up-dex/#deploy-dex).

**Expected behavior**

HelmRelease status should be `Release reconciliation succeeded`.

**Actual Behavior**

Returning an error `Helm upgrade failed: "dex" has no deployed releases`.

**Additional Context (screenshots, logs, etc)**

<img width="513" alt="Screenshot 2023-09-22 at 8 39 23 PM" src="https://github.com/weaveworks/weave-gitops/assets/100192893/0d9fff36-3ef4-43cf-a326-ff206a7dd5b3">

**Comment by yiannistri** [comment]
@UGS-DanielSoriano thank you for raising this issue. I have tested the latest version of the Dex chart (v0.15.3) and it works well with Weave GitOps. I have opened a PR to reflect this in our docs.
