### ISSUE TITLE
Message "spec.Kubeconfig is set on this HelmRelease" shows on Kustomizations

### ISSUE THREAD

**Issue by makkes** [weaveworks/weave-gitops#4057]
**Describe the bug**

Looking at the details of a Kustomization shows the message "spec.Kubeconfig is set on this HelmRelease. Details about reconciled objects are not available.".

This happens on Kustomizations that don't even have `.spec.kubeConfig` set.

Also the field name is `kubeConfig`, not `Kubeconfig`.

**Environment**

- Weave-Gitops Version: 0.33.0
- Flux Version: 2.1.1
- Kubernetes version: 1.28.1

**To Reproduce**

Look at any Kustomization.

**Expected behavior**

The whole message shouldn't be there.

**Additional Context (screenshots, logs, etc)**

![screenshot_c582e](https://github.com/weaveworks/weave-gitops/assets/387444/01f121cc-5354-4fe9-b3e1-36987f0a2c96)

**Comment by yiannistri** [comment]
This message was introduced in https://github.com/weaveworks/weave-gitops/pull/4021 cc @foot

**Comment by enekofb** [comment]
Closing as fixed by the attached PR. Should be available in the next release.
