### ISSUE TITLE
Option to completely remove login

### ISSUE THREAD

**Issue by rileyai-dev** [weaveworks/weave-gitops#4060]
**Problem**

I would like to have access to weave gitops without any login. The use case is that we have implemented weave gitops in a console which is already secured. The problem is now we have to login to get access to the console and login again to have access to weave gitops. This would be useful for anyone who would like to add it through and iframe or a proxy.

**Solution**

Simply add an option for an insecure access or hard code a password somewhere (we use helm to deploy so it would be nice to be able to configure it through this)

**Additional context**

**Comment by bigkevmcd** [comment]
You can already do this, this PR will land with documentation, but you can see what you need in the docs.

https://github.com/weaveworks/weave-gitops/pull/4034/files

**Comment by bigkevmcd** [comment]
@rileyai-dev I'm closing this for now, feel free to reopen it if you need more information.
