### ISSUE TITLE
Policy: handle policy parameter error in bool case

### ISSUE THREAD

**Issue by waleedhammam** [weaveworks/weave-gitops#4094]
stacktrace:

```
Error
error while converting policy weave.policies.containers-block-hostports-range to response: found unsupported policy parameter type bool in policy weave.policies.containers-block-hostports-range
```

like in code : https://github.com/weaveworks/weave-gitops//blob/084bdb90e7852a07fff0406b680a9b1f5a3353fb/core/server/policies.go#L72

**Comment by Samra10** [comment]
the term _bool_ is not supported on the policies parameter type, instead you should use _boolean_
