### ISSUE TITLE
Support for Flux 2.2.0

### ISSUE THREAD

**Issue by bigkevmcd** [weaveworks/weave-gitops#4175]
**Describe the bug**
With recent changes to Flux in [v2.2.0](https://github.com/fluxcd/flux2/releases/tag/v2.2.0) parsing of the inventory of HelmReleases is not working.

This will be apparent when viewing a `HelmRelease` managed by a Flux 2.2.x+ installation, the inventory will show up as empty.

**Environment**
Flux v2.2.0+

- Weave-Gitops Version
- Flux Version
- Kubernetes version

**To Reproduce**

**Expected behavior**

**Actual Behavior**

**Additional Context (screenshots, logs, etc)**

**Comment by bigkevmcd** [comment]
We have a fix for this, but we don't plan to make a further release in 2023, the fix will go out in early 2024.

**Comment by Ramblurr** [comment]
With the recent announcement, will this fix still go out?

**Comment by mhafshari** [comment]
> We have a fix for this, but we don't plan to make a further release in 2023, the fix will go out in early 2024.
half of 2024 is gone and still you don't plan to make a further release ;)) fluxcd 2.3.0 released but still no update here :(

**Comment by stalb** [comment]
> half of 2024 is gone and still you don't plan to make a further release ;)) fluxcd 2.3.0 released but still no update here :(

[Weaveworks has been shut down](https://www.linkedin.com/posts/richardsonalexis_hi-everyone-i-am-very-sad-to-announce-activity-7160295096825860096-ZS67), so it's possible that no one will make plans anymore.

**Comment by nick4fake** [comment]
It's still very confusing to not have a HUGE MESSAGE in Readme that this repository and product is abandoned

**Comment by casibbald** [comment]
There are discussions between parties on this repository.
If you are interested in contributing it would be good to put a foot
forward.

**Comment by casibbald** [comment]
This will be replaced by #4207
