### ISSUE TITLE
Documentation web doesn't have right certificate

### ISSUE THREAD

**Issue by luisxkimo** [weaveworks/weave-gitops#4204]
**What issue with the docs have you found?**

- [ ] Missing information
- [ ] Incorrect information
- [X] Something else

**Describe what you are trying to do**

Cannot access to the docs web.

URL: https://docs.gitops.weave.works/

![image](https://github.com/user-attachments/assets/14165c41-1ae6-4a03-a0d4-a32607985544)

**Comment by sleepy-manul** [comment]
Unfortunately, Weave Works has gone out of business. I fear this repository is abandoned. 
Source: https://www.crn.com/news/cloud/2024/aws-backed-kubernetes-company-weaveworks-closes-ceo-blames-failed-m-a

**Comment by kingdonb** [comment]
You can still read the docs (without search) on https://gitops.weave.works

You have to be a bit clever to get to it, because it is not developed anymore, I think it's better this way – so nobody gets the wrong idea about whether it's supported or not. (The source is fully open, along with the Weave GitOps Enterprise source!)

**Comment by kingdonb** [comment]
If you need to search the docs, find documentation for an older version, etc. the sources for the docs website are all here:

https://github.com/weaveworks/weave-gitops/tree/main/website

(The docs are currently re-homed on Fermyon Cloud, we were able to post them for free, but there isn't an active effort to maintain WG or WGE today. I'm still looking into other options for UI, there are a number of CNCF projects who could be contenders for "best Flux UI" but I'm still using a hacked-up version of VSCode GitOps Tools for Flux, myself...)

**Comment by luisxkimo** [comment]
Hi!

As I see, it seems that we should research another UI that is more "maintained". @kingdonb if you have any recomendation about new other projects, will be really welcome :)

Thanks for your links and info guys!

**Comment by kingdonb** [comment]
I'm looking into Headlamp myself this week, I saw a demo of their Flux plugin which evidently isn't finished yet, but has all of the core elements of a Flux UI that people seem to care most about. It's a bit of a lift to get it installed, but Headlamp can run as a native app, a headless app installed on your workstation, or as in-cluster config with OIDC to gate access.

Please visit #flux-ecosystem in the CNCF Slack and engage us there, I'll be making progress updates this week as I work with one of the Headlamp maintainers to establish a shared space we can use for testing to push the Flux headlamp plugin ahead!
