### ISSUE TITLE
Suppress npm build messages

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#423]
When running `npm ci`, `npm` outputs a bunch of nonsense warnings about C++ libraries not being correct from `node-gyp`. It clutters up CI logs and is very noisy.

This usually happens when installing something like `node-sass` that has C++ bindings for performance. We aren't using any packages like that explicitly, so its probably something that `parcel` is importing.

Example:

```
> @parcel/watcher@2.0.0-alpha.10 install /home/runner/work/weave-gitops/weave-gitops/node_modules/@parcel/watcher
> node-gyp-build


> msgpackr-extract@1.0.11 install /home/runner/work/weave-gitops/weave-gitops/node_modules/msgpackr-extract
> node-gyp-build

make: Entering directory '/home/runner/work/weave-gitops/weave-gitops/node_modules/msgpackr-extract/build'
  CXX(target) Release/obj.target/msgpackr-extract/src/extract.o
In file included from ../src/extract.cpp:9:
```

**Comment by mnowster** [comment]
@jpellizzari is this still a thing? I ran `npm ci` locally and I don't see it happening.

**Comment by jpellizzari** [comment]
@mnowster might be good now that we have updated several node versions. closing!
