### ISSUE TITLE
Getting started guide

### ISSUE THREAD

**Issue by tristech81** [weaveworks/weave-gitops#431]
Minor change to getting started guide https://docs.gitops.weave.works/docs/getting-started/

Install Weave GitOps into the currently active Kubernetes cluster:
`wego install`

should be: 

`wego gitops install`

**Comment by pzfreo** [comment]
We should cut a 0.1.0 version of the docs. The page refers to the 0.0.5 version and the current version is main, but this is confusing.

**Comment by palemtnrider** [comment]
Thanks for reporting this @tristech81 .  We've updated the docs based on this CLI change - https://docs.gitops.weave.works/docs/getting-started  
closing.
