### ISSUE TITLE
Implement git provider Oauth flow

### ISSUE THREAD

**Issue by markramm** [weaveworks/weave-gitops#461]
Users will need to authenticate with a git provider to add an application. With the current CLI experience, it is assumed they have a Github token specified in their `env`.

Eventually, we will store the users oauth + refresh token in a secret on the cluster. This will be correlated with an OIDC ID token that we can use to look up the oauth + refresh token for making requests on the users behalf. The Secret will be RBAC'd to a specific user.

**Comment by markramm** [comment]
Discussion at friday's meeting.

**Comment by jpellizzari** [comment]
Pivoting to this approach instead: https://github.com/weaveworks/weave-gitops/issues/498
