### ISSUE TITLE
test by katya please ignore

### ISSUE THREAD

**Issue by katya-makarevich** [weaveworks/weave-gitops#464]
**Short description**
As a [User Role] I want to [feature/functionality] so that [business outcome/value].

**Acceptance criteria**
- [ ] _does X_
- [ ] _displays Y_
- [ ] _..._

**Design materials**
- Screenshots
- Design diagrams
- WEP 
- PR/FAQ

**Work breakdown**
(optional)Task breakdown of the work
- [x] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by jpellizzari** [comment]
Ignoring by closing :)
