### ISSUE TITLE
Create a server-friendly logger implementation

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#494]
Our current logging implementation uses `fmt.Print` to log to stdout. This approach will not work for operations that are initiated via the API.

We will need to associate log messages with a particular request, and create log levels that can be toggled via command-line arguments.

**Comment by JamWils** [comment]
At team sync we decided to write up an ADR (Architecture Decision Record) for this work.

**Comment by jpellizzari** [comment]
> At team sync we decided to write up an ADR (Architecture Decision Record) for this work.

Just a guide for how and when to use each of the log levels will suffice.

**Comment by JamWils** [comment]
@palemtnrider, are you good with this?  It should at least clarify everything and if it doesn't feel like enough information we can always up it to a more concrete ADR.

**Comment by jpellizzari** [comment]
Sorry I should have clarified:
>Just a guide for how and when to use each of the log levels will suffice.
 * In the form of a short ADR about logging

**Comment by JamWils** [comment]
Thanks for the clarification!!!
