### ISSUE TITLE
Prompt the user for their Github access token and store it on the cluster

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#498]
Currently, we rely on a user's GH access token to be present in their environment. This will not work for the API server since it will be running in the cluster, so we need to prompt the user for their token ahead of time.

Once the user pastes their token, we need to save it on the cluster in a Secret for later use. This Secret should be scoped only be readable to the user doing the `wego install` command, and the API server service account.

Once the Secret is created, the API server will be able to use it to create PRs and add deploy keys to a given Source repository.

**Comment by josecordaz** [comment]
@jpellizzari  Where would the toke be pasted, at the time of installing gitops(`wego gitops install`)?

**Comment by jpellizzari** [comment]
@josecordaz via an interactive prompt, the same way we do with the SSH key passphrase

**Comment by josecordaz** [comment]
right, when the interactive prompt should show up? at the time of running `wego gitops install` ?

**Comment by jpellizzari** [comment]
@josecordaz yes

**Comment by josecordaz** [comment]
@jpellizzari How can I accomplish this? `This Secret should be scoped only be readable to the user doing the wego install command, and the API server service account.` sorry not a k8s export 😔 (yet 😎)

**Comment by jpellizzari** [comment]
I would say just get the secret saving on your cluster, and then we can pair to make sure we have the right permissions set on it (before merging the PR)

**Comment by josecordaz** [comment]
@markramm We've decided to add check for the github token. If the env var GITHUB_TOKEN exists then we use it and print out a message reflecting so. If it doesn't exist we will trigger an interactive prompt to set it. Do you think this would be ok?

**Comment by jpellizzari** [comment]
Closing in favor of using the approach laid out here: https://github.com/weaveworks/weave-gitops/pull/513
