### ISSUE TITLE
Wego install (Cluster wide)

### ISSUE THREAD

**Issue by markramm** [weaveworks/weave-gitops#5]
Connect a repository to an "empty" cluster.  Via a running weave gitops runtime. 

Prerequisites: 

"empty" cluster: Not configured with gitops runtime 

Architecture Design: 

Acceptance Criteria: 

GitOps runtime is installed into a cluster
Connected to a repo wego creates in github

Future: 
- need to be able to attach to existing repo
- need to be able to recreate this install from config stored in git (reconstitute the cluster) 

Based on a declarative configuration
- abstraction layering is an issue
- generate an "weave gitops install spec" ?
- can be used to reconstitute the system

**Comment by markramm** [comment]
Platform repository manages cluster level config.

**Comment by markramm** [comment]
Flux bootstrap opinions baked in may not match.

**Comment by markramm** [comment]
Guided CLI experience needs to be defined.   We need to have empathy for the naive experience.  Github cli has a good example of this experience.

**Comment by markramm** [comment]
- What assumptions can we make?  

Git integration 
kube session

**Comment by markramm** [comment]
- What preconditions are there for this experience?

**Comment by markramm** [comment]
We should iterate on the user experience.

**Comment by bigkevmcd** [comment]
https://github.com/kubernetes/kubectl/blob/master/docs/book/pages/app_composition_and_deployment/structure_directories.md
