### ISSUE TITLE
Create `wego ui run` command

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#519]
We want a user to be able to run a local Weave GitOps UI by running a command.

The `wego ui run` command should spin up a blocking web server and open a browser window for a default URL.

Extra credit: make the `wego ui run` command accept a flag that specifies a URL for the browser to open up to. This  might help with some auth features we want to use in the future.

**Acceptance Criteria**
The command should start a server and open a browser window. We should be able to do an HTTP request to the server on the `/health/` route. We can additionally check to make sure the `index.html` is populated.

Note that the `index.html` has a content-hash'd `<script />` tag, so checking for a specific string will cause tests to fail. Example:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <title>Weave GitOps</title>
</head>

<body>
    <div id="app"></div>
    <script src="/index.e2f333a4.js"></script>
</body>

</html>

```

**Comment by sympatheticmoose** [comment]
@luizbafilho @jpellizzari could you confirm whether the 'extra credit' functionality was included as part of this implementation?

**Comment by jpellizzari** [comment]
@sympatheticmoose Yes that functionality was added. We can pass an argument for the URL path to the command.
