### ISSUE TITLE
Support for running tests on PRs from forked repos

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#531]
**Short description**
As a Weave GitOps maintainer I want to tests run against a PR submitted from a fork so that 1) we know it passes the tests and 2) our branch protections can remain in-place and allow us to merge when the tests pass

**Acceptance criteria**
- [ ] smoke tests remain required for merging
- [ ] smoke tests are execute against a PR from a fork

**Design materials**
N/A

**Work breakdown**
Provide a workflow utilizing `pull_request_target` that runs the smoke tests against a PR from a fork.  Note, we should require the presence of a label (applied by a maintainer) so that we only run the smoke tests **after** a maintainer has reviewed them.

See this article for additional information : https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by markramm** [comment]
The note above is important.  Running arbitrary forks, means running arbitrary code, which could have a wide variety of security implications.
