### ISSUE TITLE
Spike: Support for Github Enterprise

### ISSUE THREAD

**Issue by sagarlohani** [weaveworks/weave-gitops#533]
**Question**
Gitops core should work with Github enterprise.
**Short description**
Looking for Github enterprise support.

Spike outputs:

* What considerations need to be made for GitHub enterprise? What assumptions have we made about using public Git Providers?

* Does the "[Advanced Use Case](https://github.com/weaveworks/weave-gitops/blob/main/doc/adr/0005-wego-core-auth-strategy.md#advanced-use-case)" story in the auth ADR fill the gap?

**Comment by markramm** [comment]
What is the status of github enterprise support in the git provider abstraction library?

**Comment by markramm** [comment]
Gitlab has more customer adoption, so that ticket is higher priority than this one.

**Comment by jpellizzari** [comment]
Decision: this needs to be handle in go-git-providers.

**Comment by ar-bella-jeong** [comment]
Um. our company also uses github enterprise. you know, although flux supports powerful feature, I think gitops core is more convenient and user friendly.
gitops core should has git provider managerment. I really hope gitops core will supoort it.
