### ISSUE TITLE
Improve `wego app status` output

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#535]
The `wego app status` output is unorganized and confusing. 

When using this command:

```
$ wego app add --branch=master --chart=podinfo --url=https://github.com/jpellizzari/podinfo
```

This is the current output:

```
Last successful reconciliation: No succesfull reconciliation

NAME                 	READY	MESSAGE                                                          	REVISION                                       	SUSPENDED 
gitrepository/podinfo	True 	Fetched revision: master/f846bfd668436c9288a062fb6aad520a6a0e3083	master/f846bfd668436c9288a062fb6aad520a6a0e3083	False    	

NAME                  	READY	MESSAGE                                                                                                               	REVISION	SUSPENDED 
helmrepository/podinfo	False	failed to download repository index: failed to fetch https://github.com/jpellizzari/podinfo/index.yaml : 404 Not Found	        	False    	

NAME               	READY	MESSAGE                                                 	REVISION	SUSPENDED 
helmrelease/podinfo	False	HelmChart 'wego-system/wego-system-podinfo' is not ready	        	False  
```

This triple-tabular format probably needs to be re-worked. Important information that needs to be prioritized:

* Is my app working as expected?
* When was the last time my app did something (and what was the thing)?
* If my app isn't working correctly, which component part is failing and what is its status?

Maybe @bia wants to have a go at designing the output?

**Comment by bia** [comment]
We  could get pretty far simplifying the format and limiting the MESSAGE to fewer characters. What does `SUSPENDED False` mean ?
```
No successful reconciliation

NAME                 	READY	MESSAGE                                                                 REVISION                                          SUSPENDED 
gitrepository/podinfo	True 	Fetched revision: master/f846bfd668436c9288a062fb6aad520a6a0e3083	master/f846bfd668436c9288a062fb6aad520a6a0e3083	  False    	  	

helmrepository/podinfo	False	failed to fetch https://github.com/jpellizzari/podinfo/index.yaml : 404 Not Found                                         False

helmrelease/podinfo	False	HelmChart 'wego-system/wego-system-podinfo' is not ready	        Not Found                                         False
```

**Comment by jpellizzari** [comment]
>  limiting the MESSAGE to fewer characters

I would be worried about losing important information. If we cut off the end, we lose the "meat" of the error. Not sure about cutting off the beginning in all cases.

> What does SUSPENDED False mean ?

There is a pause/unpause concept in `wego app suspend|resume`. This shows the state of that. I believe it is bubbled all the way up from flux.

**Comment by bia** [comment]
@jpellizzari As you said on the call, this output should look more like `kubectl describe`
Therefore the MESSAGE can be at the end with no character limit.

```
No successful reconciliation

NAME                 	READY                                            SUSPENDED   MESSAGE
gitrepository/podinfo	True 	master/f846bfd668436c9288a062fb6aad520a6a0e3083	  False       Fetched revision: master/f846bfd668436c9288a062fb6aad520a6a0e3083    	  	

helmrepository/podinfo	False	Not Found                                         False       failed to download repository index: failed to fetch https://github.com/jpellizzari/podinfo/index.yaml : 404 Not Found

helmrelease/podinfo	False	Not Found                                         False       HelmChart 'wego-system/wego-system-podinfo' is not ready
```

Would it be confusing to write suspended / resumed as the output of the SUSPENDED column ?
Why do we have REVISION ?
Do apps have events that we can list here ?

**Comment by jpellizzari** [comment]
> Would it be confusing to write suspended / resumed as the output of the SUSPENDED column ?

Do-able, but I want to get out of this column paradigm all together

> Why do we have REVISION ?
 
To show what version of the application is running. You can be in a state where an app isn't updated to the latest revision yet, or was reverted.

> Do apps have events that we can list here ?

Sort of...the flux controllers produce events that can be correlated to an `Application` with a little bit of work.

**Comment by jpellizzari** [comment]
Pasting from issue #355 for additional context

**Short description**
As a User
When I use `wego app status` command
Then I should see the CLI output with better formatting
And I don't have to rely on UI for proper status output

**Acceptance criteria**
- Formatting `wego app status` output does not introduce more flakiness

**Screenshots** 

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/6e200602-8d3c-40f9-968e-cf26e80dce72)

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/6d26f6f6-f429-4a40-9dfe-e414ff48003f)

**Additional Context**
- [ ] As a user, even if I have access to UI, I want a better CLI experience. I want properly formatted output messages to show up on my console. 
- [ ] As a user, installing WeGO UI components is totally optional. Ergo, I do not want to rely on the UI for a more readable `app status` output
- [ ] As a user, if I decide to forgo installing UI components, I should still have better CLI readability to make use of `wego app status`.

**Comment by bia** [comment]
@davidstauffer @sympatheticmoose 👀

**Comment by JamWils** [comment]
Not pointed, moving back to refine.

**Comment by sympatheticmoose** [comment]
closing in favour of https://github.com/weaveworks/weave-gitops/issues/1229
