### ISSUE TITLE
Weave GitOps should not require a deploy key for a public repository

### ISSUE THREAD

**Issue by jrryjcksn** [weaveworks/weave-gitops#551]
**Describe the bug**
Currently, wego creates and uploads deploy keys for public repositories. This prevents use of applications from upstream public repositories (like sock-shop).

**Environment**
 - wego: v0.2.1

**To Reproduce**

Run `wego app add` against a public repository. Note that a deploy key is created and uploaded.

**Comment by jpellizzari** [comment]
@jrryjcksn Is this related to https://github.com/weaveworks/weave-gitops/issues/545 ?
