### ISSUE TITLE
Implement Gitlab PKCE auth flow

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#554]
Depends on #553 

Per [our auth ADR](https://github.com/weaveworks/weave-gitops/blob/main/doc/adr/0005-wego-core-auth-strategy.md), we should add support for Gitlab auth.

Balsamiq Wireframe 1: https://balsamiq.cloud/s5qd59g/p340wpr/r013A

Balsamiq Wireframe 2: https://balsamiq.cloud/s5qd59g/p340wpr/r6D74

Balsamiq Wireframe 3: https://balsamiq.cloud/s5qd59g/p340wpr/r826E

Docs: https://docs.gitlab.com/ee/api/oauth2.html#authorization-code-with-proof-key-for-code-exchange-pkce

This is mainly a function of demonstrating that we can support more than one Git Provider.

It should:
* Use a token provided via Git Provider-specific environment variables (eg `GITLAB_TOKEN`) and skip the device flow when the token is provided in the CLI only.
* Open a browser window from the CLI to complete the auth flow
* Be usable via the CLI
* Fit a common interface for Git Provider auth (if possible)

The user flow (from the ADR):
User does a `wego app add` command and specifies a Gitlab repo. If no token is present, we do the following:
1. Open a browser window to the Gitlab.com auth page
2. Starts a local web server that will receive the Gitlab Oauth callback
3. `wego` CLI blocks and polls the local web server to check for the token
4. User clicks "Authorize"
5. Gitlab.com redirects to our `/oauth/gitlab/callback` route for the local web server
6. Local web server receives the Gitlab token and stores it in memory
7. `wego` CLI gets the token on its next poll
8. Local webserver stops
9. `wego` command continues with the token

**Comment by JamWils** [comment]
@jpellizzari Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/weaveworks-foss-603cb6b1d4dff9000e242dc4/issues/weaveworks/weave-gitops/554?planning-poker)
