### ISSUE TITLE
Implement `get-commits` logic

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#562]
Based on the output from this spike #514 

It should:
* Show the commits for an application when the user does `wego app get-commits`
* Return a list of commits from the `ListCommits` API response

Not doing:
* Commit pagination (yet)

**Comment by davidstauffer** [comment]
The decision is to use:
`wego app get commits`

**Comment by J-Thompson12** [comment]
@davidstauffer where does the appname go? Is it `wego app <appname> get commits`?
