### ISSUE TITLE
Implement `get-commits` pagination

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#563]
Follow on from #562

Allow for a user to page through the available commits from either the CLI or API

**Comment by JamWils** [comment]
@J-Thompson12 can we close this since you already added this logic in #608?

**Comment by jpellizzari** [comment]
@JamWils This issue is about pagination and the pull request is still open

**Comment by jrryjcksn** [comment]
I somewhat question the value of pagination in the CLI. The traditional *nix way is to pipe to `less` or something similar. Building pagination directly into the command makes it difficult to use in a script, etc.

**Comment by J-Thompson12** [comment]
The ui will have pagination but as of right now the cli is hardcoded to 10 commits
