### ISSUE TITLE
Skip authenticate on `--dry-run`

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#601]
We do the authentication flow even when the `--dry-run` flag is present, and we probably shouldn't do that. The user just wants to see how their manifests will look, so presenting them with an authentication flow is a bit strange and jarring.

**Comment by palemtnrider** [comment]
In the dry-run output we should print a message about skipping the authentication check with the git server (GitHub, GitLab, etc)

**Comment by jpellizzari** [comment]
Harder to write a test for this one with the `apputils` change. This might require a slightly larger refactor to make that package more testable.

`apputils` is also low-hanging fruit for unit test coverage increase.
