### ISSUE TITLE
[API] Create an application via Api Server

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#61]
Provide the ability to create an application via calls to the Wego Api Server. Eventually, both the CLI and UI will interact with the system via the Api Server.

**Comment by markramm** [comment]
An application is a folder in the git repo

it has a set of base configurations 

and target adapters in a /targets folder

**Comment by markramm** [comment]
Weave Gitops provides a standard structure for application deployments.   An application is a folder and an app.yaml which defines the configurations to be deployed.

**Comment by markramm** [comment]
Is this the same as installing the application CR?

**Comment by palemtnrider** [comment]
Ultimately, it will be the same.  I'll find some time to add additional details here.

**Comment by jpellizzari** [comment]
Closing, as this is a bit too broad. Individual eng tasks will be added to the #549 epic
