### ISSUE TITLE
WeGO fails to reconcile when folder containing app manifests is deleted

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#616]
**Describe the bug**
WeGO fails to delete apps running inside containers after the folder containing the app manifest files is deleted from the git repository. Once an app is added with `--path` field specified, WeGO relies on the specified folder to exist in order to continue **"gitopsing"**. If the all the files in the folder are deleted, github automatically deletes the folder. This confuses WeGO since the directory specified during `wego app add` no longer exists. Please look at the **Steps To Reproduce** section for more clarity.

**Environment**
 - wego: v0.2.2

**To Reproduce**
1. Create a git repo and save all the app manifest files in a sub-directory (do not save files at the root)
1. Have a cluster up and running
2. Install wego components by running `wego gitops install`
3. Run `wego app add . --path=<path-to-sub-directory> --auto-merge=true`
4. See app get added and containers being created (Run `kubectl get pods -A`)
5. Delete all manifest files from the sub-directory and watch the directory get removed from the git repo
6. Run `kubectl get pods -A` and see the containers still running

**Screenshots**

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/0e516d00-ead5-44f3-83de-4e7db411c0c2)

**Additional context**
Is this expected behavior? The `wego app status` is giving the right message but the containers still persist. If the directory no longer exists, then the containers that got created should get destroyed.

**Comment by jrryjcksn** [comment]
This appears to be the following flux issue: https://github.com/fluxcd/kustomize-controller/issues/187
which they do not appear to be willing to fix. I believe we have basically three options:

1. Document that users should always maintain a manifest in each app directory
2. Write a dummy manifest into the directory ourselves at add time (maybe a config map), but that could still fail if a user removed it
3. Have a controller that watches app directories and removes matching resources if a directory goes empty

or, I guess, some combination of the three

**Comment by jpellizzari** [comment]
Can we use a `.keep` file?

**Comment by jpellizzari** [comment]
Consensus: Option 1 is good enough for now (document that users shouldn't delete the last thing)
