### ISSUE TITLE
Generate CLI help docs programatically

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#646]
Currently the documentation for each command lives in two places: the CLI help text that gets printed in the user's terminal, and on the `weave-gitops-docs` website.

We should try to reconcile those two sources of truth so that the website takes the output from the CLI and adds renders it in the docs page. This can probably be done as part of a release job.

This might be of use (shoutout @sympatheticmoose): https://github.com/spf13/cobra/tree/master/doc

**Comment by jpellizzari** [comment]
https://github.com/spf13/cobra/tree/master/doc

**Comment by sympatheticmoose** [comment]
If need help with this @bigkevmcd implemented for https://github.com/redhat-developer/kam
