### ISSUE TITLE
Implement garden.io for local development of wego-app

### ISSUE THREAD

**Issue by josecordaz** [weaveworks/weave-gitops#656]
**Short description**
As a developer I want to implement garden.io so that I can have fast deployments of wego-api locally.

Garden will allow us to develop API features quickly while the `wego-app` is running on the cluster.

Success looks like: I can run a command and a `wego-app` instance runs on the cluster; when I update some `.go` files, the server reloads with the changes.

Acceptance Criteria:
* One-time installation instructions are documented in the README
* Some sort of configuration file is present in the `weave-gitops` repo that tells Garden what to do
* WeGO devs are able to run a script or Makefile target to get started
* Updating `.go` code automatically reloads the container/pod/deployment running in the cluster
* Rebuilds should not take longer than a few seconds to complete (if its taking too long to rebuild, we need to re-evaluate)
* The `wego-app` needs to be accessible via `localhost` so that UI development can happen

**Comment by jpellizzari** [comment]
Putting this on hold for now. Closing.
