### ISSUE TITLE
Provide homebrew install of Weave GitOps CLI

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#662]
**Short description**
As a developer I want to install the Weave GitOps CLI through an appropriate package manager so that it is easy to discover, install and manage.

We should try and reuse the tap and bot for `eksctl` - to make it simpler for users of that tool, and hopefully for ourselves to set up. 

I would like us to use the term `gitops` for the formula/package based on current designs for how we bring together our various CLIs into a single experience, this would be a useful first step.

**Acceptance criteria**
- [ ] A new release of the CLI should automatically update the formula
- [ ] Manual test on linux and mac
- [ ] Automated test to install WeGO on a macOS VM (GH actions) and run wego version (run in Nightly).

**Comment by jpellizzari** [comment]
@sympatheticmoose We had originally wanted to track downloads internally. A homebrew distribution channel will make that impossible. Are we abandoning that approach?

**Comment by sympatheticmoose** [comment]
It's not impossible, we can still track downloads in the same way through the releases. I don't believe any special actions are required unless we want to separate our stats to measure the effectiveness of the homebrew distribution, but I'm not too concerned by that.

**Comment by pzfreo** [comment]
Regarding tracking downloads, it was agreed that it is more important to make it easy to install and we can get useful metrics in other ways.

**Comment by steveww** [comment]
+1 for `brew install`

**Comment by sympatheticmoose** [comment]
@J-Thompson12 @JamWils do we have updated docs for this?

**Comment by J-Thompson12** [comment]
We do not have docs yet because we will have to do a release before people can download with brew.
