### ISSUE TITLE
Smoke tests do not clean up repositories

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#672]
Smoke tests leave behind a bunch of repositories when run locally. Screenshot of a GH profile after running them:

![Screenshot from 2021-08-25 14-20-28.png](https://images.zenhubusercontent.com/5a39a1308a75884b908bb1ea/af544a4d-99aa-47d2-940b-5e28134f9a8f)

**Comment by J-Thompson12** [comment]
This was fixed with https://github.com/weaveworks/weave-gitops/pull/840
