### ISSUE TITLE
Unsuccessful installation can leave components on cluster which cannot be uninstalled using wego gitops unistall

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#677]
**Describe the bug**
Whilst testing Weave GitOps on Red Hat CodeReady Containers (OpenShift) I hit an issue as a result of scc settings. Most stuff got installed except the source controller fails to start, so the verification failed in the final steps of `wego gitops install`. As verification fails, Weave GitOps seems to have no idea of the components that were deployed to the cluster. Therefore `wego gitops uninstall` fails as it claims theres nothing there

**Environment**
 - wego: [e.g. v0.2.2]
 - kubernetes:  [v1.21.1+38b3ecc]
    - OpenShift 4.8.4

**To Reproduce**
Steps to reproduce the behavior: (outlining my steps, there may be a simpler way to force this error)
1. Download [CRC](https://developers.redhat.com/products/codeready-containers/overview) & copy pull secret for later 
2. Download oc ([mac](https://downloads-openshift-console.apps-crc.testing/amd64/mac/oc.zip) / [linux](https://downloads-openshift-console.apps-crc.testing/amd64/linux/oc.tar) )
3. `crc setup`, `crc start`, grab a cup of tea,`eval $(crc oc-env)`
4. Login as kubeadmin using the information provided in the terminal `oc login -u kubeadmin -p <password> https://api.crc.testing:6443`
5. Create project `oc new-project wego-system` (probably optional, required if you want to get this to install properly)
6. Install weave gitops - `wego gitops install` and wait for it to fail
6. Check deployment to verify there is stuff there - `oc get all`
7. Try and uninstall - `wego gitops uninstall`
8. See error

**Expected behavior**
If we can **safely** attempt cleanup, we should provide this as an option either following the validation failure (not automatic I would assume as folks may want to grab info to understand the failure) and/or wego gitops uninstall should be able to remove this partly installed deployment. My concern is if there are any risks to someone who has installed the GitOps Toolkit through some other means, maybe this is a non-concern if we fail to install in that case.

**Screenshots**
<img width="670" alt="Screenshot 2021-08-24 at 14 03 08" src="https://user-images.githubusercontent.com/19860021/130988864-f3ffbb0e-96c7-44bd-946e-9f08d977622b.png">

**Additional context**
The reason this fails is the additional steps that need to be configured for OpenShift as described in the OperatorHub description for [flux](https://operatorhub.io/operator/flux)

**Comment by jpellizzari** [comment]
Let's try to replicated this outside of openshift first to see if its a more general issue

**Comment by sympatheticmoose** [comment]
Of course :)
> (outlining my steps, there may be a simpler way to force this error)
