### ISSUE TITLE
Spike: How do we update wego and flux components?

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#70]
# Short description
As a SRE I want to update wego/flux k8s cluster so that I'm running the latest code.

Flux does this by downloading new version and reinstalling...

`wego upgrade`

For now we will only support one previous version when upgrading. A PR will be created in the wego platform repository **_(assuming only one repository needs to be updated)_**. The cluster/target will be upgraded when the PR is merged.

# Discussion

## Upgrading a Weave GitOps installation

The process of upgrading Weave GitOps for a single cluster consists of two pieces:
- Upgrading flux controller resources
- Upgrading resources generated by Weave GitOps

### Flux Controller Resources
Flux controller resources should not constitute a significant problem since flux supports upgrading them by simply downloading a new flux version and re-installing flux. As we don't expect users to modify the core flux manifests, the only reason we store them at all is so that upgrading can be done via pull request. We'll simply need to run `flux install --export` and overwrite the existing flux manifests in the platform repository with the new ones generated by the install.

### Resources Generated by Weave GitOps
Resources generated by `wego app add` are potentially a bit more complicated in that we expect users may modify them (to change the sync interval, for example). It would be a much better user experience if we were to keep any such changes during the upgrade. According to the [flux migration timetable](https://fluxcd.io/docs/migration/timetable/), any breaking changes to the CRDs will come with associated conversion mechanisms. So, we should be able to run/apply such mechanisms during an upgrade when such a change occurs. As of yet, it isn't clear what such mechanisms will look like so we will have to plan to be flexible if/when breaking changes occur. In the absence of such breaking changes, we should be able to leave flux-generated resources alone. The only resource we may have to update is our own `app` resource. That should be a relatively straightforward change, though, since the `app` resource has no user-serviceable parts.

### Pull Requests
An unfortunate side effect of our choice to allow configuration to be stored in multiple places is that we can't always upgrade everything with a single pull request. For flux-only upgrades without breaking changes, we will only need to create a PR for the platform repository. However, if we change the `app` resource or a breaking change occurs in the flux CRDs, we'll need to extract the config URL from each app managed by Weave GitOps and create a PR in each referenced repository with the necessary changes. The UI or CLI will have to inform the user of all the repositories that will need PRs reviewed and merged. **_(It's possible that this issue will be go away if the directory structure changes play out as currently discussed)_**

### Multi-cluster
In a multi-cluster environment there will be applications that are deployed in multiple clusters. The GitOps management resources for the applications (other than the `app` resource), however, will be segregated by cluster. So, `wego upgrade` should be able to work just fine on an individual cluster. The only place in which that _might_ be problematic is the `app` resource, which is shared. This suggests that we'll need to ensure all `app` changes are backward-compatible (for some number of releases) so that we can upgrade the `app` resources during an upgrade for a single cluster.

**Comment by jpellizzari** [comment]
@jrryjcksn Write up looks great. Can you help me understand what the discrete work items or changes will be? A bulleted list would be great, or we can hop on a call to discuss what that list might look like.

**Comment by JamWils** [comment]
> Resources generated by wego app add are potentially a bit more complicated in that we expect users may modify them (to change the sync interval, for example). It would be a much better user experience if we were to keep any such changes during the upgrade.

This makes me nervous.  Could we give guidance on editing generated files such as "please use kustomize and we will not override those files" type of system?  I guess I view this similar to protobuf output.  You don't edit the go files because protobuf will overrides them the next time you run.

**Comment by JamWils** [comment]
This might be more of a product question, but does `wego upgrade` need to update both apps and flux?  Albeit, I should read the directory ADR which you write might make all of this moot.

**Comment by JamWils** [comment]
+1 to @jpellizzari comment.  This does look really good.  My questions above are more for my own edification @jrryjcksn.  Great work!!!

**Comment by jrryjcksn** [comment]
> @jrryjcksn Write up looks great. Can you help me understand what the discrete work items or changes will be? A bulleted list would be great, or we can hop on a call to discuss what that list might look like.

I've been assuming we don't need to upgrade existing systems as of yet (hopefully nobody is running an important cluster w/ Weave GitOps already!). There's a plan to provide a migration script when we switch to the new directory structure and it would be good to not have to mix that up with the normal upgrade.

- After the directory changes, we'll just need a `wego gitops upgrade` command that re-runs `flux install` and writes the manifests returned into the platform repo then creates a PR (we don't currently have a platform repo -- that's coming with the directory changes).

That's really all we're talking about unless/until one of the CRDs we use changes (whether a flux one like Kustomization, HelmRelease, etc. or our Application). So, not much at first. Once we see what sort of conversion support flux gives at on that day we'll have to figure out further steps.

**Comment by jrryjcksn** [comment]
> > Resources generated by wego app add are potentially a bit more complicated in that we expect users may modify them (to change the sync interval, for example). It would be a much better user experience if we were to keep any such changes during the upgrade.
> 
> This makes me nervous. Could we give guidance on editing generated files such as "please use kustomize and we will not override those files" type of system? Trying to diff the files based on the user changes them is a slipper slope. I guess I view this similar to protobuf output. You don't edit the go files because protobuf will overrides them the next time you run.

That's a good point! The kustomization approach will have direct support after the directory changes. The original design from Cornelia had us just use flux to generate the resource manifests and write them into a known location for people to edit. I don't think there's any way to stop people from directly editing the manifests, though, so we should try to be prepared for it.

**Comment by jrryjcksn** [comment]
> This might be more of a product question, but does `wego upgrade` need to update both apps and flux? Albeit, I should read the directory ADR which you write might make all of this moot.

I'm not entirely sure what you mean by "apps" in this context. Are you referring to customer manifests or our `Application` CR? We shouldn't need to do anything to customer manifests. We only touch the automation manifests that sync their repositories. If we modify our `Application` CR, though, we'll have to update the existing ones in all the repositories via PRs. 

The issue I suggested might be resolved by the directory changes is the possibility of having to generate multiple PRs. Hopefully we'll get back to the point where we have a single configuration repository so we can limit such changes to one PR. If we do go back to a single configuration repository, though, that change would likely come some time after the basic directory structure changes since it would be a much bigger modification to how our app works and I doubt we would have support to do it in the very near term.
