### ISSUE TITLE
WeGO UI does not show app list if apps are added at a later step

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#705]
**Describe the bug**

When I run `wego ui run` _before_ adding any apps to the cluster, http://localhost:9001 manages to show a webpage with error message:

`could not list wego applications: Get "https://127.0.0.1:51568/apis/wego.weave.works/v1alpha1/namespaces/wego-system/apps": dial tcp 127.0.0.1:51568: connect: connection refused`

After adding an app to the cluster, the page fails to change or show the newly added app unless I rerun `wego ui run` with a different `port` number.

**Environment**
 - WeGO: binary with latest changes
 - Browser: 
   - [x] chrome 
   - [x] firefox 
 

**To Reproduce**

1. Create a brand new cluster
2. Run `wego gitops install`
3. Run `wego ui run`
4. Open a browser and navigate to http://localhost:9001
5. See error message on the webpage
6. Add any app (`wego app add --url=https://charts.bitnami.com/bitnami --chart=nginx --app-config-url=NONE`)
7. Refresh your browser and see no change
8. Run `wego ui run --port=9003`
9. Navigate to http://localhost:9003 and see your app listed

**Expected behavior**

I expected the UI page to refresh and show the newly added app. 

**Screenshots**

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/012255d3-09ed-4ba0-b048-1e26839c3aea)

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/86c38b1b-0f59-4f52-b588-d0e373e015e2)

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/394c3b20-a91c-4300-93ea-6daa2e905838)

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/d78d9923-f835-4971-b248-4dd3d2fd6de9)

**Comment by jpellizzari** [comment]
@rokshana-b I am unable to reproduce.

Based on the error messages you are getting, it might be possible that you have a context selected for a cluster that does not exist. The wego API looks at the current selected context in the kube config.

**Comment by rokshana-b** [comment]
Saw this error because my system kept using the default port:9001, even after I quit using UI (a classic case of orphan process running in the background). Once I killed the process from my terminal, everything worked fine.
