### ISSUE TITLE
Docs mobile menu removes number of options

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#708]
**Describe the bug**
Using a window <=1245px wide drops to mobile menu (hambuger) but omits a number of pages. Given this isnt a tiny window, perfectly reasonable to hit when using laptop and then not having things like the CLI reference seems amiss. Also the light/dark mode toggle seems off.

**Screenshots**
Regular menu
<img width="361" alt="Regular" src="https://user-images.githubusercontent.com/19860021/131735486-39414055-5afc-4abc-94ad-b01c7e011132.png">

Mobile-style menu
<img width="523" alt="Mobile" src="https://user-images.githubusercontent.com/19860021/131735496-ef1a0284-553a-4f45-8c1b-ef98bfb5589b.png">

**Additional context**

**Comment by sympatheticmoose** [comment]
Note this hides all the enterprise stuff as well... would be good to start to tackle now that we have more awesome folks on board.

**Comment by sympatheticmoose** [comment]
I've lined up for next sprint, but if someone wants to take earlier... wonderful :)

**Comment by palemtnrider** [comment]
This is working as designed.  When the screen size is reduced a new hamburger menu is added containing the left menu bar.  On my browser, it shows up in the lower right-hand corner.

![Screen Shot 2021-12-21 at 8 53 44 AM](https://user-images.githubusercontent.com/7633548/146960502-85c5ef54-587e-4da1-b2f9-0edfef1a02ba.png)

![Screen Shot 2021-12-21 at 8 53 53 AM](https://user-images.githubusercontent.com/7633548/146960542-86301258-4ad7-46f6-80c5-72c30f2211c3.png)

**Comment by palemtnrider** [comment]
@sympatheticmoose does this address the issue for you?

**Comment by sympatheticmoose** [comment]
Ah yes, I remember realising this in a conversation with @JamWils but forgot to update the issue. No, I think it's super weird to have 2 hamburger menus and the secondary one is not visible from the homepage.

**Comment by sympatheticmoose** [comment]
No second menu on home
![image](https://user-images.githubusercontent.com/19860021/146962494-0b1e7e39-fb1d-45af-a88f-d8d94e059155.png)

What you can access from home
![image](https://user-images.githubusercontent.com/19860021/146962603-0c1cac80-2887-414b-b47e-16dc5508e732.png)

Two menus
![image](https://user-images.githubusercontent.com/19860021/146962777-799fba57-b1a4-4821-9af3-a0b9dc15b312.jpeg)

**Comment by JamWils** [comment]
Two hamburger menus is weird.

**Comment by sympatheticmoose** [comment]
this is fixed
