### ISSUE TITLE
Speed up time spent running acceptance/smoke/nightly tests

### ISSUE THREAD

**Issue by josecordaz** [weaveworks/weave-gitops#712]
**Short description**
As a developer I want to speed up smoke/acceptance tests so that I can get faster feedback related to the changes in my PR.

Right now smoke tests take around `~21m` to run , acceptance tests take around `~30m`, nightly tests take around `~1h21m`, all of this happens in the CI pipeline.

This is the current approach, we create a cluster then we clean it up and reuse it:
![image.png](https://images.zenhubusercontent.com/606389311ead0cc4788a9a72/0a4feb51-bbff-49ea-ad1b-c7c4a4d5f305)

The idea is to be able to **run chunks of integration tests in parallel**. focusing on creating brand new clusters when the chunk of integration tests runs so they are ready for the next chunk of integration tests:
![image.png](https://images.zenhubusercontent.com/606389311ead0cc4788a9a72/543af8b3-2822-46c8-bb93-3fa47709b740)

I successfully was able to implement a middle step to this proposal by creating one single brand new kind cluster when an integration is running so it is ready right before the next integration tests runs. By doing this I was able to speed up the tests locally by ~50%. A key to implement this was to create a kubeconfig file for each kind cluster and set it in the env var `KUBECONFIG` so the tests do not conflict with each other. This is the diagram of that:
![image.png](https://images.zenhubusercontent.com/606389311ead0cc4788a9a72/dac5af5f-9289-4d31-a5c9-413047c1e273)

**Acceptance criteria**
- [ ] Brand new cluster for each integration test
- [ ] Time spend should be less then the current time

**Design materials**
- Screenshots
- Design diagrams
- WEP 
- PR/FAQ

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by jpellizzari** [comment]
Let's timebox this to a couple of tests

**Comment by jpellizzari** [comment]
We went a different direction for CI acceptance tests. Closing.
