### ISSUE TITLE
wego app remove has extraneous flag --name

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#717]
**Describe the bug**
The help for `wego app remove` lists a name flag but the name is an argument to the command.

**Environment**
 - wego: 
 > Current Version: v0.0.0
GitCommit: bbd9cb6
BuildTime: 2021-09-03_10:06:47
Branch: main
Flux Version: v0.16.0

**Affects versions**
- v0.2.4
- 
**To Reproduce**
1. run `wego app remove --help`
2. Takes a parameter --name and the long help says name is an argument

**Expected behavior**
Remove --name from the help and code

**Comment by HassanAlsamahi** [comment]
I'd like to work on this issue, if I may ?

**Comment by jpellizzari** [comment]
@HassanAlsamahi It's all yours! I will assign it to you. You can @ me if you have any questions.

**Comment by HassanAlsamahi** [comment]
Great, thanks very much
