### ISSUE TITLE
Remove --private-key flags and uses of them in tests / docs / workflows

### ISSUE THREAD

**Issue by jrryjcksn** [weaveworks/weave-gitops#721]
**Short description**
Weave GitOps no longer uses external ssh keys but the commands still take them as arguments (mostly so that all the acceptance tests still work). We need to update the docs, the acceptance tests, the commands, and the github workflows to remove the ssh keys.

**Acceptance criteria**
- [ ] Commands no longer take `--ssh-key` arguments
- [ ] Acceptance tests no longer use ssh keys
- [ ] The documentation no longer references ssh keys
- [ ] The workflows no longer set up ssh agents

**Comment by J-Thompson12** [comment]
Removing of ssh keys from the acceptance tests cannot be done until hub has been removed.
