### ISSUE TITLE
Add an app with a `GITLAB_TOKEN` present in the users environment

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#724]
We should prove that we can handle an app from a Gitlab repo.

Timebox: 2h

Possible Outcomes of this spike:
1. We are able to add a Gitlab app no problem, in which case we should "lock it in" with smoke/acceptance test
2. There is only a minimal amount of work needed to "make Gitlab work", and we can handle it in a single PR.
3. There is a LOT of work, and the outcome of this Spike is one-or-more other issues that encapsulate that work

**Comment by J-Thompson12** [comment]
From what I found it could be put in one PR but if it makes sense to split it into two here are the two places i saw that need changes:
- There is some things to figure out around groups and subgroups. 
- There is also some work to be done around the url parsing i get errors for gitlab when url parsing is run

**Comment by jpellizzari** [comment]
@J-Thompson12 If you want to go ahead and PR this, go for it!

**Comment by J-Thompson12** [comment]
issues created here https://app.zenhub.com/workspaces/weaveworks-foss-603cb6b1d4dff9000e242dc4/issues/weaveworks/weave-gitops/752

**Comment by J-Thompson12** [comment]
Acceptance criterea 
- [ ] add gitlab user project 
- [ ] add gitlab group project
- [ ] add gitlab sub group project
