### ISSUE TITLE
Remove wego-app resources on uninstall

### ISSUE THREAD

**Issue by josecordaz** [weaveworks/weave-gitops#729]
**Short description**
As a user I want to use the uninstall command to remove all `wego-app` resources so that the cluster is clean from all gitops related resources.

**Acceptance criteria**
- [ ] After running `uninstall` there is no resources on `wego-system`
- [ ] After running `uninstall` (using a different ns than the default one in the install command) there should be no resources.
- [ ] Add test coverage

**Comment by HassanAlsamahi** [comment]
So do you mean, that by running "wego uninstall" it will remove all apps, uninstall flux and uninstall gitops, right? Like a combination of "wego app remove", "wego flux uninstall", "wego gitops uninstall" ?

**Comment by jpellizzari** [comment]
@HassanAlsamahi We also have a deployment that will be running on the cluster (in the next release of `wego`). We need to clean that up as well.

I would say this one will be tricky for an outside contributor. More info to come on this issue after our internal refinement meeting tomorrow.

**Comment by HassanAlsamahi** [comment]
> @HassanAlsamahi We also have a deployment that will be running on the cluster (in the next release of `wego`). We need to clean that up as well.
> 
> I would say this one will be tricky for an outside contributor. More info to come on this issue after our internal refinement meeting tomorrow.

Sure yeah, that's cool :D

**Comment by jpellizzari** [comment]
Holding on this until #725 is done
