### ISSUE TITLE
Deploy MCCP into dev with sqlite and using a shared cluster repo deploy in staging with external DB

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#74]
**Short description**
As a SRE I need to deploy the existing MCCP cluster observability tools with sqlite in dev and postgres in UAT so that the UAT environment data lives longer

**Given** two kind clusters (`dev` and `UAT`) with `Weave GitOps` installed
**And** the Helm Chart for the MCCP cluster observability tools is in a git repository
**And** there are two `Values.yaml` files in distinct directories within the git repository
**And** the values file for `dev` defines the db as sqlite
**And** the values file for `UAT` defines the db as postgreSQL
**When** I `wego app add` the Helm Chart to each cluster
**And** the `paths` for the apps point to the distinct directories
**Then** the MCCP tools are deployed to the `dev` cluster using sqlite
**And** the MCCP tools are deployed to the `UAT` cluster using postgreSQL

**Comment by markramm** [comment]
Requires a helm chart that can install MCCP.

**Comment by markramm** [comment]
@katya-makarevich how do we want to handle dependencies across Zenhub/Jira?

**Comment by katya-makarevich** [comment]
@markramm for the moment we can do it only manually. I'll talk with the Pesto team about this dependency tomorrow

**Comment by katya-makarevich** [comment]
@markramm for the moment we can do it only manually. I'll talk with the Pesto team about this dependency tomorrow

**Comment by jpellizzari** [comment]
I would like to close this as out-of-scope for Weave GitOps Core.

**Comment by markramm** [comment]
Out of scope for core, but not out of scope for weave gitops teams or enterprise.
