### ISSUE TITLE
How does a user fix a bad Application input? A bad "path" for example

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#751]
While troubleshooting a `wego` app with a user, it wasn't immediately obvious how someone could remediate an invalid `Application` CR parameter. In this case, it was the `path` parameter that needed to be changed.

The remediation step that was actually taken: `wego app remove my-app`, then re-added the app.

**Comment by jpellizzari** [comment]
Decision: alloow the user to re-run `app add` with different inputs in order to remediate bad user input.

**Comment by jpellizzari** [comment]
We should push a new commit with the changes to that same branch

**Comment by J-Thompson12** [comment]
@jpellizzari 
I have some questions about this task I want to get clarification on. 
- Does this only have to do with the auto-merge=false path?
- If so is the scope of this issue only if the pr has not been merged yet?

**Comment by jpellizzari** [comment]
> Does this only have to do with the auto-merge=false path?

That was NOT the original intent, but I see how that could be tricky. 

@J-Thompson12  Can you do some investigating and find out if it would be easier to start with `--automerge=false` for updates, or if it would be easier to just do the same things no matter if its `automerge` or not?

**Comment by jpellizzari** [comment]
Situations:
* PR is open
* Auto-merged already

**Comment by jpellizzari** [comment]
The new directory structure may make this work easier. Moving to Icebox for now.
