### ISSUE TITLE
Add an app with a `GITLAB_TOKEN` present in the users environment

### ISSUE THREAD

**Issue by J-Thompson12** [weaveworks/weave-gitops#752]
A spike was done on this here https://app.zenhub.com/workspaces/weaveworks-foss-603cb6b1d4dff9000e242dc4/issues/weaveworks/weave-gitops/724

We should prove that we can handle an app from a Gitlab repo.
Things from the spike to look out for. 
-  There will be things to figure out around groups and subgroups. Github uses organizations while gitlab uses groups. Subgroups is its own thing that needs to be figured out.

- url parsing when normalizing the url works for github but gitlab will need different work done to get it working.

Acceptance criterea:
add a gitlab application with gitlab token set in the env.

**Comment by jpellizzari** [comment]
Closing in favor of the #724 spike
