### ISSUE TITLE
Cannot use weave-gitops@v0.2.5 as a go module

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops#757]
**Describe the bug**

`flux` is included as a `go:embed` directive but its not included in the source archive that is `go get`'d by the go module that depends on weave-gitops: https://proxy.golang.org/github.com/weaveworks/weave-gitops/@v/v0.2.5.zip

I would guess this was introduced when flux was moved into the apiutils and so importing https://github.com/weaveworks/weave-gitops/blob/main/pkg/server/server.go now also includes `"github.com/weaveworks/weave-gitops/pkg/flux"` via apiutils in https://github.com/weaveworks/weave-gitops/pull/687 (maybe, not sure)

**Environment**

```
$ go version
go version go1.17 darwin/amd64
```

**Affects versions**

`v0.2.5`

**To Reproduce**

```bash
$ git clone https://github.com/weaveworks-gitops-test/wego-library-test
$ vim go.mod # remove the replace directive for weave-gitops
$ go build main.go
../../go/pkg/mod/github.com/weaveworks/weave-gitops@v0.2.5/pkg/flux/setup.go:11:12: pattern bin/flux: no matching files found
```

**Expected behavior**

Be able to include the `wego_server "github.com/weaveworks/weave-gitops/pkg/server"` from another project and build successfully

**Comment by jpellizzari** [comment]
@foot and I discussed, and we think the best remediation will be to let consumers of the `weave-gitops` packages specify their own path to the flux binary
