### ISSUE TITLE
View applications deployed into a cluster (SRE view)

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#76]
**Short description**
As an application operator, I would like to go the core UI and see the status of all my applications -- whether they are in sync, healthy, or there are errors.
After I've deployed something, I would like to see the status of the deployment.
(See weave cloud deploy page for related example)

**Acceptance criteria**
- [ ] ?
- [ ] ?

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by markramm** [comment]
The high level idea here is to replicate the feedback that is given by the argo cd deployment page, and weave cloud's deploy page. 

When I have a new config (example new image) I want deployed, I can go to the weave gitops core UI's application page and push a button, watch the pods be updated in the UI, see when the deployment is finished.

**Comment by markramm** [comment]
When I connect to the weave gitops core UI I get a list of all the running applications on the "Applications" page, their status, and can click into an app to see more details.

**Comment by markramm** [comment]
- [ ] This is the same as the applications list view.
