### ISSUE TITLE
Error trying to get list of app commits

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#764]
**Describe the bug**
When trying to get list of commits for an empty repo, wego gives an error. 

**To Reproduce**
1. Create a repo without committing any files to it.
2. Run `wego gitops install` on your cluster
3. Add the empty repo as an app: `wego app add . --auto-merge=true --app-config-url=NONE`
4. Run `wego app <appName> get commits`

**Config and Logs**
`Existing deploy key found`
`Error: failed to get commits for app new-test: unable to get Commits for org repo: error getting commits for repo [https://github.com/weaveworks-gitops-test/new-test] err [GET https://api.github.com/repos/weaveworks-gitops-test/new-test/commits?per_page=10&sha=main: 409 Git Repository is empty. []]`

**Screenshots**

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/ca9399a5-acb0-402e-b791-927e349e99c7)

**Additional Context**
Is this the expected behavior?

**Comment by J-Thompson12** [comment]
No this is not really expected behavior. It should just return an empty list of commits. Given the error though that is either coming from go git providers or github. It is something we can fix though.

**Comment by J-Thompson12** [comment]
This error is returned from go-git-providers. This is also expected behavior. Since app-config-url is set to NONE we dont add a commit. I will make it return an empty list though.

**Comment by J-Thompson12** [comment]
go-git-providers throws this error if the repo is empty. We can return an empty list of commits instead. This same error occurs when doing add with --auto-merge=false on an empty repo. Create pull request creates a branch and to create that branch we use latest commit sha.
