### ISSUE TITLE
Add/Remove App using the new `.weave-gitops` directory structure

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#768]
From the ADR: https://github.com/weaveworks/weave-gitops-private/blob/main/docs/adrs/0007-directory-layout.md

Acceptance Criteria
* Make our repo write operations match the new file structure
* Ensure the behaviors listed in the [consequences section](https://github.com/weaveworks/weave-gitops-private/blob/main/docs/adrs/0007-directory-layout.md#consequences) are implemented
* Create a single entry-point for read/write operations from the `.weave-gitops` directory (ie create a `WeGODirectoryClient` object or some such)
* Ensure removing an app with the new directory structure works (does NOT include "remove via PR)
* Clean up existing references to the `.wego` directory and use the aforementioned client in their place ^^

Edit: After working through the multi-cluster stuff, here is a proposed `interface` that I have in my head:

```golang
type GitOpsDirectoryWriter interface {
	AddApplication(ctx context.Context, app models.Application, repo models.GitRepository) error
	AddCluster(ctx context.Context, cluster models.Cluster, repo models.GitRepository) error
}
```
A further idea where a some sort of `RepoWriter` service is passed as an argument:

```golang
type RepoWriter interface {
	Write(ctx context.Context, path string, file []byte) error
}

type GitOpsDirectoryWriter interface {
	AddApplication(ctx context.Context, app models.Application, w gitrepo.RepoWriter) error
	AddCluster(ctx context.Context, cluster models.Cluster, w gitrepo.RepoWriter) error
}
```

**Comment by jpellizzari** [comment]
@palemtnrider Does this sufficiently capture the work that needs to be done for the ADR^^

**Comment by palemtnrider** [comment]
Yes, that captures the majority of the work.  Couple questions - 

> * Create a single entry-point for read/write operations from the `.weave-gitops` directory (ie create a `WeGODirectoryClient` object or some such)
By this do you mean you want there to be a package/lib that handles the interaction with the directory structure?

**Comment by jpellizzari** [comment]
> By this do you mean you want there to be a package/lib that handles the interaction with the directory structure?

@palemtnrider Yep. WDYT?

**Comment by palemtnrider** [comment]
Additionally, we want to have AC for removing apps as this work isn't as straightforward in the new directory structure.

**Comment by jpellizzari** [comment]
> Additionally, we want to have AC for removing apps as this work isn't as straightforward in the new directory structure.

Added

**Comment by palemtnrider** [comment]
> > By this do you mean you want there to be a package/lib that handles the interaction with the directory structure?
> 
> @palemtnrider Yep. WDYT?

Makes sense to me.  We should call this out when sizing in case this work impacts the time necessary to complete the work.

**Comment by jpellizzari** [comment]
Question from refinement: Do we limit the config repos to one per cluster?

**Comment by jpellizzari** [comment]
Updated the title to better reflect the work being done

**Comment by jpellizzari** [comment]
Adding @rokshana-b and @josecordaz as testers

**Comment by josecordaz** [comment]
Everything look ok on the main branch. I was able to add/remove apps successfully.
