### ISSUE TITLE
[nit] Table elements misaligned in Application UI

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#777]
**Describe the bug**
The message columns in the tables for Source and Automation conditions are out of line and would be nicer if they matched. 

**Screenshots**
<img width="1779" alt="nit - wgo UI bug" src="https://user-images.githubusercontent.com/19860021/133982548-83d6e889-7873-4c99-94dd-37aa4913e94b.png">

**Comment by jpellizzari** [comment]
The top element isn't a traditional `<table />`, but rather a table of key-value pairs that will wrap to the next line if a fourth is added. I'll see about making the bottom two align, although it would be better to let HTML do its thing there to avoid overflow.

The new graph make the alignment of the `KeyValue` table and other two less noticeable.

**Comment by sympatheticmoose** [comment]
despite the new graph, this still irks me ;)
