### ISSUE TITLE
Error on attempts to use device auth flow

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#782]
**Describe the bug**
Running "wego app add" or "wego app status" without a PAT to drive the device auth flow appeared to timeout on certain attempts. 

Error returned -

Error: failed to create app service: error getting git clients: error creating auth service: error obtaining git provider token: could not complete auth flow: error doing auth request: slow_down

**Environment**
 - gitops: [e.g. v0.2.5]

**Comment by jpellizzari** [comment]
Github is telling us to slow down polling and we aren’t incorporating the new interval and re-polling, but exiting instead.
