### ISSUE TITLE
Improve "PR already exists" error message

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#783]
In cases where a user tries to add an app a second time, Github returns a 422. This is surfaced in the error message, but we can probably help the user out with a better error message, since this is a known situation.

```
Authentication successful!

Adding application:

Name: podinfo-deploy
URL: ssh://git@github.com/scottrigby/podinfo-deploy.git
Path: ./
Branch: main
Type: kustomize

◎ Checking cluster status
✔ Wego installed
✚ Generating Source manifest
✚ Generating GitOps automation manifests
✚ Generating Application spec manifest
► Cloning ssh://git@github.com/scottrigby/podinfo-deploy.git
Error: failed to add the app : unable to create pull request: error creating branch [wego-a716ae5855fee338c408e0f4c4819704] for repo [https://github.com/scottrigby/podinfo-deploy] err [POST https://api.github.com/repos/scottrigby/podinfo-deploy/git/refs: 422 Reference already exists []]

I did in fact already have this repo.
I then deleted my fork, and re-ran the command, then got:
Authentication successful!

Error: failed to create app service: error getting git clients: error setting up deploy keys: error getting repo info: error getting user repository multiple errors occurred: 
- GET https://api.github.com/repos/scottrigby/podinfo-deploy: 404 Not Found []
- the requested resource was not found

```

https://weaveworks.slack.com/archives/CMDJFD3P0/p1632160110087700

**Comment by scottrigby** [comment]
@jpellizzari  OK,  the first error can be reproduced by running `wego app add .` twice. First time authenticates, and succeeds. Second timeI get this error:
> ► Cloning ssh://git@github.com/scottrigby/podinfo-deploy.git
Error: failed to add the app : unable to create pull request: error creating branch [wego-a716ae5855fee338c408e0f4c4819704] for repo [https://github.com/scottrigby/podinfo-deploy] err [POST https://api.github.com/repos/scottrigby/podinfo-deploy/git/refs: 422 Reference already exists []]

The second error above was a silly mistake. I deleted the repo, but did not in fact re-fork. that one probably works as designed.

**Comment by jpellizzari** [comment]
@scottrigby That first error is working as expected. Maybe we can do something around better error messages.

**Comment by jpellizzari** [comment]
Updated this to be an "error message improvement" ticket

**Comment by scottrigby** [comment]
Hmm, `wego app add` isn't intended to be idempotent like flux bootstrap is?

**Comment by jpellizzari** [comment]
> Hmm, wego app add isn't intended to be idempotent like flux bootstrap is?

Not currently, no.
