### ISSUE TITLE
WeGO and impact to DORA metrics

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#79]
**Question**
What are 2 or 3 ways WeGO can have a positive impact on users Deployment Frequency, Lead Time For changes, MTTR, Change Failure Rate.

**Short description**
DORA identified the following metrics as key attributes for measuring a team/product health:
* Deployment Frequency
* Lead Time For changes
* MTTR
* Change Failure Rate.

**Timebox**
3 days

**Questions**
* Most of the benefit is provided by GitOps in general.  What, if anything, does wego add above just GitOps.
* Is this already covered by existing white papers and work Cornelia is already doing?

---

**Outcome**
Writeup your findings here.  Please include the following (if any have been created) :
- Screenshots
- Design/architecture diagrams
- WEP 
- PR/FAQ

**Comment by markramm** [comment]
We may have some pre-existing gitops whitepapers that can be used here.
