### ISSUE TITLE
Deploying podinfo on second cluster throws failure: "kustomize build failed: accumulating resources: accumulation err='merging resources from './.wego/targets/.../podinfo-deploy-gitops-deploy.yaml'"

### ISSUE THREAD

**Issue by talaverant** [weaveworks/weave-gitops#810]
**Describe the bug**
When trying to deploy podinfo app on second cluster (EKS), I'm facing this failure:
kustomize build failed: accumulating resources: accumulation err='merging resources from './.wego/targets/minikube/podinfo-deploy/podinfo-deploy-gitops-deploy.yaml': may not add resource with an already registered id: source.toolkit.fluxcd.io_v1beta1_GitRepository|wego-system|podinfo-deploy': got file 'podinfo-deploy-gitops-deploy.yaml', but '/tmp/podinfo-deploy956763450/.wego/targets/minikube/podinfo-deploy/podinfo-deploy-gitops-deploy.yaml' must be a directory to be a root	        	False    

**Environment**
 - gitops: [e.g. v0.3.0]
 - kubernetes:  [e.g. 1.20]
    - [ ] cloud [EKS]  
 - Browser + version: [e.g. chrome 91.0.4472.101]
 -
**Affects versions**
v0.2.0 and v0.3.0

**To Reproduce**
(kubectl pointing at cluster a) gitops install
(kubectl pointing at cluster a) gitops app add . (in a local clone of a forked copy of podinfo-deploy)
(kubectl pointing at cluster B) gitops install
(kubectl pointing at cluster B) gitops app add . (same clone as before)

**Expected behavior**
Capacity to deploy an app into multiple clusters without failures

**Config and Logs**
Please let me know which logs are needed and how to get them.

**Screenshots**
<img width="1380" alt="Screenshot 2021-09-27 at 14 29 21" src="https://user-images.githubusercontent.com/53871388/135074105-0fdfef1e-7f47-4b50-9e50-ad80a1435e02.png">
<img width="1380" alt="Screenshot 2021-09-27 at 15 16 06" src="https://user-images.githubusercontent.com/53871388/135074124-ad4fe0dc-2131-4846-9610-7438223c5a43.png">
<img width="1373" alt="Screenshot 2021-09-28 at 08 52 31" src="https://user-images.githubusercontent.com/53871388/135074128-4f13c69e-1b36-46d5-bad3-e7a7b118e173.png">
<img width="1379" alt="Screenshot 2021-09-28 at 09 32 58" src="https://user-images.githubusercontent.com/53871388/135074132-9bf38d60-1f9b-4acb-b8b1-0a37b8c7bbfb.png">

**Additional context**
Mark E and David H have been kindly supporting me on this issue! Really thankful!!!

**Comment by palemtnrider** [comment]
There is a couple of issues at work here.  The Kustomization files we create for deploying the app aren't setting the path correctly (or at all)

when using an external config repo the source and kustomization objects we apply directly to the cluster have different names than the manifests being stored in the repo.  This causes duplicate objects within the cluster.

**Comment by talaverant** [comment]
Thanks @palemtnrider !! Is there a way to undo that situation? I tried reinstalling gitops (gitops uninstall and gitops install) but the issue persists. Would a cluster recreation be needed?

**Comment by jrryjcksn** [comment]
The actual problem is that using `gitops app add .` in an application repository makes the path for the `Kustomization` `./` (which is really all we can do unless someone specifies an actual path). Unfortunately, the `.wego` directory is _within_ `./`, so all the manifests in the `.wego` directory (including automation ones for other clusters) get pulled in by flux.There's only one source (GitRepository) for the app repo so we can't `ignore` the `.wego` directory in the source. I think our only options are either to create an additional source (which is a signficant burden if the app repo is large) or _require_ a `path` always be specfied in `gitops app add`.
