### ISSUE TITLE
GitOps UI fails to list app added under user defined namespace

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#816]
**Describe the bug**

After installing gitops components under user namespace and adding an app, gitops fails to list the app in the UI. Gitops looks for apps saved under `wego-system` and ignores any other namespace. 

**Environment**

 - gitops: [v0.3.0]

**To Reproduce**

1. Download the gitops binary
2. Run `gitops install --namespace=my-namespace`
3. Run `gitops app add . --namespace=my-namespace`
4. Run `gitops app list --namespace=my-namespace` and see the app listed
5. Run `gitops ui run`
6. See the blank UI page

**Screenshots**

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/257c268c-f6e6-4da8-bb32-c3cbb5a9949d)

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/337707c5-4759-4b68-897e-4c39acd95311)

**Comment by jpellizzari** [comment]
Working as intended, but needs to be addressed. Removing the bug label.
