### ISSUE TITLE
Automated release process

### ISSUE THREAD

**Issue by luizbafilho** [weaveworks/weave-gitops#83]
**Short description**
As a developer, I want to push a tag and a draft release gets created into GitHub.

**Acceptance criteria**
- [ ] there is a GitHub action that runs the tests, builds the artifacts, collects the changelogs, and creates a release with it.

**Comment by palemtnrider** [comment]
What about Docs?  Is this handled via another ticket or should it be addressed here?

**Comment by luizbafilho** [comment]
Better another task because it involves adding completely different gh action in the docs repo. 

But in this task one of the steps could be pulling the docs repo, and pushing a tag to the it. For now nothing will happen. But we'll have the integration point ready.
