### ISSUE TITLE
PR always goes to main

### ISSUE THREAD

**Issue by steveww** [weaveworks/weave-gitops#834]
**Describe the bug**
gitops app add --branch foo .
The PR created on GitHub wants to merge to main not foo

**Environment**
 - gitops: [e.g. v0.1.0]
 - kubernetes:  [e.g. 1.20.4]
    - [X ] KinD - _version_]
    - [X ] k3s - _version_
    - [ X] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_
 - Browser + version: [e.g. chrome 74, safari 12, firefox 87]
 -
**Affects versions**

**To Reproduce**

**Expected behavior**
The PR on GitHub should merge to the specified branch e.g. foo.

**Config and Logs**
If applicable, add logs to help explain your problem. _please compress the output before attaching_
- [ ] gitops config
- [ ] `gitops` cli call output (and parameters)
- [ ] gitops-controller logs
- [ ] Events from wego-* namespaces
- [ ] `kubectl cluster-info dump`
- [ ] Prometheus alerts

**Screenshots**

**Additional context**

**Comment by jpellizzari** [comment]
This is working as intended. The `--branch` flag is for the source repository, not the destination "Config" repo.

**Comment by steveww** [comment]
> --branch string            Branch to watch within git repository (default "main")

So if I want `gitops` to watch my branch *foo* I pass it `--branch foo`. It creates a PR to merge its changes into main. Why not *foo*? Does it matter that the .wego files are in a different branch to the watched branch?

If it always uses the `main` branch, is it possible to use one repo with two branches for staging and prod?

**Comment by jpellizzari** [comment]
> So if I want gitops to watch my branch foo I pass it --branch foo

@steveww Correct. The `--branch` argument only applies to the `Source` of the manifests. All config files get written to the default branch of the configuration repo.

We do have this issue: #380 , but we are waiting for a larger refactor around the config repo directory structure.

> It creates a PR to merge its changes into main. Why not foo?

The configuration repo is separate from the `Source` repo.

> Does it matter that the .wego files are in a different branch to the watched branch?

No, they are (logically) separate repositories in the system.

> If it always uses the main branch, is it possible to use one repo with two branches for staging and prod?

They will be treated as two different `Applications`.

Happy to hop on a call to discuss.

**Comment by steveww** [comment]
Thanks for the tips. I think I'm getting the hang of it now.

IMHO the docs could be improved around how it works with the repos and to detail some more advanced use cases.
