### ISSUE TITLE
Update beta add app to support helm charts

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#848]
**Short description**
As a developer, I want to add helm charts to my weave gitops environment so that I can test helm chart support with the new directory layout.

**Acceptance criteria**
- [ ] beta add app command supports adding helm charts the same way it's done today

**Design materials**
- n/a

**Comment by JamWils** [comment]
This hasn't been tested on the beta path, but could work.

**Comment by palemtnrider** [comment]
Closing as the beta commands have been folded in the main path.
