### ISSUE TITLE
Flaky auth retry tests

### ISSUE THREAD

**Issue by luizbafilho** [weaveworks/weave-gitops#850]
The auth retry tests sometimes are failing in the CI

https://github.com/weaveworks/weave-gitops/pull/820/checks?check_run_id=3827600879#step:10:455

**Comment by dhwthompson** [comment]
As far as I can tell, it looks like this is the same issue as #1199. The GitHub Actions run this links to isn’t available any more, so I can’t be 100% certain, but that also means this issue doesn’t contain enough information to reproduce the problem any more.
