### ISSUE TITLE
Feature Request - SSH key management

### ISSUE THREAD

**Issue by steveww** [weaveworks/weave-gitops#871]
Weave GitOps Core creates deploy key(s) in the GitHub repos when an application is added.
When using `--app-config-url` the deploy key in the source repo is created read/write even though that repo will only ever be read from. This could be seen as a security weakness. The deploy key should be created read-only here. Additionally if the repo has public access, there is no requirement to add a deploy key at all; this would be neater.

Security admins like to keep a track of the SSH keys in use. There should be the option to use existing deploy keys that are externally managed rather than creating new ones all the time. E.G. an admin may grant read access to a GitHub repo by adding a read-only key for GitOps to use when adding an application. Similarly for read-write access to the configuration repo.

The private keys should be managed securely.

**Comment by bigkevmcd** [comment]
@steveww What if they're using SOPS (per-Flux) or something else?

**Comment by jpellizzari** [comment]
@jpellizzari split into 3 tickets
