### ISSUE TITLE
UI improvements to application flow

### ISSUE THREAD

**Issue by bia** [weaveworks/weave-gitops#876]
1. #1016
so that the application's state is apparent once the page loads. The 'Application / podinfo-deploy' title is also not needed because of the breadcrumbs in the navbar above.
<img width="821" alt="Screenshot 2021-10-13 at 15 32 56" src="https://user-images.githubusercontent.com/92439/137142838-4891f88c-b550-4549-8881-5192a049cdf6.png">

2. #1017
Each node should have a more subtle drop shadow, more of an outline like `drop-shadow(rgb(189,189,189) 0px 0px 1px)`. Each circle should also be larger to be able to display more text.
<img width="868" alt="Screenshot 2021-10-13 at 15 05 15" src="https://user-images.githubusercontent.com/92439/137138209-1405d149-56ac-47c3-8bb2-db78e092d0a2.png">

How are the graph nodes being distributed? Could we move to a radial distribution? That would save space and remind me less of Argo. 
When I scroll down on the page, I am most often accidentally zooming out the graph instead. It would make sense if the graph was completely zoomed out (such that all nodes are visible) on page load.
![20211013app-graph](https://user-images.githubusercontent.com/92439/137141089-bf1afd26-437a-4250-9b71-23c1d4ce588c.png)

3. Are there ever going to be more rows on this table? If not, this information should be included in the status section instead of formatted as a table.
<img width="1137" alt="Screenshot 2021-10-13 at 15 20 27" src="https://user-images.githubusercontent.com/92439/137140735-b33c0f75-c04b-4378-bfce-3f88064db8a1.png">

4. #1032
The Applications page should use the same table style as the Clusters page. The title of that table should be something more descriptive like 'Installed GitOps Applications,' and each item will have a status/health metric displayed.
![20211013applications](https://user-images.githubusercontent.com/92439/137141677-e004c366-26d8-48b4-a841-9f9e6642601b.png)

5.  #1033
Implement counts for Applications and Clusters in the menu bar navigation as is important for maintaining context.

Let me know your thoughts and suggestions!
cc @sympatheticmoose @jpellizzari

**Comment by jpellizzari** [comment]
> We need a top level status section on each application's page so that the application's state is apparent once the page loads. The 'Application / podinfo-deploy' title is also not needed because of the breadcrumbs in the navbar above.

We don't have those status metrics and need to discuss what an aggregated "Healthy" would mean. We can make space for them in the mean time.

We can move the location of the breadcrumbs, but we won't be able to show the count of things next to each of them. 

> Each node should have a more subtle drop shadow, more of an outline like drop-shadow(rgb(189,189,189) 0px 0px 1px)

:+1: 

> How are the graph nodes being distributed? Could we move to a radial distribution? That would save space and remind me less of Argo.

The are using a traditional directed-acyclic graph. If you could do some research on what layout algo would give us the arrangement you are going for, that would be great. Any supporting `npm` libraries would be an added bonus.

> When I scroll down on the page, I am most often accidentally zooming out the graph instead. It would make sense if the graph was completely zoomed out (such that all nodes are visible) on page load.

Not much we can do about that, unless you are suggesting we disable mouse-wheel scrolling on the graph in favor of a slider control.

> Are there ever going to be more rows on this table? If not, this information should be included in the status section instead of formatted as a table.

Probably. We  have more data being returned from the API but haven't attempted to organize it yet.

**Comment by jpellizzari** [comment]
@bia Has graciously volunteered to break this ticket up. Re-assigned.
