### ISSUE TITLE
Publish docker image containing the gitops binary

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#889]
**Short description**
As an app developer, I want to gitops in a docker container so that I can use some of the functionality within a cluster.

**Acceptance criteria**
- [ ] When releasing a new version of weave gitops, a public docker image is made available tagged with the same version as the release in GitHub
- [ ] When the nightly build passes, a new version of the weave gitops docker image is made available with a tag indicating it is a nightly build.  The tag should be v[last release]+[git commit].  e.g., v0.3.4+0d475c65 
- [ ] When the nightly build fails, no image is made available
- [ ] gitops process doesn't run as root
- [ ] gitops process takes parameters and arguments 

**Questons**
**1.** Do we publish to dockerhub or GitHub CR?

**Comment by jpellizzari** [comment]
I would like to close this. The main reason to do nightly builds is to be able to point users (internal or external) to it between releases. I don't feel comfortable doing this in the near term, given how fast things are changing in the code base.
