### ISSUE TITLE
Uninstall weave gitops

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#890]
**Short description**
As an SRE I want to uninstall weave gitops from my cluster to reduce the overhead these workloads consume.

**Acceptance criteria**
- [ ] optionally removes the cluster information from the weave gitops repo
- [ ] optionally removes the applications installed into the cluster
- [ ] removes all GORT and GOAT resources from the cluster.  **NOTE** this may become an option if the cluster was bootstrapped using flux.
- [x] when prompted for an input during `gitops uninstall`, user is be able to enter **case insensitive** `Y`as valid input
- [x] anything other than `y|Y` input will trigger cancellation of `gitops uninstall`, in which case a quitting message will display: `uninstall cancelled`

- Check to make sure the namespace we are deleting is the correct namespace. If the user passes a different namespace, we should fail.

Related to persisting gitops repo and namespace data: https://app.zenhub.com/workspaces/weaveworks-foss-603cb6b1d4dff9000e242dc4/issues/weaveworks/weave-gitops/1128

**Existing behavior**
* uninstall flux 
* delete the wego-system namespace (or namespace passed to the CLI)
  * if the namespace passed isn't where gitops was install, existing controllers crash
* prompt to continue is already implemented.

**Comment by JamWils** [comment]
@palemtnrider how does this work today and how does this new experience differ?  Please put it in the description.

**Comment by palemtnrider** [comment]
Today, uninstall removes the GORT, the Flux CRDS and the wego-system namespace. However, it doesn't update the app-config-url repo contents. I'm not certain what happens to the apps (except those in wego-system will be deleted).  No GOAT will remain due to the removal of flux.
