### ISSUE TITLE
`pollAuthStatus` doesn't seem to retry auth on `ErrSlowDown`

### ISSUE THREAD

**Issue by AlinaGoaga** [weaveworks/weave-gitops#893]
**Describe the bug**
If the user gets the `slow down` error on Github Auth the polling should retry. Atm the modal stays open and no further request seems to go through (please see attached).
![137303106-51dbc560-df1b-447f-829a-bf5f7d854ada](https://user-images.githubusercontent.com/35202557/137485149-7a983c08-89e4-4b7d-87ce-9626b4d75bc5.png)

**Environment**
 - gitops: latest version of main 
 - Browser: chrome 94

**To Reproduce**
1. Start ui and go to application detail 
2. In the commits sections authenticate with Github. 
3. At times a `slow down` error would appear. 

**Expected behavior**
Following the slow down error we should resend the auth request without user input. 

**Additional context**
Tagging @foot also. He was suggesting that this might also be due to us removing the token multiple times from the local storage as we test the auth flow. Looking forward to your thoughts!

**Comment by jpellizzari** [comment]
We DO handle it here, but in the case of the UI, the browser is doing the polling to avoid a long hanging request:

https://github.com/weaveworks/weave-gitops/blob/62104e643e1b1f8d4796a1f6b17da491a0a5a968/pkg/services/auth/github.go#L176
