### ISSUE TITLE
Gitops fails to add some apps from upstream helm repos

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#894]
**Describe the bug**
Gitops fails to add some apps from an upstream helm repo. The failure is inconsistent and baffling. 

**Environment**
 - gitops: [v0.3.1]

**To Reproduce**
1. Run `gitops install`
2. Run `gitops app add --url=https://charts.kube-ops.io --chart=loki`
3. Run `gitops app list` and see app listed
4. Run `kubectl get pods -A` and see a pod getting created for `loki`
5. Run `gitops app add --url=https://charts.kube-ops.io --chart=generate`
6. Run `gitops app list` and see app listed
7. Run `kubectl get pods -A` and you'll notice no pods getting created for `generate`

**Screenshots**

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/e457300b-ab3d-4541-b3f0-8448ced265bb)

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/ecdd0fa2-9c0e-463f-b431-ccdc8a83f6c8)

**Comment by J-Thompson12** [comment]
So I was able to replicate this issue and in the helm-controller I see:
```
{"level":"error","ts":"2021-11-08T22:08:51.567Z","logger":"controller.helmrelease","msg":"Reconciler error","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"grafana","namespace │
│ ":"wego-system","error":"Helm install failed: execution error at (grafana/templates/secret.yaml:10:33): Grafana admin password must be set"}  
```
This is an issue with that chart.
