### ISSUE TITLE
Move git operations from app-centric packages

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#907]
**Short description**
As a weave gitops developer, I want to perform git operations on clusters in addition to apps so the git operations should live in a central package.

**Acceptance criteria**
- [ ] existing app calls that interact with the git repo still pass tests
- [ ] git operations (e.g., cloneRepo) live in a new package instead of on apps

**Comment by jpellizzari** [comment]
This work was done in #1024. Closing.
