### ISSUE TITLE
Support adding the same app with different names

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#908]
**Short description**
As an app developer, I want to deploy an app multiple times to a cluster using a different name for testing purposes

**Acceptance criteria**
- [ ] add app foo with repo/path/branch set to a/b/c
- [ ] add app foo2 with repo/path/branch set to a/b/c
- [ ] if I remove foo2, all GitOps machinery is still present in the cluster

**Notes**
Currently, the code hashes applications and leaves the name out of the hash.  This is intentional due to how the GitOps automation was stored on the cluster. The new directory structure changes how this works and we can support the same app being deployed into a cluster with a new name.

**Comment by sympatheticmoose** [comment]
@palemtnrider could you elaborate on the testing purposes which require you to deploy the exact same application?
