### ISSUE TITLE
Support gitops install via PR

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#917]
**Short description**
As a [User Role] I want to [feature/functionality] so that [business outcome/value].

**Acceptance criteria**
- [ ] _does X_
- [ ] _displays Y_
- [ ] _..._

**Design materials**
- Screenshots
- Design diagrams
- WEP 
- PR/FAQ

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by JamWils** [comment]
@palemtnrider please fill out the story.  How does it currently work today and what needs to change.  Please keep in mind that the beta command functionality was moved to the "production" command.

**Comment by jpellizzari** [comment]
Included in #1002. Closing.
