### ISSUE TITLE
Direct helm chart support

### ISSUE THREAD

**Issue by markramm** [weaveworks/weave-gitops#92]
**Short description**
As an application developer, I want to install a helm chart such as cassandra to provide part of my application stack; this should be supported in the case of a single platform/application repository as well as the "standard" model of separate platform, wego application, and external app repositories.

**Acceptance criteria**
- [ ] A helm chart deployed to the chosen repository is synced and installed into the system

**Design materials**
- Screenshots
- Design diagrams
- WEP 
- PR/FAQ

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by J-Thompson12** [comment]
Addressed on https://github.com/weaveworks/weave-gitops/pull/263
