### ISSUE TITLE
Duplicate application

### ISSUE THREAD

**Issue by steveww** [weaveworks/weave-gitops#921]
**Describe the bug**
Adding an application with the name set creates two

**Environment**
 - gitops: 0.3.1
 - kubernetes:  [e.g. 1.20.4]
    - [X] KinD - _version_]
    - [ ] k3s - _version_
    - [X] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_
 - Browser + version: [e.g. chrome 74, safari 12, firefox 87]
 -
**Affects versions**

**To Reproduce**
gitops app add \
--app-config-url git@github.com:foo/bar \
--url git@guthub.com:foo/foobar \
--name foo

gitops app list
NAME
foo
foobar

**Expected behavior**
Just one application called foo

**Comment by sympatheticmoose** [comment]
@steveww I can't reproduce this anymore, believe it is resolved but please re-open if you are hitting this issue.
