### ISSUE TITLE
UI: Show the Application Deployment

### ISSUE THREAD

**Issue by markramm** [weaveworks/weave-gitops#93]
**Short description**
As an application operator  I want to go to a page in the UI that shows the current status of my deployment, so that I can determine if the deployment has gone as expected, and can drill down to debug any errors.

**Acceptance criteria**
- [ ]  there is a web page that shows the current status of each object in the application. 

**Design materials**
- Screenshots
- Design diagrams

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by palemtnrider** [comment]
superseded by #257
