### ISSUE TITLE
`wego-app` pod missing when you install Weave GitOps via Marketplace

### ISSUE THREAD

**Issue by Himangini** [weaveworks/weave-gitops#934]
**Describe the bug**
PitchBlack team needs some help with solving the curious case of missing `wego-app-xyz` pod when you install Weave GitOps via Marketplace. It has been pointed out by @sympatheticmoose that `wego-app` missing [screenshot added below]. We have followed the docs https://docs.gitops.weave.works/docs/getting-started/#install-weave-gitops-onto-the-cluster and the output here doesn't mention the `wego-app` pod either so we are not sure where this is coming from.

Output shown in aws docs here https://docs.gitops.weave.works/docs/aws-marketplace
```
kubectl get pods -n wego-system
# you should see something like the following returned
wego-system          helm-controller-5b96d94c7f-tds9n                    1/1     Running   0          53s
wego-system          image-automation-controller-5cf75fd555-zqm89        1/1     Running   0          53s
wego-system          image-reflector-controller-6787985855-l4q4g         1/1     Running   0          53s
wego-system          kustomize-controller-8467b8b884-x2cpd               1/1     Running   0          53s
wego-system          notification-controller-55f94bc746-ggmwc            1/1     Running   0          53s
wego-system          source-controller-78bfb8576-stnr5                   1/1     Running   0          53s
wego-system          wego-metering-f7jqp                                 1/1     Running   0          53s
```

<img width="727" alt="Screenshot 2021-10-20 at 15 15 23" src="https://user-images.githubusercontent.com/10995114/138282906-d1916879-d74d-4604-84b5-8c48e9eafe17.png">

 -
**Affects versions**
We have noticed `wego-app` pod missing when installing all versions for weave gitops available via marketplace

**To Reproduce**
Follow the steps here https://docs.gitops.weave.works/docs/aws-marketplace

**Expected behavior**
We're not sure if this `wego-app` pod should be present when you install Weave GitOps via a helm chart. 
If its a required pod then we need help to figure why it's not installing via helm

**Comment by palemtnrider** [comment]
I'll take a look into this issue.

**Comment by Skarlso** [comment]
Also, this is something very recent? Because the docs isn't mentioning this pod at all.
