### ISSUE TITLE
Support Flux commands/integrations from Weave GitOps

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#936]
Converted from: https://www.notion.so/weaveworks/Initiatives-5c7bc3e6c137421dbcd566b5e97c511d?p=ffcbc0ae7e844eb3b9c29da3bc95a5a5

`wego flux logs` - or `gitops flux logs`
This does not work, I think because of a mismatch between the labels or namespaces. Flux expects to be installed in flux-system not in wego-system so flux logs will not work without changes to accommodate this difference

`wego flux get kustomizations` - similar to above, the default behavior looks in the flux-system namespace. (At least this one provides enough output to clarify what has gone wrong: "X no Kustomization objects found in flux-system")

Generally I have also had issues around the idea that flux and wego cannot be used together, because I am a Flux developer that makes it very difficult to participate as I have many clusters but all of my clusters are generally running Flux, so I have to spin up another one in order to try Weave GitOps. This is actually the first time I've been able to make it to the end of a Wego tutorial myself (in spite of guiding several people through it and being present at several wego sessions before...)

It is counter-intuitive to me that there is no bridge for wego users to work on existing Flux clusters when the Flux APIs are considered stable, it seems unecessary. "Doubling down on Flux" seems contradictory to the idea that I would first need to uninstall Flux before proceeding into use Weave GitOps. Please do not let this come across as harsh criticism. This is a great onboarding flow for users who do not have Flux and I can see now that I've had a chance to run through it myself that it is very easy, and the newly released device-flow OAuth workflow feature in 0.3.0 is a fantastic addition

- [ ]  `wego flux logs` does not work and does not provide any error output, see:
[https://github.com/weaveworks/flux2-openshift/pull/5](https://github.com/weaveworks/flux2-openshift/pull/5) for some additional context around why this issue exists
([https://github.com/weaveworks/flux2-openshift/issues/7](https://github.com/weaveworks/flux2-openshift/issues/7) solved it for openshift-flux)
- [ ]  `wego flux get kustomizations`
    - [ ]  Problem number one: weave gitops does not use the flux-system namespace but the output says (hopefully it's excessively clear why this is unhelpful as a default):
    
    $ wego flux get ks
    ✗ no Kustomization objects found in flux-system namespace
    
    - [ ]  I don't know how to suggest solving this. I really want Flux to add an environment variable that you can use like old-school Flux v1 `fluxctl` had `--k8s-fwd-ns` but you could also set an environment variable `FLUX_FORWARD_NAMESPACE` and it would be used as the default value. Adding this feature wouldn't straight-away solve this, as Weave GitOps users are not going to be asked to set a variable, but perhaps `gitops flux` could set the variable? (At present there is no equivalent feature in Flux v2 so it is not straightforward.)

**Comment by JamWils** [comment]
I wonder if we could take advantage of the info in https://github.com/weaveworks/weave-gitops/issues/1103 on knowing which cluster flux is installed.

1. The user provides a namespace and we pass that through.
2. The user does not provide a namespace so we detect where Flux is installed on the cluster.
3. If flux is installed we pass that namespace to each flux command.
4. If flux is not installed we either default to `flux-system` or `wego-system`.

@sympatheticmoose thoughts?

**Comment by JamWils** [comment]
Removing the following from the description since we are tackling this as an epic:

>  wego should be able to leverage an existing Flux v2 installation
>  I'm sure I am wrong about this but I feel it very strongly — Kingdon
> Is it ever going to be on the roadmap? (If the answer is no, I'm happy to keep this feedback to myself! I want weave gitops to succeed as much as anyone else does.)
> I feel like it could be tackled at some point with some kind of compatibility matrix that certifies certain versions of Flux which work with certain versions of Weave Gitops, perhaps that is not a desirable solution, I'd be much happier if I knew it was on the roadmap but even as distant future! I understand it will be challenging to implement.

**Comment by sympatheticmoose** [comment]
I'd wonder whether we can leverage https://github.com/fluxcd/flux2/pull/2034 and set this appropriately to wego-system or flux-system. 

The issue on logs not outputting however, it's not clear to me exactly what we need to change there... we set:
```
app.kubernetes.io/instance=wego-system  
app.kubernetes.io/part-of=flux
```

and still get nothing
