### ISSUE TITLE
"gitops app status", "gitops app pause", and "gitops app unpause" require auth token

### ISSUE THREAD

**Issue by jrryjcksn** [weaveworks/weave-gitops#940]
**Describe the bug**
Running `gitops app status <app name>` invokes the auth flow if the GIT(HUB|LAB)_TOKEN is not set in the environment. This also occurs for `gitops app pause <app name>` and `gitops app unpause <app name>`

**Environment**
 - gitops: 0.3.2-rc1

**To Reproduce**
1. Add an app via `gitops`
2. unset GITHUB_TOKEN
3. run `gitops app status <app name>`
4. See auth flow occur

**Expected behavior**
Status does not talk to git and should not need an auth token.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5db83c9473e8f70001d9f27a/7755dd79-1521-4bf6-ba64-cdaf07fd9ef7)

**Comment by josecordaz** [comment]
@JamWils  I just tested these commands with changes on branch `jlw-cli-fix`, all looks good now.

**Comment by jpellizzari** [comment]
Closed by #872
