### ISSUE TITLE
Wego-app UI auto-refresh application list

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#942]
As an app developer, when I add applications either through the UI or CLI I want the application list to show the application in the list once it is available in the cluster without having to perform any action, e.g., browser refresh, click the application link.

---
_The original ticket_

**Describe the bug**
I opened the ui from the wego-app pod running in the cluster.  When I added an app via the CLI, the app wasn't displayed in the UI until refreshing the page.  I waited several minutes.  I also tried clicking the applications link on the nav.

**Environment**
 - gitops: v0.3.2-rc1
 - kubernetes:  1.21.1
    - [ ] KinD - 0.11.1]
  - Browser + version: chrome Version 94.0.4606.61 (Official Build) (x86_64)
 -
**Affects versions**
* v0.3.2-rc1

**To Reproduce**
1. install weave gitops
2. do a port forward to the weave gitops service
3. stay on the applications page
4. add the app via `gitops app add .`
5. watch the UI page

**Expected behavior**
After a short period of time, the list of applications shows my new app

**Comment by jpellizzari** [comment]
Scope for this: add polling to the app list and app detail pages.

Acceptance Criteria:
* Poll every n seconds
* Indicate to the user that the page is polling
