### ISSUE TITLE
GitOps uninstalls components in wego-system while ignoring the namespace flag

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#944]
**Describe the bug**

When provided with a namespace flag with a namespace, gitops deletes components under all namespaces — even the default one. Any apps saved under the default namespace are deleted as well. The containers, however, keep running even though user is not able to add anymore apps via gitops. 

**Environment**

 - gitops: [v0.3.2-rc1]

**To Reproduce**

1. Run `gitops install`
2. Run `gitops app add --url=<url> --name=my-app`
3. Run `gitops app list` and see app get added
4. Run `gitops install --namespace=foo`
5. Run `gitops uninstall --namespace=foo`
6. See finalizers get deleted in ALL namespaces — thereby deleting any apps saved under the default namespace
7. Run `gitops app list` and see error message
8. Run `kubectl get pods -A` and see components listed as `Running`

**Screenshots**

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/593b3600-04a0-4021-8e1e-9f1ef518b551)

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/4ad748f2-a28e-47a6-b20a-110108b695b0)

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/d900346a-6827-4ca9-9b66-5a00b3f0ab71)

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/f6f471b4-5597-4487-a551-5c082691d461)

**Comment by luizbafilho** [comment]
this is expected, flux controllers are supposed to be unique by cluster, with that said @sympatheticmoose if we add validation to stop people from running the install again we make the command non-idepotent.

And regarding the app deletion that's a broader discussion because we are using the `purge` option from Flux, meaning that once the kustomization is deleted it will delete all resources managed by it, so how to proceed on this case is TBD.

**Comment by jpellizzari** [comment]
Fix: don't let the user install on the same cluster twice

**Comment by luizbafilho** [comment]
Verification step:
1. Look for a namespace that contains the label `part-of: flux`
2. Validate if that namespace is equal to the provided one, in case not fail the install process.
