### ISSUE TITLE
GitOps deletes apps during uninstallation, thereby preventing idempotency

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#945]
**Describe the bug**

When uninstalling gitops components, gitops deletes the app deployed in the cluster. This does not adhere to the idempotency requirement of the product. 

**Environment**
 - gitops: [e.g. v0.3.1-rc1]

**To Reproduce**

1. Run `gitops install`
2. Run `gitops app add . --auto-merge=true`
3. Run `gitops app list` and see app listed
4. Run `gitops uninstall` and see all finalizers get deleted
5. Run `gitops app list` and see error

**Screenshots**

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/38cfda73-c1cc-4675-a8c4-67064aed9018)

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/a01a761f-7033-4e49-9356-a0c0f6e9e793)

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/1a246d73-feb7-49fd-b948-fdb5404fe6d2)

**Comment by jpellizzari** [comment]
Working as designed. We will be enhancing this in #890.
