### ISSUE TITLE
Publish rc versions to npm

### ISSUE THREAD

**Issue by J-Thompson12** [weaveworks/weave-gitops#956]
We have been ignoring an error in the release process that we can easily skip past. In the publish_npm_package step of the release github action this error occurs: 
```
npm ERR! 400 Bad Request - PUT https://npm.pkg.github.com/@weaveworks%2fweave-gitops - failed to stream package from json: unhandled input: Cannot publish over existing version.
```
Currently we only publish the full release version. 
Acceptance Criteria:
- Publish the rc versions. 
- Update the release docs accordingly.

**Comment by mnowster** [comment]
Fixed.
