### ISSUE TITLE
install adds a kustomization file into /system with references to all the system resources

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#960]
**Short description**
As an SRC I want to specific control over the system resources installed into my cluster.

**Acceptance criteria**
- [ ] kustomization.yaml in the system directory containing all the yaml files installed into the system directory
- [ ] when profiles are installed, they add resources to this kustomization file (Change. to the bootstrapping process)

**note: ** This matches how the user directory operates.

**Comment by JamWils** [comment]
This seems like it is out of scope and pertains to profiles.  How does the existing functionality work today this seems purely additive.
