### ISSUE TITLE
wego-app container needs kubectl included

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#962]
**Short description**
As a SRE I want to use weave gitops from a container.

We are publishing an existing container, wego-app, however, it will only run commands which don't require kubectl.  This includes the install command. 

**Acceptance criteria**
- [ ] ability to run the install gitops CLI commands from within a container.
- [ ] ability to run the application add gitops CLI commands from within a container.

**Comment by palemtnrider** [comment]
Removing from the epic "Directory Structure". However, it is required for boot-strapping leaf clusters.

**Comment by jpellizzari** [comment]
No longer relevant. Bootstrapping a cluster is working. There may be other work to convert install to use client calls instead.
