### ISSUE TITLE
Running add-app inside the cluster fails with bad secret name

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops#976]
**Describe the bug**

**Environment**
 - gitops: [e.g. v0.3.3]
 - kubernetes:
    - kind

**Affects versions**

0.3.3

**To Reproduce**

I'm not sure how best to repro. We consume and run weave-gitops as a go module and so run some of the code inside the cluster (add app), whereas its usually run outside the cluster from a user's terminal.

Running the api-server in the cluster and then hitting the add_application endpoint we receive:

> could not create app service: error creating git client for app repo: error setting up deploy keys: error retrieving deploy key: error getting deploy key secret: invalid resource name "wego-https://10.96.0.1:443-podinfo-deploy": [may not contain '/']

Appears to be hitting this code when running inside a cluster: https://github.com/weaveworks/weave-gitops/blob/c21522b2998665e6034b25782ec3eab6e0357978/pkg/kube/kubehttp.go#L120-L121

k8s clusters don't know their own names, so perhaps this value should be provided manually? Not sure.

**Comment by jpellizzari** [comment]
The comment is telling:

> // TODO when running in a cluster and not used for bootstrapping, what is the cluster name used for?

Answer: When running in a cluster and not used for bootstrapping, `clusterName` is used for generating secret names.

@foot Struggling with this one, a naive solution was this:

```
		// When running in a cluster and not used for bootstrapping,
		// clusterName is used for generating secret names.
		clusterName = "in-cluster"
```
I'm pretty sure this will cause secret naming conflicts ^^ in the GitOps repo (or maybe source repo)?

One idea was to pass an environment variable to the `gitops` deployment so it knows what it's cluster name is. Any thoughts?

cc @palemtnrider

**Comment by palemtnrider** [comment]
I was running into the same issue with the beta commands.  Once we added the kubeconfig from CAPI, we are given a good name for the cluster and this name is used in the gitops repo.  I was thinking the cluster needs to know who it is and the kubeconfig handed to us by k8s doesn't have a proper context - and host is the only field that made sense.

I think an environment value is OK for now but moving forward I think we will want a CR that lives in the cluster repo and is synced into the cluster and therefore available for use in commands like this.  A configmap is another option but I can envision us storing data for the cluster in the status fields of the CR.

**Comment by foot** [comment]
> I think an environment value is OK for now

🎉  sgtm

**Comment by foot** [comment]
I put together a quick PR just in case it would make the cut for this release. No stress though, we can work around it.
