### ISSUE TITLE
Fix server SyncApplication test flakiness

### ISSUE THREAD

**Issue by luizbafilho** [weaveworks/weave-gitops#981]
**Short description**
The SyncApplication test that verifies we wait for the flux reconciliation to happen is flaky, it works when running in isolation or in a dev machine but sometimes breaks on the CI.

**Acceptance criteria**
- [ ] _does X_
- [ ] _displays Y_
- [ ] _..._

**Design materials**
- Screenshots
- Design diagrams
- WEP 
- PR/FAQ

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by luizbafilho** [comment]
Failed run: https://github.com/weaveworks/weave-gitops/runs/4107133411?check_suite_focus=true

**Comment by sympatheticmoose** [comment]
closing given it is likely invalid now
