### ISSUE TITLE
Prevent running of GitOps dashboard if Weave GitOps is not installed

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#982]
As a user, when I run `gitops ui run` without installing the Gitops runtime on the cluster I get the following error message.

![Screen Shot 2021-10-28 at 11.34.22 AM.png](https://images.zenhubusercontent.com/60f5a90306cf76325d5accdc/80e4112f-0361-4a96-9190-4fa1fe4dbc3b)

While the error points out it doesn't know what an Application is it would be nice to have a more clear error message that informs the user that the current cluster is not set up for running Weave Gitops and that they should install it via the CLI with `gitops install`.

We can avoid this occurring by running the same logic we use in other commands to check for the presence of Weave GitOps on the cluster, and if we fail to detect, error out.

**Comment by sympatheticmoose** [comment]
I'd love to avoid the user being able to hit this rather than fix the error message. Particularly given the future of running the UI on the cluster, maybe we do a check on install as part of running this?

**Comment by luizbafilho** [comment]
We need to validate if gitops is present into the cluster right before proceeding with the ui run

**Comment by sympatheticmoose** [comment]
updated title/description
