### ISSUE TITLE
Support using Gitlab in wego

### ISSUE THREAD

**Issue by jrryjcksn** [weaveworks/weave-gitops#99]
**Short description**
As a WeGO customer I want to use Gitlab _for the platform_

**Acceptance criteria**
- [ ] wego allows a choice of Gitlab (as well as github) 
- [ ] system works correctly using Gitlab
- [ ] I can add an github application repo to point to an existing cluster (which already has an application defined in a separate gitlab repository.)

**Comment by markramm** [comment]
We have to have automated tests for both of these.

**Comment by markramm** [comment]
Question that came up in backlog refinement:  Should this be one git provider defined at the platform level?  Does this make things easier?

**Comment by davidberglund** [comment]
Looking forward to introduce Weave Gitops in my org when Gitlab support and docs has landed!

**Comment by markramm** [comment]
We should abstract all git interactions behind go git providers.

**Comment by jpellizzari** [comment]
Closing in favor of the more specific auth issue in #554. One auth is done, gitlab **should** be supported.
