### ISSUE TITLE
Clear guidance in CLI for which features require a Weave GitOps Enterprise subscription

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#991]
**Short description**
As a user of any tier of Weave GitOps I want to understand which features of the product are available to me so that there's less chance of executing a command which will fail.

We decided to provide a single CLI/binary for Weave GitOps regardless of tier, whether someone is using the open source Weave GitOps Core, or the commercially supported Weave GitOps Enterprise. Simpler for individuals to use and to distribute amongst teams. However, given some commands will fail without a valid entitlement to Enterprise, we need to make sure this is clearly discoverable for a user before they try and execute.

We've followed the Kind example and have as our global help

```
gitops help
short summary

Usage:
  gitops [command]

Available Commands:
- list
```

I would propose we separate 'Available Commands' into 
```
Core Commands:
- list

Enterprise Commands:
- list
```
In global it would just be upgrade that needs to be under enterprise. Then for add/get we could separate under the appropriate command help, i.e. 

`gitops add h-` would show:
```
Core Commands:
app - blah

Enterprise Commands:
cluster - blah
```
Additionally we could add "Requires entitlement to Weave GitOps Enterprise." to the help text description for each enterprise command. i.e. for `gitops add cluster -h` 
"Add a new cluster using a CAPI template. Requires entitlement to Weave GitOps Enterprise."

Note this description is different to the description shown at the parent level i.e. `gitops add -h` therefore (correctly) I believe it wouldn't show in that view where we have already brought under a Enterprise Commands heading.

**Comment by bia** [comment]
>I would propose we separate 'Available Commands' into [Core Commands, Enterprise Commands]

LGTM so long as cobra supports it.

> "Add a new cluster using a CAPI template. Requires entitlement to Weave GitOps Enterprise."

This would read strangely to me. Yes, you would need an entitlement to do this, but more directly you would need to have bought Weave GitOps Enterprise. Maybe just `Add a new cluster using a CAPI template. Requires Weave GitOps Enterprise.` ?

**Comment by sympatheticmoose** [comment]
I mean I assume its possible with cobra give the (seemingly) arbitrary groupings in kubectl... 

I'm fine with a simpler `Requires Weave GitOps Enterprise`

**Comment by sympatheticmoose** [comment]
@foot would be great if y'all could have a go at this as part of wrapping up the CLI integration

**Comment by JamWils** [comment]
This is closed as we have pulled enterprise only CLI commands into a separate binary.
