### ISSUE TITLE
User is prompted twice to authenticate to GitHub in beta install command

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#995]
**Describe the bug**
User is prompted twice to authenticate to GitHub in beta install command

**Environment**
 - gitops: main, v0.4.0

**Affects versions**
v0.4.0

**To Reproduce**
1. create KinD cluster
2. clear GITHUB_TOKEN from env
3. issue github beta install --app-config-url your-repo
4. You are prompted near the start of the command and again when persisting files to the repo

**Expected behavior**
A single GitHub auth prompt for the entire call

**Comment by JamWils** [comment]
This issue should be resolved with #953.  I will verify.

**Comment by jpellizzari** [comment]
Closed by #872
